### ISSUE TITLE
Handle "maximum authentication attempts exceeded"

### ISSUE THREAD

**Issue by leofeyer** [ossec/ossec-hids#1012]
It seems that OSSEC does not yet handle the sshd "maximum authentication attempts exceeded" messsage:

```
Received From: ab->/var/log/auth.log
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Dec 27 03:23:51 r1 sshd[21183]: error: maximum authentication attempts exceeded for root from 183.106.179.x port 34100 ssh2 [preauth]
```

There should be a rule in the `sshd_rules.xml` file so this does not trigger a 1002, shouldn't it?

**Comment by ddpbsd** [comment]
PR #1013 should handle this. Thanks for the sample!

**Comment by leofeyer** [comment]
Although the fix is in the master branch (see https://github.com/ossec/ossec-hids/blob/master/etc/decoder.xml#L321-L326), it is not included in version 2.9.1 (see https://github.com/ossec/ossec-hids/blob/2.9.1/etc/decoder.xml). @ddpbsd Why is this?

**Comment by leofeyer** [comment]
The same applies to the `sshd_rules.xml` file.

**Master branch**
https://github.com/ossec/ossec-hids/blob/master/etc/rules/sshd_rules.xml#L396-L401

**Version 2.9.1**
https://github.com/ossec/ossec-hids/blob/2.9.1/etc/rules/sshd_rules.xml

Rules no. 5754 to 5758 are missing in version 2.9.1.

**Comment by ddpbsd** [comment]
Perhaps nobody backported them? If there was a pull request or issue asking for it, I missed them.

**Comment by leofeyer** [comment]
Ok, so can I ask you to back port them then? 😄

**Comment by atomicturtle** [comment]
Yeah I can do it for 2.9.2. Do you think you could go through the other rules to see if there are any other deviations? Thanks!

**Comment by leofeyer** [comment]
Sure. The following files from the master branch all have rules which are not present in version 2.9.1:

* [dovecot_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/dovecot_rules.xml#L78-L88)
* [exim_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/exim_rules.xml) (does not exist in v2.9.1 at all)
* [msauth_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/msauth_rules.xml#L944-L968)
* [netscreenfw_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/netscreenfw_rules.xml#L114-L118)
* [openbsd_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/openbsd_rules.xml#L241-L290)
* [syslog_rules.xml](https://github.com/ossec/ossec-hids/blob/master/etc/rules/syslog_rules.xml#L535-L554)

**Comment by atomicturtle** [comment]
I just added all of these to the v2.9.2 branch, I want to add you to the credits on this if that is OK with you?

**Comment by leofeyer** [comment]
Sure. Thank you.
