### ISSUE TITLE
Ossec 2.8.3 and problems with ossec-maild

### ISSUE THREAD

**Issue by rimvydukas** [ossec/ossec-hids#1023]
Hi,

I noticed one strange thing on one of my Debian 8 box'es. I saw that I'm not seeing mail notifications from ossec. Everything worked in the past on this server with this ossec installation. I checked process list and saw that I have at least 8 ossec-maild processes started. I restarted ossec killed all maild processes. Ossec started with one maild process but after short time I saw that second maild process was started. And I still can't see any ossec mail notifications. Can anyone help me to troubleshoot this issue? Thanks.

**Comment by ddpbsd** [comment]
Try turning on the debugging to see what logs maild produces:
`/var/ossec/bin/ossec-control enable debug && /var/ossec/bin/ossec-control restart`

You can also try using tcpdump to see what's happening on the network between maild and the smtp daemon.

**Comment by marcRBD** [comment]
i confirm the same behavior:
crash of maild !
i will try some debug too

**Comment by ddpbsd** [comment]
Any updates? I haven't noticed this behavior.

**Comment by rimvydukas** [comment]
An update:) Problem was that smtp server I was using was non functional so because of that I had these crashes.

---

**Comment by marcRBD** [comment]
i see some defunct again with big load, but ossec-remoted and cpu were breaking the law too.
So it is logical
