### ISSUE TITLE
Uninstall from Linux

### ISSUE THREAD

**Issue by t3kg33k** [ossec/ossec-hids#1025]
I was looking for documentation but was having a hard time finding it.
What are the steps for completely removing OSSEC from a Linux (Red Hat) machine?

**Comment by ddpbsd** [comment]
Assuming you installed from source:
`/var/ossec/bin/ossec-control stop && rm -rf /var/ossec && rm /etc/init.d/*ossec* && rm /etc/ossec-init.conf`

**Comment by q2dg** [comment]
I think these steps should be mentioned in official documentation. I've had to look at here to know them...it's not beautiful

**Comment by kompjuteras** [comment]
> Assuming you installed from source: `/var/ossec/bin/ossec-control stop && rm -rf /var/ossec && rm /etc/init.d/*ossec* && rm /etc/ossec-init.conf`

Just to add missing parts and to complete removal....
`
/var/ossec/bin/ossec-control stop
service ossec-hids stop
chkconfig ossec-hids --del
rm -rf /var/ossec
rm -f /etc/ossec-init.conf
rm -f /etc/init.d/*ossec*
userdel ossecr
userdel ossec
groupdel ossec
`
