### ISSUE TITLE
Problem reading log file with ossec agent

### ISSUE THREAD

**Issue by SteBoschini** [ossec/ossec-hids#1029]
Hi all
I am using alienvault USM and i need ossec HIDS agent to read log file. I have some problem when I try to read a customized log file.
I already set up the hids on a windows machine and the USM recognizes it correctly on the agent list (active status and I can see event coming from the agent).

I have a first problem when I configure the text file on the ossec configuration file, sometimes the USM does not receive the log lines and I cannot visualize the lines in the archive.log file.
I check the log file of the ossec agent but it seems to work correctly, it is running, it is connected to server and the real time monitoring is running. I can see also that it analyses the file that i want to read.

I  specify that this file is updated (overwritten) every 60 seconds.

Moreover what it does not work is when I create a new decoder on USM to parse the incoming log lines,
for example :
<decoder name="myapplication">
  <prematch>^myapplication: </prematch>
</decoder>

the ossec-logtest does not recognize the decoder (in phase 2) when I insert the line: "myapplication: this is a test."

I already tried to restart ossec service on USM and also on windows but the problems remain.

Thanky you very much

Stefano

**Comment by ddpbsd** [comment]
Can you provide any details?

- localfile configuration on the agent

- log samples

- decoder you're attempting to use

**Comment by SteBoschini** [comment]
Hi, thank you very much for the response,
I already fixed the issues

The agent server was reading the wrong decoder.xml file in another folder (not "/var/ossec/etc/local_decoder.xml" but "/var/ossec/alienvault/decoders/decoders.xml"),
I edit the conf file and now it works

Thank you
Stefano
