### ISSUE TITLE
Alerting daemon hangup

### ISSUE THREAD

**Issue by mohakkataria** [ossec/ossec-hids#1031]
Following is a log of slack integration for alerts which we have done.

2017/01/24 11:17:35 ossec-integratord: ERROR: Unable to run integration for slack -> /var/ossec/integrations/slack

After some time, such kind of error message appears out of blue and we stop getting the alerts from the ossec system to our slack channel. Although the alert.log is getting filled with new alerts, but I am unable to get the alerts on slack. And if i check the status of ossec service, it shows as running.

The issue doesnt get fixed until i restart the ossec service

**Comment by vikman90** [comment]
Hi @mohakkataria,

how did you install OSSEC? This project has no `integratord`, you may have got it from Daniel Cid's repository at BitBucket or from Wazuh. Perhaps you should report this issue on another project.

Regards.
