### ISSUE TITLE
syslog-ng timestamp log format iso

### ISSUE THREAD

**Issue by aci2** [ossec/ossec-hids#1032]
OSSEC HIDS v2.8.3 / CentOS release 6.8
default log 
Jan 26 09:20:02 localhost su[8060]: (pam_unix) session opened for user adm01 by (uid=0)
my log format 
2017-01-26T09:20:02.000+00:00 localhost sshd[8721]: pam_unix(sshd:session): session opened for user adm01 by (uid=0)

/var/ossec/bin/ossec-logtest
2017-01-26T09:20:02.000+00:00 localhost sshd[8721]: pam_unix(sshd:session): session opened for user adm01 by (uid=0)

**Phase 1: Completed pre-decoding.
       full event: '2017-01-26T09:20:02.000+00:00 localhost sshd[8721]: pam_unix(sshd:session): session opened for user adm01 by (uid=0)'
       hostname: 'syslog'
       program_name: '(null)'
       log: '2017-01-26T09:20:02.000+00:00 localhost sshd[8721]: pam_unix(sshd:session): session opened for user adm01 by (uid=0)'

**Phase 2: Completed decoding.
       No decoder matched.
	   
**how to set decoder to parse logs?**

**Comment by ddpbsd** [comment]
You'll probably have to modify analysisd to recognize the timestamp.
