### ISSUE TITLE
Incorrect rule for apache logs

### ISSUE THREAD

**Issue by alex-front** [ossec/ossec-hids#1044]
I have the following log lines:

- [Thu Feb 02 01:44:27.699327 2017] [access_compat:error] [pid 7934] [client ::1:50058] AH01797: client denied by server configuration: /var/www/html/'
- [Thu Feb 02 00:59:02.285651 2017] [core:error] [pid 20009] (13)Permission denied: [client ::1:49934] AH00132: file permissions deny server access: /var/www/html/1

I would expect to have a rule that would detect such important events. However, they are incorrectly classifiled by logtest and no alerts are fired:

[Thu Feb 02 00:59:02.285651 2017] [core:error] [pid 20009] (13)Permission denied: [client ::1:49934] AH00132: file permissions deny server access: /var/www/html/1

**Phase 1: Completed pre-decoding.
       full event: '[Thu Feb 02 00:59:02.285651 2017] [core:error] [pid 20009] (13)Permission denied: [client ::1:49934] AH00132: file permissions deny server access: /var/www/html/1'
       hostname: 'i360-dev-agent-el7-1'
       program_name: '(null)'
       log: '[Thu Feb 02 00:59:02.285651 2017] [core:error] [pid 20009] (13)Permission denied: [client ::1:49934] AH00132: file permissions deny server access: /var/www/html/1'

**Phase 2: Completed decoding.
       decoder: 'apache-errorlog'
       srcip: '::1'
       srcport: '49934'
       id: 'AH00132'

**Phase 3: Completed filtering (rules).
       Rule id: '30301'
       Level: '0'
       Description: 'Apache error messages grouped.'

I used master branch for the test. 
Please create such rules.

**Comment by ddpbsd** [comment]
If they are not Apache error messages, what are they?

**Comment by ddpbsd** [comment]
```
  <rule id="30412" level="2">
    <if_sid>30301</if_sid>
    <match>Permission denied: | client denied by server configuration: </match>
    <description>Permission denied.</description>
  </rule>
```
