### ISSUE TITLE
Website link to PGP signing key results in 404 error

### ISSUE THREAD

**Issue by torataks** [ossec/ossec-hids#1046]
The instructions at [http://ossec.github.io/downloads.html#pgp-key](http://ossec.github.io/downloads.html#pgp-key) refer to a non-functional link, [https://ossec.github.io/files/OSSEC-ARCHIVE-KEY.asc](https://ossec.github.io/files/OSSEC-ARCHIVE-KEY.asc).  I had to retrieve the key from a keyserver instead.

Also, there should be two dashes in front of the gpg "import" and "verify" commands.

**Comment by ddpbsd** [comment]
https://github.com/ossec/ossec-docs/pull/194 should fix the dash issue. Not sure why the key isn't uploaded yet.

**Comment by torataks** [comment]
Thanks!  Also the link to the PGP key is working now.
