### ISSUE TITLE
Apache file name too long rule

### ISSUE THREAD

**Issue by alex-front** [ossec/ossec-hids#1053]
When running a scanner against an apache server I see lines like this in error_log:

'[Tue Feb 07 09:59:05.775395 2017] [core:error] [pid 14442] (36)File name too long: [client 10.101.1.50:51286] AH00036: access to /oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo failed'

OSSEC does not generates alerts for this:

**Phase 1: Completed pre-decoding.
       full event: '[Tue Feb 07 09:59:05.775395 2017] [core:error] [pid 14442] (36)File name too long: [client 10.101.1.50:51286] AH00036: access to /oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo failed'
       hostname: 'i360-dev-agent-el7-1'
       program_name: '(null)'
       log: '[Tue Feb 07 09:59:05.775395 2017] [core:error] [pid 14442] (36)File name too long: [client 10.101.1.50:51286] AH00036: access to /oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo failed'

**Phase 2: Completed decoding.
       decoder: 'apache-errorlog'
       srcip: '10.101.1.50'
       srcport: '51286'
       id: 'AH00036'

**Phase 3: Completed filtering (rules).
       Rule id: '30301'
       Level: '0'
       Description: 'Apache error messages grouped.'

There are 2 rules concerning this kind of event: 30117, 30317 but none of them are fired.

**Comment by ddpbsd** [comment]
```
<rule id="30319" level="10">
    <if_sid>30301</if_sid>
    <id>AH00036</id>
    <match>File name too long: </match>
    <description>File name too long.</description>
  </rule>
```
