### ISSUE TITLE
bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by jerryemby** [ossec/ossec-hids#1058]
When the active response calls the script sendsnmptrap.sh it is using this line below to pass parameters.  The issue is it is adding the () brackets around the hostname which the shell doesn't like.  Is there a way to modify agent so it doesn't use the brackets around the parameters?

/var/ossec/active-response/bin/sendsnmptrap.sh add - - 1486672874.7898221 550 (wisldap3) 10.3.5.213->syscheck -
-bash: syntax error near unexpected token `('

Here is an example from local server and remote server

Thu Feb  9 14:20:51 CST 2017 /var/ossec/active-response/bin/sendsnmptrap.sh add - - 1486671651.7805203 550 syscheck -

Remote:
Thu Feb  9 14:41:14 CST 2017 /var/ossec/active-response/bin/sendsnmptrap.sh add - - 1486672874.7898221 550 (wisldap3) 10.3.5.213->syscheck -

**Comment by ddpbsd** [comment]
You'll probably have to modify analysisd(?) to either not print the parentheses or escape them properly.

**Comment by ddpbsd** [comment]
I also don't see `sendsnmptrap.sh` in the source tree, is it stored somewhere strange?

**Comment by jerryemby** [comment]
The sendsnmptrap.sh is not having the problem with the ( ) is the shell itself. If you take any Linux script and try to pass parameters enclosed in ( ) that error is encounter.  If you want a copy of the script I will glad to provide it.

**Comment by jerryemby** [comment]
How does one modify the analysisd  bin?  Is that the executable to called the sendsnmptrap.sh script I point to?

**Comment by ddpbsd** [comment]
`ossec-execd ` executes the script. I'm a little fuzzy on how ARs are triggered inside OSSEc, so guessed with analysisd. But execd might be the easier place to do it.

**Comment by jerryemby** [comment]
I'm not sure what do with this are you suggesting to use execd verse calling the script?  It just seems to be a bug in the OSSEC code to call a script with parameters.  Is there someone I can talk to?

**Comment by ddpbsd** [comment]
I'm saying that adding the code to escape the parameter might best be added to execd. 
What kind of person do you want to talk to?

**Comment by jerryemby** [comment]
The OSSEC code is passing the parameters so I don’t have that control. Are you a developer of the OSSEC product I could talk with?  Jerry

**Comment by ddpbsd** [comment]
I fiddle with the code on occasion. This isn't a problem I've come across, so I haven't looked into it much. I'm not even sure which field is being passed to the AR script that's causing the issue.

**Comment by jerryemby** [comment]
Dan,

            When the script is called by the action response from ossec it passes these parameters to the script.


ACTION=$1       # Action to do, not used here

USER=$2         # User extracted by decoder

IP=$3           # Ip extracted by decoder

ALERTID=$4      # The alert ID a unique number for each alert fired

RULEID=$5       # The Rule ID


echo "`date` $0 $1 $2 $3 $4 $5 $6 $7 $8" >> ${PWD}/../logs/active-responses.log
The contents of the active-respones.log is below.

Sun Feb 12 05:19:26 CST 2017 /var/ossec/active-response/bin/sendsnmptrap.sh add - - 1486898366.1787499 550 syscheck –

Regards,
Jerry

**Comment by atomicturtle** [comment]
whats the log event for this AR look like?

**Comment by ddpbsd** [comment]
Can you provide your active response configuration?

**Comment by jerryemby** [comment]
I sorry I have figure a way to get around this in my code.  I’m all set for now.  Thanks

**Comment by ddpbsd** [comment]
I'll continue trying to reproduce it, and fix it if I do.
