### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [ossec/ossec-hids#1060]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by ypid** [comment]
Overlooked it, sorry! https://bestpractices.coreinfrastructure.org/projects/31

**Comment by atomicturtle** [comment]
No problem!  With many thanks to David Wheeler at IDA for introducing us to the certification project and loaning us an intern to finish up some of the paperwork
