### ISSUE TITLE
Ossec 2.9.0 agent upgrade failure on Aix

### ISSUE THREAD

**Issue by keith-mo** [ossec/ossec-hids#1075]
Hi

Getting the following errors when trying to upgrade an agent from 2.8.3 to 2.9.0 on Aix 7.1

5- Installing the system
 - Running the Makefile
cd external/lua/ && make posix
make[1]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3'
cd src && make posix
make[2]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make all SYSCFLAGS="-DLUA_USE_POSIX"
make[3]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[2]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[1]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3'
    CC os_auth/main-client.o
/bin/sh: cc:  not found.
Makefile:1007: recipe for target 'os_auth/main-client.o' failed
make: *** [os_auth/main-client.o] Error 127

 Error 0x5.
 Building error. Unable to finish the installation.``

**Comment by ddpbsd** [comment]
Do you have gcc installed?

**Comment by keith-mo** [comment]
Yes

```
# echo $CC
gcc
# which gcc
/usr/bin/gcc
# gcc --version
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ddpbsd** [comment]
I'll assume you're making an agent at the moment, but use the appropriate target if you're not.
Try:
```
cd src
make TARGET=agent V=1 2>&1 | tee /tmp/buildlog
```
Then put that buildlog somewhere I can see it. :-)

**Comment by keith-mo** [comment]
i was just upgrading the agent from 2.8.3 to 2.9.0 on aix 7.1 using the /install.sh when i got the above error messages.

here's the buildlog..

cd external/lua/ && make posix
make[1]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3'
cd src && make posix
make[2]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make all SYSCFLAGS="-DLUA_USE_POSIX"
make[3]: Entering directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[2]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3/src'
make[1]: Leaving directory '/tmp/ossec-hids-2.9.0/src/external/lua-5.2.3'
cc  -O2 -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DAIX -DAIX -DHIGHFIRST -DPICVIZ_OUTPUT_ENABLED -DLIBOPENSSL_ENABLED -DCLIENT -Wall -Wextra -I./ -I./headers/  -I./os_auth -DARGV0=\"ossec-authd\" -c os_auth/main-client.c -o os_auth/main-client.o
make: cc: Command not found
Makefile:1007: recipe for target 'os_auth/main-client.o' failed
make: *** [os_auth/main-client.o] Error 127

**Comment by keith-mo** [comment]
if its any help, i can compile the agent on the same server for version 2.8.3.

version 2.9.0 fails both the compile and upgrade..

**Comment by felipee07** [comment]
http://www.linuxquestions.org/questions/linux-newbie-8/make-cc-command-not-found-make-***-%5Bmain-o%5D-error-127-on-opensuse-11-3-a-860641/

**Comment by ddpbsd** [comment]
2.8.3 was very different, and unfortunately I don't have a way to test AIX.
You can try setting $CC to gcc, just to see if that works. I can't really see anything in the build log that points to where it's getting "cc" from.

**Comment by mkvocka** [comment]
I had a similar issue a while ago with Ossec 2.9.0 on AIX 6.1, but not with 2.8.3. I think the culprit is install.sh, but didn't spend too much time on it. According to my notes I didn't use install.sh but compiled in src/ with the following:

gmake PREFIX=/opt/ossec TARGET=agent CC=/usr/bin/gcc USE_OPENSSL=no LUA_USE_POSIX=yes build

(note the gmake instead of make)

This was compiled on a lab machine, I then created an agent archive for distribution manually, without install.sh. If you can't get it to work I'll have a look at the install.sh again and will try to debug it.
