### ISSUE TITLE
Error with eventchannel

### ISSUE THREAD

**Issue by ebdavison** [ossec/ossec-hids#1076]
I have added a new eventchannel log for Windows Server Backup as follows:

`
  <localfile>
    <location>Microsoft-Windows-Backup/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>
`

This results in the following error of which I saw no reference in any other issue:

`
2017/03/01 11:15:11 ossec-agent(1951): INFO: Analyzing event log: 'Microsoft-Windows-Backup/Operational'.
2017/03/01 11:15:11 ossec-agent: ERROR: Could not EvtSubscribe() for (Microsoft-Windows-Backup/Operational) which returned (15007)
`

**Comment by awiddersheim** [comment]
According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681384(v=vs.85).aspx) that error means the event channel can't be found:

```
ERROR_EVT_CHANNEL_NOT_FOUND
15007 (0x3A9F)
The specified channel could not be found. Check channel configuration.
```

You sure you have the right name?

**Comment by ebdavison** [comment]
This is the log name per Event Viewer:

`Microsoft-Windows-Backup/Operational`

However, this is what is the the system section of a log entry in the XML viewer:

`Microsoft-Windows-Backup`

I am going to try without "/Operational" and see if it likes it any better ...

**Comment by ebdavison** [comment]
Seems I do not get an error when changing to `Microsoft-Windows-Backup` as the log name but now I need to get these events to the SIEM ... One thing at a time, I guess.
