### ISSUE TITLE
<auto_ignore>no</auto_ignore> not working!!!

### ISSUE THREAD

**Issue by JTSEC** [ossec/ossec-hids#1081]
Hello everyone,

I've been trying to make this feature work, I created a directory under Documents/FMI_TEST in it I have two files one of them is a text file. It is my understanding that OSSEC can monitor in "realtime" but after the 3rd time I modified the file ( in the directory) , I stopped receiving notifications.  Even if not reporting changes on the file itself, it should have reported changes on the Directory (hash)

I checked on the Server and is is not getting any new notifications:
#/var/ossec/bin/syscheck_control -i 001

I'm not sure if the "auto_ignore" option must be configured on a different file or location. Any advise?

Below is the config on  the agent. (/var/ossec/etc/ossec.conf

Running Ubuntu 14 x64
--------------------------------------------------------------------
<ossec_config>
  <client>
    <server-ip>192.168.100.253</server-ip>
  </client>

  <syscheck>
    
    <auto_ignore>no</auto_ignore>

    
    <frequency>79200</frequency>
    
    
    <directories realtime="yes" check_all="yes" restrict=".txt>/home/ubuntu1/Documents/FMI_TEST</directories>

**Comment by ddpbsd** [comment]
Disabling auto ignore must happen on the ossec server, not the agents.

**Comment by JTSEC** [comment]
ThanK you so much! it worked :+1:
