### ISSUE TITLE
Queue connection refused

### ISSUE THREAD

**Issue by mzar5584** [ossec/ossec-hids#1087]
Hi,

Yesterday it's look no problem at all. But i notice not receive any alert.
Then i check log. Get those error:

2017/03/09 11:08:54 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/03/09 11:08:54 ossec-rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/03/09 11:09:07 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/03/09 11:09:07 ossec-rootcheck(1211): ERROR: Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..

total 0
srwxr-xr-x 1 root root 0 Feb 28 09:47 queue

Any idea what i miss?

Thanks./

**Comment by mzar5584** [comment]
I get this error on every agent:
2017/03/09 11:58:29 ossec-logcollector: INFO: Started (pid: 18938).
2017/03/09 11:58:31 ossec-logcollector: WARN: Process locked. Waiting for permission...
2017/03/09 11:58:42 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '42.0.xxx.yyy'.
2017/03/09 11:58:44 ossec-agentd: INFO: Trying to connect to server (42.0.xxx.yyy:1514).
2017/03/09 11:58:44 ossec-agentd: INFO: Using IPv4 for: 42.0.xxx.yyy .
2017/03/09 11:59:06 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '42.0.xxx.yyy'.

I have flush already iptables on ossec server. Still getting same error.

**Comment by ddpbsd** [comment]
Check the status of the processes on the OSSEC server:
`/var/ossec/bin/ossec-control status`

Is ossec-remoted running?
