### ISSUE TITLE
Analogi

### ISSUE THREAD

**Issue by quangvi282** [ossec/ossec-hids#1098]
why database has data but amcharts of analogi not show anything just note: No data found, but everything checks out ok. Try broadening your search parameters.. Please help me soon

**Comment by quangvi282** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7436522/24394382/fe4542ee-13c5-11e7-94f5-0883ae488067.png)
)

**Comment by ddpbsd** [comment]
This question could be better addressed by Anologi. Perhaps someone with experience with that product is on the mailing list.
