### ISSUE TITLE
ossec-auth SSL error (server doesn't support version client proposes)

### ISSUE THREAD

**Issue by dwendt** [ossec/ossec-hids#1105]
v2.8.3 - Server is running the el5 package, agent is running the el7 package.

**Edit:** OK so, I think this is caused by openssl 0.9.8 on the server not supporting the version of SSL/TLS the client proposes. Looking at the source code for the client connection, [it looks like it attempts TLSv1_2](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/os_auth/ssl.c#L113) but the server, being 0.9.8 can't parse the TLSv1_2 clienthello so they fail to negotiate to any other supported method (TLSv1_1 / SSLv3). I think this might be fixed by using the base [SSLv23 clienthello](http://stackoverflow.com/questions/23709664/openssl-let-the-server-and-client-negotiate-the-method) -- SSLv2 will still be disabled according to the rest of the linked code.

On the server we see:
```
2017/04/06 19:18:02 ossec-authd: ERROR: SSL Accept error (0)
2017/04/06 19:18:02 ossec-authd: INFO: New connection from 10.80.27.128
2017/04/06 19:18:03 ossec-authd: ERROR: SSL read error (0)
```

On the client:
```
# ./agent-auth -m ossecl01.ilcb.tcprod.local -d
2017/04/06 19:18:02 ossec-authd: DEBUG: Starting ...
2017/04/06 19:18:02 ossec-authd: INFO: Started (pid: 34908).
2017/04/06 19:18:02 ossec-authd: DEBUG: Returning CTX for client.
139761794611136:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:339:
2017/04/06 19:18:02 ossec-authd: ERROR: SSL error (-1). Exiting.
```

A cursory google shows that error occurs when an SSLv3 client attempts to connect to a server that doesn't support it. I'm not sure that is the case here.

openssl @ server:
```
openssl.x86_64                   0.9.8e-40.0.3.el5_11
```

openssl @ client:
```
openssl.x86_64                    1:1.0.1e-60.el7_3.1
```

**Comment by ddpbsd** [comment]
I don't think we want anything below tls 1.2 to work. Perhaps it's time to upgrade openssl?

**Comment by dwendt** [comment]
@ddpbsd TLS1.0/1.1 aren't insecure, attacks against them are flimsy at best (BEAST - don't use CBC, POODLE - downgrades don't apply here).

**Comment by ddpbsd** [comment]
Just covering our bases. Why support something that has weaknesses when no modern system has issues with the latest and greatest? 
If you really want to support the old versions, submit a pull request.
