### ISSUE TITLE
Right way to monitor server localhost?

### ISSUE THREAD

**Issue by cwynd** [ossec/ossec-hids#1117]
We have an ossec server managing about 30 agents, and everything is working very well (2 yrs +), with ossec web ui and analogi on the front end.

I have to extend this to monitor the localhost that the ossec server itself is running on, but after an hour of searching I cannot find clear guidance on how to set this up, hence the subject question.

It seems an obvious requirement, is there a right way to do this? I would rather not reinstall from scratch if at all possible, given I have a fairly large installation working flawlessly right now.

Thanks for any advice.

Ossec 2.8.1 compiled from source
OS: Debian 7.7

**Comment by ddpbsd** [comment]
The server should monitor its own logs and file integrity, just like an agent. What further functionality are you searching for?

**Comment by cwynd** [comment]
Thanks - yes it does. I am probably missing something, but as far as I can tell it does not show up in the web UI 'Available Agents' list or the 'Integrity checking' agent name list. I use these two to confirm that each agent is 'alive', and to monitor modified files.

**Comment by ddpbsd** [comment]
The wui has been discontinued for several years.  Do the server's alerts show up in alerts.log? Is the server's sycheck db updated (`/var/ossec/queue/syscheck/syscheck` I think)?

**Comment by cwynd** [comment]
Yes they do show up, and I think so i.e. if I tail /var/ossec/queue/syscheck/syscheck (you were right) the last timestamp in there is sometime ago, but it does correspond to the last changes I remember making. So I think I can assume all is fine.

Do updates to /var/ossec/queue/syscheck/syscheck get surfaced for quick review anywhere? All my other agents I can quickly review filesystem changes, correlate with known activity, and flag where necessary for closer inspection.

Thanks and sorry if this is all a silly question

**Comment by pgporada** [comment]
@cwynd Your questions helped me out 👍

**Comment by ddpbsd** [comment]
@cwynd I'm sorry, I don't understand the question. The OSSEC server is treated as agent 000. syscheck alerts get logged the same way they do for other agents.

**Comment by cwynd** [comment]
Sorry for the confusion: I actually now found the ossec server in the analogi reporting. What confused me was that it does not appear in the 'Available agents' list from manage_agents. I had to turn the analogi rule threshold down to 2 to see it start to appear. I guess it is just very quiet from a IDS point of view (as it should be of course).

@ddpbsd thanks for your help and patience.
