### ISSUE TITLE
Please default to HTTPS on ossec.github.io

### ISSUE THREAD

**Issue by benbailess** [ossec/ossec-hids#1118]
The site "supports" HTTPS, but it doesn't default to it. So coming from a search engine like Google, users are prompted with a plain HTTP site experience. Especially since the site offers downloads of packages and signatures, these pages especially should be served over HTTPS.

Sure, it's easy enough for any competent and sufficiently paranoid admin / user to manually switch over to HTTPS (or use an extension like HTTPS Everywhere), but it should be necessary considering the minimal effort these days to enforce HTTPS. 

Thank you,

Ben

**Comment by ddpbsd** [comment]
Thanks, didn't even know that was an option.
