### ISSUE TITLE
after editing /var/ossec/rules/local_rules.xml getting error on ossec-control restart

### ISSUE THREAD

**Issue by d1my4n** [ossec/ossec-hids#1119]
hello,
i just tried to add some rules to the ossec
i tried few times just like in the tutorials
and everytime i finish editing the local_rules.xml file and try to restart ossec-control
i get ossec-analysisd ERROR

it happens only if i modify the rules file..

**Comment by ddpbsd** [comment]
What error do you see in the ossec.log?

**Comment by d1my4n** [comment]
When I add:
<rule id=”554″ level=”7″ overwrite=”yes”>
<category>ossec</category>
<decoded_as>syscheck_new_entry</decoded_as>
<match>/var/www/html/[site directory]</match>
<description>File added to the [site] directory.</description>
<group>syscheck</group>
</rule>

To:   /var/ossec/rules/local_rules.xml

I get:
root@ubuntu:/var/ossec/bin# ossec-control restart
ossec-control: command not found
root@ubuntu:/var/ossec/bin# ./ossec-control restart
Killing ossec-monitord .. 
Killing ossec-logcollector .. 
Killing ossec-syscheckd .. 
Killing ossec-analysisd .. 
ossec-maild not running ..
Killing ossec-execd .. 
OSSEC HIDS v2.9.0 Stopped
Starting OSSEC HIDS v2.9.0 (by Trend Micro Inc.)...
ossec-analysisd: Configuration error. Exiting.

**Comment by d1my4n** [comment]
The protection filtered: 
rule id=”554″ level=”7″ overwrite=”yes”
category ossec /category
decoded_as syscheck_new_entry /decoded_as
match /var/www/html/[site directory] /match
description File added to the [site] directory ./description
group syscheck /group
/rule

**Comment by ddpbsd** [comment]
What error do you see in the ossec.log?

**Comment by d1my4n** [comment]
Thx
