### ISSUE TITLE
Disabling Specific Alert?

### ISSUE THREAD

**Issue by Ruok2bu** [ossec/ossec-hids#1123]
My email keeps getting spammed with 1 specific error message (its the result of a 3rd party script i have no idea how to fix) and i have no idea how to disable the alert rather than disable all alerts for mysql.  The alert is:

OSSEC HIDS Notification.
2017 May 14 06:00:13

Received From: xxxxxxxxx->/var/log/syslog
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

May 14 06:00:12 xxxxxxxxx mysqld[1877]: 2017-05-14  6:00:12 121304217373440 [Warning] Aborted connection 39260 to db: 'xxx' user: 'xxx' host: 'xxx.xxx.xxx.xxx' (Got an error reading communication packets)

Any idea how to make the rule that stops this spam?

**Comment by snaow** [comment]
Hi,

Rule 1002 has enable setting *"<options>alert_by_email</options>" *which
will send the email no matter what.
Open file syslog_rules.xml and remove the <options> line. Restart your
manager to apply changes.

Best regards,
Pedro.

**Comment by ddpbsd** [comment]
The following rule will match that log message, and should silence it for you. Turning off the email option for sid 1002 is not something we recommend.

```
  <rule id="400001" level="0">
    <if_sid>1002</if_sid>
    <program_name>mysqld</program_name>
    <match>Got an error reading communication packets)$</match>
    <description>ignore this message</description>
  </rule>
```

**Comment by Ruok2bu** [comment]
ddpbsd, Awesome

These past few days i've been investigating what's been happening and i think i have it solved.  But thanks for the information anyhow.
