### ISSUE TITLE
Email alerts level not respected

### ISSUE THREAD

**Issue by bastienk** [ossec/ossec-hids#1128]
Hello,

I only want email notifications for alerts > 10. I added the following in my configuration:
```
   <email_alerts>
      <email_to>xxxxx@xxxx.xx</email_to>
      <level>10</level>
   </email_alerts>
   <alerts>
     <log_alert_level>1</log_alert_level>
     <email_alert_level>10</email_alert_level>
   </alerts>
```

But I am still getting emails from alerts < 10. I checked the documentation but didn't find something to help me with my issue. Am I doing something wrong or is it a real issue?

Thank you!

**Comment by ddpbsd** [comment]
Do these rules have the email alert option set?

**Comment by Cramix** [comment]
Rules (in .xml files) have the `<options>alert_by_email</options>` enabled.
Is it overwriting my `<email_alert_level rule>`?

**Comment by ddpbsd** [comment]
It over rides that option, yes.

**Comment by epicavic** [comment]
it's possible to override rule with local rule thus silencing it
for example:

add to file /var/ossec/rules/local_rules.xml

<group name="local,">
  
  <rule id="100001" level="2">
    <if_sid>xxx</if_sid>
      <description>Ignore xxx rule message</description>
  </rule>
</group>


if you need to search for a certain pattern in triggered rule and silence only it you can add following regex matching section right after the <if_sid>xxx</if_sid>
      <regex>some string you're looking for</regex>
