### ISSUE TITLE
Ossec server disconnect with agent when revert VMware snapshot

### ISSUE THREAD

**Issue by samz-github** [ossec/ossec-hids#1129]
Restarting Ossec service is not working. I have to remove Ossec agent and register again to resolve this issue. Can you fix this issue?

**Comment by ddpbsd** [comment]
Have you disabled rids? The agents and server track how many messages are passed, and the server ignores duplicates. If you roll back an agent, it may re-use an ID and be considered sending duplicate messages. Disabling rids will solve this.

**Comment by samz-github** [comment]
Thanks Dan for your quick respond, I didn't disable rids before. How to disable rids? I will have a try in next time.

**Comment by ddpbsd** [comment]
I believe it is this option in internal_options.conf:
```
# Verify msg id (set to 0 to disable it)
remoted.verify_msg_id=1
```
