### ISSUE TITLE
Line number in error message

### ISSUE THREAD

**Issue by tomlobato** [ossec/ossec-hids#1133]
When I try to restart the agent locally:

```$ /etc/init.d/ossec restart```
2017/05/29 20:17:50 ossec-logcollector(1202): ERROR: **Configuration error at** '/var/ossec/etc/shared/agent.conf'. Exiting.

How could I get the line number? Shouldn`t it be there by default?

**Comment by nbuuck** [comment]
@tomlobato [logcollector/config.c:15](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/logcollector/config.c#L15) invokes `ReadConfig()` which should write the line number where the error occurred (from `xml.err_line`) to the _debug_ log via `merror()` if debugging is [enabled](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/logcollector/config.c#L15). The call stack to read the config generally returns `int` to the caller, so there's no opportunity to pass the error context like line number up to `LogCollectorConfig()` in [logcollector/main.c](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/logcollector/main.c#L110) where the log line you provided is generated.

**Comment by nbuuck** [comment]
@tomlobato The line number `xml.err_line` should be written to `/logs/ossec.log` in the context of the call stack

_log() in shared/debug_op.c
merror() in shared/debug_op.c
ReadConfig() in [config/config.c:156](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/config/config.c#L156) (`xml.err_line` is passed here)
LogCollectorConfig() in logcollector/config.c
main() in logcollector/main.c

You could try enabling [debugging](http://ossec-docs.readthedocs.io/en/latest/faq/unexpected.html#how-to-debug-ossec) but that shouldn't actually be necessary based on what's in the source.

**Comment by casare** [comment]
It doesnt show up in the ossec.log...

```cat logs/ossec.log |grep Configur```
2017/05/29 20:01:45 ossec-logcollector(1202): ERROR: Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.

Maybe enabling debug, I will try, thanks!

**Comment by nbuuck** [comment]
@casare I misread, the error is being generated at [config/config.c:179](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/config/config.c#L179), not :156. This error is thrown when the first child element of the root element of the XML config doc has no child elements. Line numbers appear to only be indicated when the XML itself is malformed. In this case, the XML itself is well-formed markup but not logically acceptable to `ReadConfig()`.

Uploading a Gist of agent.conf (after sanitizing any secret/private values) and linking it in this issue or to the [mailing list](https://groups.google.com/forum/#!forum/ossec-list) may make it easier for someone to spot the issue.

**Comment by casare** [comment]
I see.
The error was solved before my first reply. I had command and full command in agent.conf.
Thanks!

**Comment by ddpbsd** [comment]
The ossec.log generally has a log entry previous to the "configuration failed" message that should give more information. It's not perfect, but it's what we have at the moment.
