### ISSUE TITLE
active-response on Master

### ISSUE THREAD

**Issue by tomlobato** [ossec/ossec-hids#1134]
On ossec 2.9, this active response is set on master:
```xml
  <active-response>
    <command>firewall-drop</command>
    <location>all</location>
    <level>6</level>
    <timeout>600</timeout>
  </active-response>  
```
When I try a ssh brute force on any client, active response triggers for everybody but the master. Shouldn`t ```<location>all</location>``` makes firewall-drop run on all machines?

**Comment by ddpbsd** [comment]
It should run on all sensors. If you want it to work on the server as well, add a second `<active-response>` block with `<location>server</location>` (I think)
