### ISSUE TITLE
v2.9 update failed at ossec-authd

### ISSUE THREAD

**Issue by yawnbox** [ossec/ossec-hids#1138]
Hello,

I am attempting to update from v2.8.3 to v2.9. I receive the following error during the update:

<pre>    CC ossec-authd
os_auth/ssl.o: In function `get_ssl_context':
ssl.c:(.text+0x10d): undefined reference to `OPENSSL_init_ssl'
ssl.c:(.text+0x119): undefined reference to `OPENSSL_init_ssl'
ssl.c:(.text+0x125): undefined reference to `OPENSSL_init_crypto'
ssl.c:(.text+0x144): undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
Makefile:1013: recipe for target 'ossec-authd' failed
make: *** [ossec-authd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.</pre>

Cheers

**Comment by ddpbsd** [comment]
Do you have the openssl development package installed? Which version?

**Comment by yawnbox** [comment]
1.0.2l-0~ubuntu16.04.1+deb.sury.org+1

**Comment by ddpbsd** [comment]
Is this the dev package, or just the regular package? Which version of ubuntu?

**Comment by yawnbox** [comment]
libssl-dev 1.0.2l for Ubuntu Server 16.04 as part of openssl 1.0.2l

However, it seems I have two versions of openssl installed -- 1.0.2l is a dependency for Let's Encrypt Certbot.

<pre>openssl version

OpenSSL 1.1.0f  25 May 2017</pre>

**Comment by ddpbsd** [comment]
I have a similar problem on one of my systems, but I haven't looked into how to work around it yet.

**Comment by atomicturtle** [comment]
For what its worth, this is not an issue with the ubuntu 16 package: 2.9.0-1681xenial
