### ISSUE TITLE
1002 

### ISSUE THREAD

**Issue by Trapulo** [ossec/ossec-hids#1152]
Hi,
from a few days (I think after the last upgrade of OSSEC) OSSEC 2.9 started to report from my AD controllers a lot of this alerts. Is there some bug? What's this?

thanks

Level:
2 - Unknown problem somewhere in the system.
Rule Id:
1002
Location:
(Server) xx.xx.xx.xx->WinEvtLog
2017 Jun 28 09:13:42 WinEvtLog: Security: AUDIT_SUCCESS(4776): Microsoft-Windows-Security-Auditing: (no user): no domain: Server.domain.local: The computer attempted to validate the credentials for an account. Authentication Package: MICROSOFT_AUTHENTICATION_PACKAGE_V1_0 Logon Account: username
 Source Workstation: PC01 Error Code: 0x0

**Comment by ddpbsd** [comment]
Try 2.9.1. There were some issues with the Windows decoder in 2.9.0.

**Comment by Trapulo** [comment]
I've installed with rpm from Atomic and 2.9.1 has not been yet deployed... :(

**Comment by ddpbsd** [comment]
I'm not seeing this behavior with an updated system:
```
**Phase 1: Completed pre-decoding.
       full event: '2017 Jun 28 09:13:42 WinEvtLog: Security: AUDIT_SUCCESS(4776): Microsoft-Windows-Security-Auditing: (no user): no domain: Server.domain.local: The computer attempted to validate the credentials for an account. Authentication Package: MICROSOFT_AUTHENTICATION_PACKAGE_V1_0 Logon Account: username'
       hostname: 'ix'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4776): Microsoft-Windows-Security-Auditing: (no user): no domain: Server.domain.local: The computer attempted to validate the credentials for an account. Authentication Package: MICROSOFT_AUTHENTICATION_PACKAGE_V1_0 Logon Account: username'

**Phase 2: Completed decoding.
       decoder: 'windows'
       status: 'AUDIT_SUCCESS'
       id: '4776'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'Server.domain.local'

**Phase 3: Completed filtering (rules).
       Rule id: '18104'
       Level: '0'
       Description: 'Windows audit success event.'
```

**Comment by Trapulo** [comment]
so my problem starting from 2.9.0 upgrade has no explanation?

p.s. why 2.9.1 has been released as rpm only for CentOS 7?
