### ISSUE TITLE
Missing source IP - SSHD decoder

### ISSUE THREAD

**Issue by xJota** [ossec/ossec-hids#1156]
Hi everyone,

I'm not sure if this is a bug, or just something that has not yet been fully developed, but the srcip element is missing from this rule:

```{"rule":{"level":8,"comment":"Possible attack on the ssh server (or version gathering).","sidid":5701,"group":"syslog,sshd,"},"id":"1498674940.113598","TimeStamp":1498674940000,"decoder":"sshd","decoder_parent":"sshd","location":"(xxx.xxx.xxx.xxx) 10.66.0.3->/var/log/secure","full_log":"Jun 28 19:35:39 xxx sshd[30255]: Bad protocol version identification '' from 188.18.81.21 port 60787","hostname":"(xxx.xxx.xxx.xxx) 10.66.0.3->/var/log/secure","program_name":"sshd"}```

The srcip element is missing from the JSON, and it can be seen in the full_log. 

I'm using the latest OSSEC version pulled from the master branch.

Is this intended?

**Comment by ddpbsd** [comment]
It looks like the current decoder doesn't expect the port information.
```
<decoder name="ssh-scan2">
  <parent>sshd</parent>
  <prematch>^Did not receive identification|^Bad protocol version</prematch>
  <regex offset="after_prematch"> from (\S+)$</regex>
  <order>srcip</order>
</decoder>
```
Removing the `$` seems to fix it.
```
**Phase 1: Completed pre-decoding.
       full event: 'Jun 28 19:35:39 xxx sshd[30255]: Bad protocol version identification '' from 188.18.81.21 port 60787'
       hostname: 'xxx'
       program_name: 'sshd'
       log: 'Bad protocol version identification '' from 188.18.81.21 port 60787'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       srcip: '188.18.81.21'
```

**Comment by xJota** [comment]
Thank you, I should start learning more about decoders :)

If you prefer I can open another issue, but I found a similar issue with another decoder:

This is my log sample:
```{"rule":{"level":5,"comment":"User login failed.","sidid":5503,"group":"pam,syslog,authentication_failed,"},"id":"1498687286.455476","TimeStamp":1498687286000,"decoder":"pam","decoder_parent":"pam","dstuser":"lipjigaglgihgoeadcdaa.p.salmon@xxx.xxx.xxx.xxx","location":"(xxx.xxx.xxx.xxx) 10.66.0.12->/var/log/secure","full_log":"Jun 28 23:01:27 xxxx auth: pam_unix(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=lipjigaglgihgoeadcdaa.p.salmon@xxx.xxx.xxx.xxx rhost=91.195.103.44 ","hostname":"(xxx.xxx.xxx.xxx) 10.66.0.12->/var/log/secure","program_name":"auth"}```

Notice the space after the rhost IP. I have no idea why it's there but it happens several times. This causes the decoder to miss the srcip. I guess this is the one?

```<decoder name="pam-ruser">
  <parent>pam</parent>
  <regex> rhost=(\S+)$</regex>
  <order>srcip</order>
</decoder>```

Once again removing the $ will do it, but in this case I'm not sure what that space is doing at the end.

**Comment by ddpbsd** [comment]
I'll take a look at it, this issue will be fine.
