### ISSUE TITLE
Ossec package which supports sles11 sp4?

### ISSUE THREAD

**Issue by cookie33** [ossec/ossec-hids#1160]
Hi,

Which rpm should we use for sles11sp4? Is there a build for that version of OS?

**Comment by ddpbsd** [comment]
I'm not aware of a Suse specific rpm.

**Comment by cookie33** [comment]
So can we just use the one also mentioned for Centos?

**Comment by atomicturtle** [comment]
It might work, give it a shot and see what happens

**Comment by ddpbsd** [comment]
*report what happens

SLES isn't something we test. I think we cover the main linux distros (ubuntu and rhel), but not many of the niche ones.
