### ISSUE TITLE
Unable to set maxagents

### ISSUE THREAD

**Issue by enunez16** [ossec/ossec-hids#1163]
Wanting to adjust the maxagents allowed on version 2.9.1, but unable to run the make command to do so.

```
# make setmaxagents
make: *** No rule to make target `setmaxagents'.  Stop.
```

**Comment by ddpbsd** [comment]
It looks like you can run `make MAXAGENTS=NUMBER_OF_AGENTS` now

**Comment by enunez16** [comment]
Ended up needing a target, so ran it like this.
`# make TARGET=server MAXAGENTS=2048`

Thanks!
