### ISSUE TITLE
Debian stretch install is broken

### ISSUE THREAD

**Issue by drewcrawford** [ossec/ossec-hids#1167]
```
$ apt-get install ossec-hids
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ossec-hids : Depends: libmysqlclient18 but it is not installable
              Depends: libssl1.0.0 but it is not installable
```

Neither `libmysqlclient18` nor `libssl1.0.0` are stretch packages.  For `libssl1.0.0` I assume is meant [libssl1.0.2](https://packages.debian.org/stretch/libssl1.0.2), for `libmysqlclient18` it may be meant [libmariadbclient18](https://packages.debian.org/stretch/libmariadbclient18).

It isn't clear to me if this is just an ABI-compatible dependency change or if a recompile is necessary with these dependencies.

**Comment by atomicturtle** [comment]
Thanks drew! Would it be possible for you test this version from the testing repo?

https://updates.atomicorp.com/channels/atomic-testing/debian/pool/main/o/ossec-hids-server/ossec-hids-server_2.9.1.1801stretch_amd64.deb

**Comment by GiantRavens** [comment]
Using the testing repo linked above installed properly on Debian stretch and didn't trigger the dependency issues drew noticed.

**Comment by drewcrawford** [comment]
Testing package works for me

**Comment by ad-clearhaus** [comment]
This package doesn't seem to have made it into the official mirror yet. Any update on that?

**Comment by Napsty** [comment]
Same problem here, just tried to install ossec-hids from http://ossec.wazuh.com/repos/apt/debian for Debian Stretch and get the same error. It's June 2018 now.
Package version from repository is 2.8.3-4stretch.

```
# apt-cache show ossec-hids | grep -i version
Version: 2.8.3-4stretch
```

**Comment by Napsty** [comment]
After switching to Atomicorp repository (instructions http://www.ossec.net/downloads.html), server package (ossec-hids-server) now installs fine on Stretch.

```
# apt-cache show ossec-hids-server | grep -i version
Version: 2.9.3.4466stretch

# dpkg -l|grep ossec
ii  ossec-hids-server               2.9.3.4466stretch              amd64        OSSEC Server - Host Based Intrusion Detection System
```

**Comment by jerm** [comment]
This issue has resurfaced in 3.3.0, thought 3.2.0 seems to be fine
