### ISSUE TITLE
SMTP client speaks before its turn

### ISSUE THREAD

**Issue by jknockaert** [ossec/ossec-hids#1175]
The OSSEC hids SMTP client speaks before its turn, resulting in an error on the side of the SMTP server. I am running a postfix server, and from my mail log:
> Jul  3 16:32:53 host postfix/postscreen[3312]: PREGREET 23 after 0 from [ip.ip.ip.ip]:port: Helo notify.ossec.net\r\n

This seems to point to an incorrect implementation of the SMTP protocol in OSSEC, as described here: http://www.postfix.org/POSTSCREEN_README.html#pregreet

**Comment by ddpbsd** [comment]
Can you provide a transcript of one of these failing conversations? It looks like maild is supposed to receive a 220 before sending the HELO

**Comment by ddpbsd** [comment]
I just did a tcpdump and saw the 220 before OSSEC responses with the HELO.

**Comment by jknockaert** [comment]
It happens only once in while that this goes wrong. I couldn't yet identify what triggers the wrong behaviour.

**Comment by ddpbsd** [comment]
Ok, I'll just leave this open until someone has a transcript I might be able to work with.

**Comment by jknockaert** [comment]
No transcript yet, but it seems to happen when the conversation goes over IPv6.
