### ISSUE TITLE
ossec rules/signature updates

### ISSUE THREAD

**Issue by mbrozay** [ossec/ossec-hids#1176]
Hi there, general question. 
How does ossec get its latest rules to keep up with the latest threats. For instance, I received an alert Alert Level: 6; Rule: 31508 - Blacklisted user agent.......srcip: 185.40.4.129; 185.40.4.129. 

Where is this list of IP addresses and how does it get updated?

Great product, cheers.

**Comment by ddpbsd** [comment]
OSSEC does not ship with any IP blacklists or anything. As stated in the description of the rule, it is matching on the user-agent:
```
  <!-- BAD/Annoying user agents -->
  <rule id="31508" level="6">
    <if_sid>31100</if_sid>
    <match> "ZmEu"| "libwww-perl/|"the beast"|"Morfeus|"ZmEu|"Nikto|"w3af.sourceforge.net|MJ12bot/v</match>
    <description>Blacklisted user agent (known malicious user agent).</description>
  </rule>
```

**Comment by mbrozay** [comment]
Thank you for the reply.
I still don't totally understand. Does w3af.sourceforge.net have an updated blacklist that the rule is checking dynamically.

**Comment by atomicturtle** [comment]
Its a fixed list in rule 31508, if the webserver logs the useragent, and it matches that string, and it is configured with active response, it will trigger a firewall drop event

**Comment by ddpbsd** [comment]
The user-agent field the client presented to the web server contained:
```ZmEu```
or
```libwww-perl/```
or
```"the beast"```
or any of the other things in that rule.

**Comment by mbrozay** [comment]
Understood. Thank you both.
