### ISSUE TITLE
Remoted error with UDP

### ISSUE THREAD

**Issue by joaopsys** [ossec/ossec-hids#1182]
I just git cloned the latest version of OSSEC and when starting it, with the following remote configs:
```
  <remote>
<connection>secure</connection>
<protocol>udp</protocol>
<local_ip>10.66.0.254</local_ip>
  </remote>
```
(the same configs I was using before, just added the protocol line for testing)

OSSEC is not binding to port 1514 UDP, and gives me this error:

`2017/07/08 23:54:06 ERROR: ossec-remoted Couldn't accept TCP connections.`

If I change the protocol to TCP, it will bind successfully.

**Comment by ddpbsd** [comment]
Thanks for the report. We're in the middle of pulling in a number of changes, so the breakage isn't a surprise.

**Comment by ddpbsd** [comment]
Actually, this should be fixed with pull request #1183
Thanks again for pointing it out!

**Comment by xJota** [comment]
Thank you for fixing it so fast :)

**Comment by xJota** [comment]
(Didn't mean to close it, haven't tested it yet)

**Comment by xJota** [comment]
Quick test and I'm getting spammed this warning now, although it is now binding correctly to 1514 UDP. This does not happen with <protocol>tcp</protocol>

`WARN: Message from '0.0.0.0' not allowed.`

**Comment by aquerubin** [comment]
Really should be using the system defined defs instead of creating our own.

Tony

**Comment by ddpbsd** [comment]
The remoted problems are going to take some time to figure out. I'm trying to decide what to do until then.

**Comment by ddpbsd** [comment]
@aquerubin Which ones are you cryptically referencing? I'll fix it.
