### ISSUE TITLE
Ossec agent installation error on Oracle Solaris 10

### ISSUE THREAD

**Issue by hlckalana** [ossec/ossec-hids#1185]
I'm Planning to install OSSEC agent( https://ossec.github.io/downloads.html) on Oracle Solaris 10 1/3.

When I am installing agent on I got following error.

"5- Installing the system -Running the Makefile make:Fatal error in reader:Makefile,line 4: Unexpected end of line seen
Error0x5. Building error.Unable to finish the installation"

already installed Compiler and make with OS.

If any one knows the issue please kind to help me to sort this.

**Comment by ddpbsd** [comment]
Which version of OSSEC are you trying to install?
Are you sure you have GNU make installed and it is used?

**Comment by hlckalana** [comment]
@ ddpbsd Yes I have. 

following finding will be useful to you

# uname -a
SunOS cbprrpt 5.10 Generic_150400-23 sun4v sparc sun4v

.......................................................................................................................
# cat /etc/release

                   Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC

  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.

                            Assembled 17 January 2013

............................................................................................................................
#find / -name gmake
/usr/sfw/bin/gmake

**Comment by nbuuck** [comment]
@hlckalana Which version of gmake do you have installed? You should be able to check with `gmake -v`.
