### ISSUE TITLE
Sregex problems on agents

### ISSUE THREAD

**Issue by CrazyLlama** [ossec/ossec-hids#1204]
Hi guys,

Having a problem with implimenting sregex to ignore certain filetypes, in that it still does even with the following line:

```
<ignore type="sregex">.tpl</ignore>
```

I have also tried this in the following formats to no avail:

```
<ignore type="sregex">.tpl$</ignore>
<ignore type="sregex">\..tpl</ignore>
<ignore type="sregex">\..tpl$</ignore>
```

If anyone has any ideas or wants any further info I am happy to share as much as I can!

**Comment by ddpbsd** [comment]
Did you restart the OSSEC processes after making these changes?

**Comment by CrazyLlama** [comment]
Yes, I restarted ossec every time using the ./bin/ossec-control script

**Comment by nbuuck** [comment]
@CrazyLlama Is the impacted agent(s) a Linux or Windows agent? Which version of OSSEC server and agent are you running? There's an open issue (https://github.com/ossec/ossec-hids/issues/1205) that could be preventing a Windows agent from receiving the new syscheck database which could explain what you're experiencing.

**Comment by CrazyLlama** [comment]
This is a Linux agent running OSSEC agent v2.8, the server is actually Wazuh so it may be that I move over to those guys instead and ask the questions there.

The changes are being made in the agents ossec.conf, but if it requires that the agent be the same as server so that you can use sregex then so be it 😄

**Comment by nbuuck** [comment]
@CrazyLlama Have you reviewed the agent's log to verify that it's receiving, validating, and parsing the syscheck DB delivered by the server successfully?

**Comment by CrazyLlama** [comment]
@nbuuck Is the only way to use ignores by putting them in the shared config from server side? Because ourselves have exclusively been trying to put it in the agents ossec.conf with no changes to the servers /shared/agent.conf except that which we want to share out to all agents.

We're currently just trying to do this locally as we only wish to ignore the file extensions on this agent/machine only.

I can try writing a rule in-stead of this to cover our needs but I'd prefer to use core ossec configuration if possible 😟

**Comment by nbuuck** [comment]
@CrazyLlama Per http://ossec-docs.readthedocs.io/en/latest/syntax/head_ossec_config.syscheck.html#supported-types, defining these ignores in the agent's local config is valid.

**Comment by CrazyLlama** [comment]
Does anyone have any ideas as to why this is occurring in that case? Absolutely no clue on our side as all of the ignores are within the documentation standards.

**Comment by nbuuck** [comment]
@CrazyLlama Can you clarify what you meant (i.e. what symptom you're seeing) in your original post by "in that it still does"? Are you actually being alerted? The syscheck documentation shows that the file will still be checked but that the result will be ignored.

**Comment by CrazyLlama** [comment]
@nbuuck 

I think I may understand the problem I am having now, I'd just need to clarify with you:

* Syscheck ignore is specifically for OSSEC alerting right?
* Syscheck still logs the checks and files and sends this up stream to manager server?
* If these are both true then I have been looking in the wrong place - as we manage our alerts more up stream from this and as such there isn't actually an issue with OSSEC.

If those are true ^ then I think that this is closed 😄

**Comment by nbuuck** [comment]
Per the first two conditional checks in `read_file()` in [cread_db.c](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/syscheckd/create_db.c#L25), there should be no alert message generated when a file matches an `<ignore>` or `<ignore type="sregex">` as the function will `return (0)` before `send_syscheck_msg(alert_msg)` can be invoked.

**Comment by CrazyLlama** [comment]
Thank you for your help nathan, I understand my issue now:

- We actually do our alerting more upstream than on ossec so as the syscheck still produce the logs for the checks (with no alerts), we still alert on these logs as they are aggregated.
- I did not realize that the `<ignore>` is specifically tailored for syscheck alerting and not actually ignores the file and as such I deal with this more upstream in the pipeline.

Thank you again for the help
