### ISSUE TITLE
mysql.schema is missing the data table def

### ISSUE THREAD

**Issue by choadrocker** [ossec/ossec-hids#1213]
Should look like this:

CREATE TABLE IF NOT EXISTS data
    (
    id              MEDIUMINT   UNSIGNED NOT NULL,
    server_id       SMALLINT    UNSIGNED NOT NULL,
    user            TEXT        NOT NULL,
    full_log        TEXT        NOT NULL,
    PRIMARY KEY (id, server_id)
    );

**Comment by nbuuck** [comment]
@choadrocker The only SQL operations against a table with a column named `full_log` is for a table named `alert`, e.g. [alert.c:162](https://github.com/ossec/ossec-hids/blob/ef46a72250c84c068751a0161d8b5fb009fb7699/src/os_dbd/alert.c#L162). While the PostgreSQL schema has this table, the code doesn't seem to interact with it. The table described by your DDL overlaps completely with the `alert` table. Was this Issue created to make the MySQL schema mirror the PostgreSQL schema or has the absence of this table actually caused an issue in your experience?

**Comment by choadrocker** [comment]
The absence of this table caused problems. I was forced to recreate it from the PG schema

```
2017/07/24 18:53:28 ossec-dbd(5203): ERROR: Error executing query 'INSERT INTO data(id, server_id, user, full_log) VALUES ('1', '1', '(null)', 'Jul 24 18:53:26 HOSTNAME sshd[28922]: Did not receive identification string from 10.3.64.38') '. Error: 'Table 'ossec.data' doesn't exist'.
2017/07/24 18:53:28 ossec-dbd(5209): INFO: Closing connection to database.
```

**Comment by nbuuck** [comment]
@choadrocker Which version of OSSEC are you running?

The `data` table was deprecated from the MySQL integration in [v2.9.0beta06](https://github.com/ossec/ossec-hids/releases/tag/v2.9.0beta06) in commit https://github.com/ossec/ossec-hids/commit/10bda76d617e812fcdcee376e899bff1eabed94a

**Comment by ddpbsd** [comment]
I don't see anything trying to INSERT into the data table in master. If I missed it, provide a link and re-open the issue.
