### ISSUE TITLE
Windows Events Truncated When Forwarding via CEF

### ISSUE THREAD

**Issue by cm405d** [ossec/ossec-hids#1214]
We are seeing truncated windows event messages being sent out in CEF format to our ArcSight SIEM, specifically Windows Events 4624. I have verified by looking at archives.log that the full message is being received.

Nothing complicated about the configuration:

  <syslog_output>
    <server>x.x.x.x</server>
    <port>514</port>
    <format>cef</format>
  </syslog_output>

Any help would be appreciated.

**Comment by nbuuck** [comment]
@cm405d Have you observed at what length these alerts are being truncated?

OSSEC reads input with fixed buffer sizes such as the generic `OS_BUFFER_SIZE`, by default hard-coded to a value of `OS_SIZE_2048` which is, as the name indicates, an `int` with value 2048. `OS_BUFFER_SIZE` is the buffer size used when `ossec-dbd` invokes `fgets()` (OS_DBD() -> Read_FileMon() -> GetAlertData() -> fgets(str, OS_BUFFER_SIZE, fp)) to read the file queue it uses to receive alerts before inserting them into the configured database. As such, I'd expect you're seeing alerts truncated at 2047 readable characters.

**Comment by cm405d** [comment]
The character count of the raw message is 1475, but that doesn't include
any IP header. Do you know if the 2048 limit includes IP header, or just
payload?

**Comment by nbuuck** [comment]
@cm405d When you say "IP header," do you mean the Layer 3 component of the UDP message from OSSEC to your CEF server?

**Comment by cm405d** [comment]
Yes, the layer 3 header, I'm not sure if that would be included in the
buffer you mentioned, or if the buffer was for the payload only.

Either way, could I simply change the value and recompile?

**Comment by nbuuck** [comment]
Theoretically, yes, you could change the assignment of `OS_BUFFER_SIZE` to something greater. Some testing in a non-prod environment is advisable, though.

Regarding the IP header, what _is_ interesting about your observation is how close 1475 is to the default 802.3 MTU of 1500 octets. Do you see the same truncation in `alerts.log` in your OSSEC install directory?

**Comment by cm405d** [comment]
Interesting, I turn logall on, and in archives.log, I see the full message,
but in alerts.log I see the message truncated.

The raw log in archives.log is 2290 characters.

The multi-line truncated log in alerts.log is 1459 characters, and that
includes the OSSEC header info, and then the raw log. I'm wondering if you
are on to something with the MTU, and OSSEC is truncating to fit inside of
a single IP packet.

**Comment by cm405d** [comment]
FYI, 1256 characters from the raw log make it into the processed log in
alerts.log

**Comment by cm405d** [comment]
Found a relevant open issue from 2014
https://github.com/ossec/ossec-hids/issues/473

**Comment by nbuuck** [comment]
The mailing list [thread](http://marc.info/?l=ossec-dev&m=134550679026814&w=2) referenced by that issue cited the line that imposes a fixed length on the alert log message component: https://github.com/ossec/ossec-hids/blob/6ca53a163a1009f4ec534c9c9a7f93aa90248b56/src/analysisd/alerts/log.c#L99
