### ISSUE TITLE
Define Repo Topics

### ISSUE THREAD

**Issue by nbuuck** [ossec/ossec-hids#1216]
On 2017-01-31, GitHub [released](https://github.com/blog/2309-introducing-topics) the Topics feature. I think it would be handy to add at least the `intrusion-detection` and perhaps the `hids` topics to this repo. The [Wazuh](https://github.com/wazuh/wazuh) fork has adopted a handful of relevant topics.

**Comment by atomicturtle** [comment]
Great idea! I just added a few to the list, let me know if we should add any others

**Comment by nbuuck** [comment]
Those look good to me, and certainly cover the more "marketable" topics. I'm going to close this but any contributors that have further opinions are welcome to comment here or perhaps more preferably start a thread on the [mailing list](https://groups.google.com/forum/#!forum/ossec-dev).
