### ISSUE TITLE
Alert gets populated with portion of alerts from another host

### ISSUE THREAD

**Issue by epicavic** [ossec/ossec-hids#1218]
Hello,

i'm facing pretty weird issue
Alert generated for one host contains some events generated on another host.
here is the quick example from /var/ossec/logs/alerts/alerts.log
*****************************************************************************************************
** Alert 1501743728.1095133: mail  - syslog,sshd,
2017 Aug 03 07:02:08 (host1.example.local) x.x.x.x->/var/log/secure
Rule: 5703 (level 10) -> 'Possible breakin attempt (high number of reverse lookup errors).'
Src IP: x.x.x.x
Aug  3 09:53:57 host1 sshd[11788]: reverse mapping checking getaddrinfo for [x.x.x.x] failed - POSSIBLE BREAK-IN ATTEMPT!
Aug  3 07:00:45 host2 sudo: omsagent : TTY=unknown ; PWD=/opt/microsoft/omsconfig/Scripts/2.6x-2.7x ; USER=root ; COMMAND=/opt/microsoft/omsconfig/Scripts/OMSAuditdPlugin.sh
*****************************************************************************************************
as you can see first event belong to host1 and second to host2

host1 ossec version:
ossec-hids.x86_64                          1:2.9.0-1700.el6.art        @atomic
ossec-hids-agent.x86_64                    1:2.9.0-1700.el6.art        @atomic

ossec server version:
ossec-hids.x86_64                       2.9.0-49.el7.art               @atomic
ossec-hids-server.x86_64                2.9.0-49.el7.art               @atomic

Regards,
Viktor

**Comment by nbuuck** [comment]
It's curious that the Azure OMS agent (which can perform log aggregation and other functions) is present on the second host; is there any kind of log forwarding configured between these two hosts? Not even necessarily through OMS but through a syslog daemon?

**Comment by epicavic** [comment]
there are no any log forwarding configured between those 2 hosts in any way
 - host1 does not have OMS agent installed (resides in datacenter A)
 - host2 have OMS agent installed by default (resides in datacenter B - Azure)
 - both are linux instances
 - i receive notification with a mixed logs content (from host1 and host2) right after i login on host1 via ssh  (rule 5703 fired)
adding local_rules.xml - don't think that local rules might be the cause of issue - but who knows.
[local_rules.xml.txt](https://github.com/ossec/ossec-hids/files/1401354/local_rules.xml.txt)
