### ISSUE TITLE
Not getting email alerts

### ISSUE THREAD

**Issue by vaibhavanand31** [ossec/ossec-hids#1219]
Hi i am getting ERROR

2014/12/18 17:48:35 os_sendmail(1767): WARN: End of DATA not accepted by server
2014/12/18 17:48:35 ossec-maild(1223): ERROR: Error Sending email to 74.125.131.26 (smtp server)

var/ossec/etc/ossec.conf email configuration: 

  <global>
        <email_notification>yes</email_notification>
        <email_to>******@******.com</email_to>
        <smtp_server>alt1.aspmx.l.google.com.</smtp_server>
        <email_from>ossecm@ip-172-31-13-83</email_from>
  </global>

**Comment by nbuuck** [comment]
@vaibhavanand31 Please review Google's requirements for relaying SMTP through their service(s).

https://support.google.com/a/answer/176600?hl=en
