### ISSUE TITLE
Ossec 

### ISSUE THREAD

**Issue by Hartinah** [ossec/ossec-hids#1220]
Hai, Sorry I want to ask about Ossec. Actually how to categorize the existing levels in Ossec, can I create my own level category on Ossec and how?
Thank you

**Comment by ddpbsd** [comment]
The levels don't have any set definition, although `docs/rules.txt` has some guidelines.
You can create groups for rules, and those may help you categorize alerts.

**Comment by Hartinah** [comment]
Thanks..
Do you have any ebook for make group and categorize alert?

_Sent from my OPPO F1f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ddpbsd** [comment]
No, but there are plenty of examples in the default rule sets.
