### ISSUE TITLE
Upgrade from server2.8.3 to 2.9.1

### ISSUE THREAD

**Issue by DaniJusto** [ossec/ossec-hids#1229]
Hi ,

I try  to upgrade from ossec server 2.8.3 to 2.9.1 (last stable version) , When I run install.sh it does not give me the option to update the version , it seems that the installer does not see that I already have the ossec server with version 2.8.3.

If I perform the installation, will I save the local rules rules.xml?

Thanks and Regards
Daniel Justo

**Comment by ddpbsd** [comment]
Is 2.8.3 installed to the default location? Does `/etc/ossec-init.conf` exist?

**Comment by DaniJusto** [comment]
Hi ,

No is in other location , and ossec-init.conf is exit but in other route. 

Regards

**Comment by DaniJusto** [comment]
Hi Dan,

I have already been able to perform the update after copying the ossec-init.conf file to / etc.

Thanks and regards
Dani
