### ISSUE TITLE
Ubuntu 16.04 packages

### ISSUE THREAD

**Issue by kir-b** [ossec/ossec-hids#1230]
I did install ossec 2.9.2 packages from Atomic repo, and some issues in this packages.

1. No LSB header in /var/ossec/etc/init.d/ossec-authd and post install configuration isn't correct.
2. Probably systemd in xenial isn't correct work with symlinks in /etc/init.d and ossec service isn't start automatically. And error "No such file or directory" arise.
When I put ossec init script to /etc/init.d - OK.

**Comment by ddpbsd** [comment]
1. What post install configuration is incorrect?

**Comment by kir-b** [comment]
update-rc.d -f ossec defaults

This is command finish with error, because isn't LSB header in /var/ossec/etc/init.d/ossec-authd

**Comment by ddpbsd** [comment]
Thanks, I'll try to look into that soon. (Hardware failure has delayed my work for a bit)

**Comment by atomicturtle** [comment]
Closing this as out of date, ossec-authd init scripts are no longer in the package
