### ISSUE TITLE
decoder.xml expects old asterisk log file format

### ISSUE THREAD

**Issue by martin9959** [ossec/ossec-hids#1232]
This has already been reported here (in 2015!):
[https://groups.google.com/forum/#!msg/ossec-list/XsAn1aJKwxw/SwcBeWp8u90J](url)

and the solution suggested still holds true: Since 1.8, Asterisk adds the port number to the srcip, so that the current decoder.xml: 

`<decoder name="asterisk-denied2">
  <parent>asterisk</parent>
  <prematch>Registration from </prematch>
  <regex offset="after_prematch">failed for '(\S+)'</regex>
  <order>srcip</order>
</decoder>`

decodes 'x.x.x.x:y' as the srcip. 

As by the suggestion referenced above, 

`<decoder name="asterisk-denied2">
  <parent>asterisk</parent>
  <prematch>Registration from </prematch>
  <regex offset="after_prematch">failed for '(\S+):(\d+)'</regex>
  <order>srcip,srcport</order>
</decoder>`

leads to the right result. 

By the way, am I right that "asterisk-denied2" is enough, because it covers all possible occurrences of "asterisk-denied", so that the latter is actually superfluous?

**Comment by ddpbsd** [comment]
Does the new decoder work for the old format as well?

**Comment by martin9959** [comment]
I just realised that we'll have to "fix" (if not delete) asterisk-denied as well, because it triggers and blocks asterisk-denied2 from kicking in - therefore, I would suggest, similar to #1234 above: 

`<decoder name="asterisk-denied">`
`<parent>asterisk</parent>`
`<prematch>^NOTICE[\d+]: \S+ in \S+: Registration from </prematch>`
`<regex offset="after_prematch">^'\.+' failed for '(\S+):(\d+)'|^'\.+' failed for '(\S+)'</regex>`
`<order>srcip,srcport</order>`
`</decoder>`

This should cover both old and new log formats, and also the case of spaces in the "from" item, like: 

`Dec 16 18:02:04 asterisk1 asterisk[31774]: NOTICE[31787]: chan_sip.c:11242 in handle_request_register: Registration from '"503"<sip:503@192.168.1.107>' failed for '192.168.1.137' - Wrong password`

and 

`Aug 29 07:21:05 hostname asterisk[3284]: NOTICE[3734]: chan_sip.c:28088 in handle_request_register: Registration from '"3810" <sip:3810@1.2.3.4:5060>' failed for '37.8.26.31:5065' - Wrong password`

**Comment by ddpbsd** [comment]
I have updated the pull request with these changes. 
If you have anymore log samples you'd like to share, please feel free.  You can either add them to contrib/ossec-testing/tests/asterisk.ini and submit a pull request, or I can do it.

**Comment by martin9959** [comment]
I have one more suggestion for asterisk, for others I think I better open a new issue. 

Log:

`Aug 30 16:02:29 hostname asterisk[3284]: NOTICE[3734][C-00001c7a]: chan_sip.c:25650 in handle_request_invite: Call from '' (89.163.146.112:5071) to extension '70046313115067' rejected because extension not found in context 'default'.`

Decoder:

`<decoder name="asterisk-denied3">`
 ` <parent>asterisk</parent>`
`  <prematch>^NOTICE[\d+][\w+]: \S+ in \S+: Call from </prematch>`
 ` <regex offset="after_prematch">^'\S*' \((\S+):(\d+)\) to extension '(\S+)' rejected because extension not found in context '(\S+)'.$</regex>`
  `<order>srcip, srcport, extra_data, extra_data</order>`
`</decoder>`

Rule: (asterisk_rules.xml)

 `<rule id="6212" level="5">`
    `<if_sid>6201</if_sid>`
    `<match>No matching peer found|extension not found in context</match>`
    `<description>Login session failed (invalid extension).</description>`
    `<group>invalid_login,</group>`
  `</rule>`

**Comment by ddpbsd** [comment]
Updated PR #1234 with the additions, thanks again!
