### ISSUE TITLE
feature request: ossec.log file path in config file

### ISSUE THREAD

**Issue by eduda** [ossec/ossec-hids#1239]
Need a way in the config file to configure the directory where the ossec.log file will be written. Thanks.

**Comment by ddpbsd** [comment]
My initial assumption is that this will not do what you want it to do. Most of the OSSEC processes are chrooted, so the log file will end up in `/var/ossec` (or where ever you install to) anyway. Changing from `/var/ossec/logs/ossec.log` to `/var/ossec/other/ossec.log` might not fit your use case. Can you provide more information on the problem you're trying to solve?

**Comment by eduda** [comment]
Just trying to be able to store the logs in another partition. example, /otherpart/logs/ossec.log
another option would be if it was possible to have ossec syslog the log file, that way, i could have rsyslog save it as needed but i don't believe ossec support syslog yet.

**Comment by ddpbsd** [comment]
It does not support syslog, and there are no plans to do so at the moment. There are enough things going on without having to worry about some kind of log loop.
