### ISSUE TITLE
Ossec 2.9.2: Rpm for centos 5 and 6

### ISSUE THREAD

**Issue by marcRBD** [ossec/ossec-hids#1247]
Hi 
i can't find any, there is only 2.9.0.

Example:
https://updates.atomicorp.com/channels/atomic/centos/6/x86_64/RPMS/

Any chance for an update ?
Thanks

**Comment by atomicturtle** [comment]
El5 I'm not sure about since its EOL now. Is there enough demand for it?

El6 should be up though, have a look and let me know.
