### ISSUE TITLE
input not trimmed from debconf selections

### ISSUE THREAD

**Issue by jeffdyke** [ossec/ossec-hids#1250]
First, thanks for continuing to support and update a very useful product.  And given time i'll try to see if i can find the code to fix this.

I install from the ubuntu/atomic packages and use `debconf-set-selections` to answer the question that both the manager and agent requires for installation, the issue is that the install takes these inputs without stripping white space, so you'll end up with `<server-ip> 10.0.2.10</server-ip>` rather than `<server-ip>10.0.2.10</server-ip>`, and they are not trimmed when being used, from what i can tell.  The first place i noticed this was in the smtp server address as it tried to connect to ` 1.1.1.1` with the extra space and threw an error in the logs failing to connect, after removing the space, it worked fine.

Easy workarounds, so a bit more of an FYI.

Thanks!

**Comment by ddpbsd** [comment]
I'm not familiar with the debian packaging magic. Is `debconf-set-selections` adding these extra spaces?

**Comment by jeffdyke** [comment]
Not necessarily, but with most packages it does not seem to matter (and i use this feature often), so if the user wants to use the debconf magic, which is a great help when you have an array of servers, this is installed on, you can automate the answers to the question.  

The way i found this was to manually install once, then run `sudo debconf-get-selections | grep ossec`, copy and paste those into the install automation and in there they had two spaces, or it may have been a tab and a space.  It seems like it uses tabs by default so the latter is my guess.  I don't think this is the end of the world of course, i just modified my scripts, but as i stated in the issuer report, more of an FYI.  

Thanks for checking it out.
