### ISSUE TITLE
Ossec windos agent silent uninstall

### ISSUE THREAD

**Issue by salllas** [ossec/ossec-hids#1265]
How can i silently uninstall ossec agent ?
uninstall.exe /s not working

**Comment by nbuuck** [comment]
Please describe the specific behavior that occurs when attempting to call `uninstall.exe /s`.
Are you executing that command from an elevated context (e.g. launch cmd.exe as Administrator)?

**Comment by salllas** [comment]
When i run this comand graphic menu apears, with "Next", like ussual uninstall without /s switch

**Comment by nbuuck** [comment]
The `/S` parameter must be **capitalized**.

**Comment by salllas** [comment]
THANKS ! :)

**Comment by nbuuck** [comment]
@salllas You're welcome. Please mark this issue closed.
