### ISSUE TITLE
Missing logging of REJECT/DENY iptables in firewall_rules.xml

### ISSUE THREAD

**Issue by kdslkdsaldsal** [ossec/ossec-hids#1267]
When checking https://github.com/ossec/ossec-hids/blob/ee6fc194a09db08868dde546a76464d4c459d8a7/etc/rules/firewall_rules.xml it seems only DROP messages are evaluated there. 

Depending on the use case an administrator might choose REJECT/DENY for the iptables rules as well (see e.g. http://www.linux-admins.net/2013/07/drop-versus-reject-packet.html)

I'm also quite unsure if this comment here is valid these days:
https://github.com/ossec/ossec-hids/blob/ee6fc194a09db08868dde546a76464d4c459d8a7/etc/rules/firewall_rules.xml#L23-L25

Ref: https://github.com/wazuh/wazuh-ruleset/issues/73

**Comment by ddpbsd** [comment]
Can you provide log samples?

**Comment by kdslkdsaldsal** [comment]
Sure, basically the mentioned rule is only matching the following:

``
Oct  2 06:26:25 example kernel: [593219.016960] RULE 24 -- DROP IN=eth0 OUT= MAC=00:11:22:33:44:55:66:88:99:00:11:22:33:44 SRC=192.168.0.1 DST=192.168.0.2 LEN=40 TOS=0x00 PREC=0x00 TTL=113 ID=59263 PROTO=TCP SPT=15314 DPT=21379 WINDOW=53920 RES=0x00 SYN URGP=0
``

but not the following:

``
Oct  2 06:26:25 example kernel: [593219.016960] RULE 24 -- DENY IN=eth0 OUT= MAC=00:11:22:33:44:55:66:88:99:00:11:22:33:44 SRC=192.168.0.1 DST=192.168.0.2 LEN=40 TOS=0x00 PREC=0x00 TTL=113 ID=59263 PROTO=TCP SPT=15314 DPT=21379 WINDOW=53920 RES=0x00 SYN URGP=0
``

**Comment by kdslkdsaldsal** [comment]
Mhhh, nevermind. I just had another look and it seems that "DENY" is some custom text when using fwbuilder:

``
Oct  2 06:26:25 example kernel: [593219.016960] RULE 24 -- DENY IN=eth0 OUT= MAC=00:11:22:33:44:55:66:88:99:00:11:22:33:44 SRC=192.168.0.1 DST=192.168.0.2 LEN=40 TOS=0x00 PREC=0x00 TTL=113 ID=59263 PROTO=TCP SPT=15314 DPT=21379 WINDOW=53920 RES=0x00 SYN URGP=0
``

I think there is nothing which needs to be done here, sorry.
