### ISSUE TITLE
Monitoring of specific files?

### ISSUE THREAD

**Issue by TriciaE66** [ossec/ossec-hids#1270]
Could you please advise if within the configuration file there is an option to monitor specific files or is it at directory level only?

**Comment by ddpbsd** [comment]
If you mean syscheck scanning, I just tried to monitor an individual file and it doesn't seem to work. I'll update if it pops up after this scan.

**Comment by TriciaE66** [comment]
Thank you for checking. Did it pop up today for you?

**Comment by ddpbsd** [comment]
Nope. Looks like it isn't a feature.

**Comment by TriciaE66** [comment]
Any advise on an alternative option / workaround?

**Comment by ddpbsd** [comment]
You could add the feature to syscheck. Ignore files in directories that you don't care about?

**Comment by TriciaE66** [comment]
Thats what we have been doing on other folders, so guess the reverse logic isnt an option so will go down that path with these too. Thanks

**Comment by TriciaE66** [comment]
Found this when seaching around which does suggest it can monitor specific files, anyone used this?
Configuration Examples
To configure syscheck, a list of files and directories must be provided. The check_all option checks md5, sha1, owner, and permissions of the file.
Example:
<syscheck>
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/root/users.txt,/bsd,/root/db.html</directories>
</syscheck>

**Comment by ddpbsd** [comment]
I just tested this again, and it worked.
```
    <directories check_all="yes">/var/test3/file</directories>
```

Results:
```
+++12:33188:0:0:SHA256=7fe8b63fc1ed71ec8f964ad88bfb8a430631082a23e733ff4d009f2795b5d01d:GENERIC=20ab78a15a5d6ac7c8302e00e176a15bde1967029486c7fa84beff5bf749944ba897d36dee57ad188f8695c81d9b59b9ee856b8ea8098f7fda62e2f66d5f7732f6438bdbf708cd0508f155a86146e4ea !1547054102 /var/test3/file
```
