### ISSUE TITLE
mailx as local smpt_sever, email_maxperhour and updates

### ISSUE THREAD

**Issue by knzudgt** [ossec/ossec-hids#1272]
I read digitalocean's tutorial on [how to Install and Configure OSSEC Security Notifications on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ossec-security-notifications-on-ubuntu-14-04) and after that reading I am considering the opportunity to install `ossec` on my Ubuntu 16.04 server.
In this tutorial it is suggested to install `Postfix` as smtp server in order to send notification alerts. However, since I installed the `heirloom-mailx`, I wonder if I can use `mailx` for this purpose.

In the above guide it is stated that `OSSEC`, by default, sends 12 emails per hour, number that can be reduced to the minimum of 1 per hour. Does this mean that I would receive emails even though there is nothing to be notified? I thought that `OSSEC` would send notifications only if it is necessary, that is for instance if a file was modified.

My last question: how to update `OSSEC`?

**Comment by ddpbsd** [comment]
`mailx` might work. Their documentation is lacking and I've never tried it, so I can't say for sure.
You should only receive emails for alerts. Some alerts send emails by default, but most don't. There is an alert level thresh hold to control the ones not expressly configured to send emails.
The `install.sh` script can handle upgrades as well as installations.

**Comment by knzudgt** [comment]
Thanks @ddpbsd. Before closing I copy and paste here an unanswered question from a user at the above Digital Ocean link: "Are there reasons for compiling from source rather than using the DEB [packages](http://www.ossec.net/?page_id=19) OSSEC provides for Ubuntu", considering that I would choose for a `local` installation type? At [weekipedia](https://en.wikipedia.org/wiki/Host-based_intrusion_detection_system_comparison) OSSEC is even considered not having support for Ubuntu.

**Comment by ddpbsd** [comment]
That's up to you. I do development on OSSEC, so the source makes sense for me. I have never looked at the ubuntu packages. We support ubuntu just fine though, it's one of the platforms I use when working on it.
