### ISSUE TITLE
deb packages, wazuh repository and stable versions

### ISSUE THREAD

**Issue by knzudgt** [ossec/ossec-hids#1277]
I am interested in trying to install the deb package for Ubuntu 16.04 Xenial.
In the [package installation](https://ossec.github.io/docs/manual/installation/installation-package.html#deb-installation) section of the documentation it is stated that OSSEC’s deb packages are available in the Wazuh repository, and also that the available distributions are Precise, Trusty and Utopic.
However in the [download page](https://ossec.github.io/downloads.html) it is clear that there are packages also for Xenial. However OSSEC's version of these packages is 2.9.2, which corresponds to the OSSEC's development version. The latest stable release of the source is in fact 2.9.1.
On the other hand, the latest packages of the [Wazuh repository](http://ossec.wazuh.com/) are of version 2.8.3.

I am a bit confused, not knowing what to do to install from packages and also to install the `local` kind of installation as suggested by an interesting article at [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ossec-security-notifications-on-ubuntu-14-04). Packages seems in fact only for `server` or `agent`.

**Comment by nbuuck** [comment]
I'm not confident that your assertion that 2.9.1 is stable and 2.9.2 is development is accurate. The project announced 2.9.2 as release on Facebook on [2017-08-09](https://www.facebook.com/ossechids/posts/490863781260294). Sometimes, the downloads page on ossec.github.io lags the partner repositories such as [this one](https://updates.atomicorp.com/channels/atomic/debian/dists/xenial/main/binary-amd64/Packages) operated by Atomicorp - sometimes a release tag gets finalized like 2.9.2 but a contributor doesn't get around to updating [ossec/ossec-docs](https://github.com/ossec/ossec-docs) for weeks.

To achieve a `local` build target installation, I expect you'll need to [compile](https://ossec.github.io/docs/manual/installation/installation-binary.html) the project from sources using `make TARGET=local`.

**Comment by knzudgt** [comment]
@nbuuck thank you for your reply. Probably as you say the documentation is outdated, because in the [`code` section](https://github.com/ossec/ossec-hids#quick-install) of this GitHub page the quick install defines the variable `ossec_version="2.9.0"`, while the [download page](https://ossec.github.io/downloads.html) on ossec.github.io states that the Latest Stable Release is 2.9.1
I take for granted that instead at present version 2.9.2 is the right one.
However, considering that occasionally I would like to know where I can get updated information about the latest stable release and so keep myself informed, are you to some extent seriously suggesting to get this information on Facebook? Although I use facebook I am probably an old fashioned internet user, a bit awkward with social networks, because if I know about a open source project hosted at GitHut, that is the place where I would look first.

**Comment by nbuuck** [comment]
> ...are you to some extent seriously suggesting to get this information on Facebook?
@knzudgt 

Given the state of documentation management for the project (that's not a jab at my fellow contributors, but it's known that ossec-docs doesn't get the love it needs), one has to leverage any available and maintained source to get a comprehensive understanding of the release state, regrettable as that may be. You could rely on the latest version observable in the Atomicorp repository referenced in my previous comment as an indicator of the current release version.

As a GitHub user, you could also - like I do - monitor PRs on the project by [Watching](https://github.com/ossec/ossec-hids/subscription) it. This isn't a precise indicator of when a particular version tag is finalized, but it worked for my purpose as an OSSEC user before getting involved.

**Comment by ddpbsd** [comment]
Sorry, I've been slacking: https://github.com/ossec/ossec-docs/pull/220

Our whole release process needs an overhaul, but just like working on the project, it takes free time. And free time is very hard to come by.

**Comment by knzudgt** [comment]
@nbuuck @ddpbsd I decided to install from source.
I downloaded from https://github.com/ossec/ossec-hids/archive/2.9.2.tar.gz
Do you know where can I find the checksum file?
The https://github.com/ossec/ossec-hids/archive/ page is not browsable
I tried with https://github.com/ossec/ossec-hids/archive/2.9.2-checksum.tar.gz but it does not work.

**Comment by nbuuck** [comment]
@knzudgt Project archives are generated by GitHub - maintainers don't generate them, so they can't provide file hashes for verification. I can't find any evidence that GitHub provides hashes for GitHub-generated archive files. Alternatively, you could use the `git` client to `git clone --branch 2.9.2 https://github.com/ossec/ossec-hids.git` the repo to a build machine and then compile it, rather than using the compressed tarball from the archive.

**Comment by ddpbsd** [comment]
This is one of the topics that will be covered by a more formal (yes, I hate myself for saying it) release process. We used to provide hashes and the gpg signature. Then the gpg key expired and Daniel Cid left the project and that was kind of ignored. So we provided checksums. Then we tried the github release thing, and provided a new gpg key. This left checksums by the wayside. I personally want a process that includes both checksums and gpg signatures. So I'll make time to write something up, and provide it to the community for comment (probably after a quick browse by the active dev members?). This won't be an instantaneous change, but OSSEC users should be used to my slowness. :-)

**Comment by atomicturtle** [comment]
It's easy enough to add checksum generation to the CI side of this. Dan and I both sign our commits to the repo, and I sign all the release tags, so it was more important to use gpg signatures since they are used all along the chain of trust:

1) on commits
2) on release tags
3) on release archives
4) on binary (rpm) packages
5) on repo (rpm/deb) data

So its true that github creates the archive, which would be a vulnerable to a MITM attack if it also werent for the fact that we sign the tag before that happens (FYI, the creating a tag creates the release). So we can verify the tar.gz against the signature on the tag.

TLDR; We can do it, its just weaker than relying on the .asc GPG signatures
