### ISSUE TITLE
OSSEC Download Flagged as Malcious File with Outbound Traffic

### ISSUE THREAD

**Issue by dyersev3** [ossec/ossec-hids#1279]
I downloaded version OSSEC 2.9 client version to update clients in my environment. Our security filter Zscaler flagged this file as malicious and blocked outbound traffic to an external IP 158.69.253.161. The file flagged as malware is MALWARE_NAME=backdoor/zaccess.zoc.z

Is there confirmation of file alteration from the download URL / malicious outbound traffic, or is this a known false positive?

I downloaded the updated Windows Agent from the OSSEC downloads page at https://ossec.github.io/downloads.html

**Comment by nbuuck** [comment]
This would appear to be a false positive that is common to a very limited number of AV products: https://www.virustotal.com/#/file/eaa57d96706fefaed0f99208f610557313cfb19afe614bf65c153019cad12227/detection

**Comment by nbuuck** [comment]
You can verify the signature of the Windows executable you downloaded by retrieving the corresponding `.asc` file from the source, in this case https://updates.atomicorp.com/channels/atomic/windows/

**Comment by nbuuck** [comment]
I reviewed the indicators alleged by [Payload Security](https://www.hybrid-analysis.com/sample/eaa57d96706fefaed0f99208f610557313cfb19afe614bf65c153019cad12227?environmentId=100) in addition to the previous review of the VirusTotal report. I affirm this to be a false-positive. If you disagree, please re-open this issue.
