### ISSUE TITLE
OSSEC and logrotate 

### ISSUE THREAD

**Issue by knzudgt** [ossec/ossec-hids#1281]
I am on a Ubuntu 16.04 server machine.
Apart from the` /var/ossec/logs/ossec.log` log file, I found various log files in `/var/ossec/logs/alerts`, `/var/ossec/logs/archives` and `/var/ossec/logs/firewall`.
In the [documentation](http://ossec-docs.readthedocs.io/en/latest/faq/ossec.html#how-can-i-get-ossec-log-to-rotate-daily) it is written that "Currently OSSEC does not rotate the ossec.log, use logrotate.d or newsyslog to rotate it for now."

Is OSSEC rotating some other logs? I could not find any configuration file in `/etc/logrotate.d`
However I found in Internet conversations from users having configuration files installed with OSSEC, probably from the Wazuh repository: see at [GitHub](https://github.com/wazuh/wazuh/issues/87) and at [alienvault](https://www.alienvault.com/forums/discussion/8098/logrotate-rotate-var-ossec-logs-alerts-alerts-log-weekly-but-why).

Could you suggest what files it is better be rotated and a useful logrotate configuration file for OSSEC to put in `/etc/logrotate.d`?

**Comment by ddpbsd** [comment]
`alerts.log` should be rotated daily.
I haven't ever tried log rotation for `ossec.log`, but it seems tricky (too many daemons write to it).

**Comment by knzudgt** [comment]
@ddpbsd where can I find the logrotate configuration file for `alerts.log`?
I installed OSSEC from source.

**Comment by ddpbsd** [comment]
@knzudgt That's actually handled by monitord (I think), not logrotate or newsyslog or anything.

**Comment by knzudgt** [comment]
@ddpbsd so what are you suggesting to do with `/var/ossec/logs/ossec.log` to prevent it from growing too much? Is it so a bad idea to add a logrotate configuration for it? <br> According to a [Wazuh GitHub issue](https://github.com/wazuh/wazuh/issues/87), in May 13 they had the following logrotate configuration in `/etc/logrotate/ossec-hids`:

    # Log rotation for Ossec HIDS
    /var/ossec/logs/*.log {
        create 640 ossec ossec
        rotate 31
        compress
        missingok
        notifempty
        olddir /var/ossec/logs/archives/
        sharedscripts
        postrotate
           /var/ossec/bin/ossec-control restart
        endscript
    }

**Comment by ddpbsd** [comment]
I am not currently suggesting anything. It's an exercise for the user to figure out what works for them.

**Comment by ddpbsd** [comment]
I'm not entirely sure if the restart is necessary (but Wazuh would know better than me), but I'll try the logrotate config. If it works out, and I remember, I'll put it somewhere in the documentation or source tarball.
