### ISSUE TITLE
ssh login not reported

### ISSUE THREAD

**Issue by 97zgxgw** [ossec/ossec-hids#1283]
Hello.
Server v2.9.2, clients v2.9.2, Ubuntu 16
When login to server over ssh no any reports.

----------
/var/ossec/bin/ossec-logtest
2017/10/12 16:13:58 ossec-testrule: INFO: Reading local decoder file.
2017/10/12 16:13:58 ossec-testrule: INFO: Started (pid: 29763).
ossec-testrule: Type one log per line.

Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46.*.*.* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI

**Phase 1: Completed pre-decoding.
       full event: 'Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46.*.*.* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'
       hostname: 'web1'
       program_name: 'sshd'
       log: 'Accepted publickey for root from 46.*.*.* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'root'
       srcip: '46.*.*.*'

**Phase 3: Completed filtering (rules).
       Rule id: '10100'
       Level: '4'
       Description: 'First time user logged in.'
**Alert to be generated.

---------------------

When try login with console with wrong password, again no warnings.

**Comment by ddpbsd** [comment]
Because it's the first run of ossec-logtest you're going to get the FTS alert. Pasting the log in a second time provides an alert of 5715:
```
ossec-testrule: Type one log per line.

Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI


**Phase 1: Completed pre-decoding.
       full event: 'Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'
       hostname: 'web1'
       program_name: 'sshd'
       log: 'Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'root'
       srcip: '46...*'

**Phase 3: Completed filtering (rules).
       Rule id: '10100'
       Level: '4'
       Description: 'First time user logged in.'
**Alert to be generated.


Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI


**Phase 1: Completed pre-decoding.
       full event: 'Oct 12 16:13:09 web1 sshd[121997]: Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'
       hostname: 'web1'
       program_name: 'sshd'
       log: 'Accepted publickey for root from 46...* port 39281 ssh2: RSA SHA256:zmQeMOTMTf1iOyyb3/bYxaEPlmo1CZHp1iGAZMAGaQI'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'root'
       srcip: '46...*'

**Phase 3: Completed filtering (rules).
       Rule id: '5715'
       Level: '3'
       Description: 'SSHD authentication success.'
**Alert to be generated.
```

**Comment by 97zgxgw** [comment]
I need increase level to 14 and add <options>alert_by_email</options> for mail allerts ?

**Comment by ddpbsd** [comment]
By default the email alert level is `<email_alert_level>7</email_alert_level>`
So you can either decrease that or increase the level of rules you want email alerts for.
The `alert_by_email` option isn't usually necessary.

**Comment by 97zgxgw** [comment]
Good ! 
Thank you !
