### ISSUE TITLE
Does an alert flag if the date / time changes only?

### ISSUE THREAD

**Issue by TriciaE66** [ossec/ossec-hids#1288]
Can anyone advise if an alert would be triggered for a file which **only has the date / time changed?** 
I understand it checks fo changes onr:
•	The sha1 and/or Md5 – Iis this based on the contents of the file only?.
•	The size of the file.
•	The owner of the file.
•	The group of the file.
•	The permissions of the file.
Thanks

**Comment by ddpbsd** [comment]
I don't believe so.
