### ISSUE TITLE
Installer installs the wrong type of installation

### ISSUE THREAD

**Issue by Avamander** [ossec/ossec-hids#1293]
```
 - In order to connect agent and server, you need to add each agent to the server.
   Run the 'manage_agents' to add or remove them:

   /var/ossec/ossec-agent/bin/manage_agents
```

When executing "/var/ossec/ossec-agent/bin/manage_agents" I get:

```
****************************************
* OSSEC HIDS v2.9.2 Agent manager.     *
* The following options are available: *
****************************************
   (I)mport key from the server (I).
   (Q)uit.
Choose your action: I or Q: Q

manage_agents: Exiting.
```

Any ideas how I can fix this weird state?

**Comment by ddpbsd** [comment]
Re-run the installer. Do not upgrade the install, choose the server type installation.

**Comment by Avamander** [comment]
Still the same output.

**Comment by Avamander** [comment]
Okay, so if someone stumbles upon this, do not abort mid-setup and try to install a different type of install from the same extracted folder. The installation script doesn't handle that.

**Comment by ddpbsd** [comment]
Sorry, I forgot a step. Tou probably needed to `make clean` in src

**Comment by Avamander** [comment]
Maybe the line could be included in the installation script?
