### ISSUE TITLE
warning: script 'ossec-authd' missing LSB tags and overrides

### ISSUE THREAD

**Issue by ogmueller** [ossec/ossec-hids#1298]
During `apt dist-upgrade` I get the following error message:

```
update-initramfs: deferring update (trigger activated)
insserv: warning: script 'ossec-authd' missing LSB tags and overrides
insserv: There is a loop between service monit and ossec-authd if stopped
insserv:  loop involving service ossec-authd at depth 2
insserv:  loop involving service monit at depth 1
insserv: Stopping ossec-authd depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
```

This could be solved by adding LSB tags to the init script like those from `ossec`:
```
### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop OSSEC HIDS
# Description:       Controls OSSEC HIDS daemons
#
### END INIT INFO
```

Would it be possible to add those LSB tags to prevent issues with apt or similar commands?

More info:
I am on an Ubuntu 16.04.

```
# /var/ossec/bin/manage_agents -V

OSSEC HIDS v2.9.2 - Trend Micro Inc.
```

**Comment by ddpbsd** [comment]
Which file needs this information? I don't see a `ossec-authd` script in the repo.

**Comment by martin9959** [comment]
The Ubuntu deb distributed by Atomicorp comes with a "/var/ossec/etc/init.d/ossec-authd" script which lacks LSB tags. Their postinst script then creates the link to /etc/init.d/. 

The github sources here don't seem to create this "/var/ossec/etc/init.d/ossec-authd" file, and the [postinst script](https://github.com/ossec/ossec-hids/blob/master/contrib/debian-packages/ossec-hids/debian/postinst) doesn't contain the part that creates the link from /etc/init.d either, so maybe Atomicorp is at fault? On the other hand, the Debian scripts in this repository look rather outdated, referring to 2.8.2.

**Comment by ddpbsd** [comment]
Maybe @atomicturtle knows where the script comes from?

**Comment by atomicturtle** [comment]
Yeah its something generated during the build process. We'll get it in 2.9.3
