### ISSUE TITLE
ossec.conf in YAML?

### ISSUE THREAD

**Issue by a3rd** [ossec/ossec-hids#1299]
I would like to write the entries for ossec.conf in YAML, as its becoming a popular tool for writing in automation.

There would be ways of parsing YAML to XML where the XML is then read into ossec, however a more permanent solution would be that the files are natively written in YAML then parsed by the application, or something similar.

Basically YAML configuraiton would be the single source of truth, and OSSEC would do the parsing behind the scenes.

**Comment by ddpbsd** [comment]
As you work on this, keep in mind converting current xml based `ossec.conf` files. Making it as seamless as possible would be necessary due to the install base.
