### ISSUE TITLE
ossec + elk

### ISSUE THREAD

**Issue by borbelyau** [ossec/ossec-hids#1300]
Hi guys
How are you?
Anybody have any clue, how integrate ossec + elk?

Tks

**Comment by ddpbsd** [comment]
There are a number of ways to do this.  I haven't done it in a while though.
I want to try using `filebeat` to read the `alerts.json` file, but haven't had a chance to test it yet.
You could using `ossec-csyslogd` to send alerts to a listening `logstash` instance. json or cef might even work nicely there.

**Comment by borbelyau** [comment]
@ddpbsd tks... I want integrate with logs sended by ossec agent

**Comment by ddpbsd** [comment]
You want to ingest the individual log messages sent from the agents into elasticsearch? If so, OSSEC isn't really setup to handle that exactly. You can get part way there using `archives.log`, but the header might be problematic.

**Comment by borbelyau** [comment]
@ddpbsd not for elastic... but from logstash

**Comment by ddpbsd** [comment]
I guess I don't understand the question.

**Comment by borbelyau** [comment]
How I send logs from agent to logstash on manager to reproduce in kibana

**Comment by ddpbsd** [comment]
You don't. The agents communicate with the OSSEC manager server. If you want the individual agent logs to be ingested into whatever by logstash, you can use the `archives.log` file if you turn on the `logall` option on the manager. There is a header attached to each log message though, and you may have to figure out how to remove it before ingestion.

**Comment by borbelyau** [comment]
tks @ddpbsd

**Comment by vichargrave** [comment]
I wrote a blog on how to get OSSEC alerts into ELK - https://vichargrave.github.io/articles/2013-11/ossec-log-management-with-elasticsearch <https://vichargrave.github.io/articles/2013-11/ossec-log-management-with-elasticsearch>.  It is somewhat dated, but still a valid approach.  I used the syslog approach that Dan mentioned.

**Comment by dbgdngit** [comment]
ossec-csyslogd does work for forwarding to ELK. You have to have some decent grok filters as per @vichargrave advice to get the best out of it. Also its UDP so I have experienced message loss which can be difficult to trace, however i suspect a udp load balancer I have in front the elk cluster

**Comment by dbgdngit** [comment]
actually @ddpbsd is issue 812 truly fixed in 2.9.2. I'd really like to use DNS name in the syslog_output parameter so i can take advantage of route 53 load balancing?

**Comment by ddpbsd** [comment]
I haven't tested csyslogd.
