### ISSUE TITLE
blog post references to vichargrave.com must be changed, as that domain has gone to the dogs

### ISSUE THREAD

**Issue by carehart** [ossec/ossec-hids#1301]
Folks, I was directed by a colleague today to OSSEC for the first time today, and while perusing things, I came upon this post:

https://ossec.github.io/blog/posts/2013-12-15-OSSEC-Log-Management-with-Elasticsearch.markdown.html

which has a "Read more" link that tries to go to: 

http://vichargrave.com/ossec-log-management-with-elasticsearch/

When I clicked it, I got nasty warnings about having been hit by a virus, etc. After restarting my browser and digging further, I see that Vic's old vichargrave.com domain has sadly become a dumping ground for spam and viruses. (I realize that's out of his hands if he gave it up or lost it for not renewing.)

At a minimum, that read more link should be changed to reference:

https://vichargrave.github.io/articles/2013-11/ossec-log-management-with-elasticsearch

Better would be for someone to look for any other old references in the blog (or broader project site) to vichargrave.com and change them to vichargrave.github.io. (I didn't see any way for me to do that for you here. I admit I've never had an occasion to consider modifying blog posts in a github project.)

Of course, my goal here is not to embarrass him or denigrate the project but indeed just trying to help both, especially given the project's goals.

**Comment by vichargrave** [comment]
Sorry about that.  I should have changed the link on the OSSEC website.  I’ll fix that right away.

— vic

**Comment by ddpbsd** [comment]
Looks like that was the only one. Fixed by Vic in https://github.com/ossec/ossec-docs/pull/225
Thanks for pointing it out!
