### ISSUE TITLE
Mail notification on root didn't give a notification

### ISSUE THREAD

**Issue by gagantous** [ossec/ossec-hids#1303]
i have read this tutorial

https://komunity.komand.com/learn/article/security-monitoring/how-to-install-and-configure-ossec-on-ubuntu-linux/

they said, i need to configure my `ossec.conf` like this

```
<global>
  <email_notification>yes</email_notification>
  <email_to>root@localhost</email_to>
  <smtp_server>127.0.0.1</smtp_server>
  <email_from>ossecm@localhost</email_from>
</global>
```

After that i will check with command `mail` to get the notification. but instead i got  `no mail for root`  ....
when i tried to use the web UI, it give me the notification, but with command `mail` it gives me nothing

Is anything wrong with my conf ?

**Comment by ddpbsd** [comment]
I don't see an error in the configuration. Are there any related errors in the `ossec.log` or your smtpd's log file?

**Comment by gagantous** [comment]
where can i check my smtpd log ?

**Comment by atomicturtle** [comment]
wherever your mail server logs to, usually /var/log/maillog or the like
