### ISSUE TITLE
Error config

### ISSUE THREAD

**Issue by borbelyau** [ossec/ossec-hids#1305]
Hey Guys ...
How are you?
When I install ossec... I dont know why my /var/ossec/queue/ossec is empty!
I reinstall and is the same error

Tks

**Comment by ddpbsd** [comment]
What is the error you receive?

**Comment by borbelyau** [comment]
That directory is empty

**Comment by ddpbsd** [comment]
Strange, I'm not seeing that error message in the source:
```
[ddp@ix] :; pwd
/home/ddp/src/projects/git/github/ddpbsd/ossec-hids
[ddp@ix] :; grep -ri 'directory is empty' *
[ddp@ix] :;
```

**Comment by borbelyau** [comment]
/var/ossec/queue/ossec

**Comment by ddpbsd** [comment]
```
2017/10/31 11:35:09 ossec-testrule(1226): ERROR: Error reading XML file '/var/ossec/etc/ossec.conf': XMLERR: Element 'jsonout_output' not closed. (line 3).
```

That seems pretty self explanatory. Perhaps you mis-typed `</json_output>`? I do that kind of thing constantly.
