### ISSUE TITLE
The global email notification always return to my old email and smtp setting 

### ISSUE THREAD

**Issue by gagantous** [ossec/ossec-hids#1308]
The ossec service always killed whenever a package were being installed in our linux ( i am using Debian 7 ).  Whenever i tried to for example `#apt-get install ****`, the ossec always stop and just after it, it will restart again. I think it's a normal behavior. But WHen ossec is trying to start , it always give me an error like this.

```
Processing triggers for man-db ...
Setting up ossec-hids-server (2.9.2.2154wheezy) ...
update-rc.d: using dependency based boot sequencing
Deleting PID file '/var/ossec/var/run/ossec-remoted-12367.pid' not used...
Killing ossec-monitord ..
Killing ossec-logcollector ..
ossec-remoted not running ..
Killing ossec-syscheckd ..
Killing ossec-analysisd ..
Killing ossec-maild ..
Killing ossec-execd ..
OSSEC HIDS v2.9.1 Stopped
Starting OSSEC HIDS v2.9.1 (by Trend Micro Inc.)...
2017/10/31 08:54:06 ossec-maild(1501): ERROR: Invalid SMTP Server:
2017/10/31 08:54:06 ossec-maild(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
2017/10/31 08:54:06 ossec-maild(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
ossec-maild did not start correctly.
dpkg: error processing ossec-hids-server (--configure):

```
This was happen when i tried to install any package.
It's kinda weird so i check my `ossec.conf`, i was surprised that the global conf were return to my oldest setting like the conf below:

```
  <global>
    <email_notification>yes</email_notification>
    <email_to>fa***************@gmail.com</email_to>
    <smtp_server></smtp_server>
    <email_from>ossec@localhost</email_from>
  </global>
```

The default setting is like : 

```
<global>
    <email_notification>yes</email_notification>
    <email_to>root@localhost</email_to>
    <smtp_server>127.0.0.1</smtp_server>
    <email_from>ossec@localhost</email_from>
  </global>
```

Look at the `<email_to>` and `<smtp_server>`, It give me my email, and the smtp were missing. Before i turn my conf into default, i tried to used postfix so i changed my `<email_to>` with my gmail account, and `<smtp_server>` into my own ip address ( i have configure my postfix so the it will forwarded ).

i have `#apt-get purge postfix` it means that the `postfix` were completely removed from debian. but why my setting are still on there ? can you help me with this ?

**Comment by ddpbsd** [comment]
The OSSEC processes stopping when you install a package isn't normal. I can't think of anything in ossec that would account for this behavior. What version of OSSEC are you using? Are you using the package? If so, is there a configuration step that hasn't completed or something?

**Comment by reyjrar** [comment]
Set <email_notifications>no</email_notifications> if you don't want email notifications, having an empty element in that block will result in a failed start of OSSEC.

OSSEC will not restart on every package install/upgrade, but it's possible that apt is recording the failure to start OSSEC and is trying to get '/var/ossec/bin/ossec-control start' to exit with a 0 before it's clearing it from it's internal transaction list.

I would '/var/ossec/bin/ossec-control restart' to see what's happening.  It's also possible someone configured apt to run a global hook after installation.  I'm not a Debian admin, so you're going to need to use your Google skills to figure out if that's the case.
