### ISSUE TITLE
Can OSSEC turn into HIPS ?

### ISSUE THREAD

**Issue by gagantous** [ossec/ossec-hids#1309]
I know that OSSEC is Open Source Host Intrusion Detection system. Is there any possible way that OSSEC can "prevent" a data for being infected to a virus or a hacker attack ?

For example:
- I have install ossec on my OS
- Trying some Rules, it seems work
- Some of the default rules can even handle the "brute force" attack.
- ( in case ) suddenly, out of nowhere, the attacker can acces the OS
- They did like spread some virus like trojan horse/malware, exlpoit, spoofing the data, etc

Can we make the ruler to handle that such thing ? if so, how ? 

I am sorry, i am just starting ossec a couple days ago so i dont quiet understand

Sincerely

**Comment by givilleneuve** [comment]
Hi gagantous,
I'm also newer with OSSEC, but I have read about, it can also act as HIPS once you have active response enabled.
In your example, you can use active response for if a rule brute force is matched, the action to block source ip is triggered.

**Comment by gagantous** [comment]
@givilleneuve  okay got it
