### ISSUE TITLE
Sysmon + Ossec

### ISSUE THREAD

**Issue by borbelyau** [ossec/ossec-hids#1312]
Hey guys... 
The integration of sysmon on ossec is possible?
tks

**Comment by nbuuck** [comment]
As `sysmon` (for those following along, it's a low-level/kernel event logging process from the [Sysinternals](https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon) suite for Windows hosts) logs to Event Viewer, it's absolutely possible. There's already a decoder and [default rules](https://github.com/ossec/ossec-rules/blob/4f32c0d2fcf6529d40e2ecb2b9b8eab3d9d9623f/rules.d/50-sysmon_rules.xml) for `sysmon`.
