### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by adamgyongyosi** [ossec/ossec-hids#1314]
centos 7

/var/ossec/bin/ossec-dbd
2017/11/09 11:29:08 ossec-dbd(5207): ERROR: OSSEC not compiled with support for 'mysql'.
2017/11/09 11:29:08 ossec-dbd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

why??

OSSEC HIDS v2.9.2 - Trend Micro Inc.

**Comment by krallin** [comment]
You need to configure it with MySQL support when you compile OSSEC:

```
DATABASE=mysql ./install.sh
```

Be mindful that if you've run `install.sh` already , this doesn't work as-is, you'll need to run `cd src && make clean` from the source checkout first.

**Comment by adamgyongyosi** [comment]
thx @krallin
