### ISSUE TITLE
Bug in decoder interpreter

### ISSUE THREAD

**Issue by rwagner-inf** [ossec/ossec-hids#1315]
I'm creating a custom decoder for pfSense.
The decoder follows:
```

<!-- PFSENSE
Nov  8 12:37:34 pfSense filterlog: 5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166
 -->
<decoder name="pf">
  <prematch>^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
</decoder>

<decoder name="pf_filterlog">
  <parent>pf</parent>
  <regex offset="after_parent">^ filterlog: \d+,,,(\d+)</regex>
  <order>id</order>
</decoder>
```

When testing with ossec-logtest, putting a log entry with only 1 digit in the day field of the date the decoder does not work.
If I put 2 digits in the date day field it works. This is strange.

Here is an example:
![image](https://user-images.githubusercontent.com/24550871/32606324-ac044276-c533-11e7-8073-6b4031764600.png)

I also tried putting the following:
```
<prematch>^\w\w\w  \d \d\d:\d\d:\d\d pfSense|^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\.*pfSense</prematch>
and
<prematch>^\w\w\w  \w \d\d:\d\d:\d\d pfSense|^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\w\w\w\s\s\d+ \d\d:\d\d:\d\d pfSense</prematch>
```

None of these ways worked, just with the \d+ and 2 digits in day field of log entry.

**Comment by ddpbsd** [comment]
In your 2 digit date example, it looks like there are 2 spaces between `Nov` and `18`. There should be only 1 space for 2 digit days, 2 spaces for 1 digit.

**Comment by ddpbsd** [comment]
Ok, I got it straight now. Your decoder works for the second example because there are too many spaces between `Nov` and `18`, so the pre-decoder does not recognize it and considers it part of the log instead of the metadata.

**Comment by rwagner-inf** [comment]
Hi @ddpbsd!

In both cases there are 2 spaces between the "MMM" field and the day, but the decoder only recognizes everything as a log when the day has 2 digits, which is strange.

Sorry for misinformation, but recognize the "pfSense" and "filterlog" fields as part of the log is wrong if I want to do a custom decoder?

**Comment by ddpbsd** [comment]
If there is only 1 digit in the day, there should be 2 spaces. If the day has 2 digits (18), there should be only 1 space. There are too many spaces in the double digit day example, which changes the way the log message is pre-decoded.
As I explained on the mailing list, the date, hostname, and program_name are metadata. The program and maybe hostname can be accessed by a decoder or rule, but not in a match field.

**Comment by ddpbsd** [comment]
How are you sending the logs to elasticsearch?

**Comment by rwagner-inf** [comment]
Yes!

syslog(514)  > ossec > logstash > elasticsearch

**Comment by ddpbsd** [comment]
Ok, and what configuration have you don't with logstash? It's been a while since I've looked at logstash for OSSEC stuff.
How are you reading the alerts?
What filters do you have in place?

**Comment by rwagner-inf** [comment]
Hi @ddpbsd!

I did not customize filter for this. Why would it be so much better if this information came from ossec. and I find it wasteful to process twice the same log, since ossec already does decode, changing again with logstash would not be efficient.

Vikman90 set this on wazuh, follow the commit:
https://github.com/wazuh/wazuh/commit/846ca232424aae7bc352b08bd920ef2c251a3874

**Comment by ddpbsd** [comment]
Port that over to OSSEC. I'll test it out.

**Comment by ddpbsd** [comment]
On second thought, they've done a lot of work in the json output. Copying it exactly might be difficult.

**Comment by ddpbsd** [comment]
In a fit of extreme laziness, you can try this branch:
https://github.com/ddpbsd/ossec-hids/tree/wazuh_timestamp
