### ISSUE TITLE
OSSEC v2.9.2 missing commit for decoders to extract filenames

### ISSUE THREAD

**Issue by reyjrar** [ossec/ossec-hids#1321]
This commit is currently not in the v2.9.2 release but is merged into master:

https://github.com/ossec/ossec-hids/commit/86eb1c5e2395806f7d77044b58a0ae322938da47

**Comment by ddpbsd** [comment]
2.9.2 is done. I don't think we're going to push anything else to that branch.

**Comment by atomicturtle** [comment]
Adding this to 2.9.3 branch
