### ISSUE TITLE
Significant OSSEC traffic after Mcafee installation

### ISSUE THREAD

**Issue by LFBernardo** [ossec/ossec-hids#1325]
Hi All,

I am not quite sure how to articulate this but will do my best. 

We have been running OSSEC 2.8.3 for close to 2.5 years now without incident. Recently we started rolling out Mcafee on Microsoft Server 2012. We now have random remote sites after the implementation of Mcafee flooding our WAN links with uploads to the OSSEC server (not that it takes much with the slow speeds in South Africa). The traffic generated is encrypted so TCPDUMP and wireshark doesn't really tell me much. The logs on OSSEC server side is also not being updated with any information or events. So there is no way (that I can see) in which to determine what traffic is actually being sent to remedy the situation. Unfortunately updating the clients to 2.9 is no small task as we are looking at almost 4.5K endpoints. This is also only seen on the server and not the other end points (but they are also receiving different Mcafee products)

**Service Specs:**
OSSEC server 2.8.3 Appliance as supplied - compiled run to support large number of hosts (no modifications other than that)
Ossec Agents 2.8.3 32-bit

**Client:**
Server 2012 X64

**Mcafee Versions:**
ENS Security Platform 10.5.2.2072
ENS Threat prevention 10.5.2.2108
Agent 5.0.6.220

**Config:**
Standard config with two folders added that I may not disclose here.

**Timing:**
Mcafee products installed server reboots traffic starts. 

**Log Information:**
Client logs - no information of any kind of error or problem state. 
Server logs (Alerts, Messages etc) - No information relating to problematic host.

Any advice or troubleshooting assistance would be appreciated.

**Comment by atomicturtle** [comment]
you can enable the logall setting: https://ossec.github.io/docs/faq/ossec.html?highlight=logall#where-are-ossec-s-logs-stored this will record every event to archives.log, not just those that match a rule.

**Comment by LFBernardo** [comment]
Ta, will give it a go. Have to put it through change control so will update once that process completes.

**Comment by LFBernardo** [comment]
Further information has come to light, after removal of the current AV and implementation of Mcafee, the servers require a reboot to finalise the configuration. At this point something in the Mcafee install triggers massive logging to Windows Filtering Platform (WPF) causing a log transfer loop. The sequence is as follows:
Step 1. OSSEC HIDS sends data OSSEC server
Step 2. A log entry is created in WPF for the activity
Step 3. OSSEC HIDS sends new log entry to OSSEC server triggering step 2.

Essentially causing a log loop. Cause of WPF becoming enabled still undetermined. Will update if further information becomes available.
<img width="559" alt="event" src="https://user-images.githubusercontent.com/18407412/33446633-5abb7682-d609-11e7-8feb-29d83a987662.png">
<img width="585" alt="logs" src="https://user-images.githubusercontent.com/18407412/33446635-5cc76d50-d609-11e7-9fcd-15475555adfc.png">

**Comment by atomicturtle** [comment]
Not sure if theres anything else actionable here on our side, but if you have any further info feel free to open this issue back up

**Comment by LFBernardo** [comment]
Just a small update, this problem is specific to Microsoft server 2012 and later as far as the evidence go. To fix the noise a GPO setting that has the same configuration as the cli command below is required. This command can also be run on a schedule. 

NOTE: The settings needs to be re-applied on reboot, tested with both production and fresh test servers.

auditpol /set /category:"Policy Change" /success:disable /failure:enable

**Comment by nbuuck** [comment]
That's strange, as the events shown in your screenshot from https://github.com/ossec/ossec-hids/issues/1325#issuecomment-348270492 are not within the Policy Change event category. The `auditpol` command you shared disables the auditing of attempts to change user rights assignment policy, audit policy, account policy, or trust policy. Your screenshots show a different type of Security event, `Filtering Platform Connection`. Perhaps some other change that was concurrent with running that command is responsible for the resolution.

**Comment by LFBernardo** [comment]
Apologies, I posted the original from a forum. The correct one is

auditpol /set /subcategory:"Filtering Platform Connection" /success:disable /failure:enable

sorry about that.
