### ISSUE TITLE
Windows Agent gives useless alerts

### ISSUE THREAD

**Issue by Avamander** [ossec/ossec-hids#1326]
I'm getting "Rule: 18111 fired (level 8) -> "User account changed." e-mails every time the system (Windows 10) boots, but the e-mails are rather useless, the only thing that changes is the date and time. Or is the "user account changed" email misleading and I am just supposed to get e-mail about the system booting?

Log snippet I'm getting:
`2017 Dec 03 11:38:08 WinEvtLog: Security: AUDIT_SUCCESS(4738): Microsoft-Windows-Security-Auditing: (no user): no domain: DESKTOP-QWERTY: A user account was changed. Subject:  Security ID:  S-1-2-34  Account Name:  DESKTOP-QWERTY$  Account Domain:  WORKGROUP  Logon ID:  0x000  Target Account:  Security ID:  S-1-2-34-5678909876-5432101234-5678909876-5432  Account Name:  Taavi  Account Domain:  DESKTOP-QWERTY  Changed Attributes:  SAM Account Name: -  Display Name:  Taavi Eamae  User Principal Name: -  Home Directory:  -  Home Drive:  -  Script Path:  -  Profile Path:  -  User Workstations: -  Password Last Set: -  Account Expires:  -  Primary Group ID: -  AllowedToDelegateTo: -  Old UAC Value:  -  New UAC Value:  -  User Account Control: -  User Parameters: -  SID History:  -  Logon Hours:  -  Additional Information:  Privileges:  -`

**Comment by ddpbsd** [comment]
The log message literally says `A user account was changed`. A quick google of event id `4738` gives me `A user account was changed`. I don't see anything in the log message that really explains what was changed (but I'm not an expert or anything). I don't know how we could modify things to exclude reboots.

**Comment by nbuuck** [comment]
Because `Display Name:` has a value and appears after the `Changed Attributes:` header, your user's display name is being updated by your workstation's computer account when this particular instance of the event occurs. You could suppress this event in OSSEC by creating a new rule in `local_rules.xml` that matches on rule `18111` and matches on `Display Name: Taavi Eomäe` and sets the level to anything less than the current value of `<email_alert_level>` in `ossec.conf`.

**Comment by Avamander** [comment]
Why would the username be changing though?

**Comment by nbuuck** [comment]
This is likely a result of running the agent on desktop release like Windows 10. I've reviewed my environment's logs consisting of a mix of Server 2008 R2 and 2012 R2 domain controllers and this kind of event simply does not occur when a user first logs on.

**Comment by Avamander** [comment]
Should I rename this issue to something like "Agent on Windows 10 gives erroneous warnings"?

**Comment by nbuuck** [comment]
I think that's debatable. I don't think the default rule set was made with workstation editions of Windows specifically in mind - that's not to say that they're unsupported, but I think the Server edition is the primary audience. Further, _other_ changes to user account objects may be significant to security analysts, so I'm not sure this is an issue so much as an atypical use case. My recommendation is still the same: use `local_rules.xml` to reclassify events that match this scenario to an alert level (even 0) that is appropriate for your situation.

**Comment by ddpbsd** [comment]
I think this is a case of "local tuning is required."
