### ISSUE TITLE
Missing RPMs for Centos7

### ISSUE THREAD

**Issue by derekzyc** [ossec/ossec-hids#1329]
The RPMs for Centos7 are missing from https://updates.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/

Because of that, yum fails to install ossec

**Comment by atomicturtle** [comment]
Should be sorted out now! Cleanup issue when we were posting 2.9.3

**Comment by dlyub** [comment]
@atomicturtle it appears that 'ossec-hids-client' package is still missing. Can you please look into this?

**Comment by atomicturtle** [comment]
Sure, that package is now called ossec-hids-agent. It is tagged internally as Provides: ossec-hids-client

**Comment by dlyub** [comment]
Thank you @atomicturtle
