### ISSUE TITLE
CC ossec-authd.  Installing Issues

### ISSUE THREAD

**Issue by zuoanyingxue** [ossec/ossec-hids#1331]
os_auth/main-server.c: In function 'main':
os_auth/main-server.c:178: warning: implicit declaration of function 'OS_PassEmptyKeyfile'
    CC os_auth/ssl.o
os_auth/ssl.c: In function 'get_ssl_context':
os_auth/ssl.c:107: warning: implicit declaration of function 'TLSv1_2_method'
os_auth/ssl.c:107: warning: assignment makes pointer from integer without a cast
    CC os_auth/check_cert.o
    CC ossec-authd
os_auth/ssl.o: In function `get_ssl_context':
ssl.c:(.text+0x26b): undefined reference to `TLSv1_2_method'
collect2: ld returned 1 exit status
make64: *** [ossec-authd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
-----------------------------------------------------------------------------------------------------------
How can I solve this problem, can anyone help me？？？？？thank you！！！！

**Comment by ddpbsd** [comment]
What version of the openssl development libraries do you have installed?

**Comment by zuoanyingxue** [comment]
thank you your answer！！
I had Installed it on VM successfully.Because I use the company‘s server, there is permission limit。
But after I added agent inwindows，“./agent_control -lc” command cannot list this "Active" agent.Why?

**Comment by ddpbsd** [comment]
Check the ossec.log on the agent and the server. Perhaps the key was not installed correctly?
