### ISSUE TITLE
Issues with "Manual APT Installation on Ubuntu and Debian"

### ISSUE THREAD

**Issue by lachlanmunro** [ossec/ossec-hids#1332]
From: https://ossec.github.io/downloads.html#manual-apt-installation-on-ubuntu-and-debian

The line: `wget -q -O - https://www.atomicorp.com/RPM-GPG-KEY.art.txt  | sudo apt-key add -` does not reference a key matching the repo (for debian at least).

Trawling through https://www.atomicorp.com/installers/atomic (the all in one script) references https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt which seems to work fine.

**Comment by atomicturtle** [comment]
Added to ossec-docs project
