### ISSUE TITLE
Cannot compile from master: sqlite3.h: no such file or directory

### ISSUE THREAD

**Issue by HatBeardMe** [ossec/ossec-hids#1354]
Having issues installing ossec server on new amazon ubuntu 16.04 instance. 
Tried installing via released tar (2.9.3) and it installed, but did not register a listener on 1514.
So, finding an old related issue #1061 and PR #1259 (merged), tried installing via cloning master (after cleanup of older install attempts).
Getting the following error:
```
In file included from analysisd/analysisd.c:44:0:
analysisd/syscheck-sqlite.h:1:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
Makefile:1135: recipe for target 'analysisd/analysisd-live.o' failed
make: *** [analysisd/analysisd-live.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
```

It appears that it is looking to include `sqlite3.h` in `src/analysisd/syscheck-sqlite.h` however that file is not included when cloning master branch.

as an aside, I have cloned a couple of tags and branches, they seem to build fine, but I still have issues with 1514 not listening.

**Comment by ddpbsd** [comment]
Not sure about your 1514 issue, you didn't provide any details. But master now requires sqlite. Maybe I'll ifdef it so people don't have to install sqlite, but I'd rather not at this point.

**Comment by testerrrrrr** [comment]
I am facing same issue.

**Comment by testerrrrrr** [comment]
5- Installing the system
 - Running the Makefile
cd external/lua/ && make posix
make[1]: Entering directory '/home/stg03/ossec-hids/src/external/lua-5.2.3'
cd src && make posix
make[2]: Entering directory '/home/stg03/ossec-hids/src/external/lua-5.2.3/src'
make all SYSCFLAGS="-DLUA_USE_POSIX"
make[3]: Entering directory '/home/stg03/ossec-hids/src/external/lua-5.2.3/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/stg03/ossec-hids/src/external/lua-5.2.3/src'
make[2]: Leaving directory '/home/stg03/ossec-hids/src/external/lua-5.2.3/src'
make[1]: Leaving directory '/home/stg03/ossec-hids/src/external/lua-5.2.3'
    CC analysisd/analysisd-live.o
In file included from analysisd/analysisd.c:44:0:
analysisd/syscheck-sqlite.h:1:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
Makefile:1135: recipe for target 'analysisd/analysisd-live.o' failed
make: *** [analysisd/analysisd-live.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
 
root@ubuntu:/home/stg03/ossec-hids#

**Comment by ddpbsd** [comment]
@testerrrrrr Did you install the sqlite package?

Pull request #1364 makes this unnecessary, as the feature will be optional.

**Comment by testerrrrrr** [comment]
Yes, I have installed sqlite package, still getting the error, I have downloaded the latest one from master branch.

**Comment by ddpbsd** [comment]
@testerrrrrr Which distro are you using?

**Comment by testerrrrrr** [comment]
https://github.com/ossec/ossec-hids.git

**Comment by testerrrrrr** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by ddpbsd** [comment]
Ok, I'll try to test it out.

**Comment by testerrrrrr** [comment]
Thank you,

**Comment by nbuuck** [comment]
Perhaps the associated lib package is required when compiling? https://packages.ubuntu.com/xenial/libsqlite3-dev

I only mention this because the comments on this issue could be interpreted as you having installed sqlite but not the development package needed for linking to `sqlite3.h`.

**Comment by testerrrrrr** [comment]
@nbuuck Yes, It worked !!

Thanks a lot, I just installed libsqlite3-dev and it worked like a charm.

Thanks again.

**Comment by ddpbsd** [comment]
It looks like Ubuntu needs `libsqlite3-dev`

**Comment by testerrrrrr** [comment]
Correct.

**Comment by ddpbsd** [comment]
I've added these packages to the documention (https://github.com/ossec/ossec-docs/pull/237) pull request.

**Comment by alansmid** [comment]
@nbuuck Thank you!
