### ISSUE TITLE
Changing the default name of the syscheck agent files

### ISSUE THREAD

**Issue by GuillaumeOrlando** [ossec/ossec-hids#1355]
Hi,

I am building a script for monitoring file integrity in multiple cluster of ossec agents, but I have some trouble with the names that are given by default to the agent, in the /var/ossec/queue/syscheck/ directory. 
By default, on the ossec server, it's something like '(Agent_Name) IP -> syscheck '. 
I need to change this for all of the new agents, but i didn't found where to do that ...

Ideally, the syscheck files should have the same name as the agents.

Any idea ?

Thanks 😄

**Comment by ddpbsd** [comment]
A guess off the top of my head, it would be somewhere in https://github.com/ossec/ossec-hids/blob/master/src/analysisd/decoders/syscheck.c

**Comment by HomardBoy** [comment]
Well, i managed to solve this with these lines of bash =

`if [ -e "/var/ossec/queue/syscheck/.(${1}) ${IPADDR}->syscheck.cpt" ]; then
        mv "/var/ossec/queue/syscheck/.(${1}) ${IPADDR}->syscheck.cpt" \
           "/var/ossec/queue/syscheck/.${2}"
fi`

It's not as practical as i thought, but it work !
