### ISSUE TITLE
WinEvtLog alerts after upgrade - need to stop

### ISSUE THREAD

**Issue by TriciaE66** [ossec/ossec-hids#1358]
Recently upgraded the windows agents and now receiving lots of alerts for the following rules:
Rule 18107 - Windows Logon Success - WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: <id>: <domain>: <server>: An account was successfully logged on.
Rule 18149 - Windows User Logoff - WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: <id>: <domain>: <server>: An account was logged off.
Rule: 1002 - Unknown problem somewhere in the system. WinEvtLog: Application: INFORMATION(0): xxx: (no user): no domain: <server>: Error occurred getting most recent errorlog item: ORA-12170: TNS:Connect timeout occurred    
Rule: 18145 - Service startup type was changed. WinEvtLog: System: INFORMATION(7040): Service Control Manager: SYSTEM: NT AUTHORITY: <server>: The start type of the Windows Modules Installer service was changed from demand start to auto start.  
Rule: 7501 - McAfee Windows AV informational event. WinEvtLog: Application: INFORMATION(5000): McLogEvent: SYSTEM: NT AUTHORITY: <server>: McShield service started.    Engine version : 5900.7806    DAT version : 8786.0000        Number of signatures in EXTRA.DAT : None    Names of threats that EXTRA.DAT can detect : None  

Suspect more will come out in due course.
Can someone please advise on a) how to stop these alerts being generated or b) how to reduce the lert level from 3/2 to a 1.

Thanks

**Comment by nbuuck** [comment]
Being an OSSEC user in a primarily-Windows environment, I'd caution that configuring the email threshold for anything lower than 5 is rather aggressive and unsurprisingly results in an excessive volume of alerts being sent. Have you considered increasing your `email_alert_level` value in `ossec.conf`[[1](https://ossec.github.io/docs/syntax/head_ossec_config.alerts.html#element-email_alert_level)]?

Short of that, you can define a custom rule in `/rules/local_rules.xml` to assign a different level to an alert like this:

```
<group name="windows,">

  <rule id="100012" level="0">
    <if_sid>18105</if_sid>
    <description>Suppress failed logons.</description>
  </rule>

</group> <!-- WINDOWS, -->

<!-- EOF -->
```

In this example, the `id` in the `<rule>` element is one you arbitrarily assign but must be unique. The ID in `<if_sid>` is the existing rule ID that you're acting on (in this case, changing its `level` value).

**Comment by TriciaE66** [comment]
Thanks for the advise.... much appreciated. Our environment is less Windows than Unix but nevertheless Windows is generating the most traffic. We will look into both options. Much appreciated.
