### ISSUE TITLE
Can't insall ossec agent on HP Ux platform

### ISSUE THREAD

**Issue by abshahaman** [ossec/ossec-hids#1359]
Hii,
i want to install ossec agent on HP UX platform,
but i have error while install it, the error shown on no 5 of step instalation
i get this error below :
 
1- What kind of installation do you want (server, agent, local, hybrid or help)? 
agent

  - Agent(client) installation chosen.

2- Setting up the installation environment.

 - Choose where to install the OSSEC HIDS [/var/ossec]: 

    - Installation will be made at  /var/ossec .

3- Configuring the OSSEC HIDS.

  3.1- What's the IP Address or hostname of the OSSEC HIDS server?: 
xx.xx.xx.xx

   - Adding Server IP xx.xx.xx.xx

  3.2- Do you want to run the integrity check daemon? (y/n) [y]: 
y

   - Running syscheck (integrity check daemon).

  3.3- Do you want to run the rootkit detection engine? (y/n) [y]: 
y

   - Running rootcheck (rootkit detection).

  3.4 - Do you want to enable active response? (y/n) [y]: 
y

  3.5- Setting the configuration to analyze the following logs:
    -- /var/adm/syslog/syslog.log

 - If you want to monitor any other file, just change 
   the ossec.conf and add a new localfile entry.
   Any questions about the configuration can be answered
   by visiting us online at http://www.ossec.net .
   
   
   --- Press ENTER to continue ---
                            

5- Installing the system
 - Running the Makefile
Make: line 4: syntax error.  Stop.

 Error 0x5.
 Building error. Unable to finish the installation.
 
before it i install on RHEL platform and success,

looking forward for your help and suggestion

Many Thanks

**Comment by nbuuck** [comment]
Please run `make --version` and provide the output here.

**Comment by ddpbsd** [comment]
OSSEC required GNU make, and is only tested with gcc and clang (I'm unsure whether other compilers would work or not).
