### ISSUE TITLE
Are there any plans to support journald logs?

### ISSUE THREAD

**Issue by q2dg** [ossec/ossec-hids#1367]
It seems it's pretty common nowadays having this kind of logs in current distros (Debian/Ubuntu, Fedora/CentOS, etc) instead of classical syslog ones.
Thanks!

**Comment by ddpbsd** [comment]
Not at the moment. I'm still hoping they see how bad of an idea journald is and revert.

**Comment by atomicturtle** [comment]
I think the biggest limitation with journald right now is that it buffers, so its not a mechanism that lets us analyze data in real time. That definitely puts it at a disadvantage to other kinds of log based intrusion detection

**Comment by ddpbsd** [comment]
Looking at the documentation (*shock*), it looks like the `ForwardToSyslog` option might be do-able. I'll try taking a look at it after I'm done with the current things I'm working on.
https://www.freedesktop.org/software/systemd/man/journald.conf.html#ForwardToSyslog=

**Comment by sempervictus** [comment]
@atomicturtle: that may actually be an advantage if disks went RO for some reason, or space filled up from a zip bomb all of a sudden (though I've not seen one in a while, and no, please don't send me one :-) ).
What about hooking journald itself, or using _journalctl -f_ to track subject units (or all the things)? There is a similar issue with Beats collectors, for which someone wrote journal beat as it required a wholly separate implementation (or ElasticCo folks had the same glimmer of hope for sanity to return).

**Comment by bbayles** [comment]
For what it's worth, modern `journalctls` support a cursor, which allows for easy following along. I've used the `journalctl --show-cursor --unit <whatever>` command and then followed a log with the `--after-cursor` switch before.

**Comment by dwellkamp** [comment]
Is there any progress on this issue? I'd really appreciate it.
Without journald support, logfile monitoring with ossec becomes more and more difficult on almost any modern Linux systems.

**Comment by ddpbsd** [comment]
@dwellkamp I haven't seen any pull requests related to this, and no one has asked questions about implementing anything. The work to support crippled systemdOS is either secret or non-existent. If you need help getting started, write down some ideas of how you'd like to tackle it and we can all look into it.

**Comment by dwellkamp** [comment]
Since I am not a developer/programmer I'd describe what my thought are.

Well, I'm no expert on this topic, but it seems systemd already got an (optional?) HTTP interface to follow it's logs called "systemd-journal-gatewayd".
I found this documentation on how to use it: https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html

I'd suggest systemd-journal-gatewayd could be listening for local connects only, since I'd like to avoid exposing this to remote connects. Would it be possible an ossec-agent continiously reads that interface? A follow option is mentioned in the docs.
Further it states it has a format option "text/plain" to return syslog-like plaintext output.

That would eliminate the need to forward all the journald-logs to a separate local syslog instance just to be able to dump them in plaintext logfiles.

**Comment by sempervictus** [comment]
Systemd services can log to stdout/err and the output will be captured and stored in the units log... That can be extracted via CLI invocation and tailed.
Far as supporting systemd... Doubt we have a choice. I held on to that dream for a while, finally had to say ... it and went to arch with it full tilt. It underpins most modern major distros (creating a pleasantly uniform attack surface).

**Comment by ddpbsd** [comment]
I have some test code for this (not linked to ossec in any way, just to learn). I'm having trouble figuring out the journald fields. For instance, which field would align to our `program_name`?
Some aspects of journald aren't as bad as I thought, and some are way worse. If I don't kill what I learned today with rum, I might be able to have a rough draft in a week or 2.

**Comment by illuusio** [comment]
As everyone hates journald there is work around to use syslog-ng with it. So it'll pass events to normal files in /var/log. In long run there should be support in for journald as it's not going away soon.

**Comment by sempervictus** [comment]
Windows has eventchannels, maybe another os-specific log ingest is not too outlandish. Part of the problem with systems though is the somewhat unpredictable development trajectory... Its stabilized a lot over the last couple years, and there should be enough consumers off of it to make em think twice about an api/abi change, but not out of the realm of possibility that this would entail some ongoing support.

**Comment by illuusio** [comment]
Yes.. Everyone  wants to invent wheel again that what happened with journald. System-ng is working as needed for me at least.

**Comment by illuusio** [comment]
Actually I investigated this a bit and for example fluent-bit systemd parser (https://github.com/fluent/fluent-bit/tree/master/plugins/in_systemd) uses systemd journald c-libary which read those journal-files straight ahead not from any socket.
I'm wondering how OSSEC-HIDS does these log format stuff are they just pre-configured for some log-format or can one do that kind of hack to use some external c-library as input log-format?

**Comment by ddpbsd** [comment]
I don't imagine getting basic journald support would be too difficult. I figured out most of the arcane bits necessary to get syslog-ish messages out of that mess, but gluing it into OSSEC was boring.

**Comment by zboszor** [comment]
When will this code be included in OSSEC?

**Comment by ddpbsd** [comment]
@zboszor After it's written.

**Comment by zboszor** [comment]
@ddpbsd I thought its was already because of your comment made on 22nd February this year.

**Comment by ddpbsd** [comment]
@zboszor I started writing it, got some parts of it figured out and got bored. So I moved to something more interesting.

**Comment by illuusio** [comment]
@ddpbsd Do you have any of code left for starting point or is better to start on clean desk?

**Comment by ddpbsd** [comment]
@illuusio No, I don't have anything useful. It was mostly to figure out how the journald stuff worked. I didn't try integrating it into logcollector or anything.

**Comment by sempervictus** [comment]
@atomicturtle: can you assign this to me? Working on a native systemd C interface implementation, its getting too problematic to wait for someone else to do it.

**Comment by illuusio** [comment]
Is there code to test?

**Comment by sempervictus** [comment]
@illuusio: #1852, to test and hack on (i dont expect it to even compile right now). This is in a rotating queue with metasploit work and other non-essential tasks on my kanban-chainsaw-of-hatef... thing, so would really appreciate any commits folks can stack on that first scaffold to at least help fill in the features described as needed in the commit/PR.

**Comment by illuusio** [comment]
@sempervictus Ok I'll give it a go

**Comment by illuusio** [comment]
Ok code mainly works but needs little bit polishing and add journald as accepted XML value for 
_logformat_

**Comment by sempervictus** [comment]
@illuusio: thank you! Please feel free to PR any diffs or if GH is being difficult just link to a branch and i'll pull your commits

**Comment by illuusio** [comment]
Now there should be PR for fixing compiling. I bundled all compiling problems in one PR if you like to merge more I can split them in separated ones.

**Comment by illuusio** [comment]
I someone is interested in testing WIP (Beta stage code) PR #1852 now should be the time.

**Comment by illuusio** [comment]
As now it official merged in git please test at least now..

**Comment by atomicturtle** [comment]
Closed by PR 1952
