### ISSUE TITLE
setfullsubject

### ISSUE THREAD

**Issue by mstarks01** [ossec/ossec-hids#1370]
setfullsubject=0, which makes subject lines more compact, seems to no longer work.

It used to be that I could just do this:

`#cd src; make setfullsubject
#cd ..; ./install.sh`

but the Makefile changed. So, I went in and set `CLEANFULL?=yes`, recompiled, and subsequently set `maild.full_subject=0` in etc/local_internal_options.conf.

I'm still getting longer subject lines.

**Comment by ddpbsd** [comment]
I didn't even know this was a feature.
Compiling with:
```
 gmake TARGET=server CLEANFULL=y
```
and setting this in `internal_options.conf`:
```
maild.full_subject=1
```
gives me this:
```
2 - Unknown problem somewhere in the system. - (rossak) 192.168.18.204
```

Is that what you're hoping for? When was the last time it worked how you expected?

**Comment by mstarks01** [comment]
It has been awhile since I have used OSSEC in production. Maybe 2.8.3? Look at step 5 [here](https://www.immutablesecurity.com/index.php/2010/10/20/2woo-tips-tricks/) to see how it is supposed to work.

**Comment by mstarks01** [comment]
I downgraded to 2.8.3 and it works correctly in that version, so this appears to be a regression.

**Comment by ddpbsd** [comment]
Tracking it down now. I'm not entirely sure how interested I am in when it was changed and why, but I'm expecting to have a fix shortly.

**Comment by mstarks01** [comment]
I'm going to do some more digging as well. I don't want you to spend too much time on this in case I configured the new makefile incorrectly or just forgot a step. :)

**Comment by ddpbsd** [comment]
I think the smaller subject may become the default post-3.0.

**Comment by ddpbsd** [comment]
Pull request #1377 allows this to work the way it used to.
