### ISSUE TITLE
upgrading from 2.8 to 2.9 via source

### ISSUE THREAD

**Issue by TechGameTeddy** [ossec/ossec-hids#1371]
I want to upgrade from 2.8.0 to the latest version of OSSEC (2.9) and have backed up the necessary files in case anything goes bad (https://ossec.github.io/docs/manual/notes/manager_backup.html?highlight=backup) but I'm still hesitant on the upgrade process. There is a guide from Digital Ocean that shows an upgrade process (https://www.digitalocean.com/community/tutorials/how-to-upgrade-ossec-2-8-1-to-ossec-2-8-2) but for the same version upgrade. I would like to know if I run an upgrade like this will I lose any of the rules or keys currently setup after updating to 2.9? 
Is there an easier way to do this on a CentOS/RHEL system?

**Comment by ddpbsd** [comment]
If you've kept your rule changes to `local_rules.xml` and decoder updates to `local_decoder.xml`, you shouldn't lose any rules. I haven't tried a 2.8 to 2.9 upgrade in a while, but I don't think there should be any major issues.

**Comment by TechGameTeddy** [comment]
Thank you for the help. What are the best ways to revert in case of an unsuccessful update? Is there a support link or guide that you may know of?

**Comment by ddpbsd** [comment]
I'm not aware of anything. If you stop the OSSEC processes on the server, and `cp -a` all of the files to a safe location, I imagine you could reverse it if you have any issues.

**Comment by variablenix** [comment]
>What are the best ways to revert in case of an unsuccessful update?

I would recommend making a copy of the entire OSSEC directory in `/var/ossec` before doing the upgrade. For what its worth -- when I went from 2.8 to 2.9 I ran into no alarming issues; however you may need to restore your local rules file as mentioned in this thread and back up any other important files you care about from the posted upgrade page: https://ossec.github.io/docs/manual/notes/manager_backup.html?highlight=backup

In my case, I did need to restore my local rules file in addition to configuration files.

**Comment by TechGameTeddy** [comment]
I performed the backup https://ossec.github.io/docs/manual/notes/manager_backup.html?highlight=backup 
then 
downloaded the source https://github.com/ossec/ossec-hids/releases 
ran the update and now all my servers are pinging back in showing notifications again..

I am using "cat /etc/ossec-init.conf" 
to check the ossec-version 
and it shouws TYPE=agent 


DIRECTORY="/var/ossec"
VERSION="v2.9.3"
DATE="Wed Mar  7 17:05:55 EST 2018"
TYPE="agent"


Shouldnt it be listed as a Server. 
The latest source doesnt have a seperate sever install so im not sure if I have to revert or reinstall the new update with different parameters. 

@variablenix  have you ever ran into something like this?

**Comment by variablenix** [comment]
Probably different parameters. If you're expecting the TYPE to be server then you may need to make sure `make TARGET=$USER_INSTALL_TYPE` is specified as server from `src` directory.

**Comment by TechGameTeddy** [comment]
I didnt have a v8 this morning @variablenix the upgraded completed and I now have a backup of it which is great. Thanks guys.
