### ISSUE TITLE
update from 2.8 to 2.9 ossec not complied with support for mysql

### ISSUE THREAD

**Issue by TechGameTeddy** [ossec/ossec-hids#1375]
I just recently update ossec from 2.8 to 2.9.2 from source. 
While trying to run it I get an error 

[root@squatch ossec-hids-2.9.3]# ossec-control start
Starting OSSEC HIDS v2.9.3 (by Trend Micro Inc.)...
2018/03/09 11:44:44 ossec-dbd(5207): ERROR: OSSEC not compiled with support for 'mysql'.
2018/03/09 11:44:44 ossec-dbd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
ossec-dbd did not start correctly.

I have checked and the upgrade was done with new rules. I can connect to mysql with the username and password that is in the ossec.conf file  and have tried troubleshooting with 
"/var/ossec/bin/ossec-dbd -df" 

but get the same errors 

2018/03/09 11:43:23 ossec-dbd(5207): ERROR: OSSEC not compiled with support for 'mysql'.
2018/03/09 11:43:23 ossec-dbd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

  <database_output>
     <hostname>127.0.0.1</hostname>
     <username>ossec_u</username>
     <password>********</password>
     <database>ossec</database>
     <type>mysql</type>
  </database_output>

#password is not actually *

**Comment by ddpbsd** [comment]
OSSEC needs to be compiled with database support if you plan on using a database.
`$ sudo env DATABASE=mysql ./install.sh`

**Comment by TechGameTeddy** [comment]
I found that and tried that but it failed. the original config and database were still present.... I decided to use the repo and do a yum install and ossec started running again. Not sure why sudo env DATABASE=mysql ./install.sh or /var/ossec/bin/ossec-control enable database didnt fix it but im okay now that its working.

**Comment by ddpbsd** [comment]
It might have been interesting to try and track that down. But glad it's working.

**Comment by TechGameTeddy** [comment]
Unfortunately I dont have that time at work. But if I can replicate it this weekend I will pm you and start troubleshooting more

**Comment by BClev** [comment]
I'm having the same issue. None of the commands here are working. I'll try pulling from apt-get
