### ISSUE TITLE
AIX build 7.1 ossec-hids 2.9.3

### ISSUE THREAD

**Issue by mascarasnake66** [ossec/ossec-hids#1379]
Hi, running into a bit of an issue....O/S is AIX 7.1 using GCC:

[root@host:/]# oslevel -s
7100-04-05-1720

[root@host:/]# gcc --version
gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is the compiler from AIX Toolbox online, the RPM install.

Build goes well )nothing special, running install.sh with preloaded-vars.conf

and get stuck at:

*************************************************
*************************************************
...
    CC monitord/compress_log.o
    CC monitord/generate_reports.o
    CC monitord/main.o
    CC monitord/monitor_agents.o
    CC monitord/monitord.o
    CC monitord/manage_files.o
    CC monitord/sign_log.o
    CC ossec-monitord
    CC reportd/report.o
    CC ossec-reportd
    CC os_auth/main-server.o
    CC os_auth/ssl.o
    CC os_auth/check_cert.o
In file included from os_auth/check_cert.c:33:0:
os_auth/check_cert.h:40:16: error: redefinition of 'struct label_t'
 typedef struct label_t {
                ^~~~~~~
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include-fixed/sys/types.h:510:0,
                 from /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include-fixed/stdio.h:501,
                 from os_auth/check_cert.c:27:
/usr/include/sys/m_types.h:48:16: note: originally defined here
 typedef struct label_t
                ^~~~~~~
make: *** [Makefile:1007: os_auth/check_cert.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
*************************************************
*************************************************

Can swear I've seen this before but - don't recall, and didn't want to mess with the source code. Thought it best to file a bug report instead.

Anything I can provide to help please let me know.

Thanks,
Mark

**Comment by holly1954** [comment]
I have the same issue

any comments to help resolve?

**Comment by ddpbsd** [comment]
I'm guessing that `label_t` would have to be renamed.

**Comment by mascarasnake66** [comment]
Hi, very sorry for the late reply, I have had little time to revisit.

As ddpbsd pointed out, manually renaming "label_t" to "label" in src/os_auth/check_cert.h worked. Looks like:

**typedef struct label {
    char text[DNS_MAX_LABEL_LEN + 1];
    size_t len;
}
label;**

I have not looked at #1392 yet, I shall when I have time. It may be just be the same edit provided earlier.

Thanks for the help.

**Comment by mascarasnake66** [comment]
OK looks like the resolution is in #1392 - thanks to all.
