### ISSUE TITLE
syscheck/rootcheck scanning 

### ISSUE THREAD

**Issue by jrossi** [ossec/ossec-hids#138]
It's my understanding that <ignore> on the agent does not send the hashes,
and <ignore> on the manager ignores the hashes sent. In both cases the
files/directories are still scanned (which I consider a bug).

@ddpbsd @mstarks01 @reyjrar raised in #47

**Comment by gjocher** [comment]
@jrossi 
please take a look at: https://github.com/ossec/ossec-hids/compare/2.9rc4.5...gjocher:ignore_paths
and let me know if there is something missing (i will check the WIN32 parts the next days).

**Comment by ddpbsd** [comment]
I'm not sure when it changed, but ignored files shouldn't be scanned anymore. 
https://github.com/ossec/ossec-hids/blob/master/src/syscheckd/create_db.c#L31
