### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by candlerb** [ossec/ossec-hids#1391]
At https://ossec.github.io/docs/manual/ossec-architecture.html there is a broken link to http://ossec.net/ossec-docs/auscert-2007-dcid.pdf

The hostname `ossec.net` does not resolve.  `www.ossec.net` *does* resolve, but it gives a 404 error for that document.

**Comment by ddpbsd** [comment]
Fixed in https://github.com/ossec/ossec-docs/pull/245
