### ISSUE TITLE
"Administrators group" rights needed

### ISSUE THREAD

**Issue by zekicker** [ossec/ossec-hids#1404]
Hello,

The installation process adds Administrators group rights on some ossec files and folders (client.keys, ossec.conf, ossec.log, ...).
But, when the OS language is not US, this group doesn't exists but set as permission on those files and folders. Thus, it isn't possible to start ossec service or start the GUI properly despite the local admin rights.
It's possible to play with inheritance but it's difficult to industrialize on an information system.

It's an old issue at least since 2015.

**Comment by nbuuck** [comment]
I don't see a PR or commit that tagged the previous issue, https://github.com/ossec/ossec-hids/issues/626

**Comment by nbuuck** [comment]
https://github.com/ossec/ossec-hids/issues/846

**Comment by ddpbsd** [comment]
Check pull request #1137

**Comment by zekicker** [comment]
It could be great to see this commit in the next release (2.9.4 ?)

Txs.

**Comment by zekicker** [comment]
By the way, in the command `system("echo y|icacls . /T **/G**  \"*S-1-5-32-544:F\" ")`;, the /G flag doesn't exist anymore unlike the old cacls command.
see #1137

**Comment by ddpbsd** [comment]
I removed the `/G` in pull request #1410

**Comment by igroykt** [comment]
on russian lang i was able to fix it on auto-ossec like this:
os.system('icacls "' + path + '" /reset /Q /C /T > null')
after that service start fine.
