### ISSUE TITLE
Port 1514 doesnot opened

### ISSUE THREAD

**Issue by girish624** [ossec/ossec-hids#1405]
I have downloaded tar ball version 2.9.3 from following site https://github.com/ossec/ossec-hids/releases . I wanted to install a ossec manager.

1) untar ed the pakage
2) executed ./install.sh and selected server option

I am not able to see port number 1514 opened.
even after I execute the command below I could not see port opened
/var/ossec/bin/ossec-control start
 I have used "netstat -tulpn | grep 1514"  to see the port opened.

I tried with OS centos 6 & 7. I tried with ossec 2.8.3 also. but helpless

**Comment by girish624** [comment]
I have executed manage_agents command and added the clients. I can see now port 1514 opened. and remoted service is running.
In fact, i was following https://ossec.github.io/docs/manual/installation/install-source.html . in step third says manager listens to 1514, just after step 2. which give rise confusion. it make more appropriate if the manage_agents is added to install.sh it self. Would you please let me know  step by step configuration for manager, agent integration before you close this ticket.

**Comment by ddpbsd** [comment]
I'll add a note to the documentation that an agent may have to be added before remoted will run.
I'm not sure what "step by step configuration" you're looking for. More details would be necessary for me to help.
