### ISSUE TITLE
Alienvault with HIDS

### ISSUE THREAD

**Issue by ApertureSecurity** [ossec/ossec-hids#1407]
Good day, I am trying to go through an I am not sure where to start, but let me try to explain.

I have Ossec HIDS agent deployed to a host and the host is reporting to an AlienVault node that we have.

I am trying to implement the HIDS checks in Ossec to check for credit card information and the problem seems to me that I cannot edit the rules on the Alienvault server.

How should something like this be deployed? All the documentation that I see say that I should edit rules, but I cannot edit rules like this on the AlienVault machine. . Should I have the Ossec server and agent in one?

**Comment by ddpbsd** [comment]
The last time I looked at an AlienVault server, there was a way to adjust the rules. Unfortunately I can't remember exactly where that was.
