### ISSUE TITLE
Is it possible to make the manage-agent write the client.keys to a specific file that i choose  ?

### ISSUE THREAD

**Issue by Assassinkin** [ossec/ossec-hids#1414]

**Comment by ddpbsd** [comment]
There are currently no options for this. What problem would this solve for you? I've looked into meddling with the client.keys file in the past, but haven't figured out a good way to do it yet.

**Comment by Assassinkin** [comment]
@ddpbsd  I m trying to build ossec agent for nixos system.
after the build, all binary are in some read-only store /nix/store/hashfunction-of-the-package-ossec-agent-2.7/(bin|var|etc|...). when adding the key, the current behavior is to put it under the relative path in ...../var/client.keys which we can't do as it is read only as i said as it is under /nix/store .
So i m looking into a way to patch the source files to make it possible to put that in another place.
I hope that's clear enough. 
if you want to learn more on nix ( https://nixos.org/nix/)

**Comment by ddpbsd** [comment]
It looks like the location of that file is in `src/headers/def.h`
Changing it may cause issues though, I think both `agentd` and `remoted` chroot to `/var/ossec` (or where ever you define).

**Comment by Assassinkin** [comment]
@ddpbsd  Thanks , I ll check that. Is it possible to create a feature request to add the possibility for an option in the binary to chose the destination key files.
something like "manage-keys -f /dest/file".

**Comment by ddpbsd** [comment]
It should be possible to add an option for that (I think some of the daemons already have an option for that). But the file will have to live inside of the chroot.

**Comment by Assassinkin** [comment]
@ddpbsd  Is it possible to make it somewhere outside of the chroot. as i said before the chroot will be readonly for my case and i want to put the key somewhere under /run.

**Comment by ddpbsd** [comment]
If the file is going to be outside of the chroot, everything that needs to read it must read it before chrooting and cannot update the read copy. `ossec-remoted` would have to be restarted after every agent is added for that agent to be valid.
For `ossec-agentd` I think you'd have to move `OS_ReadKeys` to before the chroot. That should be easier, but I'm not a huge fan of parsing files as root.

**Comment by Assassinkin** [comment]
@ddpbsd  In my case i m focusing on the agent side for now. I ll check if i would be able to do it the way you mentioned. Thanks for all the help, Ill close the issue for now :)
