### ISSUE TITLE
Local_rules.xml suppression of windows alerts

### ISSUE THREAD

**Issue by TriciaE66** [ossec/ossec-hids#1420]
hi

Would like to  reduce alerts for windows files using the local_rules.xml. Can anyone comment on the suggested code below in particular the multiple use of the <match> lines and the  | separator.

                        <rule id="100060" level="2">
                                <if_sid>594</if_sid>
                         <match>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\ |  xxxxxx</match>
    <match>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\mfeavfk</match>
    <match>xxxx</match>
    <description>Reduce to alert level 2 for windows events</description>

**Comment by ddpbsd** [comment]
I haven't tried it with registry stuff specifically, but watch your spacing. I would try something like this:

```
<match>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\service1|</match>
<match>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\service2|</match>
<match>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\service16</match>
```

**Comment by TriciaE66** [comment]
thanks Dan, the spacing went adrift when copying.

This does relate to an issue raised previously on https://github.com/ossec/ossec-hids/issues/1389 which didn't get any feedback on.

Tried to ignore these in the config files but can't get it to work so tried to come up with a workaround hence now trying to use the local rules file.

**Comment by TriciaE66** [comment]
It worked.
