### ISSUE TITLE
Check Owner option doesn't works in windows agent

### ISSUE THREAD

**Issue by FreddMadison** [ossec/ossec-hids#1425]
1. Deploy HIDS agent on Windows

2. Add real-time monitoring for C:\Test directory in agent ossec.conf
<directories check_all="yes" check_owner="yes" check_group="yes" check_perm="yes">C:\Test</directories>
</syscheck>

3. Create 1.txt file in C:\Test folder

4. /etc/init.d/ossec restart

5. Check that C:\Test directory is being monitored in real time by ossec agent and wait until real-time file monitoring starts by writing something into 1.txt and checking tail of ossec.log

6. Change the file owner of the 1.txt thru File Properties dialog and check ossec.log

Actual Behavior: No log events appears in ossec.log
Expected Behavior: ossec.log should contain data about owner change detection and event should be sent to server

**Comment by FreddMadison** [comment]
msdn stat() function: "st_uid - Numeric identifier of user who owns file (UNIX-specific). This field will always be zero on Windows systems."

**Comment by ddpbsd** [comment]
Maybe something from [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa446629%28v=vs.85%29.aspx) can be adapted.
In particular `GetSecurityInfo` and `LookupAccountSid`

**Comment by FreddMadison** [comment]
Yes, that's exactly what should be and will be done
