### ISSUE TITLE
Monitoring and alerting of changes to the OSSEC config files

### ISSUE THREAD

**Issue by TriciaE66** [ossec/ossec-hids#1426]
Has anyone introduced monitoring to the actual configuration files?

1) ossec.conf
2) agent.conf
3) local_rules.xml

If so, any issues doing it?

Would be good to have an alert to show that these have changed..... or is there another option......

**Comment by ddpbsd** [comment]
I usually add `/var/ossec/etc` and maybe `/var/ossec/active-response` to the syscheck config.

**Comment by TriciaE66** [comment]
Great thanks Dan

Kind Regards
Tricia Sewell

External Service Design

Assigned by
Service Management UK & Nordic
E.ON IT UK
Newstead Court
[cid:image001.png@01D051DF.8E524EA0]

www.eon.com/ebs<http://www.eon.com/ebs>

Managing Director: Ignacio Santiago Blanco.  E.ON IT UK Limited. Registered Office: Westwood Way, Westwood Business Park, Coventry, CV4 8LG. Registered in England & Wales Registered No. 5617434

Consider the environment. Please don't print this e-Mail unless you really need to.
