### ISSUE TITLE
only collect yum log in /var/log/messages?

### ISSUE THREAD

**Issue by cjw0202** [ossec/ossec-hids#1431]
my /var/log/messages is like :
`May 30 14:36:19 localhost dhclient[904]: DHCPREQUEST on ens33 to 192.168.139.254 port 67 (xid=0x434ce7a0)
May 30 14:36:19 localhost dhclient[904]: DHCPACK from 192.168.139.254 (xid=0x434ce7a0)
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   address 192.168.139.131
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   plen 24 (255.255.255.0)
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   gateway 192.168.139.2
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   lease time 1800
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   nameserver '192.168.139.2'
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33):   domain name 'localdomain'
May 30 14:36:19 localhost NetworkManager[779]: <info>  [1527662179.3017] dhcp4 (ens33): state changed bound -> bound
May 30 14:36:19 localhost dbus[720]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
May 30 14:36:19 localhost dbus-daemon: dbus[720]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
May 30 14:36:19 localhost dhclient[904]: bound to 192.168.139.131 -- renewal in 739 seconds.
May 30 14:36:19 localhost systemd: Starting Network Manager Script Dispatcher Service...
May 30 14:36:19 localhost dbus[720]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
May 30 14:36:19 localhost dbus-daemon: dbus[720]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
May 30 14:36:19 localhost systemd: Started Network Manager Script Dispatcher Service.
May 30 14:36:19 localhost nm-dispatcher: req:1 'dhcp4-change' [ens33]: new request (3 scripts)
May 30 14:36:19 localhost nm-dispatcher: req:1 'dhcp4-change' [ens33]: start running ordered scripts...
May 30 14:39:19 localhost nm-dispatcher: req:1 'dhcp4-change' [ens33]: start running ordered scripts...
May 30 14:41:41 localhost yum[6662]: Installed: 14:libpcap-1.5.3-11.el7.x86_64
May 30 14:41:42 localhost yum[6662]: Installed: 14:tcpdump-4.9.2-3.el7.x86_64
`
my alert.log is ：
`2018 May 30 13:47:25 (test) 192.168.139.131->/var/log/secure
Rule: 5710 (level 5) -> 'Attempt to login using a non-existent user'
Src IP: 192.168.139.1
May 30 13:47:24 localhost sshd[5764]: Failed password for invalid user sdf from 192.168.139.1 port 54139 ssh2

** Alert 1527659249.10913: - syslog,sshd,invalid_login,authentication_failed,
2018 May 30 13:47:29 (test) 192.168.139.131->/var/log/secure
Rule: 5710 (level 5) -> 'Attempt to login using a non-existent user'
Src IP: 192.168.139.1
May 30 13:47:28 localhost sshd[5764]: Failed password for invalid user sdf from 192.168.139.1 port 54139 ssh2

** Alert 1527662258.11254: mail  - ossec,
2018 May 30 14:37:38 es-1->ossec-monitord
Rule: 502 (level 3) -> 'Ossec server started.'
ossec: Ossec started.

** Alert 1527662503.11408: mail  - syslog,yum,config_changed,
2018 May 30 14:41:43 (test) 192.168.139.131->/var/log/messages
Rule: 2932 (level 7) -> 'New Yum package installed.'
May 30 14:41:41 localhost yum[6662]: Installed: 14:libpcap-1.5.3-11.el7.x86_64

** Alert 1527662503.11666: mail  - syslog,yum,config_changed,
2018 May 30 14:41:43 (test) 192.168.139.131->/var/log/messages
Rule: 2932 (level 7) -> 'New Yum package installed.'
May 30 14:41:42 localhost yum[6662]: Installed: 14:tcpdump-4.9.2-3.el7.x86_64

** Alert 1527662503.11923: mail  - syslog,adduser
2018 May 30 14:41:43 (test) 192.168.139.131->/var/log/secure
Rule: 5901 (level 8) -> 'New group added to the system'
May 30 14:41:42 localhost groupadd[6670]: new group: name=tcpdump, GID=72

** Alert 1527662503.12165: mail  - syslog,adduser
2018 May 30 14:41:43 (test) 192.168.139.131->/var/log/secure
Rule: 5902 (level 8) -> 'New user added to the system'
May 30 14:41:42 localhost useradd[6674]: new user: name=tcpdump, UID=72, GID=72, home=/, shell=/sbin/nologin`

only had some yum log,there is no other logs in /var/log/messages 

how to configured it ?

**Comment by cjw0202** [comment]
i know it's syslog_rules.xml
but i want collect all logs in /var/log/messages,how ?

**Comment by ddpbsd** [comment]
Based on the snippet you provided, it looks like you don't have any rules for some of those messages.
If you just want to keep all of the log messages, turn on the `<logall>` option on the manager. If you want alerts for everything, start writing rules.
If you write rules, it'd be great if you submitted a pull request for them. We're always interested in new rules.

```
**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost dhclient[904]: DHCPREQUEST on ens33 to 192.168.139.254 port 67 (xid=0x434ce7a0)'
       hostname: 'localhost'
       program_name: 'dhclient'
       log: 'DHCPREQUEST on ens33 to 192.168.139.254 port 67 (xid=0x434ce7a0)'

**Phase 2: Completed decoding.
       No decoder matched.


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost dhclient[904]: DHCPACK from 192.168.139.254 (xid=0x434ce7a0)'
       hostname: 'localhost'
       program_name: 'dhclient'
       log: 'DHCPACK from 192.168.139.254 (xid=0x434ce7a0)'

**Phase 2: Completed decoding.
       No decoder matched.


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost NetworkManager[779]: <info> [1527662179.3017] dhcp4 (ens33): address 192.168.139.131'
       hostname: 'localhost'
       program_name: 'NetworkManager'
       log: '<info> [1527662179.3017] dhcp4 (ens33): address 192.168.139.131'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2940'
       Level: '0'
       Description: 'NetworkManager grouping.'


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost NetworkManager[779]: <info> [1527662179.3017] dhcp4 (ens33): plen 24 (255.255.255.0)'
       hostname: 'localhost'
       program_name: 'NetworkManager'
       log: '<info> [1527662179.3017] dhcp4 (ens33): plen 24 (255.255.255.0)'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2940'
       Level: '0'
       Description: 'NetworkManager grouping.'


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost NetworkManager[779]: <info> [1527662179.3017] dhcp4 (ens33): gateway 192.168.139.2'
       hostname: 'localhost'
       program_name: 'NetworkManager'
       log: '<info> [1527662179.3017] dhcp4 (ens33): gateway 192.168.139.2'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2940'
       Level: '0'
       Description: 'NetworkManager grouping.'


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost NetworkManager[779]: <info> [1527662179.3017] dhcp4 (ens33): lease time 1800'
       hostname: 'localhost'
       program_name: 'NetworkManager'
       log: '<info> [1527662179.3017] dhcp4 (ens33): lease time 1800'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2940'
       Level: '0'
       Description: 'NetworkManager grouping.'


**Phase 1: Completed pre-decoding.
       full event: 'May 30 14:36:19 localhost NetworkManager[779]: <info> [1527662179.3017] dhcp4 (ens33): nameserver '192.168.139.2''
       hostname: 'localhost'
       program_name: 'NetworkManager'
       log: '<info> [1527662179.3017] dhcp4 (ens33): nameserver '192.168.139.2''

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2940'
       Level: '0'
       Description: 'NetworkManager grouping.'
```

**Comment by cjw0202** [comment]
@ddpbsd i just want to collect all logs,how to configure th` <logall>` ?

**Comment by ddpbsd** [comment]
http://www.ossec.net/docs/syntax/head_ossec_config.global.html?highlight=logall#element-logall

In the `global` section of the manager's `ossec.conf` add:
```
<logall>yes</logall>
```

This will log all messages to `/var/ossec/logs/archives/archives.log` with a metadata header attached.
