### ISSUE TITLE
"regex offet" typo in syslog_rules.xml

### ISSUE THREAD

**Issue by iasdeoupxe** [ossec/ossec-hids#1433]
https://github.com/ossec/ossec-hids/pull/1037 had introduced a "offet" typo in the following change:

https://github.com/ossec/ossec-hids/pull/1037/files#diff-4f96a5dc94f2a9f8cb1809a2510b3950R582

See also https://github.com/wazuh/wazuh-ruleset/issues/134

**Comment by ddpbsd** [comment]
Thanks for catching that!

**Comment by iasdeoupxe** [comment]
@ddpbsd No problem. But is the ``<regex offset="after_parent">`` in the rule correct at all? This is the only time i have seen this in rules so far and it is only showing up in decoders from what i can see.

**Comment by iasdeoupxe** [comment]
Could be possible that OSSEC is different to Wazuh as i only have running the latter but even after the offset typo fix the rule didn't caught the log.

Suggestion for the fix from Wazuh side is in https://github.com/wazuh/wazuh-ruleset/pull/146, can't submit one for OSSEC as i don't have it installed.

**Comment by ddpbsd** [comment]
Ok, I figured it out. Caffeine is wonderful stuff. Pull request #1443 should fix this.

**Comment by iasdeoupxe** [comment]
#1443 was merged. As i can't test this currently i just will close the issue here. Thanks
