### ISSUE TITLE
local_ip not working on OpenBSD

### ISSUE THREAD

**Issue by barajus** [ossec/ossec-hids#1455]
Hi guys. 
I am trying to use the feature "local_ip", but ossec-agent refuses to bind.
I tried with the real address from different interfaces, even from localhost, but same behavior.

OpenBSD 6.2
OSSEC : 2.9.3

I am available for further tests if needed :)

> bsdbox:~# /var/ossec/bin/ossec-agentd -f -dddd
> 2018/07/11 21:09:26 ossec-agentd: DEBUG: Starting ...
> 2018/07/11 21:09:26 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
> 2018/07/11 21:09:26 ossec-agentd(1410): INFO: Reading authentication keys file.
> 2018/07/11 21:09:26 ossec-agentd: OS_StartCounter: keysize: 1
> 2018/07/11 21:09:26 ossec-agentd: INFO: Assigning counter for agent sandbox-bsd: '10:3341'.
> 2018/07/11 21:09:26 ossec-agentd: INFO: Assigning sender counter: 2:3427
> 2018/07/11 21:09:26 ossec-agentd: DEBUG: Stored counter.
> 2018/07/11 21:09:26 ossec-agentd: INFO: Started (pid: 43192).
> 2018/07/11 21:09:26 ossec-agentd: INFO: Server 1: 10.0.0.1
> 2018/07/11 21:09:26 ossec-agentd: INFO: Trying to connect to server 10.0.0.1, port 1514.
> 2018/07/11 21:09:26 Unable to bind to local address 10.0.0.2.  Ignoring...

**Comment by ddpbsd** [comment]
Which version of OSSEC are you using? I get the following from master:
```
2018/07/12 13:48:05 ossec-agentd: INFO: Trying to connect to server ix.example.com, port 1514.
2018/07/12 13:48:05 Connecting from local address 192.168.17.12
2018/07/12 13:48:05 INFO: Connected to ix.example.com at address 192.168.17.9, port 1514
```

This system only has 1 IP though.

**Comment by barajus** [comment]
I was trying with 2.9.3, but you are right, with master it's working :)
