### ISSUE TITLE
Cisco Syslog

### ISSUE THREAD

**Issue by panhala** [ossec/ossec-hids#1456]
Hi team,

Could you guide me how to configure OSSEC to get syslog from Cisco devices?

in ossec.conf, i added: 

![image](https://user-images.githubusercontent.com/11862935/42669687-0c31bde0-8681-11e8-8000-403a92c2307c.png)

but it look like, ossec didn't get any log from cisco devices...
and idea?

**Comment by panhala** [comment]
now I see log in /var/ossec/logs/archives/archives.log but at the gui i didn't see anything....
![image](https://user-images.githubusercontent.com/11862935/42676580-f11fffb8-86a2-11e8-86b6-649b56219fea.png)

**Comment by ddpbsd** [comment]
Hopefully I got this right, it's difficult to copy & paste from a screenshot.
```
[root@rossak ddp]# cat /tmp/yyy | /var/ossec/bin/ossec-logtest
2018/07/13 06:57:59 ossec-testrule: INFO: Reading local decoder file.
2018/07/13 06:57:59 ossec-testrule: INFO: Started (pid: 29460).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: '%SW_MATM-4-MACFLAP_NOTIF: Host 00e0.fc09.bcf9 in vlan 890 is flapping between port Gil/0/32 and port Gil/0/33'
       hostname: 'rossak'
       program_name: '(null)'
       log: '%SW_MATM-4-MACFLAP_NOTIF: Host 00e0.fc09.bcf9 in vlan 890 is flapping between port Gil/0/32 and port Gil/0/33'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%SW_MATM-4-MACFLAP_NOTIF'

**Phase 3: Completed filtering (rules).
       Rule id: '4714'
       Level: '4'
       Description: 'Cisco IOS warning message.'
**Alert to be generated.
```

Is your gui (which one are you using?) configured to show level 4 alerts?

**Comment by panhala** [comment]
Last time my GUI is level 6, Do you have any idea on my problem?

**Comment by ddpbsd** [comment]
What gui are you using? If it's only configured to display level 6+ alerts, you won't see the level 4 alert.

**Comment by panhala** [comment]
I use ossec appliance

**Comment by ddpbsd** [comment]
I've never actually used the appliance. SSH into the system and check the `/var/ossec/logs/alerts/alerts.log` file. Make sure the alerts show up there.

**Comment by panhala** [comment]
I configure the alert level is 1 but the alert didn't show in the /var/ossec/logs/alerts/alerts.log and OSSEC-WUI. it shows only at the: /var/ossec/logs/archives/archives.log
![image](https://user-images.githubusercontent.com/11862935/42936213-b25450ae-8b75-11e8-9c85-d04b79a21518.png)

**Comment by ddpbsd** [comment]
@panhala Do the same test I did with `/var/ossec/bin/ossec-logtest`. If an alert is not showing up in `alerts.log`, we need to try and figure out why.

**Comment by panhala** [comment]
Here is what I did with /var/ossec/bin/ossec-logtest

![image](https://user-images.githubusercontent.com/11862935/43031959-7c26c112-8cd6-11e8-8c0b-c71eb45f7f77.png)

**Comment by ddpbsd** [comment]
You included the archive header. Look at how I did it, I removed the header. It won't parse correctly if you leave it there.

**Comment by panhala** [comment]
@ddpbsd, what i should to do now?

**Comment by ddpbsd** [comment]
I don't know. I've never used the appliance. I'm not even sure which gui the thing uses. I'd start by trying to see if an alert is generated. 
```
echo ' %SW_MATM-4-MACFLAP_NOTIF: Host 00e0.fc09.bcf9 in vlan 890 is flapping between port Gil/0/32 and port Gil/0/33' | /var/ossec/bin/ossec_logtest
```
When we know what's going on, we can try to work through it.

**Comment by panhala** [comment]
do you have any update?

**Comment by ddpbsd** [comment]
Did you run the command?
