### ISSUE TITLE
hostname does not match logfile names

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#146]
Sometime in the last 6 years &lt;hostname&gt; stopped matching the logfile path/name in a rule.

Based on a discussion on linkedin (http://www.linkedin.com/groupAnswers?viewQuestionAndAnswers=&discussionID=5849093138076966912&gid=25424&commentID=5851700194080485376&trk=view_disc&fromEmail=&ut=3EjAmuD3e4PC81).

**Comment by ddpbsd** [comment]
There's been no interest in too long, and no simple checks to see if this is still valid. If it's still an issue for anyone re-open and update, or open a new issue.

**Comment by stromnet** [comment]
So, without digging further back in the past, how *do* we have a rule compare against the logcollector's log-file location (lf->location, if I read the code correct)?

**Comment by stromnet** [comment]
There is the &lt;same_location&gt; timeframerule, but there is no plain &lt;location&gt; as we have &lt;hostname&gt;

**Comment by stromnet** [comment]
The docs at http://ossec.github.io/docs/syntax/head_rules.html says:

> 
hostname
Any hostname (decoded as the syslog hostname) or log file.

So I guess that *should* work? Last time I tested, it did not. I'll double-verify this.

**Comment by stromnet** [comment]
ossec v2.8.2 on FreeBSD 10.2 (latest version in ports).

logcollector config:
```
  <localfile>
    <log_format>syslog</log_format>
    <location>/tmp/logfile0.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/tmp/logfile1.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/tmp/logfile2.log</location>
  </localfile>
``` 


Test case 1:
```
<group name="stromnet,syslog,">
....

        <rule id="109100" level="12">
                <match>TESTWARN</match>
                <description>TESTWARN in any source</description>
        </rule>
        <rule id="109101" level="12">
                <match>TESTWARN</match>
                <hostname>logfile1.log</hostname>
                <description>TESTWARN in logfile1.log</description>
        </rule>
        <rule id="109102" level="0">
                <match>TESTWARN</match>
                <hostname>logfile2.log</hostname>
                <description>Supressed TESTWARN in logfile2.log</description>
        </rule>
</group>
```


Creating entries
```
echo "I am TESTWARN" > /tmp/logfile0.log
echo "I am TESTWARN" > /tmp/logfile1.log
echo "I am TESTWARN" > /tmp/logfile2.log
```
Results
```
** Alert 1459592146.602775: mail  - stromnet,syslog,
2016 Apr 02 12:15:46 back-1->/tmp/logfile0.log
Rule: 109100 (level 12) -> 'TESTWARN in any source'
I am TESTWARN
** Alert 1459592157.602942: mail  - stromnet,syslog,
2016 Apr 02 12:15:57 back-1->/tmp/logfile1.log
Rule: 109100 (level 12) -> 'TESTWARN in any source'
I am TESTWARN
** Alert 1459592165.603109: mail  - stromnet,syslog,
2016 Apr 02 12:16:05 back-1->/tmp/logfile2.log
Rule: 109100 (level 12) -> 'TESTWARN in any source'
I am TESTWARN
```

Expected: for logfile1, 109101 should match. logfile2 should be surpressed (level=0).
Note: not sure if that is actually what I *should* expect, might need if_sid for that?

Testcase 2:
Remove rule 109100, otherwise same.

```
echo "I am TESTWARN 2" > /tmp/logfile0.log
echo "I am TESTWARN 2" > /tmp/logfile1.log
echo "I am TESTWARN 2" > /tmp/logfile2.log
```

Results: No alerts at all. 
Expected: 
Based on the docs in my previous comment, "logfile1.log" should be matched in the <hostname> rule.
Thus, rule 109101 should alert for logfile1.log


Bug or not, it does not behave as described in docs of today.

**Comment by stromnet** [comment]
Tested with `<hostname>/tmp/logfile1.log</hostname>` too, i.e full exact filename as in logcollector config, without any luck

**Comment by dcid** [comment]
Only works if the alert is coming from an agent, not on the local install.

**Comment by stromnet** [comment]
Verified, when writing to these logfiles on a remote machine, it works as documented and expected.

I'd say that is a bug, reopen?
