### ISSUE TITLE
authpass is set to default value by mistake

### ISSUE THREAD

**Issue by phamvuong** [ossec/ossec-hids#1465]
authpass variable is originally set as NULL
If user does not specify option "-P" then insecure mode is used.
 
However the authpass is set to some default value by mistake which forces user to always use password. Following is the error when a client is trying to authenticate to server (server uses certificate and key for agent management instead of password)
`
/var/ossec/bin/agent-auth -m <server> -A <agent>
2018/07/19 09:16:29 ossec-authd: INFO: Started (pid: 13429).
2018/07/19 09:16:29 INFO: Connected to <server> at address <server>, port 1515
INFO: Connected to <server>:1515
INFO: Using agent name as: <agent>
INFO: Send request to manager. Waiting for reply.
ERROR: Unable to create key. Either wrong password or connection not accepted by the manager.
INFO: Connection closed.
`
ossec server and agent are installed on CentOS 7.4
I have created a PR to fix this issue overhere
https://github.com/ossec/ossec-hids/pull/1464

**Comment by ddpbsd** [comment]
Merged, thanks!
