### ISSUE TITLE
'local_internal_options.conf' is overwritten during upgrades

### ISSUE THREAD

**Issue by hibari0614** [ossec/ossec-hids#1466]
I was running OSSEC on **Ubuntu 16.04 LTS**, and upgraded it with APT package manager.

As the OSSEC was upgraded to 3.0.0, I found the `/var/ossec/etc/local_internal_options.conf` is overwritten, and the configurations created by user are all loss. It is not sure that the same issue is also occurred on old version.

The user document indicates the `local_internal_options.conf` will not be overwritten during upgrades.
[http://www.ossec.net/docs/syntax/internal_options.html](url)

Could someone please look over it, It seem a bug.

**Comment by atomicturtle** [comment]
Added in build: 12034

Thanks again for the report (note: this also tagged local_rules.xml as %config)
