### ISSUE TITLE
ossec-hids-server 3.0 missing for amd64 stretch

### ISSUE THREAD

**Issue by zeroecco** [ossec/ossec-hids#1473]
hello! ossec-hids-server 3.0 seems to be missing for stretch 64bit (as of Wed Jul 25 10:44:29 PDT 2018) per: https://updates.atomicorp.com/channels/ossec/debian/pool/main/o/ossec-hids-server/

Is there an issue with 64bit atm that would prevent me from upgrading? We are bit by:
https://github.com/ossec/ossec-hids/pull/862

 and would like to upgrade if at all possible

**Comment by zeroecco** [comment]
bump

**Comment by zeroecco** [comment]
sorry to be a pain in the butt but @atomicturtle is there any idea when there will be a 3.0 build for debian stretch?

**Comment by repl-mike-roest** [comment]
You need to use the ossec-3-testing channel there are packages there.  They were in the atomic channel but that seems to have been reverted.

**Comment by atomicturtle** [comment]
Debian 9 and Ubuntu 16 should be up now, thanks for the report!

**Comment by zeroecco** [comment]
@atomicturtle Thanks! I doubled checked, and I see debian 9 32bit, but I don't see debian 9 64 bit :(

**Comment by zeroecco** [comment]
what I am currently seeing
<img width="950" alt="screen shot 2018-08-23 at 8 32 43 am" src="https://user-images.githubusercontent.com/947613/44535555-27adf680-a6af-11e8-8f25-98dde80f25ae.png">

**Comment by zeroecco** [comment]
@atomicturtle Sorry to keep bugging but there is no x86-64 for stretch ATM just only i386

**Comment by atomicturtle** [comment]
I think we found the issue. Debian stretch is version 9, not version 8.

**Comment by zeroecco** [comment]
awesome! thanks for you work on this.
