### ISSUE TITLE
Questions about the manager checksum db

### ISSUE THREAD

**Issue by jcheroske** [ossec/ossec-hids#1474]
1) What database is used to store the checksums?

2) Is it possible to plug in a different database to store the checksums?

3) Are there any hooks available that allow arbitrary code to be run before or after a checksum is modified in the database (CRUD)?

Thanks!

**Comment by ddpbsd** [comment]
1. It's currently a flat file.
2. Yes, but it takes some work adjusting the code.
3. I'm not sure what you mean.

**Comment by jcheroske** [comment]
> Yes, but it takes some work adjusting the code.

So, it sounds like there isn't a provider api for that and I'd have to fork. Is that correct?

> I'm not sure what you mean.

I'm trying to do add some data validation to the checksums, to insure the checksum db itself was not tampered with. I'm looking for the most straightforward way to have OSSEC make calls to an external system when the checksum db is read or written to.

**Comment by ddpbsd** [comment]
There's nothing right now. 2 attempts have been made to add an sqlite backend, but I haven't particularly liked either one. The first one used 1 db per agent (like we have now), and the one I wrote used 1. I'd love to keep the file descriptor use minimal, but I don't think sqlite is fast enough to only have 1 db if there are a lot of agents.
I briefly thought about trying to abstract it a little, to make using postgresql or one of the lesser databases an option, but I haven't had time. There's a pull request for my sqlite work open right now, but I'm on mobile and too lazy to look it up.
Any help would be great.

There aren't any hooks in analysisd for anything like that. I have ideas, but want to pull some of the wazuh changes in before messing with it.

**Comment by jcheroske** [comment]
Given your understanding of the database, is it possible for an intruder to tamper with it, such that it would not be detected? If an intruder had an altered version of a system file, and had the checksum of that altered file, could an intruder change the database so that ossec wouldn't alert on the changed file?

**Comment by ddpbsd** [comment]
There are a number of issues at play. If someone gets root on your system, all bets are off. If you're in an agent/server setup, they would need access to the ossec server, but in a local install the db is obviously local.

The hashes we currently use are md5 and sha1, which are pretty bad. There is active work to support sha256 and blake2b, which I expect to be merged soon. This will help against malicious hash collisions. Using multiple hashes helps a little, but newer algorithms are definitely necessary.

I assume that if an intruder has root, the filename, and hashes

**Comment by ddpbsd** [comment]
Oops, sorry. Didn't mean to close this.

I assume that if an intruder has root, the filename, hashes, file size, owner, and group they could insert an entry to the db to silence any alerts. Realtime detection on win32 and linux might help with this, but the timing would be a bit spicy.

**Comment by jcheroske** [comment]
I've been wondering if there's an application for blockchain tech in all this. Saving checksums, even if it's just a checksum for an entire machine, to a blockchain might add a degree of security. Assuming the blockchain is authoritative, then ossec could potentially compare what it has to the blockchain. Does that seem like it could eliminate certain avenues of attack?

**Comment by ddpbsd** [comment]
I don't have a high opinion of blockchains. The only use I've seen them be successful at is tricking VCs out of money.

**Comment by jcheroske** [comment]
Normally I'd agree with you, but this blockchain is not just a VC speculation. It actually has the potential to add real value, and doesn't possess the volatility found in other cryptocurrency-centric chains. Anyway, being able to store an immutable fingerprint of a server or entire cloud and then have OSSEC reference it seems like it could add another layer of security and trust. But, at the moment, it seems like OSSEC's database layer is not designed to be pluggable. Perhaps a standalone process that also reads the OSSEC database would be another approach?

**Comment by atomicturtle** [comment]
Well we did start implementing sqlite as a storage engine there. Im not sure if that helps or not!

**Comment by jcheroske** [comment]
Thanks for helpful dialog! I'm going to close this now.
