### ISSUE TITLE
GeoIP in 3.0.0

### ISSUE THREAD

**Issue by zvanderbilt** [ossec/ossec-hids#1475]
I have not been able to get GeoIP working in the 3.x version. I have only tested the latest release of 3.0.0 and only on amazon linux 1 and 2. I have tried using both the source and binary packages. 

I had been using GeoIP support in the 2.x versions for the past year or two quite successfully. 
On the 2.x version I just edited the  ./src/Makefile to set USE_GEOIP to yes. Doing the same on 3.x doesnt return any errors about the geoip_db_path option being present as it does when compiling with USE_GEOIP=no.

I tried to alter the geoip_db_path to a few different locations both in /var/ossec and out of it and I didn't encounter any error messages regardless of what the geoip_db_path option is set to. 

Lastly I also removed all the ifdefs to try to force LIBGEOIP_ENABLED to be true everywhere and that didn't work either. 

Don't really know what else to do to debug. I enabled debug for everything and I am just not seeing anything related to geoip coming through.

**Comment by variablenix** [comment]
Likewise, I'm running into the same problem with the 3.x version. I have never attempted to use GeoIP until this release. The interesting thing is that the OSSEC logs don't show any errors related to GeoIP or any log info with GeoIP. My config is identical to yours, except now I have placed the GeoIP dat files directly in the OSSEC directory.

```
    <geoip_db_path>/var/ossec/etc/GeoLiteCity.dat</geoip_db_path>
    <geoip6_db_path>/var/ossec/etc/GeoLiteCityv6.dat</geoip6_db_path>
```
I'm not sure if this will even really make a difference with the GeoIP feature though. Originally I had specified the path to point to the original location `/usr/share/GeoIP`. 

Inside of `local_internal_options.conf` I have also included the following to no avail:

```
analysisd.geoip_jsonout=1
# Maild display GeoIP data (0=disabled, 1=enabled)
maild.geoip=1
```

Last - my compile options did include `USE_GEOIP=yes`, so like you I have no idea how else to debug this problem.

**Comment by zvanderbilt** [comment]
Has anyone else had issues with GeoIP in 3.0.0? Would love to hear of someone who has it working to maybe see what they are doing different.

**Comment by ddpbsd** [comment]
I haven't played with it. Has anyone tried setting the db path relative to the chroot?
Instead of `/var/ossec/whatever/GeoLiteDB.dat` using `/whatever/GeoLiteDB.dat`

**Comment by zvanderbilt** [comment]
That is how my existing configuration is setup so that carried over to 3.0.0 when I initially tested it.

**Comment by zvanderbilt** [comment]
Ah. Looks like I just need to talk to you about it @ddpbsd.

I just recompiled with `USE_GEOIP=1` (instead of yes).

the option geoip_db_path is not read and throws no errors with `USE_GEOIP=1` but does with `USE_GEOIP=yes`.

I then replaced the `geoip_db_path` option with `geoipdb` and that option was read however it was not looking in the chroot directory so I got a `ossec-analysisd: ERROR: Unable to open GeoIP database from: /etc/GeoLiteCity.dat (disabling GeoIP)` which was a new error for me. I set the full path to /var/ossec/etc/GeoLiteCity.dat,. restarted and now I have GeoIP working on 3.0.0.

**Comment by ddpbsd** [comment]
I often make an adequate [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging).
I'm not a make expert, but I think `[1yY]` and `yes` should all mean the same thing ([link](https://github.com/ossec/ossec-hids/blob/master/src/Makefile#L216)). I haven't checked though.
Grepping through the source shows that `geoipdb` is used, but `geoip_db_path` is not.
I haven't gone through the histories of the files to see what changed, or if the path option never worked. It might be interesting to find out, but I'm not desperate for that info.
At a minimum I need to update the documentation to change the field name. Thanks for digging into all that @zvanderbilt !
