### ISSUE TITLE
Hardcoded ossec user and group in 3.0.0

### ISSUE THREAD

**Issue by mobstef** [ossec/ossec-hids#1476]
I am the OSSEC FreeBSD port maintainer.
In 3.0.0 two new bugs appeared:
- hardcoded "ossec" group in "src/init/adduser.sh"
- hardcoded "ossec" user in "src/Makefile"
See attached patches.

[patch-src_init_adduser.sh.txt](https://github.com/ossec/ossec-hids/files/2238186/patch-src_init_adduser.sh.txt)
[patch-src_Makefile.txt](https://github.com/ossec/ossec-hids/files/2238187/patch-src_Makefile.txt)

**Comment by ddpbsd** [comment]
Thanks for all of these bug reports. I think they've all been merged.
