### ISSUE TITLE
server returned error NXDOMAIN

### ISSUE THREAD

**Issue by openbayou** [ossec/ossec-hids#1479]
Hello,
I'm using OSSEC v3.0 on Ubuntu Server 18.04.1 and I keep getting these alerts.

systemd-resolved[3225]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP. 

systemd-resolved[3225]: message repeated 4 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.] 

Sometimes these messages keep sending until I shut down the server.

I have my hostname setup correctly because when I run systemd-resolve, it correctly shows the hostname, IPv4 and IPv6 address with no errors. It's going through Cloudflare protected, if that helps.

**Comment by ddpbsd** [comment]
You could probably write a rule to ignore this log message. I'm not sure how important it is.
Something like this added to `/var/ossec/rules/local_rules.xml`:
```
  <rule id="234567" level="0">
    <program_name>systemd-resolved</program_name>
    <match>Server returned error NXDOMAIN</match>
    <description>Usless systemd-resolvd log message</description>
  </rule>
```

**Comment by tabakisp** [comment]
How can you propose to someone to ignore an error message when you are not sure how important that error is?

**Comment by ddpbsd** [comment]
@tabakisp yeah, I probably shouldn’t have. But my spare time to research other peoples’ alerts for free is limited. They can however use the rule I have them to create a rule that fits their network and policies better.

**Comment by Rajpratik71** [comment]
Anyone who using old 18.04 release , will face this . In background it is creating issue to kube-proxy , which internally use iptables and depend upon underlying networking of OS. 

fix which worked for me 

`unlink /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf && systemctl restart systemd-resolved`
