### ISSUE TITLE
Add small syscheck delay for more accurate alerts

### ISSUE THREAD

**Issue by mstarks01** [ossec/ossec-hids#148]
When editing files using vim (and in other circumstances) and with realtime enabled, often there are two alerts: one that the file size changed to 0, then another that it is back at a non-zero size. I imagine inserting a small delay between the time inotify sees the change and the time OSSEC checks it would help.

**Comment by ddpbsd** [comment]
While @jrossi is probably right, this is what we have now.
https://github.com/ossec/ossec-hids/blob/master/src/syscheckd/run_realtime.c#L202
