### ISSUE TITLE
ossec syslog_output not working

### ISSUE THREAD

**Issue by daniejstriata** [ossec/ossec-hids#1485]
I have been using the OSSEC agent and servers from the Atomicorp repo with no issues. Lately the packages updated to version 3. Can I log issues for the Atomicorp version here?

I now no longer receive any CEF formatted log events sent by OSSEC server to my syslog recipient when I do a new install of OSSEC server. I uninstalled the latest version from the repo and installed 2.9.4 from source. Then using the following config works without problem. 

configuration:
edit  /var/ossec/etc/ossec.conf
add:
```
<syslog_output>
    <server>graylog.example.org</server>
    <port>12000</port>
    <format>cef</format>
</syslog_output>
```
enable the OSSEC syslog subsystem:
`/var/ossec/bin/ossec-control enable client-syslog`
Restart OSSEC and see if messages arrive.
`/var/ossec/bin/ossec-control restart`

I looked if ossec-csyslogd started in the logs and never saw it start for version 3. Only when I use 2.9.4:
I used tcpdump and can confirm that no packets where created when I was using version 3 server to my syslog confirming that ossec-csyslogd did not start

**Comment by ddpbsd** [comment]
Atomicorp reports are fine here.
If you start `ossec-csyslogd` manually, does it work?

**Comment by daniejstriata** [comment]
I'm not sure how I can start it manually. I can only start and stop the services as done by the `ossec-control` service. Can you give me the command please?

**Comment by ddpbsd** [comment]
Yeah, sorry:
`/var/ossec/bin/ossec-csyslogd -df`

The `-df` will start it in the foreground with debugging enabled.

**Comment by daniejstriata** [comment]
I think I'm on to something. I am also wondering if only IP addresses are allowed for `syslog_output server` because when I use a host-name it is not connecting. (This is not related to my original issue. I've got more info on that following below.)

```
# /var/ossec/bin/ossec-csyslogd -df
2018/08/03 11:01:59 ossec-csyslogd: DEBUG: Starting ...
2018/08/03 11:01:59 ossec-csyslogd: INFO: Chrooted to directory: /var/ossec
2018/08/03 11:01:59 ossec-csyslogd: INFO: Using user: ossecm
2018/08/03 11:01:59 ossec-csyslogd: INFO: Started (pid: 2665).
2018/08/03 11:01:59 ossec-csyslogd: INFO: File queue connected.
2018/08/03 11:01:59 getaddrinfo: System error
2018/08/03 11:01:59 ossec-csyslogd(1216): ERROR: Unable to connect to 'hostname'.
```
Could it be that my issue is specific to Centos/RHEL 6? I'm not having the exact experience on Centos 6 and 7.
On Centos 6 it runs manually:
```
# /var/ossec/bin/ossec-csyslogd -df
2018/08/03 11:28:20 ossec-csyslogd: DEBUG: Starting ...
2018/08/03 11:28:20 ossec-csyslogd: INFO: Chrooted to directory: /var/ossec
2018/08/03 11:28:20 ossec-csyslogd: INFO: Using user: ossecm
2018/08/03 11:28:20 ossec-csyslogd: INFO: Started (pid: 1591).
2018/08/03 11:28:20 ossec-csyslogd: INFO: File queue connected.
2018/08/03 11:28:20 INFO: Connected to yyyyy at address xxxx, port 5555
2018/08/03 11:28:20 ossec-csyslogd: INFO: Forwarding alerts via syslog to: 'xxxxxx:5555'.
```
But looking at the running services I get and have a missing ossec-csyslogd:
# ./ossec-control status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted not running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...

On my Centos 7 box I get:
# /var/ossec/bin/ossec-control status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted: Process 2765 not used by ossec, removing ..
ossec-remoted not running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
**ossec-csyslogd is running...**

**Comment by ddpbsd** [comment]
It could require an IP, I haven't tried. You'll probably need to copy `/etc/resolv.conf` to `/var/ossec/etc` if hostnames are ok though.
Make sure `ossec-csyslogd` has been enabled by looking at `/var/ossec/bin/.process_list`:
```
[root@rossak src]# more /var/ossec/bin/.process_list
CSYSLOG_DAEMON=ossec-csyslogd
```

**Comment by daniejstriata** [comment]
I found that .process_list was missing on my RHEL/Centos 6 servers. IS this file supposed to be created during the installation? After creating the file and restarting the ossec-hids service it started to run:

First getting service status with the missing .process_list file
```
[root@Centos6 ~]# service ossec-hids status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted not running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
```
```
[root@Centos6 ~]# !ps
ps faux | grep csyslog
root       628  0.0  0.3 103380  2060 pts/2    S+   08:28   0:00          \_ grep csyslog

```
Moving in the missing .process_list file to the bin directory.
`[root@Centos6 bin]# mv ~/.process_list .`
```
Now the service shows but is not running:
```
[root@Centos6 bin]# service ossec-hids status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted not running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
ossec-csyslogd not running...
```
Restart ossec-hids and the ossec-csyslogd service is now started
```
[root@Centos6 bin]# service ossec-hids restart
Shutting down ossec-hids:                                  [  OK  ]
Starting ossec-hids:                                       [  OK  ]
```

```
[root@Centos6 bin]# service ossec-hids status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted: Process 825 not used by ossec, removing ..
ossec-remoted not running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
ossec-csyslogd is running...

```

```
[root@Centos6 bin]# ps faux | grep csyslog
root       895  0.0  0.3 103380  2056 pts/2    S+   08:29   0:00          \_ grep csyslog
ossecm     807  0.0  0.4  44204  2160 ?        S    08:28   0:00 /var/ossec/bin/ossec-csyslogd
```

**Comment by ddpbsd** [comment]
It's supposed to be created when you run `/var/ossec/bin/ossec-control enable client-syslog`

**Comment by daniejstriata** [comment]
I deleted the file .process_list and ran the command ` /var/ossec/bin/ossec-control enable client-syslog` and it worked as expected. Not sure why all my Centos 6 installs failed initially. Closing this as it is not reproducible.

**Comment by semen-gordeev** [comment]
Hello everyone, 
I have the same issue and already tried all suggestions above. And it still won't work.
```
root:~# uname -a
Linux ip-10-1-2-37 4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root:~# 
root:~# /var/ossec/bin/ossec-control status
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild is running...
ossec-execd is running...
ossec-csyslogd: Process 16243 not used by ossec, removing ..
ossec-csyslogd not running...
root:~# 
root:~# 
root:~# /var/ossec/bin/ossec-csyslogd -df
2018/11/30 14:41:35 ossec-csyslogd: DEBUG: Starting ...
2018/11/30 14:41:35 ossec-csyslogd: INFO: Chrooted to directory: /var/ossec
2018/11/30 14:41:35 ossec-csyslogd: INFO: Using user: ossecm
2018/11/30 14:41:35 ossec-csyslogd: INFO: Started (pid: 15837).
2018/11/30 14:41:35 ossec-csyslogd: INFO: File queue connected.
2018/11/30 14:41:35 getaddrinfo: System error
Segmentation fault (core dumped)
root:~# 
root:~# 
root:~# cat /var/ossec/etc/resolv.conf 
nameserver 127.0.0.53
search us-east-2.compute.internal
root:~# 
```

config:
```
  <syslog_output>
    <server>example.com</server>
    <port>12345</port>
    <format>cef</format>
  </syslog_output>
```

Any ideas?

**Comment by daniejstriata** [comment]
Are you on Centos 6 as well? If not it might be best to create a new issue.

**Comment by semen-gordeev** [comment]
@daniejstriata ubuntu 18.04

**Comment by daniejstriata** [comment]
This ticket was resolved on an older version and a different OS. I recommend to log a new issue and supply logs as required. AS you can see from:
`ossec-csyslogd: Process 16243 not used by ossec, removing ..`
That the module is not enabled. Did you run 
`/var/ossec/bin/ossec-control enable client-syslog`
to enable the output?
