### ISSUE TITLE
ERROR: Definition not found for: 'analysisd.geoip_jsonout'

### ISSUE THREAD

**Issue by theuberuser** [ossec/ossec-hids#1488]
Since July 17, 2018, I have not been receiving emails from OSSEC and discovered the RPM was updated via YUM on that same day and my system has been unable to start ossec-control ever since. When I run `/var/ossec/bin/ossec-control start` the following error gets written to /var/ossec/logs/ossec.log:

```
ossec-testrule(2301): ERROR: Definition not found for: 'analysisd.geoip_jsonout'.
```

I have not touched my OSSEC configuration in months, so I believe this is a bug of some sort. Below is the output for `rpm -qi ossec-hids`:

```
Name        : ossec-hids
Epoch       : 1
Version     : 3.0.0
Release     : 5505.el7.art
Architecture: x86_64
Install Date: Fri 20 Jul 2018 09:28:22 AM UTC
Group       : Applications/System
Size        : 432583
License     : AGPL
Signature   : RSA/SHA256, Tue 17 Jul 2018 09:29:02 PM UTC, Key ID ffbd5d0a4520afa9
Source RPM  : ossec-hids-3.0.0-5505.el7.art.src.rpm
Build Date  : Tue 17 Jul 2018 09:28:54 PM UTC
Build Host  : 5f815512019a4d52811a065ec9ef13d4
Relocations : (not relocatable)
Packager    : Atomicorp <support@atomicorp.com>
Vendor      : http://www.ossec.net
URL         : http://www.ossec.net/
Summary     : An Open Source Host-based Intrusion Detection System
Description :
OSSEC is a scalable, multi-platform, open source Host-based Intrusion Detection
System (HIDS). It has a powerful correlation and analysis engine, integrating
log analysis, file integrity checking, Windows registry monitoring, centralized
policy enforcement, rootkit detection, real-time alerting and active response.
It runs on most operating systems, including Linux, OpenBSD, FreeBSD, MacOS,
Solaris and Windows.
```

**Comment by ddpbsd** [comment]
It definitely seems like a bug. Not sure if it's a packaging thing (not updating `/var/ossec/etc/internal_options.conf`) or an install script thing (also not updating the file).

I think you need to set this in the above mentioned file:
```
# Output GeoIP data at JSON alerts
analysisd.geoip_jsonout=0
```
I'll also look at putting default values for these things in the code, so there aren't errors if it isn't defined.

**Comment by theuberuser** [comment]
@ddpbsd I tried your suggestion but that did not seem to help

**Comment by ddpbsd** [comment]
I'm not sure what else it could be. That error message only appears in 1 place.

**Comment by theuberuser** [comment]
I found cause for ossec-control not starting. doing an ls of /var/ossec/etc revealed another internal_options.conf file.

```
[root@localhost etc]# ls -l internal_options.conf*
-rw------- 1 root ossec 2903 Aug 25 16:28 internal_options.conf
-rw-r--r-- 1 root root  3156 Jul 17 21:28 internal_options.conf.rpmnew
```
The main configuration is only has permissions for the root user to read whereas the original is readable by everyone. Also, the I noticed the modification timestamp for internal_options.conf.rpmnew matches the date that the ossec RPM was updated. 

Doing a diff on internal_options.conf and internal_options.conf.rpmnew reveals these differences:

```
[root@localhost etc]# diff internal_options.conf internal_options.conf.rpmnew
17c17
< analysisd.stats_maxdiff=25000
---
> analysisd.stats_maxdiff=999000
19c19
< analysisd.stats_mindiff=250
---
> analysisd.stats_mindiff=1250
21c21
< analysisd.stats_percent_diff=30
---
> analysisd.stats_percent_diff=150
29a30,31
> # Output GeoIP data at JSON alerts
> analysisd.geoip_jsonout=0
66c68
< # Monitord day_wait. Ammount of seconds to wait before compressing/signing
---
> # Monitord day_wait. Amount of seconds to wait before compressing/signing
78a81,83
> # Monitord notify_time. Frequency of which the clients' availability needs
> # to be checked. (60-3600)
> monitord.notify_time=600
86a92,95
> # Rootcheck checking/usage speed. Rootcheck will pause for this
> # duration after scanning a PID or port.
> rootcheck.sleep=2
>
113a123
>

So, I simply renamed internal_options.conf.rpmnew to  internal_options.conf.

```
[root@localhost etc]# cp internal_options.conf.rpmnew internal_options.conf

[root@localhost etc]# ls -l internal_options.conf*
-rw-r--r-- 1 root root 3156 Aug 25 16:32 internal_options.conf
-rw------- 1 root root 2841 Aug 25 16:31 internal_options.conf.bkp
-rw-r--r-- 1 root root 3156 Jul 17 21:28 internal_options.conf.rpmnew
```

Which then allowed me to start the service

```
[root@localhost etc]# /var/ossec/bin/ossec-control start
Starting OSSEC HIDS 3.0.0 (by Trend Micro Inc.)...
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-remoted...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.
```

So, this seems to be a bug that was introduced in the update on July 17th.

**Comment by variablenix** [comment]
This may also have some relation to what appears to be a bug with GeoIP in OSSEC 3.0.0: https://github.com/ossec/ossec-hids/issues/1475
