### ISSUE TITLE
Ossec email alert

### ISSUE THREAD

**Issue by Dzoniii** [ossec/ossec-hids#1500]
Hello everyone, i am having trouble with Ossec email alert. I use Ubuntu Server 18.04 on Virtualbox, and email alerts works fine when i use NAT Network( with 127.0.1.1 as smtp server ), but when i change it to Virtual Box Host-Only adapter my email alerts doesnt work. Does anyone has an idea what the problem is ??

**Comment by ddpbsd** [comment]
Are there any logs from your smtp server?

**Comment by Dzoniii** [comment]
Thanks for response i found a solution :) But right know i have another problem with adding an agent in ossec server. When i enter the manage_agents i do not have an option "Extract key from server", i have only standard option like for server (i have installed agent version of ossec) . I have read log files and says
2018/08/15 10:30:24 INFO: Conected to 10.0.2.5 at address 10.0.2.5 , port 1514
2018/08/15 10:30:45 ossec-agentd(4101) : WARN :  Waiting for server reply(not started). Tried 10.0.2.5
2018/08/15 10:32:35 ossec-agentd : INFO: Trying to connect to server 10.0.2.15 port 1514 
Any idea ??

**Comment by ddpbsd** [comment]
When you have a new issue, open a new issue. And I think we were emailing on the list about this?
