### ISSUE TITLE
ossec-agentlessd: INFO: Test passed for 'ssh_integrity_check' takes a looong time after ossec-control restart

### ISSUE THREAD

**Issue by dummypunter** [ossec/ossec-hids#1522]
My configuration is like the sample bellow. After ossec-control restart, it checks every instance of ssh_integrity_check and slowly the time needed to complete the check of the ssh_integrity_check script increases. I have many servers and now after 1 and half day, it takes ~9 minutes to check the ssh_integrity_check script. At this rate it will take >2 days to start actually ssh-ing the servers and checking the file integrity.

I cannot install agent to the servers due to warranty restrictions.

Any help on speeding up the process will be greatly appreciated!!!

```
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.xx</host>
  <state>periodic</state>
  <arguments>/lib64/ /var/lib/ /lib/</arguments>
</agentless>
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.xx</host>
  <state>periodic</state>
  <arguments>/opt/ /bin/</arguments>
</agentless>
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.xx</host>
  <state>periodic</state>
  <arguments>/sbin/ /usr/</arguments>
</agentless>

<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.yy</host>
  <state>periodic</state>
  <arguments>/lib64/ /var/lib/ /lib/</arguments>
</agentless>
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.yy</host>
  <state>periodic</state>
  <arguments>/opt/ /bin/</arguments>
</agentless>
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.yy</host>
  <state>periodic</state>
  <arguments>/sbin/ /usr/</arguments>
</agentless>
```

**Comment by ddpbsd** [comment]
Try running one of the scripts manually to see where it's slow.

**Comment by dummypunter** [comment]
Manually the scripts run just fine. The problem is the syntax(?) checking of the scripts on ossec start.

**Comment by dummypunter** [comment]
modifying the conf from:

<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.xx</host>
  <state>periodic</state>
  <arguments>/opt/ /bin/</arguments>
</agentless>
<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.yy</host>
  <state>periodic</state>
  <arguments>/sbin/ /usr/</arguments>
</agentless> 

to:

<agentless>
  <type>ssh_integrity_check</type>
  <frequency>y>86400</frequency>
  <host>ossec@xx.xx.xx.xx</host>
  <host>ossec@xx.xx.xx.yy</host>
  <state>periodic</state>
  <arguments>/opt/ /bin/</arguments>
</agentless>

solved the issue.
