### ISSUE TITLE
Rootcheck docker OverlayFS directories problem

### ISSUE THREAD

**Issue by oleg9301** [ossec/ossec-hids#1528]
Hello!

i have next problem in my vm with docker

```
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Files hidden inside directory '/var/lib/docker/overlay2/b95813d65af05851af3a114be77d2f4ba123c5d44ed1cbea978118c1f60f79c0/merged/dev'. Link count does not match number of files (4,1).
```

And i found next topic: https://github.com/wazuh/wazuh/issues/561

**Comment by kurczakos** [comment]
Hello!
The problem still persists in Version 3.5.0 when docker makes use of Linux namespaces (userns-remap).
```
Files hidden inside directory '/var/lib/docker/231072.231072/overlay2/...'. Link count does not match number of files (3,1).
```
The commit 460a2d2dd5706789774f425e88335b0ca74ffb57 don't seem to have fully resolved the issue.

**Comment by drmaciej** [comment]
I can confirm this is still happening on 3.6.0.

**Comment by atomicturtle** [comment]
Closed by PR 1952
