### ISSUE TITLE
false-positive for checking open ports using netstat

### ISSUE THREAD

**Issue by vivisidea** [ossec/ossec-hids#154]
```
int ret = system("netstat -an | grep \"^tcp\" | grep \"[^0-9]212 \" > /dev/null 2>&1");// port 212 is not open
printf("ret = %d \n", ret);// in my system(ubuntu12.04) it prints ret = 256
```

```
./src/rootcheck/check_rc_ports.c
int run_netstat(int proto, int port)
{
    ...(omit)...

    ret = system(nt);

    if(ret == 0)
        return(1);

    else if(ret == 1)
    {
        return(0);
    }

    return(1);// the ret is 256 so this function would return 1 for closed ports
}
```

http://man7.org/linux/man-pages/man3/system.3.html

The value returned is -1 on error (e.g., fork(2) failed), and the
return status of the command otherwise.  This latter return status is
in the format specified in wait(2).  Thus, the exit code of the
command will be WEXITSTATUS(status).  In case /bin/sh could not be
executed, the exit status will be that of a command that does
exit(127).

so I suggest add `ret = WEXITSTATUS(ret)` to extract the real exit code of the netstat command chain.

**Comment by anooppe** [comment]
Hello Vivisidea,

I am facing high CPU spikes as well, do you know if we have an option to disable the netstat checks via ossec.conf on v2.9.2?

Thanks,
Anoop
