### ISSUE TITLE
Memory leaks again on OSSEC 3.0

### ISSUE THREAD

**Issue by TheoPoc** [ossec/ossec-hids#1542]
Hi all,

I upgrade my OSSEC server from 2.9.4 to 3.0 to fix the memory leaks for ossec-analysisd process like it tell on the changelog. But the upgrade change nothing. Maybe i forget something ?

**Comment by ddpbsd** [comment]
We fixed some, but I have no doubts there are more. Also depending on configuration, OSSEC can use a decent amount of memory during normal operations (open ended rules tend to be a pain). 
Please help us find more of the leaks.
Closing this ticket since #1502 is similar enough.
