### ISSUE TITLE
Provide Debian packaging

### ISSUE THREAD

**Issue by mcallaway** [ossec/ossec-hids#156]
It would be great if ossec sources were ready for Debian packaging "out of the box". I'd be happy to help in this regard. Basically install.sh and src/Install*.sh need to be modified to work with fakeroot and debhelper, and a new directory ./debian added with build instructions.

I've started some work on this in a fork:

https://github.com/genome-vendor/ossec-hids

But any work I do will be shortly undone if the scripts ever change. It would be nice to not have to worry about that going forward.

Is there any interest in this feature?  I think the only thing I really need is a way to determine which files go in which package (common, client, server) after compilation. Right now these file locations are in ./src/Install*.sh, but you can't run those scripts without attempts to chown/chmod/useradd as well.

**Comment by anperez** [comment]
Could you guys integrate or provide the debian control files and patches so the sources can be re-packaged easily? The current repository doesn't provide the debian sources.

Thanks in advance!

**Comment by santiago-bassett** [comment]
Yes, it is in my todo. Will submit the pull request today :-)
