### ISSUE TITLE
Ubuntu 18.04 - Unable to use smtp server address

### ISSUE THREAD

**Issue by SchupsCH** [ossec/ossec-hids#1563]
Before upgrading from Ubuntu 16.04 to 18.04, we were able to configure our ossec installations (local agents) with smtp_server = smtp.domain.com

Since we started installing ossec to Ubuntus 18.04, we are not able to use the same configuration. Ossec logs show the following error:
`getaddrinfo: Temporary failure in name resolution`

I found it being generated at line 379 of os_net/os_net.c 

As a workaround we are forced to specify the smtp server address as ip (ipv4). We need to avoid doing this. Nor we want to have a postfix installed on each server because of ossec.

I found little information regarding this online. Any idea / any lead?

Thank you

**Comment by variablenix** [comment]
I vaguely remember running into an SMTP problem similar to what you describe. The fix ended up being to create a file named `hosts` in `/var/ossec/etc` containing something like:

```
<smtp IP address> mail.example.tld	  mail
```
I haven't recently tested removing the `hosts` file to see if problematic SMTP behavior occurs with current OSSEC releases, but in any case it doesn't hurt to have the `hosts` file in the OSSEC `etc` directory.

Also, it looks like there is still an open `maild` issue https://github.com/ossec/ossec-hids/issues/1122 for an earlier version which talks about having the `hosts` file present in the OSSEC directory.

**Comment by ddpbsd** [comment]
`ossec-maild` chroots to the install directory (`/var/ossec` by default). If there's nothing in `/var/ossec/etc` to help it do dns lookups, it won't be able to do dns lookups. Providing `hosts` or `resolv.conf` might help.

**Comment by SchupsCH** [comment]
Thank you indeed for your answers. I actually solved it days ago, with the following:

```sh
cp /run/systemd/resolve/stub-resolv.conf /var/ossec/etc/resolv.conf
service ossec restart
```

A symbolic link did not work, and an hard one was not possible in my case.
