### ISSUE TITLE
manage_agents on server thinks it is a agent and only shows agent options

### ISSUE THREAD

**Issue by NiGame** [ossec/ossec-hids#1566]
./manage_agents -r 1024
manage_agents: Key removal only available on a master.

I have over 100 agents connected to this server and can see they are all connected via the other commands. I also have it streaming all the events to a elastic search server and everything is working as expected.

Just this one command won't show server options, this is a fresh install of 3.1.0

**Comment by NiGame** [comment]
/var/ossec/etc/ossec-init.conf
/etc/ossec-init.conf
both say server, where does it pull it's information about what it is from?

**Comment by ddpbsd** [comment]
It's a compile time thing. For some reason your manage_agents got passed `-DCLIENT` or something like that instead of the server variant.
