### ISSUE TITLE
OSSEC agent's status

### ISSUE THREAD

**Issue by NicotianNicotian** [ossec/ossec-hids#1569]
After stopping OSSEC agent on the client machine there is about 30 minutes interval before it's status becomes "Disconnected" on the OSSEC server (via **manage_agents -l**). Is there any way to reduce this interval? I didn't find any parameters in config files.

**Comment by ddpbsd** [comment]
There's a source file somewhere with it. I can't remember if it's in `monitord` or `remoted` off hand though.

**Comment by ddpbsd** [comment]
You could try `<time-reconnect>` in the `<client>` section of the agent's ossec.conf. I'm not positive that's what the option is for, but I think it is. Still have to look into the code to find out.
