### ISSUE TITLE
OSSEC HIDS v3.1.0 email alert does't show full alert messages

### ISSUE THREAD

**Issue by junqian1992** [ossec/ossec-hids#1571]
Email alert doesn't show the changes, but the alert.log is work.
Email alert

> OSSEC HIDS Notification.
> 2018 Nov 12 16:01:49
> Received From: (nagios-server185) xxxxxxx->syscheck
> Rule: 550 fired (level 7) -> "Integrity checksum changed."
> Portion of the log(s):
> Integrity checksum changed for: '/home/hehe.txt'
> 
>  --END OF NOTIFICATION

alerts.log

> ** Alert 1542009709.59473: mail  - ossec,syscheck,
> 2018 Nov 12 16:01:49 (nagios-server185) xxxxxxx->syscheck
> Rule: 550 (level 7) -> 'Integrity checksum changed.'
> Integrity checksum changed for: '/home/hehe.txt'
> **Permissions changed from 'rwxr--r--' to 'rwxr-xr-x'**

I found only some of the alert no show full message on email alert.
Example permission changed "chmod and chown".
The diff changed is working perfectly without problem on email alert.

**Comment by Jamalc0m** [comment]
am not getting the alerts all, only when I restart I get start ossec alert.
for file integrity change nothing comes!

**Comment by ddpbsd** [comment]
Give pull request #1593 a try. Seems to fix it for me.

**Comment by ddpbsd** [comment]
PR #1593 has been merged. Re-open this ticket if it's still an issue.
