### ISSUE TITLE
How to check a log file that contains Shellshock attacks?

### ISSUE THREAD

**Issue by hamadodene** [ossec/ossec-hids#1575]
my configuration in ossec is :

  <localfile>

    <log_format>syslog</log_format>

    <location>/var/log/wazuh_log/web.log</location>

  </localfile>

in the file web.log there is the row:
92.168.2.100 - - [02/Nov/2015:01:35:55 +0100] "GET /cgi-bin/test.sh HTTP/1.1" 200 292 "-" "() { gry; };/usr/bin/perl

but no alerts are generated, though
doing a logtest of the rowI get out which is a Shellshock attacks.

what's the problem?

**Comment by hamadodene** [comment]
I'm using wazuh, the alert does not appear in alert.log.

**Comment by ddpbsd** [comment]
Please contact Wazuh for help with their product.

**Comment by iasdeoupxe** [comment]
Seems this hasn't ended up in the wazuh repo (but maybe in a mailinglist?). Nevertheless for the records:

@hamadodene 
```
<log_format>syslog</log_format>
```

should be:

```
<log_format>apache</log_format>
```

and the shellshock attack should be detected.
