### ISSUE TITLE
OSSEC  v3.1.0 not sending email

### ISSUE THREAD

**Issue by domugtong** [ossec/ossec-hids#1576]
Hello,

I just noticed. Why is my OSSEC not sending any emails? i've configured it properly

```
    <email_notification>yes</email_notification>
    <email_to>******@*****.com</email_to>
    <smtp_server>********.mail.protection.outlook.com</smtp_server>
    <email_from>OSSEC-OFFCE@*********.com</email_from>
    <email_maxperhour>9999</email_maxperhour>

```

i am checking the logs through /var/ossec/logs/ossec.log but i dont see any logs about emails being sent. Is there anything that im missing?

**Comment by domugtong** [comment]
i have verified that my SMTP server is working properly because i also use that as SMTP server on my other applications

**Comment by ddpbsd** [comment]
Try running maild in debug mode. 
Make sure there is a copy of resolv.conf in `/var/ossec/etc`

**Comment by domugtong** [comment]
@ddpbsd  how do i run the maild in debug mode?
after running maild -d nothing  happens.

**Comment by ddpbsd** [comment]
Dis you kill the other maild first? The `-d` flag is indeed what you’d need

**Comment by domugtong** [comment]
@ddpbsd that resolv.conf fixed the issue. thank you so much!
