### ISSUE TITLE
OSSEC WUI  Unable to retrieve alerts. 

### ISSUE THREAD

**Issue by domugtong** [ossec/ossec-hids#1577]
Hello @ddpbsd 

I am having this error on OSSEC WUI

![image](https://user-images.githubusercontent.com/45157731/48687182-e9b36680-ebfa-11e8-81e1-da58c33c7e60.png)

Ive tried to set my /var/ossec/tmp to 777 but still the same. is there anything im missing? 
My apologies. im new to this OSSEC thing

**Comment by ddpbsd** [comment]
Dis you add your webserver user to the ossec group and restart the webserver processes?

**Comment by domugtong** [comment]
yes. my web server user is apache. i found this [link](https://github.com/ossec/ossec-wui/issues/11) do you think it could be the answer?

**Comment by ddpbsd** [comment]
No idea. The wui project has been abandoned for years, and I haven’t used it in forever. 
You should check your apache logs for errors.

**Comment by domugtong** [comment]
ive tried to set chmod 777 -R * on bot /var/ossec/ and /var/www/html/ossec-wui
here is the results when i execute 

```
[root@rhel-home ossec-wui]# grep ossec /etc/group
ossec:x:995:apache
```

is the group correct?

**Comment by ddpbsd** [comment]
Ok, assuming apche runs as the `apache` user it should be ok. Make sure apache got restarted so the group takes effect.
You can also look at `/var/log/audit/audit.log` for any failures.

**Comment by sdellenb** [comment]
As @ddpbsd mentioned, it could be an SELinux issue (check `/var/log/audit/audit.log`).

I have this SELinux module (`ossec-wui.te`) to allow the webserver running ossec-wui to access the log files:
```
module ossec-wui 1.1;

require {
        type var_log_t;
        type httpd_t;
        type var_t;
        class file { read getattr open };
}

#============= httpd_t ==============
allow httpd_t var_log_t:file { read open };
allow httpd_t var_t:file { read getattr open };
```

The error message re-appears after every logrotate and is resolved with
```
restorecon -Rv /var/ossec/logs
```

I'm not sure why it messes up the SELinux labels all the time.
This is the fcontext for the log files on my system:
```
# semanage fcontext -l | grep ossec
/var/ossec/logs(/.*)?                              all files          system_u:object_r:var_log_t:s0
```

**Comment by aquerubin** [comment]
https://github.com/ossec/ossec-docs/issues/146

Tony
