### ISSUE TITLE
Decoder identifying apache logs as pure-transfer

### ISSUE THREAD

**Issue by XenoPhage** [ossec/ossec-hids#158]
Title says it all.  Here are some log entries to test with : 

23.244.230.217 - - [23/Mar/2014:03:19:53 -0400] "GET /blog/archives/309-towards-building-more-secure-networks.html HTTP/1.1" 200 10881 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"
107.22.134.166 - - [23/Mar/2014:03:20:40 -0400] "GET /robots.txt HTTP/1.1" 404 228 "-" "Mozilla/5.0 (compatible; linkdexbot/2.0; +http://www.linkdex.com/about/bots/)"
107.22.134.166 - - [23/Mar/2014:03:20:40 -0400] "GET /blog/index.php?/plugin/tag/computer HTTP/1.1" 200 10671 "-" "Mozilla/5.0 (compatible; linkdexbot/2.0; +http://www.linkdex.com/about/bots/)"
188.143.232.31 - - [23/Mar/2014:03:20:59 -0400] "GET /blog/index.php?/archives/26-Windows-XP-ISO-Mount-Utility.html HTTP/1.1" 200 47268 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"

**Comment by jseel001** [comment]
ddpbsd - How is this working for you? I have a fresh instance of OSSEC 2.8.1 and apache is being decoded as pure-transfer when the time offset is a "-".

**Comment by ddpbsd** [comment]
@jseel001 Try using a fresh checkout of the code, not the older tarballs. I think this commit fixed it: https://github.com/ossec/ossec-hids/commit/26e56b398fd235e00bf24be8b4ad246cdbdf4c58

**Comment by jseel001** [comment]
@ddpbsd That did it. Thank you!

**Comment by awiddersheim** [comment]
Fixed by #324.
