### ISSUE TITLE
ossec-hids/etc/ossec-agent.conf contains double hyphen in comment

### ISSUE THREAD

**Issue by mwmahlberg** [ossec/ossec-hids#1582]
This is illegal as per https://www.w3.org/TR/REC-xml/#sec-comments

> [...]the string " -- " (double-hyphen) must not occur within comments.

The occurrence of a double hyphen may prevent proper processing of the file by various XML libraries, not the least of them Python's lxml module, which is used by Ansible.

**Comment by ddpbsd** [comment]
PR merged, thanks!
