### ISSUE TITLE
Download for ossec-hids-3.1.0-5711.el7.art.src.rpm is missing

### ISSUE THREAD

**Issue by MarkRWatts** [ossec/ossec-hids#1584]
I need to rebuild the ossec agent to install to /opt (as we mount /var as noexec).
Where can I find ossec-hids-3.1.0-5711.el7.art.src.rpm? https://updates.atomicorp.com/channels/source/ossec-hids/ only has 2.9 as the latest.

**Comment by atomicturtle** [comment]
Yeah we have some heavy duty custom builders behind the scenes to handle the multi-distro builds automatically so they're not really something you could build on your own unless you had our system.

I just uploaded a de-macro'd version (5787) that should build in a regular mock builder environment. If it doesnt,  you may have to do some additional tweaking.

**Comment by MarkRWatts** [comment]
Sorry I guess I'm not looking in the right place - I'm not seeing any 3.1 SRPM versions for download here: https://updates.atomicorp.com/channels/source/ossec-hids/

Should I be looking elsewhere?

**Comment by swindmill** [comment]
I am also looking for ossec-hids-3.1.0-5711.el7.art.src.rpm or newer SRPMs so we can rebuild to address requirements similar to those @MarkRWatts described

@atomicturtle thank you for your willingness to provide a de-macro'd version - how can I retrieve that?

Thanks!

**Comment by atomicturtle** [comment]
Yeah are you on slack with us? I could use the help on cleaning it up

**Comment by swindmill** [comment]
@atomicturtle I am not on Slack with you but would be happy to join and help. How do I do that?

**Comment by atomicturtle** [comment]
just send us an invite request to slack@ossec.net and we can add you from there
