### ISSUE TITLE
Error 126

### ISSUE THREAD

**Issue by prasadchitti** [ossec/ossec-hids#1591]
Hi,
There is an error while installing. Error 126 and it shows permission denied

![image](https://user-images.githubusercontent.com/10075329/49778472-6c779f00-fd2b-11e8-8340-afe18ba19af3.png)

**Comment by ddpbsd** [comment]
There's not much to go on here.
Are you running the installer as root? Does the user have permission to run /bin/sh on ./configure and write to the output files it writes to?
Is the filesystem read only or no exec or something?

**Comment by ddpbsd** [comment]
Please re-open and update if this is still an issue.
