### ISSUE TITLE
Manage agents Doubt

### ISSUE THREAD

**Issue by AndreMTrindade** [ossec/ossec-hids#1623]
Did you remove agent-auth?

Now how can i add an agent with one command line? 

Thank you! :+1:

**Comment by ddpbsd** [comment]
I don't think so. What makes you think it was removed?

**Comment by AndreMTrindade** [comment]
Does not appear on /var/ossec/bin/. Just manage-agents.

**Comment by ddpbsd** [comment]
How did you install OSSEC?

**Comment by AndreMTrindade** [comment]
All my input to ossec installation: 
  en/br: "en"
          Press ENTER: ""
          What kind of installation do you want: server
          Choose where to install the OSSEC HIDS: /var/ossec
          Do you want e-mail notification: y
          e-mail address: any_email@temp.com
          Do you want to use it: y
          SMTP server ip: n
          Do you want to run the integrity check daemon: y
          Do you want to run the rootkit detection engine: y
          Do you want to enable active response: y
          Do you want to enable the firewall-drop response: y
          Do you want to add more IPs to the white list: n
          Do you want to enable remote syslog:  n
          Press ENTER: ""
          Press ENTER: ""

Thanks for helping me :+1:

**Comment by ddpbsd** [comment]
My best guess would be openssl isn't getting picked up. Do you have the dev/devel packages installed for it?

**Comment by atomicturtle** [comment]
ah, agent-auth doesnt get installed on a server config. Only on an agent or hybrid config
