### ISSUE TITLE
Rule id not woking.

### ISSUE THREAD

**Issue by Nishanthkrish** [ossec/ossec-hids#1643]
While i click rule id i am getting this 

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by ddpbsd** [comment]
Where are you clicking `rule id`? Please provide some context, I haven't had enough coffee yet.

**Comment by Nishanthkrish** [comment]
![image](https://user-images.githubusercontent.com/46801726/51407864-10eacd80-1b83-11e9-8fc4-eb7616bb411e.png)

**Comment by ddpbsd** [comment]
We don't support ossec-wui
