### ISSUE TITLE
active-response.log will never get written by disable-account.sh?

### ISSUE THREAD

**Issue by mpalermo73** [ossec/ossec-hids#1647]
https://github.com/ossec/ossec-hids/blob/ac1d6d11217b4d65f2f61f3361bb4faa3af8b59f/active-response/disable-account.sh#L17-L21

If `$LOCAL` is the directory the script lives in, then ultimately `${PWD}` is `/var/ossec/active-response/bin`.  One directory up is `/var/ossec/active-response` thus making "`../log/`" be `/var/ossec/log` as the logging directory.  However, the existing logging directory is plural "logs" not singular "log".

Am I reading this script wrong?

```
[root@here active-response]# pwd
/var/ossec/active-response

[root@here active-response]# ls -l ../
total 12
dr-xr-x---  3 root  ossec   17 Aug  7 14:16 active-response
dr-xr-x---  2 root  ossec  286 Aug  7 14:16 agentless
dr-xr-x---  2 root  ossec 4096 Aug  7 14:17 bin
dr-xr-x---  6 root  ossec  248 Jan 16 12:57 etc
drwxr-x---  5 ossec ossec  289 Jan 14 03:13 logs <----- PLURAL
drwxr-xr-x  4 root  root    36 Aug  7 14:16 lua
dr-xr-x--- 11 root  ossec  136 Aug  7 14:16 queue
dr-xr-x---  3 root  ossec 4096 Aug  7 14:16 rules
drwxr-x---  5 ossec ossec   64 Aug  7 14:16 stats
dr-xr-x---  2 root  ossec    6 Jul 17  2018 tmp
dr-xr-x---  3 root  ossec   17 Jan 16 12:57 var
```
```
# rpm -qa | grep -i ossec
ossec-hids-3.0.0-5505.el7.art.x86_64
ossec-hids-server-3.0.0-5505.el7.art.x86_64
```
```Red Hat Enterprise Linux Server release 7.6 (Maipo)```

**Comment by ddpbsd** [comment]
Nope, that sounds right.
