### ISSUE TITLE
Help needed - How to send info to two servers at the same time

### ISSUE THREAD

**Issue by lord-kyron** [ossec/ossec-hids#1662]
Hi all, I am using ossec agent on my infrastructure, but wanted to know if I can have the agent sending info on a second server for failover?
Can I configure it in the ossec.conf or I must have a second ossec_agent installed on the same machine and configured to send to another server - if this happens will they interrupt each other?
I found, that if I write 2 IPs for server in ossec.conf, the info is sent only the the first IP and if ti cannot be reached, it goes to the second. But my goal is to send to the both IPs at the same time.

Please, provide me some info about it as I cannot find this explained anywhere, neither in the docs!
thanks!

**Comment by ddpbsd** [comment]
You'll need to modify the `ossec-agentd` code to do it. I haven't ever really looked at the code, so I'm not sure how big of a task that would be.

**Comment by Bandic007** [comment]
@ddpbsd - can two instances of the ossec agent run on the same machine and point to two different servers, or this is not possible from config side of view?

**Comment by ddpbsd** [comment]
@Bandic007 I think that could work. Just install them to different directories.

**Comment by Bandic007** [comment]
> You'll need to modify the `ossec-agentd` code to do it. I haven't ever really looked at the code, so I'm not sure how big of a task that would be.

 I will try to do it in two separate installations, but otherwise what part of the code do you think I must change and look into?

**Comment by ddpbsd** [comment]
`ossec-agentd` lives in https://github.com/ossec/ossec-hids/tree/master/src/client-agent
So there would need to be changes there. Probably in `src/config` (global?) as well.

**Comment by Bandic007** [comment]
@ddpbsd - another question - can one ossec SERVER instance receive and then send/forward the logs to another SERVER instance? Is this even possible and if yes - how to achieve it?

**Comment by atomicturtle** [comment]
Yes, that is hybrid mode during the install.sh setup
