### ISSUE TITLE
Syslog ISO timestamp events with optional fraction of second are skipped by pre-decoder

### ISSUE THREAD

**Issue by MangyCoyote** [ossec/ossec-hids#1664]
Related to   #1032 

Syslog events like:
2019-02-06T16:15:28.1+00:00 ...
2019-02-06T16:15:28.22+00:00 ...
2019-02-06T16:15:28.333+00:00 ...
etc. are not processed by [pre]decoder.

Supported formats at the moment are only:
2019-02-06T16:15:28+00:00 ... simple iso
2019-02-06T16:15:28.666666+00:00 ... due to rsyslog.

Expand fraction of a second to be optional up to reasonable time granularity (6 digits).

**Comment by ddpbsd** [comment]
Thanks for the issue and pull request!

**Comment by MangyCoyote** [comment]
You are welcome. I have to express my thank you for this tool  on the other hand 👍

**Comment by atomicturtle** [comment]
Wow this solves a bunch of issues I was having with pre-decoding some medical device logs. Thank you so much for this!

**Comment by MangyCoyote** [comment]
Extremely glad the change helped you in such critical area where medical devices are!
