### ISSUE TITLE
How to Forward syslogs from Manager to central server?

### ISSUE THREAD

**Issue by mhabicht** [ossec/ossec-hids#1676]
I have one manager with 120 nodes sending log to it. from the manager I need to forward all those to another central syslog system.

I configure the managers ossec.conf with

`<syslog_output>`
 ` <server>IP FOR Central Server</server>`
`  <port>514</port>`
`  <format>cef</format>`
`</syslog_output>`

I then

/var/ossec/bin/ossec-control stop
/var/ossec/bin/ossec-control enable client-syslog
/var/ossec/bin/ossec-control start

But the only logs being sent are the ones for the manager itself.

**Comment by ddpbsd** [comment]
Turn on the log all option on the OSSEC server (restart the processes).
Have your syslog daemon or something read `/var/ossec/logs/archives/archives.log` and forward them to your syslog server (optionally strip the OSSEC header on the log lines).

**Comment by mhabicht** [comment]
Where is "log all"?
There is nothing in my /var/ossec/logs/archives/archives.log

**Comment by ddpbsd** [comment]
Sorry, I should have included more info.
In the `/var/ossec/etc/ossec.conf` file, add `<logall>yes</logall>` to the `<global>` section.
For example:
```
<ossec_config>
  <global>
    <email_notification>yes</email_notification>
    <email_to>ddp@localhost</email_to>
    <smtp_server>mail.example.com</smtp_server>
    <email_from>ossecm@example.com</email_from>
    <logall>yes</logall>
  </global>
```

Then restart the OSSEC processes. The `<logall>` option will log all messages the server receives to `/var/ossec/logs/archives/archives.log`, with a header prepended on to it.

Documentation link (although there is not much there): 
http://www.ossec.net/docs/syntax/head_ossec_config.global.html?highlight=logall#element-logall

**Comment by mhabicht** [comment]
Still getting this error

`# /var/ossec/bin/ossec-control start`
Starting OSSEC HIDS v2.8 (by Trend Micro Inc.)...
OSSEC analysisd: Testing rules failed. Configuration error. Exiting.

**Comment by ddpbsd** [comment]
Try `/var/ossec/bin/ossec-logtest -t` or look at `/var/ossec/logs/ossec.log`

**Comment by mhabicht** [comment]
2019/02/26 13:42:04 ossec-maild(1225): INFO: SIGNAL Received. Exit Cleaning...
2019/02/26 13:42:04 ossec-execd(1314): INFO: Shutdown received. Deleting responses.
2019/02/26 13:42:04 ossec-execd(1225): INFO: SIGNAL Received. Exit Cleaning...
2019/02/26 13:42:07 ossec-config(1230): ERROR: Invalid element in the configuration: 'logall'.
2019/02/26 13:42:07 ossec-config(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
2019/02/26 13:42:07 ossec-testrule(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

**Comment by ddpbsd** [comment]
```
2019/02/26 13:42:07 ossec-config(1230): ERROR: Invalid element in the configuration: 'logall'.
```
Ok, so something is wrong with your `<logall>` option. Without seeing the config I have absolutely no idea what that would be though.

**Comment by mhabicht** [comment]
No.Sorry. 

It was another error, files are showing up in Archive.log now.

I have 
`<syslog_output>`
 ` <server>IP FOR Central Server</server>`
`  <port>514</port>`
`  <format>cef</format>`
`</syslog_output>`

So will all the logs forward now.

**Comment by ddpbsd** [comment]
You will have to configure something to forward the logs from `archives.log` to your syslog server. OSSEC does not do that for you. `syslog_output` is for the alerts only.

**Comment by mhabicht** [comment]
So the OSSEC manager will not do that? I thought that was configurable?

**Comment by ddpbsd** [comment]
I don't believe it will, but maybe I missed that option.

**Comment by mhabicht** [comment]
Thanks for all the help.
