### ISSUE TITLE
Master crashes when  "ossec-remoted(1407): ERROR: Duplicated counter for"  is present

### ISSUE THREAD

**Issue by 700grm** [ossec/ossec-hids#1680]
OSSEC Master crashes when this error is present. 
2019/03/01 14:23:39 ossec-remoted(1407): ERROR: Duplicated counter for 'XXXXXXXXXXXX'.

I am running a RH 7.5 Master VM, 8 GB of RAM, 16 agents connected, CPU usage is 10 percent, OSSEC is using around 4GB,  all settings are default and configured with utility ossec/bin/ossec-configure with exception of rule "logall" to log all events in ossec/logs/archive/ 

If this error is present in logs, master ALWAYS will crash at some point. 
Mostly is crashes after one/two days, however once it survived five.

I  have OSSEC master server on multiple sites, on the sites where the ERROR was present, but was fixed 
by  solution described here: https://ossec-docs.readthedocs.io/en/latest/faq/unexpected.html , it is stable and working without issues.

**Comment by libellux** [comment]
Stop both the OSSEC server and the agent. In the agent server go to /var/ossec/queue/rids and remove all the files within the folder. At the OSSEC server go into /var/ossec/queue/rids and remove the file corresponding to the agents ID. Do not delete the sender_counter. Restart both.

Or disable the feature by editing /var/ossec/etc/internal_options.conf
