### ISSUE TITLE
Cross compiling problems and issues to install the agent

### ISSUE THREAD

**Issue by mborba** [ossec/ossec-hids#1686]
I'm using version 3.1 of OSSEC and I'm getting some problems with the binary install. My target is a embedded Linux system that is running a custom Debian image. The target doesn't have GCC and make command, so, I need to cross compile the files on the /src folder. But for some reason, the commands to compile do not create the binaries, they just created the outputs for each C file for each folder on src directory. I saw the makefile and the install.sh script, and I found these lines:

Lines 102-105:
    if [ "X${USER_BINARYINSTALL}" = "X" ]; then
        # Add DATABASE=pgsql or DATABASE=mysql to add support for database
        # alert entry
        ${**MAKEBIN**} PREFIX=${INSTALLDIR} TARGET=${INSTYPE} build

Line 117: ${**MAKEBIN**} PREFIX=${INSTALLDIR} TARGET=${INSTYPE} install

So, the install.sh script is doing a make command, and that's the error I'm getting on installation of the agent on my target (make command not found). I can't install GCC and make command on the target.

The binaries are generated on version 2.8.3, but the cross compile seems to be more complicated. I haven't found the main file that I can write the gcc command to cross compile.

Anyway, I want to use the 3.1 version because it has more features and there's a lot of fixes. Any pointers?

**Comment by ddpbsd** [comment]
Create a script to manually install things.
