### ISSUE TITLE
Several Linux agent installs fail with: os_zlib/os_zlib.c:13:10: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by ll3N1GmAll** [ossec/ossec-hids#1690]
We have upgraded to a fresh OSSEC install version 3.2.0 and are deploying new agents (everything built from scratch, brand new server, new agent creation, etc.). We are having several linux agents failing to install with the following error:

5- Installing the system
 - Running the Makefile
cc  -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DCLIENT -Wall -Wextra -I./ -I./headers/ -c os_zlib/os_zlib.c -o os_zlib/os_zlib.o
os_zlib/os_zlib.c:13:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:694: os_zlib/os_zlib.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

Any help is greatly appreciated!

**Comment by ddpbsd** [comment]
Is the zlib development package installed on the system?
Does `zlib.h` exist?
Which distribution/version?

**Comment by ll3N1GmAll** [comment]
Thanks, this has worked to resolve the issue on the first 2 I have tried.
apt install zlib1g-dev 

One additional issue I ran into after the above fix is this error: make: execvp: ./init/adduser.sh: Permission denied

Running this resolved that:
chmod -R +x src

Hope this helps. Thanks for your response and direction!
