### ISSUE TITLE
Attempted to check FS status for C:\Windows but we don't know how on this OS

### ISSUE THREAD

**Issue by CorinaVJ** [ossec/ossec-hids#1699]
I am seeing this message in ossec.log on Windows Server 2012. Does anyone know how to fix it?

**Comment by ddpbsd** [comment]
It's a warning that can be ignored. I'll try to clean it up. 
[Source of the issue](https://github.com/ossec/ossec-hids/blob/master/src/shared/fs_op.c#L104)
