### ISSUE TITLE
Installation 3.3.0

### ISSUE THREAD

**Issue by dhenry123** [ossec/ossec-hids#1723]
Problem encountered after getting 3.3.0.tar.gz on debian 9
context : apt install build-essential zlib1g-dev libpcre2-dev
wget ... tar xfz ...
cd ossec-hids-3.3.0
./install.sh

(french language installation but language has no impact)
/bin/sh: 1: cd: can’t cd to external/pcre2-10.32/
Makefile:770 : la recette pour la cible « external/pcre2-10.32//install/lib/libpcre2-8.a » a échouée
make: *** [external/pcre2-10.32//install/lib/libpcre2-8.a] Erreur 2
Error 0x5.

Modification (1)
vi ./src/Makefile
remplace : **PCRE2_SYSTEM?=no**
with
**PCRE2_SYSTEM?=yes**

restart install.sh ---> OK

Thanks for your amazing job

**Comment by axpatito** [comment]
+1 on this issue. Please note that performing this step will also require you to install **pcre-devel** in your OS.
