### ISSUE TITLE
install ossec on HP-UX without gcc

### ISSUE THREAD

**Issue by akhalfan** [ossec/ossec-hids#1731]
Is there a way I can compile ossec agent separately using GCC and then uploading it on a production server?
I would like not to install gcc on the production server.  Can I just compile it then tar the /var/ossec folder then extract it on the HP-UX server ? 

or are there any ready binaries available for 3.3.0

**Comment by Marc-bo** [comment]
Hi,

Fro mmy own exp, you can tar the /var.ossec directory and move it to the dest server. You also need:
-create local accounts (up to 3 depending on your compile options)
-copy /etc/ossec-init.conf

Then it should work (tested on Raspi on my side).

Marc.

**Comment by ddpbsd** [comment]
We don't make packages or binaries for HP-UX. It's not an easily available platform.
You can compile it on a matching HP-UX system with a compiler.
If GNU make is isntalled on the target system you can probably do a binary installation. The instructions on the site are for the old version though, so I'm not sure of the current procedure.
Probably something along these lines.
On the build server:
```
$ cd ossec-hids-*/src
$ gmake TARGET=agent
BUILD BUILD BUILD
$ cd ../..
$ tar -cf ossec-built.tar
```

Copy `ossec-build.tar` to the target system and:

```
$ tar -xf ossec-build.tar
$ cd ossec-hids-*/src
$ sudo gmake install
```

Haven't tried it though.

**Comment by atomicturtle** [comment]
If you can get us an HP-UX system, we can take a shot at making a binary distribution for it

**Comment by akhalfan** [comment]
I can probably get one, but not sure if gmake is installed 
I know cc is  installed
