### ISSUE TITLE
error when installing ossec 3.3.0 on Eyes of network last version 

### ISSUE THREAD

**Issue by duplex007** [ossec/ossec-hids#1732]
5- Installation du système
 - Exécution du Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -I./external/pcre2-10.32//install/include/ -DPCRE2_STATIC -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/maild.c -o os_maild/maild.o
os_maild/maild.c:11:19: erreur fatale: maild.h : Aucun fichier ou dossier de ce type
 #include "maild.h"
                   ^
compilation terminée.
make: *** [os_maild/maild.o] Erreur 1

 Error 0x5.
 Erreur de compilation. Impossible de finir l'installation.

need help!

**Comment by ddpbsd** [comment]
The [file](https://github.com/ossec/ossec-hids/blob/master/src/os_maild/maild.h) exists in the repository.
Does it exist in your copy?
I don't have the output of `install.sh` handy, but from a quick compilation the `cc` lines look similar enough.
Which distribution/version are you using?

**Comment by duplex007** [comment]
Thank you for the feedback.

here is my distribution: CentOS Linux release 7.5.1804 (Core)

I add the copy of the maild.h file, and the following error appears.::

5- Installation du système
 - Exécution du Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -I./external/pcre2-10.32//install/include/ -DPCRE2_STATIC -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/maild.c -o os_maild/maild.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -I./external/pcre2-10.32//install/include/ -DPCRE2_STATIC -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/sendmail.c -o os_maild/sendmail.o
os_maild/sendmail.c:12:19: erreur fatale: event.h : Aucun fichier ou dossier de ce type
 #include <event.h>
                   ^
compilation terminée.
make: *** [os_maild/sendmail.o] Erreur 1

 Error 0x5.
 Erreur de compilation. Impossible de finir l'installation.

[root@localhost ossec-hids]#

**Comment by ddpbsd** [comment]
Do you have the libevent development package installed?

**Comment by duplex007** [comment]
no, I do not think so

**Comment by ddpbsd** [comment]
So if you're using the post-3.3 MASTER branch, you'll need the libevent development packages. Some things changed, and now they're necessary. I forget the PR number and the issue number(s), but it was all to support systems that had IPv6 disabled.

**Comment by duplex007** [comment]
okay
I installed the libevent and the installation is done.

not against i have another problem, after installing the ossec web package (ossec-wui-0.9),
I get this message when I try to connect in http://@IP EON/ossec
.......
Not Found

The requested URL /ossec was not found on this server.
........
I followed this tutorial:

https://www.sbarjatiya.com/notes_wiki/index.php/CentOS_7.x_Install_OSSEC 
and 
https://forum.eyesofnetwork.com/viewtopic.php?f=19&t=276#p2026

**Comment by ddpbsd** [comment]
OSSEC WUI has been discontinued. You can try on the mailing list or the WUI github account to see if anyone is interested in helping with it.

**Comment by duplex007** [comment]
ok thanks,
