### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ossec/ossec-hids#1735]
I would like to point out that identifiers like “[`_Eventinfo`](https://github.com/ossec/ossec-hids/blob/9c54bbbd2752a693504173f607fad717d0234c66/src/analysisd/eventinfo.h#L16 "Update candidate")” and “[`__shost`](https://github.com/ossec/ossec-hids/blob/069bf9e4c25c5c179187241b0e49232d240ffc9f/src/os_csyslogd/csyslogd.h#L35 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by atomicturtle** [comment]
By all means, send us a pull request. Would you like to join us on our slack channel to discuss?
