### ISSUE TITLE
ossec-csyslogd crash on CentOS 7.3

### ISSUE THREAD

**Issue by x86txt** [ossec/ossec-hids#1743]
I am attempting to enable ossec-csyslogd on a server which has been running ossec for a while without issue. I'm running the latest ossec from the CentOS 7 atomic repo (ossec-hids-server-3.3.0-7006.el7.art.x86_64)

When trying to start ossec-csyslogd, the following crash is registered in /var/log/messages:

Jul 12 17:06:59 ossec kernel: traps: ossec-csyslogd[2993] general protection ip:7f82d84cc71c sp:7ffef9dce428 error:0 in libc-2.17.so[7f82d8447000+1c2000]

**Comment by ddpbsd** [comment]
What’s your configuration?

**Comment by x86txt** [comment]
`<ossec_config>
  <global>
    <email_notification>yes</email_notification>
    <email_to>me@mydomain.com</email_to>
    <smtp_server>outbound.mydomain.local</smtp_server>
    <email_from>ossecm@mydomain.com</email_from>
  </global>

  <syslog_output>
    <server>graylog-lb.mydomain.local</server>
    <port>5555</port>
    <format>cef</format>
  </syslog_output>

  <rules>
    <include>rules_config.xml</include>
    <include>pam_rules.xml</include>
    <include>sshd_rules.xml</include>
    <include>telnetd_rules.xml</include>
    <include>syslog_rules.xml</include>
    <include>arpwatch_rules.xml</include>
    <include>symantec-av_rules.xml</include>
    <include>symantec-ws_rules.xml</include>
    <include>pix_rules.xml</include>
    <include>named_rules.xml</include>
    <include>smbd_rules.xml</include>
    <include>vsftpd_rules.xml</include>
    <include>pure-ftpd_rules.xml</include>
    <include>proftpd_rules.xml</include>
    <include>ms_ftpd_rules.xml</include>
    <include>ftpd_rules.xml</include>
    <include>hordeimp_rules.xml</include>
    <include>roundcube_rules.xml</include>
    <include>wordpress_rules.xml</include>
    <include>cimserver_rules.xml</include>
    <include>vpopmail_rules.xml</include>
    <include>vmpop3d_rules.xml</include>
    <include>courier_rules.xml</include>
    <include>web_rules.xml</include>
    <include>web_appsec_rules.xml</include>
    <include>apache_rules.xml</include>
    <include>nginx_rules.xml</include>
    <include>php_rules.xml</include>
    <include>mysql_rules.xml</include>
    <include>postgresql_rules.xml</include>
    <include>ids_rules.xml</include>
    <include>squid_rules.xml</include>
    <include>firewall_rules.xml</include>
    <include>apparmor_rules.xml</include>
    <include>cisco-ios_rules.xml</include>
    <include>netscreenfw_rules.xml</include>
    <include>sonicwall_rules.xml</include>
    <include>postfix_rules.xml</include>
    <include>sendmail_rules.xml</include>
    <include>imapd_rules.xml</include>
    <include>mailscanner_rules.xml</include>
    <include>dovecot_rules.xml</include>
    <include>ms-exchange_rules.xml</include>
    <include>racoon_rules.xml</include>
    <include>vpn_concentrator_rules.xml</include>
    <include>spamd_rules.xml</include>
    <include>msauth_rules.xml</include>
    <include>mcafee_av_rules.xml</include>
    <include>trend-osce_rules.xml</include>
    <include>ms-se_rules.xml</include>
    
    <include>zeus_rules.xml</include>
    <include>solaris_bsm_rules.xml</include>
    <include>vmware_rules.xml</include>
    <include>ms_dhcp_rules.xml</include>
    <include>asterisk_rules.xml</include>
    <include>ossec_rules.xml</include>
    <include>attack_rules.xml</include>
    <include>dropbear_rules.xml</include>
    <include>unbound_rules.xml</include>
    <include>sysmon_rules.xml</include>
    <include>opensmtpd_rules.xml</include>
    <include>local_rules.xml</include>
  </rules>


  <syscheck>
    
    <frequency>72000</frequency>

    
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin,/boot</directories>

    
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>

    
    <nodiff>/etc/ssl/private.key</nodiff>
  </syscheck>

  <rootcheck>
    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>
  </rootcheck>

  <remote>
    <connection>secure</connection>
  </remote>

  <alerts>
    <log_alert_level>1</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>

</ossec_config>`

**Comment by ddpbsd** [comment]
Using a hostname for the `<server>` option I get:
```
[root@rossak etc]# /var/ossec/bin/ossec-csyslogd -df -c /var/ossec/etc/test_ossec.conf 
2019/07/13 22:00:51 ossec-csyslogd: DEBUG: Starting ...
2019/07/13 22:00:51 ossec-csyslogd: INFO: Chrooted to directory: /var/ossec
2019/07/13 22:00:51 ossec-csyslogd: INFO: Using user: ossecm
2019/07/13 22:00:51 ossec-csyslogd: INFO: Started (pid: 15685).
2019/07/13 22:00:51 ossec-csyslogd: INFO: File queue connected.
2019/07/13 22:00:51 getaddrinfo: System error
Segmentation fault
```

But using an IP seems to work fine.

**Comment by ddpbsd** [comment]
Just verified, and alerts are making it into the syslog server just fine using the IP.

**Comment by x86txt** [comment]
> Using a hostname for the `<server>` option I get:
> 
> ```
> [root@rossak etc]# /var/ossec/bin/ossec-csyslogd -df -c /var/ossec/etc/test_ossec.conf 
> 2019/07/13 22:00:51 ossec-csyslogd: DEBUG: Starting ...
> 2019/07/13 22:00:51 ossec-csyslogd: INFO: Chrooted to directory: /var/ossec
> 2019/07/13 22:00:51 ossec-csyslogd: INFO: Using user: ossecm
> 2019/07/13 22:00:51 ossec-csyslogd: INFO: Started (pid: 15685).
> 2019/07/13 22:00:51 ossec-csyslogd: INFO: File queue connected.
> 2019/07/13 22:00:51 getaddrinfo: System error
> Segmentation fault
> ```
> 
> But using an IP seems to work fine.
> 
> EDIT: CentOS7, IPv6 has NOT been disabled.

Boom, that did it! Weird, but I'll take it! Thanks @ddpbsd !

**Comment by ddpbsd** [comment]
@x86txt I think it's still a bug, but I'll open a new issue for this. It won't be hard to fix, just time consuming. Thanks for reporting it!
