### ISSUE TITLE
Arm board compile ossec syntax error

### ISSUE THREAD

**Issue by hilisecs** [ossec/ossec-hids#1745]
The arm plate model is am335x
I am using ossec3.1.0 to compile a syntax error on the arm linux board.
The arm board gcc version is 7.2.1
cat /proc/version
Linux version 4.14.79-gbde58ab01e (oe-user@oe-host) (gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11)) #1 PREEMPT Thu Dec 20 04:12:32 UTC 2018
Guiqiu expert advice

./init/adduser.sh ossec ossecm ossecr ossec /var/ossec
Wait for success...
useradd: user 'ossec' already exists
make: *** [Makefile:381: install-common] Error 9
cp: cannot create regular file `/var/ossec/etc/ossec-init.conf': No such file or directory
chmod: cannot access `/var/ossec/etc/ossec-init.conf': No such file or directory

**Comment by ddpbsd** [comment]
Does `/usr/bin/getent` exist on the system?
