### ISSUE TITLE
OpenBSD - ossec-analysisd: mmap W^X violation

### ISSUE THREAD

**Issue by northox** [ossec/ossec-hids#1747]
We been having issue with analysisd on OpenBSD (6.4+). I traced the issue back to version 3.x upward - tried 3.0 to 3.3. 2.9.4 works well.

```
$ doas /var/ossec/bin/ossec-control start 
Starting OSSEC HIDS v3.0.0 (by Trend Micro Inc.)...
Bus error 
OSSEC analysisd: Testing rules failed. Configuration error. Exiting.
$
```

The issue seems to be related by the introduction of default W^X memory protection in OpenBSD and possible something new in 3.x using JIT possibly. We found the following within `/var/log/messages`: `/bsd: ossec-analysisd(<pid>): mmap W^X violation`.

I believe disabling the memory protection function for a security agent isn't the right approach... right? I'm seeking some advices about what to look for in 3.x and how I could fix/workaround this  issue.

**Comment by ddpbsd** [comment]
It’s probably the pcre2 jit. I disable it on my OpenBSD systems.
`USE_PCRE2_JIT=no ./install.sh`

**Comment by northox** [comment]
Solved. Thanks Dan.

I used `PRCE2_SYSTEM=yes USE_PCRE_JIT=no ./install.sh` with 3.2.0.

Shouldn't this be the standard on OpenBSD install? Should I send a PR?

**Comment by ddpbsd** [comment]
My pull request that sets this has been merged. It will be default in the next version.
