### ISSUE TITLE
Installation of ossec-hids-server_3.3.0.6515stretch_amd64.deb from https://updates.atomicorp.com/channels/atomic/debian fails with missing ssl-Dependency

### ISSUE THREAD

**Issue by kinimoas** [ossec/ossec-hids#1761]
The package depends on  libssl1.0.0, which is not available in debian stretch.

The current version available is libssl1.0.2:amd64 

A work around to this is to downgrade to 
ossec-hids-server_3.2.0.6122stretch_amd64.deb

**Comment by atomicturtle** [comment]
Resolved in 3.3.0+
