### ISSUE TITLE
os_regex.h fatal error pcre2.h No such file or directory

### ISSUE THREAD

**Issue by pabmuela** [ossec/ossec-hids#1766]
Hi,

I try to install ossec version 3.3.0 on a:

Red Hat Enterprise Linux Server version 7.6 (Maipo)
Architecture: ppc64le
Byte Order: Little Endian

and I get these error

##############################################################
5- Installing the system
 - Running the Makefile
cc  -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DCLIENT -Wall -Wextra -I./ -I./headers/ -I./client-agent  -DARGV0=\"ossec-agentd\" -c client-agent/sendmsg.c -o client-agent/sendmsg.o
In file included from ./headers/shared.h:215:0,
                 from client-agent/sendmsg.c:10:
./os_regex/os_regex.h:19:19: fatal error: pcre2.h: No such file or directory
 #include <pcre2.h>
                   ^
compilation terminated.
make: *** [client-agent/sendmsg.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

##############################################################

**Comment by ddpbsd** [comment]
As detailed [here](https://github.com/ossec/ossec-hids/issues/1663) you either need to unpack the pcre2 source into `external/pcre2-10.32` or use `PCRE2_SYSTEM=y` and have the appropriate package installed.

**Comment by AIissam** [comment]
Hello,
nstall the PCRE2 development libraries:  sudo yum install pcre2-devel
