### ISSUE TITLE
Export Control Classification Number (ECCN)

### ISSUE THREAD

**Issue by vincentv31** [ossec/ossec-hids#1773]
On our system, Ossec is used to control integrity, we use Ossec v3.3.

For export issues, we have to define the ECCN (Export Control Classification Number) code for the system embedding Ossec, which is (among other) determined by the ECCN code of Ossec.

Do you know if there is an ECCN code for Ossec, and if not, can you tell me which contact could be able to provide such information ?

Do you know if ossec, as an open sources software, is subject or nor to Encryption and Export Administration Regulations (EAR).

Thank you very much in advance and best regards.

**Comment by ddpbsd** [comment]
This isn't something we've looked into as a project. It's possible some of the companies using it in their products have obtained an ECCN.
