### ISSUE TITLE
OSSEC 3.3 server install

### ISSUE THREAD

**Issue by lex1993** [ossec/ossec-hids#1774]
5- Installing the system
 - Running the Makefile
cc -fPIC -no-pie -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -Wall -Wextra -I./ -I./headers/ -c external/cJSON/cJSON.c -o external/cJSON/cJSON.o
cc: unrecognized option '-no-pie'
ar -crs libcJSON.a external/cJSON/cJSON.o
ranlib libcJSON.a
cc -fPIC -no-pie -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/config.c -o os_maild/config.o
cc: unrecognized option '-no-pie'
In file included from ./headers/shared.h:215,
                 from os_maild/config.c:10:
./os_regex/os_regex.h:19:19: error: pcre2.h: No such file or directory
In file included from ./headers/shared.h:215,
                 from os_maild/config.c:10:
./os_regex/os_regex.h:46: error: expected specifier-qualifier-list before ?.cre2_code?
./os_regex/os_regex.h:56: error: expected specifier-qualifier-list before ?.cre2_code?
./os_regex/os_regex.h:67: error: expected specifier-qualifier-list before ?.cre2_code?
make: *** [os_maild/config.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

----------------------------------------------------------------------------------
OS VERSION:Red Hat Enterprise Linux Server release 6.7 (Santiago)
GCC VERSION:gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

I replaced : PCRE2_SYSTEM?=no
with 
PCRE2_SYSTEM?=yes
according to https://github.com/ossec/ossec-hids/issues/1723

Any ideas?

Best regards,

**Comment by ddpbsd** [comment]
Install the pcre2/pcre2 development packages.

**Comment by lex1993** [comment]
sovled it,thank you!
