### ISSUE TITLE
 我的OSSec 服务器重装后，所有的Agent怎么重新连接回来？

### ISSUE THREAD

**Issue by hanjian007** [ossec/ossec-hids#1775]
我的OSSec服务器硬盘故障导致我的系统重装后，下面所有的Agent 怎么连接到服务器上了，我现在有所有Agent的 key。我使用的OSSec 的版本是OSSEC HIDS v2.8.3

**Comment by lex1993** [comment]
I translated the problem:
After the hard disk failure of my OSSec server, I  reinstalled  my system. How can I connect all my agent to the server? Now I have the keys of all agents. The version of OSSec I used is OSSec HIDS v2.8.3

**Comment by atomicturtle** [comment]
Youd need to restore the client.keys file, or otherwise re-key all your agents. Also, please upgrade, we no longer support ossec 2.8.3!

**Comment by atomicturtle** [comment]
Closed as resolved / No response
