### ISSUE TITLE
OSSEC 3.3.0 Process locked. Waiting for permission...

### ISSUE THREAD

**Issue by lex1993** [ossec/ossec-hids#1778]
My agent can not connect to the server. I tried to remove the agent and then add it, and it remains the same.
agent log:
2019/10/08 16:37:41 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/config'
2019/10/08 16:37:41 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/spool'
2019/10/08 16:37:41 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/CatRoot'
2019/10/08 16:37:43 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/messages'.
2019/10/08 16:37:43 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/secure'.
2019/10/08 16:37:43 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/maillog'.
2019/10/08 16:37:43 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2019/10/08 16:37:43 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tan |grep LISTEN |egrep -v '(127.0.0.1| ::1)' | sort
2019/10/08 16:37:43 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 5
2019/10/08 16:37:43 ossec-logcollector: INFO: Started (pid: 13057).
2019/10/08 16:37:45 ossec-logcollector: WARN: Process locked. Waiting for permission...
2019/10/08 16:38:43 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2019/10/08 16:38:43 ossec-syscheckd: WARN: Process locked. Waiting for permission...

server log:
1608	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/Debug'
  1609	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/WindowsUpdate.log'
  1610	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/iis6.log'
  1611	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/wbem/Logs'
  1612	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/wbem/Repository'
  1613	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/Prefetch'
  1614	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/PCHEALTH/HELPCTR/DataColl'
  1615	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/SoftwareDistribution'
  1616	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/Temp'
  1617	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/config'
  1618	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/spool'
  1619	2019/10/08 16:37:55 ossec-syscheckd: INFO: ignoring: 'C:\WINDOWS/system32/CatRoot'
  1620	2019/10/08 16:37:56 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/messages'.
  1621	2019/10/08 16:37:56 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/secure'.
  1622	2019/10/08 16:37:56 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/maillog'.
  1623	2019/10/08 16:37:56 ossec-logcollector: INFO: Monitoring output of command(360): df -P
  1624	2019/10/08 16:37:56 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tan |grep LISTEN |egrep -v '(127.0.0.1| ::1)' | sort
  1625	2019/10/08 16:37:56 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 5
  1626	2019/10/08 16:37:56 ossec-logcollector: INFO: Started (pid: 28377).
  1627	2019/10/08 16:38:57 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
  1628	2019/10/08 16:38:57 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).

I edit the server's config file because the server didn't bind 1514 udp port:
`<remote>
    <connection>syslog</connection>
    <allowed-ips>any</allowed-ips>
    <port>1514</port>
    <local_ip>172.24.154.47</local_ip>
  </remote>` 

server netstat after I edit the config file:
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Timer
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0    232 172.24.154.47:22        172.24.2.225:3243       ESTABLISHED on (0.33/0/0)
tcp6       0      0 :::111                  :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      off (0.00/0/0)
udp        0      0 0.0.0.0:111             0.0.0.0:*                           off (0.00/0/0)
udp        0      0 172.24.154.47:123       0.0.0.0:*                           off (0.00/0/0)
udp        0      0 127.0.0.1:123           0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:123             0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:737             0.0.0.0:*                           off (0.00/0/0)
udp6       0      0 172.24.154.47:1514      :::*                                off (0.00/0/0)
udp6       0      0 :::111                  :::*                                off (0.00/0/0)
udp6       0      0 fd00::3:250:56ff:fe:123 :::*                                off (0.00/0/0)
udp6       0      0 fe80::250:56ff:fea4:123 :::*                                off (0.00/0/0)
udp6       0      0 ::1:123                 :::*                                off (0.00/0/0)
udp6       0      0 :::123                  :::*                                off (0.00/0/0)
udp6       0      0 :::737                  :::*                                off (0.00/0/0)

please help, thank you!

**Comment by ddpbsd** [comment]
Make sure there are no firewalls blocking the traffic.
Use tcpdump on the ossec server to make sure it is seeing the traffic from the agent.

**Comment by atomicturtle** [comment]
Closed as resolved / No response
