### ISSUE TITLE
Unable to update Ubuntu 18.04 LTS (libevent)

### ISSUE THREAD

**Issue by ogmueller** [ossec/ossec-hids#1782]
Our ossec is running on an Ubuntu 18.04 using apt source ```deb [arch=amd64] https://updates.atomicorp.com/channels/atomic/ubuntu bionic main```. So far so good. It worked well for a long time.

Now I am trying to make a ```aptitude upgrade``` and get
```
# aptitude upgrade 
Resolving dependencies...                
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
[master e439395] saving uncommitted changes in /etc prior to apt run
 1 file changed, 1 deletion(-)
```

When trying to do a ```aptitude dist-upgrade``` I get
```
# aptitude dist-upgrade 
The following packages will be REMOVED:  
  expect{u} libtcl8.6{u} tcl-expect{u} tcl8.6{u} 
The following packages will be upgraded:
  ossec-hids-agent{b} 
1 packages upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
Need to get 262 kB of archives. After unpacking 4,622 kB will be freed.
The following packages have unmet dependencies:
 ossec-hids-agent : Depends: libevent-2.0-5 (>= 2.0.10-stable) which is a virtual package and is not provided by any available package

The following actions will resolve these dependencies:

     Remove the following packages:             
1)     ossec-hids-agent [3.3.0-8264bionic (now)]
```

Is this a problem with ossec or ubuntu?

**Comment by nc-fosterr** [comment]
Looks like Bionic package got overwritten with Debian stretch:

http://updates.atomicorp.com/channels/atomic/ubuntu/dists/bionic/main/binary-amd64/Packages

**Comment by stephencoetzee** [comment]
Seconded on this issue. I've had the same issue with Xenial's package. Got overwritten by stretch:

http://updates.atomicorp.com/channels/atomic/ubuntu/dists/xenial/main/binary-amd64/Packages

**Comment by ogmueller** [comment]
It seems to work for bionic again :-) Thanks
