### ISSUE TITLE
os_maild/sendmail.c:12:19: fatal error: event.h: No such file or directory

### ISSUE THREAD

**Issue by nodesocket** [ossec/ossec-hids#1785]
Trying to upgrade from `v3.3.0` to `v3.4.0` and when running `PCRE2_SYSTEM=yes ./install.sh` I am getting:

```
os_maild/sendmail.c:12:19: fatal error: event.h: No such file or directory
 #include <event.h>
                   ^
compilation terminated.
Makefile:926: recipe for target 'os_maild/sendmail.o' failed
make: *** [os_maild/sendmail.o] Error 1
```

Full install commands are:

```
cat <<EOF > etc/preloaded-vars.conf
USER_LANGUAGE="en"
USER_NO_STOP="y"
USER_INSTALL_TYPE="local"
USER_DIR="/var/ossec"
USER_DELETE_DIR="y"
USER_ENABLE_ACTIVE_RESPONSE="y"
USER_ENABLE_SYSCHECK="y"
USER_ENABLE_ROOTCHECK="y"
USER_UPDATE="y"
USER_UPDATE_RULES="y"
USER_ENABLE_EMAIL="y"
USER_EMAIL_ADDRESS="ops@domain.com"
USER_EMAIL_SMTP="localhost"
USER_ENABLE_SYSLOG="n"
USER_ENABLE_FIREWALL_RESPONSE="y"
USER_ENABLE_PF="n"
USER_WHITE_LIST="127.0.0.1"
EOF

PCRE2_SYSTEM=yes ./install.sh
```

Any ideas?

**Comment by ddpbsd** [comment]
Install the libevent dev package

**Comment by nodesocket** [comment]
Was this a change in `v3.4.0` needing  libevent dev upgrading from `v3.3.0`? Previously did not need that package.

**Comment by ddpbsd** [comment]
I think so. It helps with dns resolution.

**Comment by Nono-m0le** [comment]
I actually solved my issue by doing
```
sudo apt install libssl1.0-dev
sudo PCRE2_SYSTEM=yes ./install.sh
```

**Comment by chuckyinfotec** [comment]
I resolved with:
apt install libz-dev libssl-dev libpcre2-dev libevent-dev build-essential

**Comment by upengan78** [comment]
5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ os_maild/sendmail.o os_maild/sendcustomemail.o os_maild/config.o os_maild/os_maild_client.o os_maild/maild.o os_maild/mail_list.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz  -levent ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
/bin/ld: cannot find -levent
collect2: error: ld returned 1 exit status
make: *** [ossec-maild] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

Oracle Linux 7.7

rpm -qa | grep libevent
libevent-2.0.21-4.el7.x86_64
libev-libevent-devel-4.15-3.el7.x86_64

**Comment by ddpbsd** [comment]
@upengan78 Is there a `libevent-devel` package you can install?

**Comment by upengan78** [comment]
I only see libev-libevent-devel and it's installed.
yum search libevent-devel
libev-libevent-devel.x86_64 : Compatibility development header with libevent for libev.

rpm -ql libev-libevent-devel.x86_64
/usr/include/event.h   (This file is available)

**Comment by ddpbsd** [comment]
You could run `ldconfig -p | grep event` to see if it's different on that system. But I don't really have access to oracle linux, so I can't do much investigation.

**Comment by upengan78** [comment]
@ddpbsd Thank you for helping out. I can run commands/similar commands on my platform per your hints. Thanks!! . Here is what I see
ldconfig -p | grep event
        libverto-tevent.so.1 (libc6,x86-64) => /lib64/libverto-tevent.so.1
        libtevent.so.0 (libc6,x86-64) => /lib64/libtevent.so.0
        libtevent-util.so.0 (libc6,x86-64) => /lib64/libtevent-util.so.0
        libparsevent.so (libc6,x86-64) => /lib64/libparsevent.so
        libevent_pthreads-2.0.so.5 (libc6,x86-64) => /lib64/libevent_pthreads-2.0.so.5
        libevent_openssl-2.0.so.5 (libc6,x86-64) => /lib64/libevent_openssl-2.0.so.5
        libevent_extra-2.0.so.5 (libc6,x86-64) => /lib64/libevent_extra-2.0.so.5
        libevent_core-2.0.so.5 (libc6,x86-64) => /lib64/libevent_core-2.0.so.5
        libevent-2.0.so.5 (libc6,x86-64) => /lib64/libevent-2.0.so.5
        libdmraid-events-isw.so.1 (libc6,x86-64) => /lib64/libdmraid-events-isw.so.1
        libdmraid-events-isw.so (libc6,x86-64) => /lib64/libdmraid-events-isw.so
        libdevmapper-event.so.1.02 (libc6,x86-64) => /lib64/libdevmapper-event.so.1.02
        libdevmapper-event-lvm2vdo.so (libc6,x86-64) => /lib64/libdevmapper-event-lvm2vdo.so
        libdevmapper-event-lvm2thin.so (libc6,x86-64) => /lib64/libdevmapper-event-lvm2thin.so
        libdevmapper-event-lvm2snapshot.so (libc6,x86-64) => /lib64/libdevmapper-event-lvm2snapshot.so
        libdevmapper-event-lvm2raid.so (libc6,x86-64) => /lib64/libdevmapper-event-lvm2raid.so
        libdevmapper-event-lvm2mirror.so (libc6,x86-64) => /lib64/libdevmapper-event-lvm2mirror.so
        libdevmapper-event-lvm2.so.2.02 (libc6,x86-64) => /lib64/libdevmapper-event-lvm2.so.2.02

**Comment by ddpbsd** [comment]
Oh, I should have noticed. That's libevent2. Is there a libevent1 package?

**Comment by upengan78** [comment]
@ddpbsd  No, that was available for Cent OS release 6 but any more > 7.x,

**Comment by upengan78** [comment]
@ddpbsd I edited the src/Makefile and replaced all occurences of -levent with -lev and ./install.sh worked successfully till the end. Thank you for keeping me motivated and commands you provided helped me with better understanding how to approach. Take care.....No sure why I am not emails about updates but I am refreshing this page.. ;)

**Comment by ddpbsd** [comment]
@upengan78 I've opened issue #1860 to remind myself to get back to this. Thanks for pointing it out!
