### ISSUE TITLE
Log rotation for Ossec HIDS

### ISSUE THREAD

**Issue by knzudgt** [ossec/ossec-hids#1796]
I installed Ossec from source in Ubuntu 18.04 LTS, choosing the `local` type of installation.
I wonder why there is no rotation for `/var/ossec/logs/ossec.log` and other files stored in the `/var/ossec/logs/` directory.

**Comment by ddpbsd** [comment]
No one has cared enough about that to integrate it.

**Comment by knzudgt** [comment]
Hi @ddpbsd ,
we had [a chat](https://github.com/ossec/ossec-hids/issues/1281) two years ago.
Does `/var/ossec/logs/ossec.log` grow enough large to require a logrotation?
In [the documentation](https://ossec-docs.readthedocs.io/en/latest/faq/ossec.html#how-can-i-get-ossec-log-to-rotate-daily) it is suggested to use logrotate.d 
I am not an expert user so, if a logroration is advisable, I would copy and paste the [code from wazuh](https://github.com/wazuh/wazuh/issues/87) if it works:

```
# Log rotation for Ossec HIDS
/var/ossec/logs/*.log {
    create 640 ossec ossec
    rotate 31
    compress
    missingok
    notifempty
    olddir /var/ossec/logs/archives/
    sharedscripts
    postrotate
       /var/ossec/bin/ossec-control restart
    endscript
}
```

**Comment by ddpbsd** [comment]
I guess it needs to be decided if this is the responsibility of:
* OSSEC
* packagers
* admins

The downside to pushing it on ossec is that it runs on a lot of systems. Getting it right for all of them would be difficult.

**Comment by atomicturtle** [comment]
Closed as resolved / no response

PS- the RPM and deb packages do have a logrotate set up for this and active-responses.log
