### ISSUE TITLE
Windows agent issue

### ISSUE THREAD

**Issue by mrmarkma** [ossec/ossec-hids#1798]
I installed the OSSEC server (using mostly defaults) on an Ubuntu laptop, and installed OSSEC agent on a Windows machine on the same network. Setup went smoothly, but the OSSEC server does not seem to be talking to the agent at all, as detailed below.

**Agent Log**
From the following agent log, it seems the agent is definitely trying to communicate with the server (server's IP redacted):

> ossec-agent: WARN: Process locked. Waiting for permission...
> ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '<IP redacted>'.
> ossec-agentd: INFO: Trying to connect to server <IP redacted>, port 1514.
> INFO: Connected to <IP redacted> at address <IP redacted>:1514, port 1514
> ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '<IP redacted>'.
> ossec-agentd: INFO: Trying to connect to server <IP redacted>, port 1514.
> INFO: Connected to <IP redacted> at address <IP redacted>:1514, port 1514
> ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '<IP redacted>'.

That process of (1) trying to connect, (2) connecting, and (3) warning that there is no server reply, continues indefinitely.

**Server Log**
The server side logs don't contain much information regarding the connection with the agent. No error messages are shown. 

Running ossec-remoted in DEBUG mode shows that ossec-remoted successfully bound socket 1514. In addition:

> ossec-remoted: INFO: Reading authentication keys ifle.
> ossec-remoted: DEBUG: OS_StartCounter
> ossec-remoted: OS_StartCounter: keysize: 1
> ossec-remoted: INFO: No previous counter available for '<name of agent>'
> ossec-remoted: INFO: Assigning counter for agent <name of agnet>: '0:0'
> ossec-remoted: INFO: No previous sender counter
> ossec-remoted: INFO: Assigning sender counter 0;0
> ossec-remoted: DEBUG: OS_StartCounter completed.

After that, no further messages from ossec-remoted.

**Other server-side info**
tcpdump on the server shows that it is periodically receiving UDP packets (length 73) from the agent, as well as arp requests. No communications back to the agent are reported.

`netstat -tulpan | grep ossec` results in the following:

PID | Recv-Q | Send-Q| Local Address | Foreign Address | State
---|---|---|---|---|---
udp6|0|0|:::15144|:::|   

To be clear, the State is blank (as shown above) rather than LISTEN.

I think I have the relevant Windows firewall settings in place, so that shouldn't be the issue.

Any thoughts would be appreciated.

**Comment by rsumner868** [comment]
```

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddpbsd** [comment]
Is the host firewall on the ubuntu system blocking the packets from the agent?

**Comment by atomicturtle** [comment]
closed no response, please re-open this issue if this comes back. Thanks!
