### ISSUE TITLE
Slack Integration and Notifications

### ISSUE THREAD

**Issue by cyberfarer** [ossec/ossec-hids#1799]
Greetings,

Using integrations I am having notifications sent to Rocket.Chat. What I;m finding though, is that the channel is filled with activity from whitelisted IPs. Using local rules. I can suppress email alerts. Is there a means to also support Slack/Rocket.Chat alerts? 

I have followed the instructions here: https://geekcabi.net/article/ossec-whitelisting/

However, I continue to get notifications to the Rocket.Chat channel. 

Suggestions are appreciated.

Thanks.

**Comment by rsumner868** [comment]
```

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddpbsd** [comment]
You shouldn't be getting any notifications for anything that doesn't trigger an alert. So if the IP is white listed, and it's properly decoded, there shouldn't be an alert for the event. No alert means no notification (email, slack, rocketchat, etc)

**Comment by atomicturtle** [comment]
closed as resolved / no response
