### ISSUE TITLE
Amazon Linux install can't resolve dependencies

### ISSUE THREAD

**Issue by spencescu** [ossec/ossec-hids#1800]
Hi,

I am trying to install on Amazon Linux (v1) and getting the following error:

Error: Package: 1:ossec-hids-agent-3.5.0-9609.amzn2.art.x86_64 (atomic)
           Requires: libpcre2-8.so.0()(64bit)

Please advise.

Thanks,
Sherman

**Comment by atomicturtle** [comment]
We cant make packages for Amazon Linux v1 unfortunately. You can try putting the Amazon Linux v2 repos on there, but Im not sure how that will work out
