### ISSUE TITLE
SSL Error installing OSSEC won't grab from github

### ISSUE THREAD

**Issue by yamoumonster** [ossec/ossec-hids#1802]
![OSSEC error SSL](https://user-images.githubusercontent.com/58235560/69765417-64319300-1139-11ea-938e-e18a0853c8e5.PNG)

Im a super newb with linux but can't understand why im having this error. ive already updated the system and upgraded and updated the ssl plus rebooting but this error wont budge.  I would love any help figuring this out. Ive also toggled between sudo command and [no-sudo]command and having archive in the pathname and not having archive in the pathname.

**Comment by atomicturtle** [comment]
That IP doesnt appear to be associated with github, are you going through a proxy or something? It looks like its associated with iowa state university

**Comment by yamoumonster** [comment]
So, I did some checking with our team leader and I believe its supposed to go through the proxy through ISU into the WWW.  Do you believe this is the issue?  We're students entering a competition and I'm a bit lost on how to fix this. : (

**Comment by yamoumonster** [comment]
Figured it out, the linux versions given are outdated meaning they do not have the proper wget extensions/software in order to access https websites.

**Comment by atomicturtle** [comment]
Glad you got it sorted out, and good luck on your competition!
