### ISSUE TITLE
Cannot Compile using Install Script

### ISSUE THREAD

**Issue by LivelyCarpet87** [ossec/ossec-hids#1806]
I am currently on MacOS Mojave attempting to install OSSEC 3.3.0

The following are the choices and error messages. 

  ** Para instalação em português, escolha [br].
  ** 要使用中文进行安装, 请选择 [cn].
  ** Fur eine deutsche Installation wohlen Sie [de].
  ** Για εγκατάσταση στα Ελληνικά, επιλέξτε [el].
  ** For installation in English, choose [en].
  ** Para instalar en Español , eliga [es].
  ** Pour une installation en français, choisissez [fr]
  ** A Magyar nyelvű telepítéshez válassza [hu].
  ** Per l'installazione in Italiano, scegli [it].
  ** 日本語でインストールします．選択して下さい．[jp].
  ** Voor installatie in het Nederlands, kies [nl].
  ** Aby instalować w języku Polskim, wybierz [pl].
  ** Для инструкций по установке на русском ,введите [ru].
  ** Za instalaciju na srpskom, izaberi [sr].
  ** Türkçe kurulum için seçin [tr].
  (en/br/cn/de/el/es/fr/hu/it/jp/nl/pl/ru/sr/tr) [en]: 
en

 OSSEC HIDS v3.3.0 Installation Script - http://www.ossec.net
 
 You are about to start the installation process of the OSSEC HIDS.
 You must have a C compiler pre-installed in your system.
 
  - System: Darwin name-MacBook-Air.local 18.7.0
  - User: root
  - Host: name-MacBook-Air.local

  -- Press ENTER to continue or Ctrl-C to abort. --

1- What kind of installation do you want (server, agent, local, hybrid or help)? 
local

  - Local installation chosen.

2- Setting up the installation environment.

 - Choose where to install the OSSEC HIDS [/var/ossec]: 
/User/livelycarpet87/ossec

    - Installation will be made at  /User/livelycarpet87/ossec .

3- Configuring the OSSEC HIDS.

  3.1- Do you want e-mail notification? (y/n) [y]: 
n

   --- Email notification disabled.

  3.2- Do you want to run the integrity check daemon? (y/n) [y]: 
y

   - Running syscheck (integrity check daemon).

  3.3- Do you want to run the rootkit detection engine? (y/n) [y]: 
y

   - Running rootcheck (rootkit detection).

  3.4- Active response allows you to execute a specific 
       command based on the events received. For example,
       you can block an IP address or disable access for
       a specific user.  
       More information at:
       http://www.ossec.net/en/manual.html#active-response
       
   - Do you want to enable active response? (y/n) [y]: 
y

     - Active response enabled.
   
   - By default, we can enable the host-deny and the 
     firewall-drop responses. The first one will add
     a host to the /etc/hosts.deny and the second one
     will block the host on iptables (if linux) or on
     ipfilter (if Solaris, FreeBSD or NetBSD).
   - They can be used to stop SSHD brute force scans, 
     portscans and some other forms of attacks. You can 
     also add them to block on snort events, for example.

   - Do you want to enable the firewall-drop response? (y/n) [y]: 
y

     - firewall-drop enabled (local) for levels >= 6

   - 
      - 8.8.8.8

   - Do you want to add more IPs to the white list? (y/n)? [n]: 
n

  3.6- Setting the configuration to analyze the following logs:
    -- /var/log/system.log

 - If you want to monitor any other file, just change 
   the ossec.conf and add a new localfile entry.
   Any questions about the configuration can be answered
   by visiting us online at http://www.ossec.net .
   
   
   --- Press ENTER to continue ---
                            

5- Installing the system
 - Running the Makefile
cc  -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/User/livelycarpet87/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DDarwin -DDarwin -DHIGHFIRST -DZLIB_SYSTEM -I./external/pcre2-10.32//install/include/ -DPCRE2_STATIC -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -c external/cJSON/cJSON.c -o external/cJSON/cJSON.o
ar -crs libcJSON.a external/cJSON/cJSON.o
ranlib libcJSON.a
cd external/pcre2-10.32/ && \
	./configure \
		--prefix=/Users/livelycarpet87/Downloads/ossec-hids-3.3.0/src/external/pcre2-10.32//install \
		--enable-jit \
		--disable-shared \
		--enable-static && \
	make install-libLTLIBRARIES install-nodist_includeHEADERS
/bin/sh: line 0: cd: external/pcre2-10.32/: No such file or directory
make: *** [external/pcre2-10.32//install/lib/libpcre2-8.a] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by ddpbsd** [comment]
Untar the pcre2 sources to sec/external/pcre2-10.32

**Comment by rsumner868** [comment]
```

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddpbsd** [comment]
To expand on what I posted already, OSSEC 3.3 looks for the pcre2 source in `src/external/pcre2-10.32` directory by default. If you have pcre2 installed on the system (development packages or whatever), you can pass `PCRE2_SYSTEM=y` to install.sh to use the already installed library.
