### ISSUE TITLE
Custom decoder do not pass arguments to active-response script

### ISSUE THREAD

**Issue by marinovgit** [ossec/ossec-hids#1808]
Hello, I have some custom decoders that work well but there is some problem with the arguments to the active-response scripts. The srcip is visible in the email and logtest but not in the active-response action.

Normal Decoder (ssh) to active-response:

```Mon Dec 30 13:28:22 UTC 2019 /var/ossec/active-response/bin/notify.sh add xxxx 2.2.2.2 1577712502.169531 100001 /var/log/secure - ```

Custom decoder to active-response:

``` Fri Jan  3 17:18:03 UTC 2020 /var/ossec/active-response/bin/openvpn.sh add - - 1578071883.922668 100101 /var/log/openvpn.log - ```

Only dashes on srcip!

openvpn.sh 
```
#!/bin/sh 
echo "`date` $0 $1 $2 $3 $4 $5 $6 $7 $8" >> /var/ossec/logs/active-responses.log
```

Decoder:

```
   <decoder name="openvpn-tls-event">
   <parent>openvpn</parent>
   <prematch_pcre2 offset="after_parent">TLS: Initial packet from </prematch_pcre2>
   <pcre2 offset="after_prematch">(\d+.\d+.\d+.\d+):(\d+)</pcre2>
   <order>srcip,srcport</order>
   </decoder>
```

Rule:
```
<rule id="100101" level="10">
  <if_sid>100100</if_sid>
  <match>TLS: Initial packet from</match>
  <description>TLS initial packet to the VPN</description>
  <group>connection_established,</group>
</rule>

```
Ossec-logtest:

```
 Jan  3 17:18:01 server openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513
 **Phase 1: Completed pre-decoding.
        full event: 'Jan  3 17:18:01 server openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513'
        hostname: 'server'
        program_name: 'openvpn'
        log: '1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513'
 **Phase 2: Completed decoding.
        decoder: 'openvpn'
        srcip: '2.2.2.2'
        srcport: '56515'
 **Phase 3: Completed filtering (rules).
        Rule id: '100101'
        Level: '10'
       Description: 'TLS initial packet to the VPN'
**Alert to be generated.

```

Email:
```
 OSSEC HIDS Notification.
 2020 Jan 03 17:18:03
 Received From: server->/var/log/openvpn.log
 Rule: 100101 fired (level 10) -> "TLS initial packet to the VPN"
 Src IP: 2.2.2.2
 Portion of the log(s):
 Jan  3 17:18:01 server openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513

```
Ossec version:
ossec-hids-server-3.5.0-9609.el7.art.x86_64
ossec-hids-3.5.0-9609.el7.art.x86_64

Any ideas? :)

**Comment by rsumner868** [comment]
```

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddpbsd** [comment]
What does the `<command>` look like in the ossec.conf?
It needs to have `srcip` in the `<expect>` option, like so:

```
  <command>
    <name>firewall-drop</name>
    <executable>pf.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>
```

**Comment by marinovgit** [comment]
Hello, no it does not have <expect>srcip</expect>, because if the srcip is not provided there is nothing in the log file (the script is not executed at all). If expect is empty this is the log file:

```Fri Jan 3 17:18:03 UTC 2020 /var/ossec/active-response/bin/openvpn.sh add - - 1578071883.922668 100101 /var/log/openvpn.log -```

The problem is elsewhere, the srcip is not passed to the active-response.

Best regards

**Comment by ddpbsd** [comment]
I don't think it will pass the srcip if it isn't defined in the `<expect>`.
Make sure it's being decoded properly in the alerts.log file.

**Comment by marinovgit** [comment]
No, in the documentation is written:

> If a field is not within the expect option it will be passed as a dash (-) instead of the actual value. For instance, if srcip is required for an active-response script to work it must be inside of an expect option. 
> expect is required, but it is not reqiured to populate it. <expect></expect> is valid if no options need to be passed to the active-response script.

This is the alert from the log:
```
** Alert 1578071883.922668: mail  - syslog,openvpn,connection_established,
2020 Jan 03 17:18:03 server ->/var/log/openvpn.log
Rule: 100101 (level 10) -> 'TLS initial packet to the VPN'
Src IP: 2.2.2.2
Src Port: 56515
Jan  3 17:18:01 server openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513
```

**Comment by ddpbsd** [comment]
Ok, so instead of passing the IP address it passes the dash. That's close enough to what I wrote.

I added the following for testing.
ossec.conf:
```
  <command>
    <name>openvpn</name>
    <executable>test.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>no</timeout_allowed>
  </command>
  <active-response>
    <command>openvpn</command>
    <location>server</location>
    <rules_id>100101</rules_id>
  </active-response>
```

local_decoder.xml:
```
<decoder name="openvpn">
  <program_name>openvpn</program_name>
</decoder>

<decoder name="openvpn-tls-event">
  <parent>openvpn</parent>
  <prematch_pcre2 offset="after_parent">TLS: Initial packet from </prematch_pcre2>
  <pcre2 offset="after_prematch">(\d+.\d+.\d+.\d+):(\d+)</pcre2>
  <order>srcip,srcport</order>
</decoder>
```

local_rules.xml:
```

  <rule id="100100" level="1">
    <decoded_as>openvpn</decoded_as>
  </rule>
  <rule id="100101" level="10">
    <if_sid>100100</if_sid>
    <match>TLS: Initial packet from</match>
    <description>TLS initial packet to the VPN</description>
    <group>connection_established,</group>
  </rule>
```

test.sh:
```
#!/bin/sh

echo $@ >> /var/ossec/logs/ar-test.log
```

Then I restarted the OSSEC processes.
Next I ran this command to simulate a log event coming in:
`echo '1.2.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513' | logger -t openvpn`

This produced the following log message in messages:
`Jan  9 07:57:01 ix openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513`

alert.log entry:
```
** Alert 1578574623.1529103: mail  - local,syslog,connection_established,
2020 Jan 09 07:57:03 ix->/var/log/messages
Rule: 100101 (level 10) -> 'TLS initial packet to the VPN'
Src IP: 2.2.2.2
Src Location: FR
Src Port: 56515
Jan  9 07:57:01 ix openvpn: 1.1.1.1:56515 TLS: Initial packet from [AF_INET]2.2.2.2:56515, sid=1c13g418 c4161513
```

ar-test.log entry:
`add - 2.2.2.2 1578574668.1529596 100101 /var/log/messages -`

So it should work.

I removed `srcip` from the expect, and got the following entry:
`add - - 1578574623.1529103 100101 /var/log/messages -`
So that's not the way to get it to work.

**Comment by marinovgit** [comment]
Hello, first thank you for your time.
I just tested exactly the same config as yours on ossec-hids-server-3.4.0-9229.el7.art.x86_64 ossec-hids-3.4.0-9229.el7.art.x86_64 and the result is like yours.

Again your config but on ossec-hids-3.5.0-9609.el7.art.x86_64 ossec-hids-server-3.5.0-9609.el7.art.x86_64 and the active-response script is not executed at all.
If I remove the srcip from the command this is the ar-test.log:
```
add - - 1578580263.12104 100101 /var/log/openvpn.log -
```
This is the log:
```
** Alert 1578580263.12104: mail  - syslog,openvpn,connection_established,
2020 Jan 09 14:31:03 jump->/var/log/openvpn.log
Rule: 100101 (level 10) -> 'TLS initial packet to the VPN'
Src IP: 1.1.1.1
Src Port: 55174
Jan  9 14:31:01 server openvpn: 51.68.89.172:55174 TLS: Initial packet from [AF_INET]1.1.1.1:55174, sid=6363507f 46b3c5fa
```

Something is wrong with the 3.5 version.
Best regrards

**Comment by ddpbsd** [comment]
Strangely enough, I have a system setup to use the packages (it's a rare occurrence). Unfortunately, it's the agent only.

```
[root@pkgcheck ~]# rpm -qa | grep ossec
ossec-hids-3.5.0-9609.el7.art.x86_64
ossec-hids-agent-3.5.0-9609.el7.art.x86_64
```

It worked. So I guess I need to setup a server at some point to test that too.

**Comment by marinovgit** [comment]
Hello, @ddpbsd I figure it out. The IP from which I test is in <white_list> :)
If you have nothing in the active response is executed.
If srcip is in the script is not executed at all.
It is strange because the active-response in my case is a notification script but, that`s the way it is.

Thank you for your time :)
