### ISSUE TITLE
 installation of ossec-hids-agent (3.5.0-9609buster) fails: chown: invalid user: ossec:ossec

### ISSUE THREAD

**Issue by kinimoas** [ossec/ossec-hids#1810]
Installation or upgrade to ossec-hids-agent (3.5.0-9609buster) fails for me with an error

`chown: invalid user: ossec:ossec`

when installing packages from

`https://updates.atomicorp.com/channels/atomic/debian`

The problem can be fixed with 

`sudo adduser ossec --system --gid 124 --home /var/ossec`

and installing again.

**Comment by morrinene** [comment]
Thank you for this note.  I encountered the issue when doing an update from 3.4.0 to 3.5.0 on stretch.  I did not encounter it doing an update from 3.3.0 to 3.5.0.  I have 3 servers, and one was out of sync.

I had to amend the manual fix for my ossec group number, but that was quick. 

```
grep ossec /etc/group
<capture GROUP_NUMBER>
sudo adduser ossec --system --gid GROUP_NUMBER --home /var/ossec
```

**Comment by atomicturtle** [comment]
Fixed in build 12034, thanks again for the report!
