### ISSUE TITLE
Error while Ossec 3.5.0 installation on CentOS 7

### ISSUE THREAD

**Issue by jjfeitosa** [ossec/ossec-hids#1829]
Hello everyone.

I am trying to install Ossec 3.5.0 local mode on (CentOS Linux release 7.4.1708 (Core)) server, but there is an error during installation.

> 5- Installing the system
>  - Running the Makefile
> cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/sendmail.c -o os_maild/sendmail.o
> os_maild/sendmail.c:12:19: fatal error: event.h: No such file or directory
> #include <event.h>
>                    ^
> compilation terminated.
> make: *** [os_maild/sendmail.o] Error 1
> 
>  Error 0x5.
>  Building error. Unable to finish the installation.

I downloaded and extract the package in the directory:
#tar xzf pcre2-10.32.tar.gz -C /opt/ossec-hids-3.5.0/src/external

Any idea?

Best regards.

James\m/

**Comment by jjfeitosa** [comment]
Install some package, but follow error:
5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -c os_zlib/os_zlib.c -o os_zlib/os_zlib.o
os_zlib/os_zlib.c:13:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make: *** [os_zlib/os_zlib.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by jjfeitosa** [comment]
Libraries Install:
# rpm -qa | grep libev
libevdev-1.5.6-1.el7.x86_64
libevent-2.0.21-4.el7.x86_64
libevent-devel-2.0.21-4.el7.x86_64

**Comment by jjfeitosa** [comment]
after installing the last dependencies, it worked!
sudo yum install zlib-devel
sudo yum install openssl-devel

[root@localhost ossec-hids-3.5.0]# /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v3.5.0...
2020/01/21 13:24:33 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...

Started ossec-syscheckd...
Started ossec-monitord...
Completed.

Thanks!
James\m/

**Comment by suhaylx** [comment]
yum install libevent-devel

**Comment by sachin078** [comment]
Hey i am getting the below error while trying to install ./install file of ossec. could please help me to resolve this issue 

lpcre2-8 -lssl -lcrypto -lz  ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
make: *** [ossec-maild] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by ddpbsd** [comment]
@sachin078 Please don't post this in every issue about build problems. Try turning off the systemd support (which in this case is only used for reading journald binary logs), and try the build again. If it still does not work, create your own issue.

**Comment by sachin078** [comment]
@ddpbsd okay, just wanted to get this issue resolved as I was not able to anyways thanks

**Comment by ddpbsd** [comment]
@sachin078 Yes, and I am offering ways to help you. But I do not understand how your issue relates to OSSEC 3.5.0 on CentOS 7. Or how it relates to a missing libevent development package. Your problem is off-topic in this CLOSED thread, which is why I suggested opening your own issue (after trying the thing I suggested in this and the other CLOSED thread you posted in).
