### ISSUE TITLE
Compile fail with 3.6.0 version on centos7 minial

### ISSUE THREAD

**Issue by Archerkong** [ossec/ossec-hids#1843]
the error is without the file or directory of pcre2.h ，the install package is https://github.com/ossec/ossec-hids/archive/3.6.0.tar.gz

 -如果你希望监控其他文件, 只需要在配置文件ossec.conf中
  添加新的一项. 
  任何关于配置的疑问您都可以在 http://www.ossec.net 找到答案.

  --- 按 ENTER 以继续 ---

5- 正在安装系统
 - 正在运行Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/maild.c -o os_maild/maild.o
In file included from ./headers/shared.h:215:0,
                 from os_maild/maild.c:10:
./os_regex/os_regex.h:19:19: 致命错误：pcre2.h：没有那个文件或目录
 #include <pcre2.h>
                   ^
编译中断。
make: *** [os_maild/maild.o] 错误 1

 Error 0x5.
 Building error. Unable to finish the installation.
 
 错误代码 0x5.
 编译错误. 不能完成安装.

**Comment by ThomasYHA** [comment]
How to resolved？

**Comment by ThomasYHA** [comment]
Maybe  this can be help you（reinstall please）：
#yum install libevent libevent-devel

> the error is without the file or directory of pcre2.h ，the install package is https://github.com/ossec/ossec-hids/archive/3.6.0.tar.gz
> 
> -如果你希望监控其他文件, 只需要在配置文件ossec.conf中
> 添加新的一项.
> 任何关于配置的疑问您都可以在 http://www.ossec.net 找到答案.
> 
> --- 按 ENTER 以继续 ---
> 
> 5- 正在安装系统
> 
> * 正在运行Makefile
>   cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -Wall -Wextra -I./ -I./headers/ -DARGV0="ossec-maild" -c os_maild/maild.c -o os_maild/maild.o
>   In file included from ./headers/shared.h:215:0,
>   from os_maild/maild.c:10:
>   ./os_regex/os_regex.h:19:19: 致命错误：pcre2.h：没有那个文件或目录
>   #include <pcre2.h>
>   ^
>   编译中断。
>   make: *** [os_maild/maild.o] 错误 1
> 
> Error 0x5.
> Building error. Unable to finish the installation.
> 
> 错误代码 0x5.
> 编译错误. 不能完成安装.

**Comment by ddpbsd** [comment]
It looks like you're missing the pcre2 development package.

**Comment by atomicturtle** [comment]
closing this as no-response
