### ISSUE TITLE
ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.

### ISSUE THREAD

**Issue by ahasanaki** [ossec/ossec-hids#1847]
Hi;
i inatalled ossec-hids-3.6.0 and give error starting

# bin/ossec-control start
    Starting OSSEC HIDS v3.6.0...
    ossec-analysisd: Configuration error. Exiting.
# bin/ossec-analysisd -t
    2020/02/28 18:04:10 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
    2020/02/28 18:04:10 ossec-analysisd(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.

i also replace etc/decoder.xml with https://github.com/ossec/ossec-hids/blob/master/etc/decoder.xml but get same error

**Comment by ddpbsd** [comment]
It seems like analysisd didn't get updated properly. Try stopping the ossec processes and copying the new ossec-analysisd to /var/ossec/bin and try again.

**Comment by ahasanaki** [comment]
i remove all ossec-old-version and install ossec-3.6.0. same problem!

**Comment by jiyourui** [comment]
@ahasanaki I have the same problem.Have the problem solved?

**Comment by ddpbsd** [comment]
@ahasanaki @jiyourui 
What OS/distribution/version are you using?
How are you installing OSSEC?

**Comment by jiyourui** [comment]
@ddpbsd  CentOS6.4

**Comment by jiyourui** [comment]
1.	# tar -zxvf ossec-hids-3.6.0.tar.gz
2.	# cd ossec-hids-3.6.0
3.	# ./install.sh

**Comment by jiyourui** [comment]
detailed：
2020/03/04 09:39:23 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/03/04 09:39:23 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/03/04 09:39:23 ossec-maild: INFO: Started (pid: 26634).
2020/03/04 09:39:23 ossec-execd: INFO: Started (pid: 26639).
2020/03/04 09:39:23 ossec-analysisd(1302): ERROR: Invalid active response location: 'local'.
2020/03/04 09:39:23 ossec-analysisd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
2020/03/04 09:39:23 ossec-analysisd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

**Comment by ddpbsd** [comment]
I don't have any CentOS 6 systems to try this out on. Just tested with 7.7 and it works no problem. @atomicturtle do you have a CentOS 6 box handy?

**Comment by atomicturtle** [comment]
Yeah absolutely, Ive got a bunch of them here. Coordinate on slack?

**Comment by ddpbsd** [comment]
I managed to get CentOS 6.4 up and running, but couldn't reproduce the error.

**Comment by ddpbsd** [comment]
Here's the buildlog from this experiment.

[buildlog.txt](https://github.com/ossec/ossec-hids/files/4289076/buildlog.txt)

**Comment by jiyourui** [comment]
thank you，i will continue to follow. Let me try it on CentOS7

**Comment by atomicturtle** [comment]
Closed as resolved / No response
