### ISSUE TITLE
Missing libpcre2-8-0.dll file causing Windows Ossec Agent to fail installation.

### ISSUE THREAD

**Issue by RabidGerbal** [ossec/ossec-hids#1849]
When attempting to install and/or upgrade Windows Ossec Agent v3.4.0, v3.5.0, and/or v.3.6.0 the installation fails and the OssecSvc will not start. 

I found that the ossec-agent.exe file will not open after a failed installation because the libpcre2-8-0.dll file is missing.

**Comment by tmeader** [comment]
Is it possible to use the lipcre2-8-0.dll directly from the mingw32 project?

https://github.com/git-for-windows/git-sdk-64/blob/master/mingw32/bin/libpcre2-8-0.dll

**Comment by siddharth58** [comment]
Hi,
Could you pls help me out how to resolve this issue.
I'm just installing this first time and getting this.

**Comment by atomicturtle** [comment]
Sure thing, I was just wrapping up the other duplicates of this in the tracker. This is resolved int the latest update:  ossec-agent-win32-3.6.0-12032.exe

https://updates.atomicorp.com/channels/atomic/windows/ossec-agent-win32-3.6.0-12032.exe

**Comment by siddharth58** [comment]
Thanks a lot..
