### ISSUE TITLE
ossecsvc service failiure erro while installing.

### ISSUE THREAD

**Issue by siddharth58** [ossec/ossec-hids#1854]
Ossec windows agent showing ossecsvc service failiure error while installing.
i have install OSSEC server on ubuntu 18.04.04 and trying to intsall windows agent on ws 2016 but its showing failure setting up the ossecSvc service .
![Capture](https://user-images.githubusercontent.com/62145576/76630963-e28a3780-6566-11ea-9be9-f8169d49e920.JPG)

**Comment by atomicturtle** [comment]
Duplicate of #1849
