### ISSUE TITLE
ossec-remoted(1408): ERROR: Invalid ID 1058 for the source ip: 'x.x.x.x'

### ISSUE THREAD

**Issue by Johndgnzj** [ossec/ossec-hids#1856]
Hi

I am using ossec-hids(v3.6) in my AWS environment.
```
server: ec2 (fixed IP)
client ec2(spot request Dynamic Private IP 192.168.x.x)
```
And I start the "ossec-authd" daemon on the server so that every client can request a key and connect to it when OPSWork wakes an instance up.

Because of instance comes and go, I know that agent IP address might duplicate someday.
So I found a script to remove the disconnected agents every day. 

Everything works fine, but one thing is bothering me several days.

This error keeps coming in my ossec.log
> ossec-remoted(1408): ERROR: Invalid ID 1058 for the source ip: 'x.x.x.x'

But I don't see this ID shows in
/var/ossec/queue/agent-info
or
/var/ossec/queue/rids

So my question is why this error occurs, and how can I fix it.

Thanks for watching and helping.

**Comment by ddpbsd** [comment]
Check `/var/ossec/etc/client.keys` for that IP address and see which ID is expected. (Don't post the line from client.keys here, the key should remain secret)

**Comment by Johndgnzj** [comment]
@ddpbsd Thanks
Problem solved since I manually remove the clients that disconnected.

Is there any script that can do this in crontab?

**Comment by ddpbsd** [comment]
There is not a script to automatically do this included in OSSEC. Usually disconnected agents need to be connected rather than deleted.
This may not have anything to do with the specific problem you experienced, so excuse me if I'm off base here. OSSEC has been around longer than "highly elastic workloads," and hasn't really adapted well to the culture shift. It's something I think we really need to work on (among many many other things).

**Comment by Johndgnzj** [comment]
@ddpbsd Thanks for your kindly reply.
In our case, some ec2 instance create&setup by AWS Opsworks automatically when ELB loading busy, release when loading down. so the things I try to do is to remove same IP but not the same ec2 instance every time when AWS Opswork setup new instances.

but, this not happen all the time. so I thing manually remove disconnected agents every 1 or 2 week is acceptable for me.

Thanks again, and I think this issue might be changed to close.
