### ISSUE TITLE
OSSEC 3.6.0 Installation Fatal Error with OpenSSL

### ISSUE THREAD

**Issue by armdn** [ossec/ossec-hids#1857]
During the server updating, the fatal error appears:

In file included from ./external/compat/imsg.c:21:
./external/compat/includes.h:65:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./external/compat/imsg-buffer.c:21:
./external/compat/includes.h:65:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [ossec-maild] Error 1
 Ошибка 0x5 .Ошибка компиляции. Невозможно завершить установку.

The OpenSSL Version is 1.1.1d, the system is macOS 10.13.6 (17G11023).

What to do?

**Comment by ddpbsd** [comment]
Does your system have the file? Where is it located?

**Comment by armdn** [comment]
As you can see, there is no such file in system, and for that reason i asked, what to do.

**Comment by ddpbsd** [comment]
I didn't know if it was in another location. I'm not familiar with recent MacOS versions, is there a development package that needs to be installed for openssl?

**Comment by atomicturtle** [comment]
Closed as resolved/ No response
