### ISSUE TITLE
Additional Requirement:  libevent-dev

### ISSUE THREAD

**Issue by ScottJWalter** [ossec/ossec-hids#1858]
Issue:

While upgrading (according to process) an instance of OSSEC from 3.3 to 3.6 on a Raspberry Pi B, I ran into a compile error ("file 'event.h' not found"), and traced it down to the `libevent-dev` package not being installed on the Pi.

Solution:

`sudo apt-get install libevent-dev`

Suggestion:

Updating the "prereq" section of the documentation to include this library.

**Comment by ddpbsd** [comment]
It's mentioned in the INSTALL file. I'll make sure it get added to the online documentation. Thanks!
