### ISSUE TITLE
ossec-hids-agent  3.6.0-12034buster seems not to allways start reliably

### ISSUE THREAD

**Issue by kinimoas** [ossec/ossec-hids#1862]
On restart of some of our systems, the agent does not start properly.

There is no error message visible in syslog, e.g.:

Apr 6 02:07:19 server1 ossec[487]: Starting OSSEC HIDS v3.5.0...
Apr 6 02:07:20 server1 ossec[487]: Started ossec-execd...
Apr 6 02:07:21 server1 ossec[487]: 2020/04/06 02:07:21 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
Apr 6 02:07:21 server1 ossec[487]: 2020/04/06 02:07:21 going daemon
Apr 6 02:07:21 server1 ossec[487]: Started ossec-agentd...
Apr 6 02:07:22 server1 ossec[487]: 2020/04/06 02:07:22 ossec-logcollector: Remote commands are not accepted from the manager. Ignoring it on the agent.conf
Apr 6 02:07:22 server1 ossec[487]: 2020/04/06 02:07:22 ossec-logcollector(1202): ERROR: Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.
Apr 6 02:07:22 server1 ossec[487]: Started ossec-logcollector...
Apr 6 02:07:22 server1 ossec[487]: Started ossec-syscheckd...
Apr 6 02:07:24 server1 ossec[487]: Completed.

/var/ossec/logs/ossec.log shows:
2020/04/06 02:07:28 ossec-logcollector: WARN: Duplicated log file given: '/var/log/syslog'.
2020/04/06 02:07:28 ossec-logcollector: INFO: Started (pid: 798).
2020/04/06 02:08:28 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2020/04/06 02:08:28 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).

Services seem up and running:
 ps -A | grep ossec
  526 ?        00:00:00 ossec-execd
  578 ?        00:00:00 ossec-agentd
  579 ?        00:00:00 ossec-agentd
  798 ?        00:00:00 ossec-logcollec
  807 ?        00:00:00 ossec-syscheckd

However, no entries get added to ossec.log and logs are not transported to the server.

Any idea what the problem might be? What do you need to better understand the problem?

**Comment by ddpbsd** [comment]
You could try running the processes with the debug flag (`-d`). Also, check the server's ossec.log for errors.

**Comment by atomicturtle** [comment]
Closed as resolved / No response
