### ISSUE TITLE
Remote syslog on port 514

### ISSUE THREAD

**Issue by marliyev** [ossec/ossec-hids#1864]
Hi,
Ossec 3.6.0 is up and running but cant get logs from network devices such router, firewall. no connection to syslog on port 514. from tcpdump i see am receiving logs but from netstat no connection established. ossec not listening on port 514 and when receiving logs no connection established. with ufw and without ufw. only ipv6 listening on port 514. here is my ossec.conf file config:

<ossec_config>
  <global>
    <email_notification>no</email_notification>
    <logall>yes</logall>
  </global>

<global>
    <allow_list>127.0.0.1</allow_list>
    <allow_list>::1</allow_list>
    <allow_list>localhost.localdomain</allow_list>
    <allow_list>127.0.0.53</allow_list>
    <allow_list>172.16.1.0/24</allow_list>
  </global>

  <remote>
    <connection>syslog</connection>
    <allowed-ips>172.16.1.0/24</allowed-ips>
    <port>514</port>
    <protocol>udp</protocol>
  </remote>

**Comment by ddpbsd** [comment]
```
<ossec_config>
  <global>
    <email_notification>no</email_notification>
    <logall>yes</logall>
  </global>

<global>
    <allow_list>127.0.0.1</allow_list>
    <allow_list>::1</allow_list>
    <allow_list>localhost.localdomain</allow_list>
    <allow_list>127.0.0.53</allow_list>
    <allow_list>172.16.1.0/24</allow_list>
  </global>

  <remote>
    <connection>syslog</connection>
    <allowed-ips>172.16.1.0/24</allowed-ips>
    <port>514</port>
    <protocol>udp</protocol>
  </remote>
```

**Comment by ddpbsd** [comment]
Any errors in the ossec.log on the server?
You could try setting [local_ip](https://ossec-docs.readthedocs.io/en/latest/docs/syntax/head_ossec_config.remote.html#element-local_ip) in the `<remote>` section.

**Comment by marliyev** [comment]
Hi,
Thanx for reply, my config is exactly the same as you mentioned. but port 514 listening only on ipv6.
i have tried to change from udp to tcp, from 514 to any other port, still getting the same issue. only ipv6. no ipv4.

**Comment by ddpbsd** [comment]
Oh, I was just reposting your config in a readable format.
Did you try the local_ip option?
Any errors in the ossec.log on the server?

**Comment by ddpbsd** [comment]
Just added this configuration to my ossec server's ossec.conf:
```
  <remote>
    <connection>syslog</connection>
    <protocol>udp</protocol>
    <port>514</port>
    <allowed-ips>192.168.18.1</allowed-ips>
    <allowed-ips>192.168.17.9</allowed-ips>
  </remote>
```

I don't have ipv6 setup, and this is what netstat looks like:
```
root@ossec:~# netstat -pan | grep remoted
udp6       0      0 :::1514                 :::*                                1932/ossec-remoted  
udp6       0      0 :::514                  :::*                                1933/ossec-remoted  
unix  3      [ ]         DGRAM                    292281   1932/ossec-remoted   /queue/alerts/ar
unix  2      [ ]         DGRAM                    292295   1932/ossec-remoted   
unix  2      [ ]         DGRAM                    292283   1933/ossec-remoted
```

So "only listening on ipv6" isn't quite correct. I turned on the logall option and I see the logs from one of those hosts in the archives.log file (the other host isn't sending logs for some reason).
So I guess, now I'm wondering why you think the logs aren't getting to OSSEC?

**Comment by marliyev** [comment]
Hi,
yes i have tried to use local ip, netstat looks like this:

udp6       0      0 172.16.1.1:514          :::*

but its udp6, am still not getting alerts. 

ossec.log shows me that 514 allowed on ipv6:

2020/04/11 22:26:49 IPv6: ::ffff:172.16.1.1 on port 514
2020/04/11 22:26:49 Socket bound for IPv6: ::ffff:172.16.1.1 on port 514

**Comment by ddpbsd** [comment]
Turn on the logall option and check archives.log to see if you're getting the log messages.

**Comment by marliyev** [comment]
logall option is enabled, no logs from network devices in archives, in alerts, nowhere. tcpdump shows me that am receiving logs from devices. i dont want downgrade ossec to check if version issue but no idea how to resolve this issue.

**Comment by ddpbsd** [comment]
Try running ossec-remoted in debug mode (`/var/ossec/bin/ossec-remoted -d`) and check for errors in the ossec.log file. Also, consider trying individual IPs instead of CIDRs in the allowed-ips field.

**Comment by marliyev** [comment]
Hi,

Below debug, i see ERROR: Unable to Bind port '514'

2020/04/18 23:15:23 ossec-remoted: DEBUG: Starting ...
2020/04/18 22:15:23 ossec-remoted: INFO: Started (pid: 2337).
2020/04/18 22:15:23 ossec-remoted: DEBUG: Forking remoted: '0'.
2020/04/18 22:15:23 ossec-remoted: Remote syslog allowed from: '172.16.1.2'
2020/04/18 22:15:23 IPv6: ::ffff:172.16.1.1 on port 514
2020/04/18 22:15:23 Request to allocate and bind sockets failed.
2020/04/18 22:15:23 ossec-remoted(1206): ERROR: Unable to Bind port '514'
2020/04/18 22:15:23 ossec-remoted: DEBUG: Forking remoted: '1'.
2020/04/18 22:15:23 IPv6: :: on port 1514
2020/04/18 22:15:23 Socket bound for IPv6: :: on port 1514
2020/04/18 22:15:23 ossec-remoted: INFO: Started (pid: 2339).
2020/04/18 22:15:23 ossec-remoted: DEBUG: Running manager_init
2020/04/18 22:15:23 ossec-remoted: INFO: (unix_domain) Maximum send buffer set to: '212992'.
2020/04/18 22:15:23 ossec-remoted(4111): INFO: Maximum number of agents allowed: '16384'.
2020/04/18 22:15:23 ossec-remoted(1410): INFO: Reading authentication keys file.
2020/04/18 22:15:23 ossec-remoted(1402): ERROR: Authentication key file '/etc/client.keys' not found.
2020/04/18 22:15:23 ossec-remoted(1751): ERROR: File client.keys not found or empty.
2020/04/18 23:15:45 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2020/04/18 23:15:45 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/messages'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/authlog'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/secure'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/xferlog'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/maillog'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/www/logs/access_log'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/www/logs/error_log'.
2020/04/18 23:16:54 ossec-logcollector(1904): INFO: File not available, ignoring it: '/var/log/exim_mainlog'.

**Comment by ddpbsd** [comment]
Is something else listening on 514 already, syslogd perhaps?

**Comment by marliyev** [comment]
no, only ossec configured for syslog and for port 514. netstat shows port 514 only for ossec on ipv6

**Comment by marliyev** [comment]
root@ubuntu:~# netstat -pan | grep 514
udp6       0      0 172.16.1.1:514          :::*                                1339/ossec-remoted

**Comment by ddpbsd** [comment]
Did you stop ossec-remoted before you tried starting it again? You need to stop it first so the ports are available.

**Comment by marliyev** [comment]
just stopped and started again ossec-remoted and ossec-control, still same

**Comment by ddpbsd** [comment]
Still same? Same as what? You stopped ossec-remoted (`pkill ossec-remoted`), and started it back up in debug mode (`/var/ossec/bin/ossec-remoted -d`) and it still complains about not being able to bind to the port?

**Comment by marliyev** [comment]
not error but still udp6:

2020/04/19 08:54:00 ossec-remoted: DEBUG: Starting ...
2020/04/19 07:54:00 ossec-remoted: INFO: Started (pid: 2046).
2020/04/19 07:54:00 ossec-remoted: DEBUG: Forking remoted: '1'.
2020/04/19 07:54:00 IPv6: :: on port 1514
2020/04/19 07:54:00 Socket bound for IPv6: :: on port 1514
2020/04/19 07:54:00 ossec-remoted: INFO: Started (pid: 2048).
2020/04/19 07:54:00 ossec-remoted: DEBUG: Forking remoted: '0'.
2020/04/19 07:54:00 ossec-remoted: Remote syslog allowed from: '172.16.1.2'
2020/04/19 07:54:00 IPv6: ::ffff:172.16.1.1 on port 514
2020/04/19 07:54:00 Socket bound for IPv6: ::ffff:172.16.1.1 on port 514
2020/04/19 07:54:00 ossec-remoted: INFO: Started (pid: 2047).
2020/04/19 07:54:00 ossec-remoted: INFO: (unix_domain) Maximum send buffer set to: '212992'.
2020/04/19 07:54:00 ossec-remoted: DEBUG: Running manager_init
2020/04/19 07:54:00 ossec-remoted: INFO: (unix_domain) Maximum send buffer set to: '212992'.
2020/04/19 07:54:00 ossec-remoted(4111): INFO: Maximum number of agents allowed: '16384'.
2020/04/19 07:54:00 ossec-remoted(1410): INFO: Reading authentication keys file.
2020/04/19 07:54:00 ossec-remoted(1402): ERROR: Authentication key file '/etc/client.keys' not found.
2020/04/19 07:54:00 ossec-remoted(1751): ERROR: File client.keys not found or empty.
2020/04/19 08:54:20 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2020/04/19 08:54:20 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).

**Comment by marliyev** [comment]
@ddpbsd from your past outputs i see that in your system ossec unable to bind port 514, only to ipv6, seems to be this issue for everyone who using ossec without agent. am not tried to use ossec with agent cause i have only network devices, no machines. today i tried ossec in different systems, ubuntu 18, redhat, fedora, suse, in all machines same issue, ossec syslog on port 514 not functioning, only for ipv6.

**Comment by ddpbsd** [comment]
@marliyev Mine worked just fine, that's just how it shows up in netstat (probably because it binds both ipv4 and 6). I think worrying about the ipv6 representation there is a red herring. You could try disabling ipv6 on the system if you really want to.
Try adding an agent (even a fake one). I haven't tried without an agent.

**Comment by marliyev** [comment]
are you receiving logs from network devices, router switch, firewall?

**Comment by ddpbsd** [comment]
From a unix host, yes. Haven’t tried anything else yet.

**Comment by marliyev** [comment]
with agent no problem, port 1514 is functioning, the issue is ossec as syslog server on port 514. not receiving logs from network devices.

**Comment by ddpbsd** [comment]
I understand. I forwarded syslog from that host to the ossec server. An ossec agent wasn’t involved.

**Comment by marliyev** [comment]
understand. very strange. no ideas

**Comment by ddpbsd** [comment]
Just figured out why my firewall wasn’t sending logs, and it wasn’t ossec’s fault. So I’m successfully getting syslog messages from an edgerouter max into archives.log

**Comment by marliyev** [comment]
how to separate log destination for each device?

**Comment by ddpbsd** [comment]
That’s not really how it works. Logall just shoves everything into archives.log. You can then use those (minus the header ossec adds) to write rules for alerts. But those aren’t logged per host, just to alerts.log.

**Comment by marliyev** [comment]
@ddpbsd thank you for help
