### ISSUE TITLE
Unable to run ossec-syscheckd and ossec-logcollector

### ISSUE THREAD

**Issue by mandraid** [ossec/ossec-hids#1866]
I am running Ubuntu 16 desktop agent, the latest version of ossec as of today.
I get these errors when running as root:
` /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v3.6.0...
Deleting PID file '/var/ossec/var/run/ossec-logcollector-16026.pid' not used...
Deleting PID file '/var/ossec/var/run/ossec-agentd-16021.pid' not used...
ossec-execd already running...
ossec-agentd already running...
Started ossec-logcollector...
2020/04/14 20:30:30 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2020/04/14 20:30:30 rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2020/04/14 20:30:38 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2020/04/14 20:30:38 rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2020/04/14 20:30:51 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2020/04/14 20:30:51 rootcheck(1211): ERROR: Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
ossec-syscheckd did not start
`
I tried stop then start, but get the same thing.
` /var/ossec/bin/ossec-control status
ossec-logcollector: Process 16251 not used by ossec, removing ..
ossec-logcollector not running...
ossec-syscheckd not running...
ossec-agentd is running...
ossec-execd is running...
`

**Comment by ddpbsd** [comment]
How did you install OSSEC?
Stop all of the processes. Make sure they're stopped. Then start them up. Check the ossec.log file for errors.
If it's still having trouble, try starting them individually with the `-d` flag. That might provide more information.

**Comment by atomicturtle** [comment]
Closed as resolved/No response
