### ISSUE TITLE
Facing Issue make: 1254-055 Dependency line needs colon or double colon operator when trying to install Ossec 3.6.0 on AIX 7.2

### ISSUE THREAD

**Issue by fawazmohmd** [ossec/ossec-hids#1870]
Dears,

When Trying to install Ossec 3.6.0 onAIX 7.2 facing the below error. Please help me on the same.

"Makefile", line 714: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 715: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 717: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 718: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 722: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 725: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 729: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 762: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 768: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 777: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 785: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 786: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 816: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 822: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 826: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 912: make: 1254-055 Dependency line needs colon or double colon operator.
"Makeile", line 918: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1006: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1008: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1010: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1261: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1264: make: 1254-055 Dependency line needs colon or double colon operator.
make: 1254-058 Fatal errors encountered -- cannot continue.

Regards,
Fawaz

**Comment by ddpbsd** [comment]
Are you using gnu make? It pretty much requires gnu make to work.

**Comment by fawazmohmd** [comment]
Yes i have already installed GNU make 4.2.1

**Comment by ddpbsd** [comment]
I don't know enough about gnu make versions, but I'm guessing the Make isn't picking it up. I don't have access to AIX to do any testing either.

**Comment by atomicturtle** [comment]
Closed as resolved/no response
