### ISSUE TITLE
issue with os_net/os_net.c on solaris

### ISSUE THREAD

**Issue by owlmind** [ossec/ossec-hids#1877]
Hello,

Ossec wouldn't compile on Solaris 114. with this error. 

os_net/os_net.c: In function ‘OS_DecodeSockaddr’:
os_net/os_net.c:749:49: error: ‘struct sockaddr’ has no member named ‘sa_len’
  749 |     rc = getnameinfo ((struct sockaddr *) sa, sa->sa_len, ipaddr,
      |                                                 ^~
gmake: *** [Makefile:838: os_net/os_net.o] Error 1

Had to edit the file src/os_net/os_net.c and replace the sa->sa_len  with **sizeof (sa)** under the comment,  BSD systems require the value in sa->sa_len or error 4 occurs.

**Comment by ddpbsd** [comment]
Just submitted pull request #1878 which should hopefully solve this.

**Comment by owlmind** [comment]
Tested it. Works fine.
Thank you.

**Comment by ddpbsd** [comment]
Thanks for testing!
