### ISSUE TITLE
OSSEC dfoesn't seem to process local_rules.xml

### ISSUE THREAD

**Issue by prosinger** [ossec/ossec-hids#1879]
I got a simple custom rule in /var/ossec/etc/rules/local_rules.xml:

`<group name="web,appsec,attack,"> <rule frequency="8" id="31533" overwrite="yes" level="9" timeframe="20"> <if_matched_sid>31530</if_matched_sid> <same_source_ip/> <description>High amount of POST requests in a small period of time (likely bot).</description> <group>pci_dss_6.5,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SA.11,nist_800_53_SI.4,</group> </rule> 
</group>`

What it should do is to change the alert level of the original rule to "9", but as per ossec-logtest -v it doesn't process local_rules.xml at all.
Any idea?

**Comment by alberpilot** [comment]
Hello @prosinger 

  Sorry for the late response. I copied your custom rule and use it in my lab (Wazuh manager v3.13.1) and looks good. If I run `ossec-logtest -ddd` I get: 

```
2020/09/09 10:24:22 ossec-testrule[1483] rules.c:2303 at printRuleinfo(): DEBUG: 3 : rule:31533, level 9, timeout: 0
```

which I understand as correct. In addition to this, I get:
```
2020/09/09 10:24:22 ossec-testrule[1483] testrule.c:304 at main(): DEBUG: Reading rules file: 'etc/rules/local_rules.xml'
2020/09/09 10:24:22 ossec-testrule[1483] rules.c:212 at Rules_OP_ReadRules(): DEBUG: etc/rules/local_rules.xml is the rulefile
```

which means that the local_rules are being read. 

When you paste your log, do the log generate an alert? Could you please share the logtest output?

Regards, 
Alberto R

**Comment by prosinger** [comment]
It was some exclusion I made in the config file I think. It was a while ago :)
