### ISSUE TITLE
Unable to build OSSEC 3.6.0 on AIX 7.2

### ISSUE THREAD

**Issue by moosa-aslam** [ossec/ossec-hids#1881]
I am trying to build OSSEC 3.6.0 but unable to do so any leads will be helpful.
running make --version command gives me this 
**make --version
make: Not a recognized flag: -
usage: make [-einqrst] [-k|-S] [-d[A|adg[1|2]mstv]] [-D variable] [-f makefile] [-j [jobs]] [variable=value ...] [target ...]**

**# which make
/usr/bin/make**

"Makefile", line 678: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 700: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 702: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 704: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 707: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 709: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 712: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 714: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 715: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 717: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 718: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 722: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 725: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 729: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 762: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 768: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 777: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 785: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 786: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 816: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 822: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 826: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 912: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 918: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1006: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1008: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1010: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1261: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 1264: make: 1254-055 Dependency line needs colon or double colon operator.
make: 1254-058 Fatal errors encountered -- cannot continue.

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by ddpbsd** [comment]
You need GNU make.

**Comment by atomicturtle** [comment]
Closed as resolved/no response
