### ISSUE TITLE
decoder nginx log

### ISSUE THREAD

**Issue by Richard-Tang** [ossec/ossec-hids#1883]
```txt
10.1.2.1 - - [12/Jun/2020:15:44:37 +0800] "GET /favicon.ico HTTP/1.1" 404 555 "http://10.1.2.20/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
```

```xml
<decoder name="web-nginx-accesslog">
  <parent>web-accesslog</parent>
  <regex>^(\d+.\d+.\d+.\d+) \w+ \w+ [\S+ \S\d+] "(\w+) (\S+) (\S+)" (\d+) \d+ </regex>
  <regex>"\S+" "(\.+)"</regex>
  <order>srcip, action, url, protocol, status, extra_data</order>
</decoder>
```

How to remove "

![image](https://user-images.githubusercontent.com/30547741/84454391-00ae2380-ac8d-11ea-91e4-b00306a8e054.png)

**Comment by ddpbsd** [comment]
Which version of OSSEC are you using? Here's what I get:
```
**Phase 1: Completed pre-decoding.
       full event: '10.1.2.1 - - [12/Jun/2020:15:44:37 +0800] "GET /favicon.ico HTTP/1.1" 404 555 "http://10.1.2.20/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"'
       hostname: 'arrakis'
       program_name: '(null)'
       log: '10.1.2.1 - - [12/Jun/2020:15:44:37 +0800] "GET /favicon.ico HTTP/1.1" 404 555 "http://10.1.2.20/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip: '10.1.2.1'
       action: 'GET'
       url: '/favicon.ico'
       proto: 'HTTP/1.1'
       status: '404'
       extra_data: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
```

**Comment by Richard-Tang** [comment]
> 您正在使用哪个OSSEC版本？这是我得到的：
> 
> ```
> **Phase 1: Completed pre-decoding.
>        full event: '10.1.2.1 - - [12/Jun/2020:15:44:37 +0800] "GET /favicon.ico HTTP/1.1" 404 555 "http://10.1.2.20/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"'
>        hostname: 'arrakis'
>        program_name: '(null)'
>        log: '10.1.2.1 - - [12/Jun/2020:15:44:37 +0800] "GET /favicon.ico HTTP/1.1" 404 555 "http://10.1.2.20/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"'
> 
> **Phase 2: Completed decoding.
>        decoder: 'web-accesslog'
>        srcip: '10.1.2.1'
>        action: 'GET'
>        url: '/favicon.ico'
>        proto: 'HTTP/1.1'
>        status: '404'
>        extra_data: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
> ```

I used 2.8.1

**Comment by ddpbsd** [comment]
2.8.1 is super old. You could try updating just the nginx decoders from a more recent release to see if that helps.

**Comment by Richard-Tang** [comment]
> 2.8.1 is super old. You could try updating just the nginx decoders from a more recent release to see if that helps.

For some special reasons, I can only use this version for now!
