### ISSUE TITLE
Problem with OSSEC not displaying file changes.

### ISSUE THREAD

**Issue by Flaspaw** [ossec/ossec-hids#1884]
Hi, im new to ossec and i created a rule at `/var/ossec/rules/local_rules.xml` to check file creation:

`
  <rule id="554" level="10" overwrite="yes">
    <category>ossec</category>
    <decoded_as>syscheck_new_entry</decoded_as>
    <description>File added to the system.</description>
    <group>syscheck,</group>
  </rule>
`

I placed the rules to monitor at Desktop folder but it does not show any changes be it file creation of checksum integrity to the logs. The only logs they show would be an escalation of privileges to root or when OSSEC starts. May I know what might be the problem here? Im running a local version of OSSEC and the services are running fine.
![Capture2](https://user-images.githubusercontent.com/41560026/84512452-99c75380-acfa-11ea-8036-7ef3956e7c94.PNG)

**Comment by ddpbsd** [comment]
Did you add the directories to your ossec.conf's syscheck section?
Are the checksums for the files in `/var/ossec/queue/syscheck/syscheck`?

**Comment by weilun513** [comment]
> Did you add the directories to your ossec.conf's syscheck section?
> Are the checksums for the files in `/var/ossec/queue/syscheck/syscheck`?

Hi, sorry for the late reply. Yes i did add directories in my config file.
![ossec_git](https://user-images.githubusercontent.com/41560026/85218737-9f462d00-b3cf-11ea-83ac-6278d85a234a.PNG)

In `/var/ossec/queue/syscheck/syscheck` there are checksums inside but no the ones that i added, like changes to file **active.txt** or newly added desktop files.

Also, in `/var/ossec/logs/ossec.log`, it keeps showing that real time file monitoring is not started for some reason, is this normal?
`ossec-syscheckd: INFO: Initializing real time file monitoring (not started).`

**Comment by ddpbsd** [comment]
`/home/ubuntu/Downloads/active.txt` should be picked up by the `/home/ubuntu/Downloads` entry.
After adding the `<directories>` entries to the ossec.conf did you restart the OSSEC processes? Try restarting syscheckd in debug mode (`pkill ossec-syscheckd && /var/osec/bin/ossec-syscheckd -d`) and look for log messages about the added directories.

**Comment by weilun513** [comment]
> `/home/ubuntu/Downloads/active.txt` should be picked up by the `/home/ubuntu/Downloads` entry.
> After adding the `<directories>` entries to the ossec.conf did you restart the OSSEC processes? Try restarting syscheckd in debug mode (`pkill ossec-syscheckd && /var/osec/bin/ossec-syscheckd -d`) and look for log messages about the added directories.

Alright I'll try it out and see the results

**Comment by atomicturtle** [comment]
Closed/No response
