### ISSUE TITLE
OSSEC implementation on AIX 7.1 server

### ISSUE THREAD

**Issue by adarshhirenallur** [ossec/ossec-hids#1885]
Hi All,
I am unable to install OSSEC File integrity monitoring on AIX 7.1 server and Oracle Linux 6.9.
F2.9.3 
![OSSEC AIX7 1_A](https://user-images.githubusercontent.com/66686925/85033763-f31dff80-b19e-11ea-88da-aff01e0128fb.PNG)
![OSSEC AIX7 1_B](https://user-images.githubusercontent.com/66686925/85033772-f44f2c80-b19e-11ea-94ef-d85ab8ef9c9c.PNG)
![OSSEC AIX7 1_C](https://user-images.githubusercontent.com/66686925/85033774-f4e7c300-b19e-11ea-8997-5bef5b37d2a3.PNG)
![OSSEC AIX7 1_D](https://user-images.githubusercontent.com/66686925/85033775-f5805980-b19e-11ea-9b99-290b5cfe9660.PNG)
![OSSEC AIX7 1_E](https://user-images.githubusercontent.com/66686925/85033780-f618f000-b19e-11ea-8ff4-ffaff55c7849.PNG)

Please provide some feasible workarounds.

Thanks.
Adarsh Hirenallur

**Comment by ddpbsd** [comment]
Try GNU make

**Comment by adarshhirenallur** [comment]
> Try GNU make

Mr. Dan Parriott can you please elaborate your input. Sorry I am at the beginner level. Appreciate your help.

**Comment by ddpbsd** [comment]
The OSSEC compilation process requires [GNU Make](https://www.gnu.org/software/make/). Other make programs may work, but probably will not.

**Comment by atomicturtle** [comment]
Closed / No response
