### ISSUE TITLE
!! Fedora 32 package broken & mirror list missing !!

### ISSUE THREAD

**Issue by agharta** [ossec/ossec-hids#1895]
Hi all, a big problem.
Mirror list does not contains Fedora 32 mirrors!
See https://updates.atomicorp.com/channels/mirrorlist/ossec/ it stops on 31

Another crashing problem: package https://updates.atomicorp.com/channels/ossec/fedora/32/x86_64/RPMS/atomic-release-1.0-21.fc32.art.noarch.rpm is totally broken!
If You open the rpm and see the atomic.repo file, you'll see that it was builded upon CentOS repo!!!
So, a CentOS 32 release does not exists!!!!!

Please, can You repair F32 broken rpm? And, can You release a F32 mirror list?

Best regards, 
Agharta

**Comment by atomicturtle** [comment]
Thanks for the report, this has been resolved in the installer version 5.0.1. Please remove the atomic-release package, and re-run the installer:

wget -q -O - https://updates.atomicorp.com/installers/atomic |sh
