### ISSUE TITLE
How to check the checksum of an installed agent?

### ISSUE THREAD

**Issue by Crankinator** [ossec/ossec-hids#1896]
Unsure if this belongs here, and if it doesn't please close out this issue.

I am trying to confirm how we would be able to check the hashes of an installed agent (ossec-agent.exe) to confirm it is known-good.

**Comment by RedCedarForge** [comment]
Hello!
Sorry for the late response.
There are a couple of ways of approaching it;

Ossec packages are signed with GPG keys, so you can verify integrity that way. Look under the sub-heading for GPG here:
https://www.ossec.net/downloads/

The other (more roundabout) way is to download an agent from that link and check the hash using md5sum or sha<hash size>sum on Linux and compare that hash to one of the installed agent. 
You can also do that on Windows using Powershell modules.

**Comment by atomicturtle** [comment]
Closed/No response
