### ISSUE TITLE
OSSEC HIDS installation on  Red Hat Enterprise Linux Server release 5.7 fails

### ISSUE THREAD

**Issue by Augusta-Ada** [ossec/ossec-hids#1900]
Hi 

I am installing ossec hids agent on Red Hat Enterprise Linux Server release 5.7 and it fails with the message error trying to exec 'cc1': execvp: No such file or directory. I installed gcc  4.1.2 20080704 using rpm -ivf command

Kindly assist

**Comment by atomicturtle** [comment]
This probably means the Development Tools group wasnt installed on the system. Given that EL5 is really really EOL, Im marking this up for closed due to EOL. If you still need EL5 support, you might want to follow up with us in slack.
