### ISSUE TITLE
Binary packages for Ubuntu Server 20.04 LTS

### ISSUE THREAD

**Issue by noahbailey** [ossec/ossec-hids#1902]
Hey all, wondering if we could create a binary distro of v3.6.0 for Ubuntu 20.04 LTS, codename 'focal'. 

I've been running a self-compiled install for a few months on the handful of boxes that have already been upgraded to the new LTS distribution, but it would be much appreciated to have a simpler way to install.

**Comment by atomicturtle** [comment]
Packages are out now, thanks!
