### ISSUE TITLE
Recommended exclusion rule for Cisco AMP

### ISSUE THREAD

**Issue by shaunthompson709** [ossec/ossec-hids#1903]
Hi, We'd like to add an exclusion rule to our newly deployed Cisco AMP for the HIDs deployed to our servers, is there a recommedation as to what should be included in the exclusion list? (for exmaple file path, name of exe etc)

**Comment by atomicturtle** [comment]
I'm not familiar with it, but I'd be happy to help you figure it out and come up with rules/decoders for it. If you'd like we can coordinate on ossec.slack.com. You can email us for an invite at: slack@ossec.net

**Comment by ddpbsd** [comment]
@shaunthompson709 I guess it depends on what AMP is concerned with (I haven't looked into it yet). On linux systems `/var/ossec/bin` is where most of the binaries are kept, and `C:\program files (x86)\ossec-agent` on Windows. 
If you post a little about the capabilities of AMP that you're concerned with (as far as ossec interference goes), I might be able to limit that a bit better.

**Comment by atomicturtle** [comment]
Closing with no-response
