### ISSUE TITLE
OSSEC Version 3.6.0 Installation in Kali Linux

### ISSUE THREAD

**Issue by Mai-Kassem** [ossec/ossec-hids#1908]
Hi guys,
I follow the installation guide and I keep getting this error ..
Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -c external/cJSON/cJSON.c -o external/cJSON/cJSON.o
ar -crs libcJSON.a external/cJSON/cJSON.o
ranlib libcJSON.a
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/sendmail.c -o os_maild/sendmail.o
os_maild/sendmail.c:12:10: fatal error: event.h: No such file or directory
   12 | #include <event.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:926: os_maild/sendmail.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

Any ideas on what can be done ..

**Comment by ddpbsd** [comment]
Install the libevent dev package.

**Comment by Mai-Kassem** [comment]
worked, thank you =)
