### ISSUE TITLE
Ossec active-responce does not respect alow_list when srcip = dns name

### ISSUE THREAD

**Issue by varuzam** [ossec/ossec-hids#1909]
Hi
I use ossec 3.6.0. in my config: `<allow_list>10.0.0.0/8</allow_list>`
OSSEC does not resolve hostname to ip and in case of such log ` sshd[2498]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=server.local.net  user=root`, where server.local.net has ip 10.0.0.5, active-responce blocks this host.

**Comment by ddpbsd** [comment]
That's true.

**Comment by atomicturtle** [comment]
Yes, this is intentional. For the same reason hostnames arent used in firewall rules, the lookup only happens with the application starts. If the name changes later, it won't be accurately reflected
