### ISSUE TITLE
Debian buster apt-get error File has unexpected size (727936 != 724972)

### ISSUE THREAD

**Issue by faberge-eggs** [ossec/ossec-hids#1911]
```
root@ip-10-111-51-217:/home/admin# apt-get install ossec-hids-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libopts25
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  ossec-hids-server
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 725 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://updates.atomicorp.com/channels/atomic/debian buster/main amd64 ossec-hids-server amd64 3.6.0-14066buster [725 kB]
Err:1 https://updates.atomicorp.com/channels/atomic/debian buster/main amd64 ossec-hids-server amd64 3.6.0-14066buster
  File has unexpected size (727936 != 724972). Mirror sync in progress? [IP: 51.161.13.101 443]
  Hashes of expected file:
   - SHA256:186427ccef89a61d513186314f3e5bb6d3c1916a1ee0893c1fd0354d7721cb7b
   - SHA1:acbea4d4e77d2dfe9690c8678aacb548a60aea42 [weak]
   - MD5Sum:2aed04879d9403ab8c54e1a9306acc08 [weak]
   - Filesize:724972 [weak]
E: Failed to fetch https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-server/ossec-hids-server_3.6.0-14066buster_amd64.deb  File has unexpected size (727936 != 724972). Mirror sync in progress? [IP: 51.161.13.101 443]
   Hashes of expected file:
    - SHA256:186427ccef89a61d513186314f3e5bb6d3c1916a1ee0893c1fd0354d7721cb7b
    - SHA1:acbea4d4e77d2dfe9690c8678aacb548a60aea42 [weak]
    - MD5Sum:2aed04879d9403ab8c54e1a9306acc08 [weak]
    - Filesize:724972 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by localhorst-org** [comment]
same with agent

:~# apt-get install ossec-hids-agent
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libevent-2.1-6
Die folgenden NEUEN Pakete werden installiert:
  libevent-2.1-6 ossec-hids-agent
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 449 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 2.872 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
Holen:1 http://ftp2.de.debian.org/debian buster/main amd64 libevent-2.1-6 amd64 2.1.8-stable-4 [177 kB]
Holen:2 https://updates.atomicorp.com/channels/atomic/debian buster/main amd64 ossec-hids-agent amd64 3.6.0-14066buster [272 kB]
Fehl:2 https://updates.atomicorp.com/channels/atomic/debian buster/main amd64 ossec-hids-agent amd64 3.6.0-14066buster
  Datei hat eine unerwartete Größe (271972 != 272348). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 51.161.13.101 443]
  Hashes of expected file:
   - SHA256:47fa27d2b0cddc911578b1873c07289d720013a1be7ebe066fb4e9a4744e2e9d
   - SHA1:befcc1a8a715d873f4f883babf6568b7d45aedcf [weak]
   - MD5Sum:a80e05c33c15f6f840f409197928f19a [weak]
   - Filesize:272348 [weak]
Es wurden 177 kB in 1 s geholt (132 kB/s).
E: Fehlschlag beim Holen von https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-agent/ossec-hids-agent_3.6.0-14066buster_amd64.deb Datei hat eine unerwartete Größe (271972 != 272348). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 51.161.13.101 443]
   Hashes of expected file:
    - SHA256:47fa27d2b0cddc911578b1873c07289d720013a1be7ebe066fb4e9a4744e2e9d
    - SHA1:befcc1a8a715d873f4f883babf6568b7d45aedcf [weak]
    - MD5Sum:a80e05c33c15f6f840f409197928f19a [weak]
    - Filesize:272348 [weak]
E: Einige Archive konnten nicht heruntergeladen werden; vielleicht »apt-get update« ausführen oder mit »--fix-missing« probieren?

trial with wget from diffrent location

:~$ wget https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-agent/ossec-hids-agent_3.6.0-14066buster_amd64.deb

:~$ sha256sum ossec-hids-agent_3.6.0-14066buster_amd64.deb
8c58c10305f971d4118727cdaf854f225541b124d8a363d38ac1e46a4671f9ef  ossec-hids-agent_3.6.0-14066buster_amd64.deb

https://updates.atomicorp.com/channels/atomic/debian/dists/buster/main/binary-amd64/Packages
[...]
Section: admin
Filename: pool/main/o/ossec-hids-agent/ossec-hids-agent_3.6.0-14066buster_amd64.deb
Size: 272348
SHA256: 47fa27d2b0cddc911578b1873c07289d720013a1be7ebe066fb4e9a4744e2e9d
[...]

**Comment by pauldsmyth** [comment]
I have the same issue building a docker container:

E: Failed to fetch https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-server/ossec-hids-server_3.6.0-14066buster_amd64.deb  File has unexpected size (727936 != 724972). Mirror sync in progress? [IP: 51.161.13.101 443]
   Hashes of expected file:
    - SHA256:186427ccef89a61d513186314f3e5bb6d3c1916a1ee0893c1fd0354d7721cb7b
    - SHA1:acbea4d4e77d2dfe9690c8678aacb548a60aea42 [weak]
    - MD5Sum:2aed04879d9403ab8c54e1a9306acc08 [weak]
    - Filesize:724972 [weak

**Comment by hcw2016** [comment]
All, 

Can you all try the following: 

apt update (if you have already put the atomic repo on your system). Otherwise, run wget -q -O - https://updates.atomicorp.com/installers/atomic | bash and then proceed with the apt update 

apt install -y osssec-hids-server

**Comment by localhorst-org** [comment]
hi hcw2016,

looks like good for me with the atomic repo on the system.

thx!

**Comment by pauldsmyth** [comment]
Confirmed, container built sucessfully. Cheers. My issue is resolved
