### ISSUE TITLE
Why does ossec-hids-server need make?

### ISSUE THREAD

**Issue by erhan-** [ossec/ossec-hids#1915]
Hello ossec team,

I have the following question: 
Why does ossec-hids-server need make?

Thanks for taking your time!

**Comment by atomicturtle** [comment]
The autoprovreq setting can be pretty overzealous in dependency identification. Its probably because one of the contrib (my guess: selinux, just a guess though) components references it

**Comment by erhan-** [comment]
I have made an installation procedure for myself which ignores make and it works as well. But I mostly use it for the integrity checking functionality.
