### ISSUE TITLE
agentless monitoring: "File added to the system" for every file, each time the scan runs

### ISSUE THREAD

**Issue by dummypunter** [ossec/ossec-hids#1916]
Every time the agentless monitoring scan runs on a server, I get "File added to the system" for every file.

Sep 30, 2020 @ 14:12:12.824  syscheck.**sha1_after:d4c99e575e7cd913a804b6ce001db7bd3f2760d7** agentless.script:linux_check syscheck.path:**/usr/sbin/ipmievd** syscheck.size_after:500,792 syscheck.uid_after:0 syscheck.gid_after:0 syscheck.perm_after:001363 syscheck.event:added syscheck.md5_after:xxx input.type:log agent.hostname:wazuh2 agent.name:wazuh2 agent.id:4e8074ec-742c-45d9-a3e5-fba8a0c78c1e agent.type:filebeat agent.ephemeral_id:dccde761-660e-4cf9-9495-6d5188c13a1a agent.version:7.9.2 manager.name:wazuh2 agentless.host:172.xx.xx.xx agentless.user:ossec rule.firedtimes:13,426 rule.mail:false rule.level:5 rule.pci_dss:11.5 rule.hipaa:164.312.c.1, 164.312.c.2 rule.tsc:PI1.4, PI1.5, CC6.1, CC6.8, CC7.2, CC7.3 rule.description:File added to the system. rule.groups:ossec, syscheck rule.id:554 rule.nist_800_53:SI.7 rule.gpg13:4.11 rule.gdpr:II_5.1.f location:syscheck id:1601464332.30665576 decoder.name:syscheck_new_entry full_log:File '/usr/sbin/ipmievd' was added. timestamp:Sep 30, 2020 @ 14:12:12.824 _id:KIa23nQBwYyqusphe9Y9 _type:_doc _index:wazuh-alerts-3.x-2020.09.30 _score: -

Sep 30, 2020 @ 13:45:12.197  syscheck.**sha1_after:d4c99e575e7cd913a804b6ce001db7bd3f2760d7** agentless.script:linux_check syscheck.path:**/usr/sbin/ipmievd** syscheck.size_after:500,792 syscheck.uid_after:0 syscheck.gid_after:0 syscheck.perm_after:001363 syscheck.event:added syscheck.md5_after:xxx input.type:log agent.hostname:wazuh2 agent.name:wazuh2 agent.id:4e8074ec-742c-45d9-a3e5-fba8a0c78c1e agent.type:filebeat agent.ephemeral_id:dccde761-660e-4cf9-9495-6d5188c13a1a agent.version:7.9.2 manager.name:wazuh2 agentless.host:172.xx.xx.xx agentless.user:ossec rule.firedtimes:29,767 rule.mail:false rule.level:5 rule.pci_dss:11.5 rule.hipaa:164.312.c.1, 164.312.c.2 rule.tsc:PI1.4, PI1.5, CC6.1, CC6.8, CC7.2, CC7.3 rule.description:File added to the system. rule.groups:ossec, syscheck rule.id:554 rule.nist_800_53:SI.7 rule.gpg13:4.11 rule.gdpr:II_5.1.f location:syscheck

**Comment by ddpbsd** [comment]
Is this from OSSEC or Wazuh?

**Comment by dummypunter** [comment]
This is from both a fresh installation of wazuh 3.13.2-1 and an upgraded one to 3.13.2-1.

**Comment by atomicturtle** [comment]
For what its worth, I tested this on OSSEC 3.6.0 and was not able to repeat the condition. For reference, my agentless target was AIX 7.1
