### ISSUE TITLE
ossec+postfix not sending mail - Mail from not accepted by server

### ISSUE THREAD

**Issue by marliyev** [ossec/ossec-hids#1928]
hi, ossec-hids-server 3.6.0-14954focal amd64 installed on ubuntu 20.04, having also properly running postfix on same machine. trying to set up mail sending on ossec but getting below error:

ossec-maild: DEBUG: Running OS_Sendmail()
os_sendmail(1764): WARN: Mail from not accepted by server
ossec-maild(1223): ERROR: Error Sending email to 127.0.0.1 (smtp server)

ossec config:

<ossec_config>
  <global>
    <email_notification>yes</email_notification>
    <email_to>my@example.com</email_to>
    <smtp_server>127.0.0.1</smtp_server>
    <email_from>root@example.com</email_from>
    <email_maxperhour>10</email_maxperhour>
  </global>

thank you

**Comment by ddpbsd** [comment]
Do you have access to the postfix logs? They should help narrow down the issue.

**Comment by marliyev** [comment]
postfix working good, other mails to and from fine. What is this mean by ossec: os_sendmail(1764): WARN: Mail from not accepted by server?

**Comment by ddpbsd** [comment]
@marliyev It probably means that postfix rejected the email. Do you have access to the postfix logs? They should help narrow down the issue.

**Comment by marliyev** [comment]
strange, am changed <email_from>root@example.com</email_from> to <email_from>127.0.0.1</email_from> and its worked :)

**Comment by atomicturtle** [comment]
Closing out as resolved.
