### ISSUE TITLE
OSSEC 3.6.0 Installation Error on Kali Linux

### ISSUE THREAD

**Issue by Mai-Kassem** [ossec/ossec-hids#1929]
Hello, I keep getting this error when installing OSSEC, Could someone help me please on what can be done ? Thanks alot !

Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/  client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver-win.o client-agent/receiver.o client-agent/sendmsg.o client-agent/start_agent.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz  -levent ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-agentd
/usr/bin/ld: client-agent/config.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/event-forward.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/intcheck_op.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/main.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/notify.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/receiver.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/sendmsg.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/start_agent.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: os_net.a(os_net.o):(.bss+0x0): multiple definition of `agt'; client-agent/config.o:(.bss+0x10088): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:1017: ossec-agentd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by Mai-Kassem** [comment]
Done

**Comment by Jorge-Sasiain** [comment]
Hello @Mai-Kassem,  I'm running into the same issue in Kali Linux 2021.1. Could you share how you solved it? Thanks in advance.

**Comment by ddpbsd** [comment]
@Jorge-Sasiain Don't install 3.6, use git to grab the newer code. I believe this has been fixed there.

**Comment by Jorge-Sasiain** [comment]
Thanks for the quick reply @ddpbsd. I had tried both installing the release and cloning the repo but I couldn't get any of them to work. In the end I have switched to Ubuntu Focal and had no issues there.

**Comment by Mai-Kassem** [comment]
Hi, I also solved it by working with ubuntu 🤗
