### ISSUE TITLE
OSSEC 2.9.3 Installation Error

### ISSUE THREAD

**Issue by Jhay199** [ossec/ossec-hids#1930]
Hi,

Need help on installing OSSEC 2.9.3 I'm actually not good on using Linux but I followed all the installation guidelines on this link below
https://computingforgeeks.com/how-to-install-ossec-hids-on-ubuntu-18-04-16-04-debian-9/
https://blog.rapid7.com/2017/06/30/how-to-install-and-configure-ossec-on-ubuntu-linux/

but it always keep failed on the installation idk why
below is the error that I received

5- Installing the system
 - Running the Makefile
cd external/lua/ && make posix
make[1]: Entering directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3'
cd src && make posix
make[2]: Entering directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3/src'
make all SYSCFLAGS="-DLUA_USE_POSIX"
make[3]: Entering directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3/src'
make[2]: Leaving directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3/src'
make[1]: Leaving directory '/home/boldr/ossec-hids-2.9.3/src/external/lua-5.2.3'
cc -fPIC -no-pie -O2 -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DPICVIZ_OUTPUT_ENABLED -Wall -Wextra -I./ -I./headers/ -I./external/zlib-1.2.8/ client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver.o client-agent/receiver-win.o client-agent/sendmsg.o client-agent/start_agent.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a external/zlib-1.2.8/libz.a  -lm -lpthread -o ossec-agentd
/usr/bin/ld: os_net.a(os_net.o):(.bss+0x0): multiple definition of `agt'; client-agent/config.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:888: ossec-agentd] Error 1
 Error 0x5.
 Building error. Unable to finish the installation.
root@kali:/home/boldr/ossec-hids-2.9.3#

FYI: I already try this command below
env CFLAGS="-fPIC -no-pie" V=1 ./install.sh

Also I tried to clean the src dir using this command (not sure on this)
sudo apt-get autoclean src

Thank you so much

**Comment by Jhay199** [comment]
FYI I am using Kali Linux as server using virtual box on my windows OS machine

**Comment by ddpbsd** [comment]
I believe this was reported in #1871 
Fixed in #1875 but needs to be updated to the latest source.

**Comment by atomicturtle** [comment]
PR#1875 is merged, and also... 2.9.3 is way out of date. Theres nothing you could do other than update to resolve this
