### ISSUE TITLE
Failing to start with ossec-control start

### ISSUE THREAD

**Issue by wg21908** [ossec/ossec-hids#1932]
**Issue**
I'm very new to the OSSEC HIDS software.  I was able to install without problem.  I attempted to start OSSEC HIDS with following command but got errors shown below.  Some details of my OS are also below.

_root@wes-MS-7A95:/var/ossec/logs# /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v3.6.0...
ossec-analysisd: Configuration error. Exiting._

**ossec.log log error(s)**
2020/11/15 11:24:27 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/15 11:24:27 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/11/15 11:26:32 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/15 11:26:32 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.

**OS Details**
> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by ddpbsd** [comment]
I haven't tested this with ubuntu 20.04. My guess would be that JIT isn't supported in the pcre2 installation. I'd try building it with `USE_PCRE2_JIT=no`.

**Comment by ddpbsd** [comment]
Actually, it looks like I have tried it.
```
ubuntu@ubuntu-server:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

And the pcre2 packages:
```
ubuntu@ubuntu-server:~$ dpkg --list | grep pcre2
ii  libpcre2-16-0:amd64                  10.34-7                            amd64        New Perl Compatible Regular Expression Library - 16 bit runtime files
ii  libpcre2-32-0:amd64                  10.34-7                            amd64        New Perl Compatible Regular Expression Library - 32 bit runtime files
ii  libpcre2-8-0:amd64                   10.34-7                            amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
ii  libpcre2-dev:amd64                   10.34-7                            amd64        New Perl Compatible Regular Expression Library - development files
ii  libpcre2-posix2:amd64                10.34-7                            amd64        New Perl Compatible Regular Expression Library - posix-compatible runtime files
```

I don't think I've made any changes to the decoder file, so this should be what you get too:
```
root@ubuntu-server:/home/ubuntu# sha256sum /var/ossec/etc/decoder.xml 
0acb016d82199cbf9fba768055a8f5eff6a32fc9d170f10bcd2c911e41d8e91e  /var/ossec/etc/decoder.xml
```

**Comment by wg21908** [comment]
I ran your same steps to uncover differences, see below.  The only difference is the output from the dpkg command.

**OS info**
```
root@wes-MS-7A95:/var/ossec/logs# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**dpkg output - I do see differences, not sure whether this is an issue or not?**
```
root@wes-MS-7A95:/var/ossec/logs# dpkg --list | grep pcre2
ii  libpcre2-16-0:amd64                        10.34-7                               amd64        New Perl Compatible Regular Expression Library - 16 bit runtime files
ii  libpcre2-32-0:amd64                        10.34-7                               amd64        New Perl Compatible Regular Expression Library - 32 bit runtime files
ii  libpcre2-8-0:amd64                         10.34-7                               amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
```

**decoder details - I have not made any mods to this file after installation of software**
```
root@wes-MS-7A95:/var/ossec/logs# sha256sum /var/ossec/etc/decoder.xml
0acb016d82199cbf9fba768055a8f5eff6a32fc9d170f10bcd2c911e41d8e91e  /var/ossec/etc/decoder.xml
```

**result from startup attempt**
```
root@wes-MS-7A95:/var/ossec/logs# /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v3.6.0...
ossec-analysisd: Configuration error. Exiting.
```


**ossec.log log output - is the same**
```
root@wes-MS-7A95:/var/ossec/logs# tail -f /var/ossec/logs/ossec.log 
2020/11/15 11:35:25 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/15 11:35:25 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/11/16 07:49:51 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/16 07:49:51 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/11/16 10:07:33 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/16 10:07:33 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/11/16 10:11:21 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/16 10:11:21 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
2020/11/16 10:12:22 ossec-analysisd(1450): ERROR: Syntax error on regex: '\(pam_unix\)$': 9.
2020/11/16 10:12:22 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.

```

**Comment by ddpbsd** [comment]
@wg21908 How are you installing OSSEC? Mine was built from the 3.6.0 release on github.

**Comment by wg21908** [comment]
**Steps I did for the install and configuration**

1. In Firefox, browsed to https://github.com/ossec/ossec-hids/tree/3.6.0, then chose the "Downloaded ZIP" option from Code dropdown
1. unzipped the download
1. changed into ossec-hids-3.6.0 directory
1. Ran install.sh script
1. FYI: Installation completes without error, select all default as prompted
1. Then attempt ```/var/ossec/bin/ossec-control start``` to get error that was mentioned in previous post

I will attempt building-from-your-source "configure, make and make install" to see if that will bypass the error.

**Comment by ddpbsd** [comment]
I'm surprised there weren't any errors related to pcre2 during the build. I've always needed the dev packages to get it built.

**Comment by atomicturtle** [comment]
I dont get this on the deb package builds for ubuntu either. Have you tried those?

**Comment by wg21908** [comment]
not an issue for me anymore, closing out.
