### ISSUE TITLE
Fedora 33 rpm packages

### ISSUE THREAD

**Issue by agharta** [ossec/ossec-hids#1933]
Hi all,
Please can You provide official Fedora 33 rpms?
In Your official repository https://updates.atomicorp.com/channels/atomic/fedora/ packages stops at F32.
We can not migrate to F33.

Thank You and Best Regards,
Agharta

**Comment by C3dar** [comment]
Hello, 

F33 is up now: https://updates.atomicorp.com/channels/atomic/fedora/
