### ISSUE TITLE
OSSEC missing OpenSSL support

### ISSUE THREAD

**Issue by harshilmathur** [ossec/ossec-hids#194]
Hi, I was using ossec server/agent conf in my environment (all Ubutnu 12.04), recently I upgraded the server & agent machines to Ubuntu 14.04. Now I had setup a new agent machine. But when I ran 
`/var/ossec/bin/agent-auth -m <server-ip> -p 1515`
I got 
ERROR: Not compiled. Missing OpenSSL support. 
I had libssl-dev package installed before I compiled ossec. Seems a problem with Ubuntu 14.04.

**Comment by mk6032** [comment]
Hi, just a quick note that it looks like a typo in the commit fix 194, line 66. 

# Checking for OpenSSLconf.h
-    ls /usr/include/openssl/opensslconf.h > /dev/null 2>&1

This is still present within the src/Makeall of ossec-hids-2.8.1.tar.gz.

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

$ ls -l /usr/include/openssl/openssl*
-rw-r--r-- 1 root root 3750 Jan  9 12:56 /usr/include/openssl/opensslv.h
matt@monitor:~$ ls -l /usr/include/openssl/conf.h
-rw-r--r-- 1 root root 9848 Jan  9 12:56 /usr/include/openssl/conf.h

/ossec-hids-2.8.1/src$ md5sum Makeall
ae5b652536234519a905004366319a8d  Makeall
/ossec-hids-2.8.1/src$ grep "conf.h" Makeall 
    # Checking for OpenSSLconf.h
    if [ -e /usr/include/openssl/opensslconf.h ]; then
    elif [ -e /usr/include/openssl/conf.h ]; then

Regards,
Matt

**Comment by harshilmathur** [comment]
Hi,
After the fix, we are now checking both paths for openssl.
/usr/include/openssl/conf.h
works on 14.04+ and /usr/include/openssl/opensslconf.h works before that.

Presence of either file means that openssl support is present. In your case
(14.04), the second if condition(line 69) would match and hence openssl
support will be available.

Harshil Mathur

**Comment by awiddersheim** [comment]
Also, just wanted to point out that the `Make` system has been vastly changed since the original bug so much of this doesn't apply to what will be the `2.9` release.

**Comment by ehsanmostajeran** [comment]
Hi, I am having the same issue with OpenSSL support.
I have followed up with your comments but still facing same issue.
I am running Ubuntu inside docker container. 

root@434266e9a8f8:/# /var/ossec/bin/ossec-authd
ERROR: Not compiled. Missing OpenSSL support.

I have already installed libssl-dev, but I do not have opensslconf.h.
My ossec is built with latest commit to solve libss-dev.

Appreciate if anyone helps.

**Comment by ddpbsd** [comment]
@ehsanmostajeran Which version of Ubuntu? Mine (14.10 LTS) has opensslconf.h in the libssl-dev package:
```
root@earth:~# dpkg -S /usr/include/x86_64-linux-gnu/openssl/opensslconf.h
libssl-dev:amd64: /usr/include/x86_64-linux-gnu/openssl/opensslconf.h
```

**Comment by ehsanmostajeran** [comment]
@ddpbsd I have solved that issue. 
Now I have active agent.
I would like to check Docker host, I guess better to install agent at host level, not in container. But I get error as below:

2016/06/03 14:48:56 ossec-syscheckd: ERROR: Unable to add directory to real time monitoring: '/var/lib/docker/aufs/diff/3efe0b52dc7a2950f9061cafd1c45602e8c7dcb4248a6cd8764d82ef14379f8a/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/conch/test'. -1 28

**Comment by ddpbsd** [comment]
@ehsanmostajeran I haven't had to deal with docker yet, so I don't have any real ideas on how to handle that.

**Comment by ehsanmostajeran** [comment]
@ddpbsd I am actually new to both. I just want to monitor docker hosts (more specifically docker folder) with ossec. Seems that ossec is unable to add the above mentioned folder to real time monitoring.

**Comment by ddpbsd** [comment]
Are there issues with aufs and inotify?

**Comment by ehsanmostajeran** [comment]
I am not sure about inotify, but as far as I know aufs is there.
Below is docker storage driver info:  

Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1057
