### ISSUE TITLE
Can OSSEC 3.6.0 be installed on SLE 12 SP3?

### ISSUE THREAD

**Issue by kompjuteras** [ossec/ossec-hids#1942]
Hello all.

I am trying to install OSSEC as a local installation on **SLE 12 SP3** with the:
```
zypper in -y make gcc zlib-devel libopenssl-devel 

version=3.6.0
curl -O https://codeload.github.com/ossec/ossec-hids/tar.gz/${version}
tar zxvf ${version}
rm -rf ${version}
cd ossec*
curl -O https://ftp.pcre.org/pub/pcre/pcre2-10.32.tar.gz
tar xzf pcre2-10.32.tar.gz -C src/external

cat > etc/preloaded-vars.conf <<EOF
USER_LANGUAGE="en"
USER_NO_STOP="y"
USER_INSTALL_TYPE="local"
USER_DIR="/var/ossec"
USER_ENABLE_EMAIL="n"
USER_ENABLE_ACTIVE_RESPONSE="n"
USER_ENABLE_SYSCHECK="y"
USER_ENABLE_ROOTCHECK="y"
#### exit ? ###
EOF
PCRE2_SYSTEM=no ./install.sh
```

But it not work and I am getting the error message:

```
os_maild/sendmail.c:12:19: fatal error: event.h: No such file or directory
 #include <event.h>
                   ^
compilation terminated.
Makefile:926: recipe for target 'os_maild/sendmail.o' failed
make: *** [os_maild/sendmail.o] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
```

There are no `pcre2-devel` or `libevent-devel` packages available for SLE 12 SP3.

```
testing-sles12sp3:~/ossec-hids-3.6.0 # zypper se pcre2-devel libevent-devel
Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_12_SP3_x86_64'.
Loading repository data...
Reading installed packages...
No matching items found.
```

Installation from above works for OSSEC 3.3.0 (`version=3.3.0`), but starting from 3.4.0 it doesn't work anymore, guessing because of missing `libevent-devel` package for SLE 12 SP3 which was not required for 3.3.0. 
Is there some workaround for SLES 12 SP3 so I can install versions of OSSEC newer than 3.3.0?

Thanks.

...

**Comment by illuusio** [comment]
You have to compile libevent-devel and pcre2-devel. It's not easy task but doable.

**Comment by ddpbsd** [comment]
I see pcre2 packages on packagehub.suse.com, but not libevent. libevent2 is installed on my OpenSuse system though (libevent-devel is available according to zypper).

**Comment by illuusio** [comment]
You should take a look from https://build.opensuse.org if someone has compiled it

**Comment by kompjuteras** [comment]
Well, currently only SLE 12 SP5 is supported on https://build.opensuse.org/package/show/server:monitoring/ossec-hids. I will test it later on SP5 - but SP3 is not yet supported, so guessing manual compile of libevent-devel can be a workaround, but I am not sure is that applicable for production servers. I will try to reach SUSE support about this package, to check why it's not under the SP3 repo.

Thank you all.
