### ISSUE TITLE
OSSEC Rule Suppression

### ISSUE THREAD

**Issue by linuxadmin25** [ossec/ossec-hids#1947]
Hi Team,

I am using OSSEC(2.7.0) for HIDS, i have certain rules written down, which is being alerted on email, whenever a new system is provisioned.
The mails coming in are in abundance and with a lot of repetitions, I would really like to suppress them, is there a workaround that somehow i can reduce the number of mails to avoid repetition, for example Root's Crontab Entry Changed should occur only once rather than occurring 5-6 times.

Let me know if you need any other details.

Note : I didn't find any previous logged issues similar to mine, opening a new one.

Regards,
Tanmay

**Comment by mikegotroot99** [comment]
OSSEC 2..7.0 is End of Life, and is no longer maintained, which means that it will not receive any further enhancements, security or bug fix updates.  Please upgrade to 3.6.0 or higher.

If you can reproduce this issue against a currently maintained version of OSSEC please feel free to reopen this bug against that version. If you are unable to reopen this issue, please file a new report against the current release. If you experience problems, please add a comment to this bug.

**Comment by linuxadmin25** [comment]
Thank you for the response.
I'm really new to this ossec, but please correct if I'm wrong, to my understanding if I just want to suppress the rule to avoid repetition or jus' want to stop the abundance of mails coming to the mailbox, is it something related to upgradation?

Please clarify.

**Comment by atomicturtle** [comment]
Yes very much, the rules have changed considerably since then (7+ years!), as well as the rule language. You're welcome to join us on slack for more assistance: https://join.slack.com/t/ossec/shared_invite/zt-mejtq1hy-z_RfsHgaWu0C9pq1aiwSTg
