### ISSUE TITLE
No alert for new files

### ISSUE THREAD

**Issue by jctello** [ossec/ossec-hids#1968]
It seems the FIM has stopped generating events for new files at some point. 
It will alert for modified files but I haven't been able to trigger new alerts on a CentOS 7 machine with a recently installed ossec 3.6.0 with either realtime or scheduled scans.

This can be easily reproduced by adding the following to the `ossec.conf` file under `syscheck`:
```
<directories check_all="yes" realtime="yes">/fimtest</directories>
```
Then creating the directory to monitor, restarting ossec, waiting for the initial baseline scan to finish and then creating and modifying files.

```
mkdir /fimtest
/var/ossec/bin/ossec-control restart
touch /fimtest/touchfile
echo 'file created' > /fimtest/testfile
echo 'file modified' > /fimtest/testfile
```
This results in:
```
2021 Apr 12 20:18:16 ossecplus->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/fimtest/testfile'
Size changed from '13' to '14'
Old md5sum was: '5fd362b44d5888524082a456b53d634e'
New md5sum is : 'a4a652080a8304239b5391882b4bd778'
Old sha1sum was: '2f6259e561f69a5fb17d312b393529d91b8c76da'
New sha1sum is : '3428a87cc8198e33af09c554c6f33c610fecf076'
```
and no other syscheck alerts.

**Comment by wolle604** [comment]
Hey,

you should check your agent config:
annd add the following to the directories tag:
alert_new_files="yes"

for more informations: https://ossec-documentation.readthedocs.io/en/latest/configuration/ossec_conf.html#directories

best wishes

**Comment by jctello** [comment]
Thank you @wolle604 , that makes sense!
