### ISSUE TITLE
Fedora 34 RPM Broken?

### ISSUE THREAD

**Issue by agharta** [ossec/ossec-hids#1973]
Hi all,
Into a new freshly Fedora 34 installation, following your guide at https://www.ossec.net/download-ossec/#fedora I give bad result.
Mirror installation OK, but if I type: dnf install ossec-hids-agent
dnf tells me that the package does not exists.
No problems with Fedora 33, only with 34.

If I browse to Fedora 33 repository https://updates.atomicorp.com/channels/atomic/fedora/33/x86_64/RPMS/
I can view the ossec-hids-agent-3.6.0-14983.fc33.art.x86_64.rpm package

Into Fedora 34 repository at  https://updates.atomicorp.com/channels/atomic/fedora/34/x86_64/RPMS/ 
the package is missing.

What should i do to install ossec into Fedora34?

Thanks to all,
Agharta

**Comment by atomicturtle** [comment]
Added, thanks for the report!

**Comment by agharta** [comment]
> Added, thanks for the report!

Thank you for solving the issue!
Ossec is a critical part for my infrastructure.
My best regards!
