### ISSUE TITLE
OSSEC+ Server Monitoring

### ISSUE THREAD

**Issue by MaximKing1** [ossec/ossec-hids#1980]
So on my server I have the OSSEC+ Server, I didn’t know if that would monitor that server would would I have to use a agent on that server for it to work? I only have one server you see, so does the OSSEC+ Server actually monitor the server or not? How would I work that

**Comment by atomicturtle** [comment]
Yup! an ossec server has all the same functionality built in that an ossec agent does. So its going to run FIM, rootcheck, log IDS, etc
