### ISSUE TITLE
[ossec 3.6]ERROR: OSSEC not compiled with support for 'mysql'.

### ISSUE THREAD

**Issue by siutung** [ossec/ossec-hids#2014]
Hi,all.
I downloaded the ossec-hids-3.6.0.tar.gz on CentOS 7.8.
Before I compiling,I run DATABASE=mysql ,then run ./install.
There havn't any error.
But I run:
/var/ossec/bin/ossec-control start
Starting OSSEC HIDS v3.6.0...
2021/09/08 17:07:12 ossec-dbd(5207): ERROR: OSSEC not compiled with support for 'mysql'.
2021/09/08 17:07:12 ossec-dbd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
ossec-dbd did not start correctly.

How I can fix it?please!

**Comment by siutung** [comment]
resolved.

**Comment by antojeniston** [comment]
how to resolve this
