### ISSUE TITLE
False positive "Trojaned version of file '/bin/diff' detected" on Archlinux

### ISSUE THREAD

**Issue by tiiiecherle** [ossec/ossec-hids#2020]
Hey Ossec Team,

with the latest version diffutils 3.8-1 installed ossec reports a trojaned version of a few files.

```
OSSEC HIDS Notification.
2021 Oct 22 10:22:02

Received From: archvbox->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).



--END OF NOTIFICATION



OSSEC HIDS Notification.
2021 Oct 22 10:22:02

Received From: archvbox->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/sbin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).



--END OF NOTIFICATION



OSSEC HIDS Notification.
2021 Oct 22 10:22:02

Received From: archvbox->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).



--END OF NOTIFICATION



OSSEC HIDS Notification.
2021 Oct 22 10:22:02

Received From: archvbox->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/usr/sbin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
```

I opened an issue at the archlinux bug tracker here:
[https://bugs.archlinux.org/task/72519#comment203202](https://bugs.archlinux.org/task/72519#comment203202)

When testing the files against virustotal database nothing suspicious is reported and the checksum seems fine.

Changing the diff line in rootkit_trojans.txt to `diff !bash|^/bin/sh|file\.h|proc\.h|^/bin/.*sh!` solves the reporting.

I assume it is a false positive and after confirming the rootkit_trojans.txt should be changed.

Thanks in advance

**Comment by RonV666** [comment]
same for Fedora35.
Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).

**Comment by MKPlato** [comment]
Any updates on this issue? The bug still exists now.

**Comment by ddpbsd** [comment]
Please test PR #2062 
I think it will handle this.

**Comment by rileyjnevins** [comment]
Just experienced this issue on several Ubuntu hosts of mine:

  | manager.name | wazuh
  | rule.firedtimes | 8
  | rule.mail | false
  | rule.level | 7
  | rule.pci_dss | 10.6.1
  | rule.description | Host-based anomaly detection event (rootcheck).
  | rule.groups | ossec, rootcheck
  | rule.id | 510
  | rule.gdpr | IV_35.7.d
  | decoder.name | rootcheck
  | full_log | Trojaned version of file '/bin/diff' detected. Signature used: 'bash\|^/bin/sh\|file\.h\|proc\.h\|/dev/[^n]\|^/bin/.*sh' (Generic).
  | location | rootcheck

**Comment by SedonD** [comment]
I agree with the others, we are experiencing this:

Wazuh Alert: 'Host-based anomaly detection event (rootcheck).' 

DETAILS 
Description: 'Host-based anomaly detection event (rootcheck).' Log: 'Trojaned version of file /usr/bin/diff detected. Signature used: bash ^/bin/sh file/.h proc/.h /dev/[^n] ^/bin/.*sh (Generic).' Rule: '510' location: 'rootcheck'

**Comment by KamalMajaiti** [comment]
Same problem.

<html>
<body>


full_log | Trojaned version of file '/bin/diff' detected. Signature used: 'bash\|^/bin/sh\|file\.h\|proc\.h\|/dev/[^n]\|^/bin/.*sh' (Generic).
-- | --
  | id | 1672561204.10642855
  | input.type | log
  | location | rootcheck
  | manager.name | ids.majaiti.es
  | rule.description | Host-based anomaly detection event (rootcheck).
  | rule.firedtimes | 1
  | rule.gdpr | IV_35.7.d
  | rule.groups | ossec, rootcheck
  | rule.id | 510
  | rule.level | 7
  | rule.mail | false
  | rule.pci_dss | 10.6.1
  | timestamp | 2023-01-01T08:20:04.988+0000


</body>
</html>

**Comment by Practicalbutterfly5** [comment]
Too many notifications of this

**Comment by lemogra** [comment]
this issus still continues as below 
Wazuh Notification.
2023 Feb 03 14:41:32

Received From: siem1->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
title: Trojaned version of file detected.
file: /bin/diff

**Comment by fstrube** [comment]
I think the issue may be due to a reverence to `/dev/full` in the `diff` executable. 

```
# strings /bin/diff | grep /dev/[^n]
/dev/full
```

I made a change in `/var/ossec/etc/shared/rootkit_trojans.txt` to the following line to see if that fixes the issue:

```diff
-diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh!
+diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]|^/bin/.*sh!
```

**Comment by ngisvold** [comment]
Any update on this?

**Comment by ll3N1GmAll** [comment]
This is still happening on Linux Mint 21

"timestamp":"2023-03-19T14:54:44.046+0000","rule":{"level":7,"description":"Host-based anomaly detection event (rootcheck).","id":"510","firedtimes":2,"mail":true,"groups":["ossec","rootcheck"],"gdpr":["IV_35.7.d"]},"agent":{"id":"027","name":"Mint21","ip":"192.168.1.19"},"manager":{"name":"secon-server-wazuh-manager"},"id":"1679237684.3782962","full_log":"Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\\.h|proc\\.h|/dev/[^n]|^/bin/.*sh' (Generic).","decoder":{"name":"rootcheck"},"data":{"title":"Trojaned version of file detected.","file":"/usr/bin/diff"},"location":"rootcheck"}

**Comment by fuomag9** [comment]
Still happening to macOS as well

**Comment by troublestarter** [comment]
Happening on Debian 11 with Wazuh v4.3.10

**Comment by Practicalbutterfly5** [comment]
Wazuh 4.4.0 and still happening ....
Ubuntu 22.04 arm64

**Comment by serfermorhc** [comment]
Same here

**Comment by y0d4a** [comment]
can confirm same, latest ver. of wazuh

**Comment by pleibling** [comment]
Same, Wazuh 4.4.1 and Ubuntu Server minimal 22.04 (all updates).

Any News?

**Comment by titleistfour** [comment]
I have this issue with `/usr/bin/mail` on RHEL 9 and Wazuh 4.4.1.

**Comment by gand0rf** [comment]
Wanted to leave an update. 
wazuh-manager version 4.4.5
wazuh-agent version 4.4.5

Files Indicated:
/bin/diff
/usr/bin/diff

Signature used:
bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh

Going to try fstrube edit to rootkit_trojans.txt

**Comment by iNimbleSloth** [comment]
Receiving the same.

wazuh-manager version 4.4.5 running on an Ubuntu 22.04.2 LTS virtual machine.
wazuh-agent version 4.4.5 also running on an Ubuntu 22.04.2 LTS virtual machine (different VM from above).

Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).

**Comment by kayo77** [comment]
Receiving the same.
 on Debian 12.1 with wazuh-agent 4.5.0

**Comment by troublestarter** [comment]
I think nobody work on this ...

**Comment by arf20** [comment]
Getting the same notification on Debian 12, wazuh 4.5.1

**Comment by 33b5e5** [comment]
This seems to resolve the issue with Wazuh on Debian/Ubuntu:

`sudo vi /var/ossec/etc/rules/local_rules.xml`

Add something like:

```xml
<group name="rootcheck,ossec,">
  <rule id="510" level="0" overwrite="yes">
    <match>/bin/diff</match>
    <description>Ignore 510 rootcheck on /bin/diff</description>
  </rule>
</group>
```

Test the changes:

`sudo /var/ossec/bin/wazuh-analysisd -t`

If it looks good restart:

`sudo systemctl restart wazuh-manager.service`

**Comment by earthyfort** [comment]
Is there any news about this?

**Comment by dibu28** [comment]
Ubuntu 23
Trojaned version of file detected.
Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).

**Comment by vinsk0h** [comment]
I have the same thing on U22 with Wazuh v4.5.2
`Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).`

**Comment by 0xr00tx** [comment]
Same issue with Agent v4.5.2 and Debian 12

**Comment by AT-SGAI-CSIC** [comment]
Hi, on AlmaLinux release 8.8 (Sapphire Caracal) with **wazuh-agent-4.4.3-1.x86_64** I have a similar error:

![imagen](https://github.com/ossec/ossec-hids/assets/139878963/1808a842-0888-4038-91dd-8bfc69e69701)

But in this case in sendmail ....

**Comment by lpingree** [comment]
Seeing this on several of my linux machines.

**Comment by moivica** [comment]
Same issue active  - ubuntu 23.04

**Comment by sjansen1** [comment]
Seeing this on my Proxmox Hosts (based on Debian 12 Bookworm)

**Comment by edxz101** [comment]
Same issue on Ubuntu 22.04 (at the date).

**Comment by pld0vr** [comment]
Also seeing this

**Comment by pthoelken** [comment]
Still exists, please fix this ugg.

**Comment by alexeiol** [comment]
2 years later this bug is still unfixed! I'm getting the same alert in Debian Bookworm and Ossec v3.7.0: 

OSSEC HIDS Notification.
2023 Nov 02 12:18:09

Received From: debianvaio->rootcheck
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).


 --END OF NOTIFICATION

Looking at the bright size, it is good to know this is a false positive.

**Comment by ddpbsd** [comment]
This has been fixed in tree for a while. I'm kind of regretting it though, it's easy enough to fix with an ignore rule. Right now if `diff` is trojaned and has a reference to `/dev` on a non-linux system it won't be caught.
Here's the current definition though:
`diff        !bash|^/bin/sh|file\.h|proc\.h|^/bin/.*sh!`

**Comment by alexeiol** [comment]
> This has been fixed in tree for a while. I'm kind of regretting it though, it's easy enough to fix with an ignore rule. Right now if `diff` is trojaned and has a reference to `/dev` on a non-linux system it won't be caught. Here's the current definition though: `diff !bash|^/bin/sh|file\.h|proc\.h|^/bin/.*sh!`

But this "fix" is not really a "fix" because... What if 'diff' ever becomes legitimately infected? People install security software because they have legitimate security concerns. A false positive detection is a bug in the software and that's what should be fixed.

**Comment by ddpbsd** [comment]
How do you expect to check for the presence of /dev but not alert on the
presence of /dev?

**Comment by JackThird** [comment]
same here, ubuntu server 22.04, wazuh 4.5.4

**Comment by moivica** [comment]
Same problem: Wazuh v 4.6.0 
Ubuntu 23.04

**Comment by Dmitry-Ge** [comment]
Debian 12 , ossec-hids-agent_3.7.0-29672bookworm_amd64.deb - same problem.

**Comment by jdmedeiros** [comment]
Same problem: AWS AL2023
Linux xxxxxxxxxxx 6.1.59-84.139.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 24 20:57:25 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
{"error":0,"data":[{"WAZUH_VERSION":"v4.6.0"},{"WAZUH_REVISION":"40603"},{"WAZUH_TYPE":"server"}]}

**Comment by markgabrang** [comment]
Same on Ubuntu 22.04 hosts, v4.6.0

    "decoder": {
      "name": "rootcheck"
    },
    "id": "1699540605.90066869",
    "full_log": "Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\\.h|proc\\.h|/dev/[^n]|^/bin/.*sh' (Generic).",
    "timestamp": "2023-11-09T14:36:45.727+0000"

**Comment by kawaiipantsu** [comment]
Bump ... Still issue!

**Comment by pisarz77** [comment]
same on current debian 12

**Comment by redrubytech** [comment]
Bump. still same issue on Ubuntu 22.04 with Wazuh 4.6

**Comment by duckietm** [comment]
same here 4.7.0. with ubuntu 22.04

Trojaned version of file '/bin/diff' detected. Signature used: 'bash\|^/bin/sh\|file\.h\|proc\.h\|/dev/[^n]\|^/bin/.*sh' (Generic).

**Comment by atomicturtle** [comment]
This is corrected in the main branch, to update you can use:

1) OUM users: update your signatures with: oum -u
2) Manual: copy https://github.com/ossec/ossec-hids/blob/master/src/rootcheck/db/rootkit_trojans.txt to /var/ossec/etc/shared/ on your hub server. 
3) upgrade from source out of master
