### ISSUE TITLE
 Installation problems (makefile error after install.sh) 

### ISSUE THREAD

**Issue by kjslr** [ossec/ossec-hids#2021]
Installing the system
 - Running the Makefile
cc  -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/  client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver.o client-agent/receiver-win.o client-agent/sendmsg.o client-agent/start_agent.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lpthread -lssl -lcrypto -lz -o ossec-agentd
/usr/bin/ld: os_net.a(os_net.o):(.bss+0x0): multiple definition of `agt'; client-agent/config.o:(.bss+0x48): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:926: ossec-agentd] Error 1

**Comment by nodesocket** [comment]
@kjslr I believe I am having the same issue. Did you get a resolution by chance?

See https://github.com/ossec/ossec-hids/issues/2022

**Comment by ddpbsd** [comment]
I’m pretty sure this is fixed, but not in a release. Try the latest source. A new release needs to be rolled out for this.
