### ISSUE TITLE
[Makefile:1018: ossec-agentd] Error 1

### ISSUE THREAD

**Issue by Tavyah** [ossec/ossec-hids#2023]
**Trying to install an agent on my servers but i have two servers with the same error and i just can't seem to figure it out :S Could u help?**

- I've installed packages: wget git vim unzip make gcc build-essential php php-cli php-common libapache2-mod-php apache2-utils inotify-tools libpcre2-dev zlib1g-dev  libz-dev libssl-dev libevent-dev libssl-dev

- I also have: pcre2-10.32 and pcre2-10.39 within /ossec-hids/scr/external _(I had some issues with this on another server)_

- I've tried 'make clean' within /src

- I downloaded the ossec-hids from: git clone https://github.com/ossec/ossec-hids.git and I'm using version 3.6.0 C:

- I am also using Debian 11 Bullseye for all my servers

_I'm still pretty new to networking and so i'm sure I'm overlooking something C:_ 

```
5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DHAVE_SYSTEMD -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DCLIENT -Wall -Wextra -I./ -I./headers/  client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver.o client-agent/receiver-win.o client-agent/sendmsg.o client-agent/start_agent.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lpthread -lsystemd -lpcre2-8 -lssl -lcrypto -lz  ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-agentd
/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
make: *** [Makefile:1018: ossec-agentd] Error 1
```

**Comment by yilas** [comment]
Hi,
Could you install the package `libsystemd-dev` ?

**Comment by Tavyah** [comment]
Hi! Thank you so much and also I am so sorry for wasting your time. It totally worked. I should practice my googling a bit :) Have a great day!
