### ISSUE TITLE
Fedora 35 Packages missing

### ISSUE THREAD

**Issue by agharta** [ossec/ossec-hids#2026]
Hi all,
As my previous submitted issues i would suggest you, if possible, to add Fedora 35 packages in https://updates.atomicorp.com/channels/atomic/fedora mirror.

This will allows me to upgrade from F34 to F35, without losing ossec packages.

Thanks to all for support,
Agharta

**Comment by atomicturtle** [comment]
Fedora 35 packages are now available

**Comment by michaelfuckner** [comment]
could you please have a look at the packages? OSPd-openvas-21.4.3-24064.fc35.art.x86_64.rpm installs to /opt/atomicorp/lib/python3.9/site-packages/, but F35 uses python3.10 by default
