### ISSUE TITLE
Makefile:930: recipe for target 'ossec-maild' failed

### ISSUE THREAD

**Issue by Azwaliyana** [ossec/ossec-hids#2039]
I got this error while installing OSSEC HIDS version 3.7.0.

5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/osse                                                                                c\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=                                                                                \"ossecm\" -DLinux -DINOTIFY_ENABLED -DHAVE_SYSTEMD -DZLIB_SYSTEM -DUSE_PCRE2                                                                                _JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ os_maild/se                                                                                ndmail.o os_maild/sendcustomemail.o os_maild/config.o os_maild/os_maild_clien                                                                                t.o os_maild/maild.o os_maild/mail_list.o os_crypto.a config.a shared.a os_ne                                                                                t.a os_regex.a os_xml.a  -lm -lpthread -lsystemd -lpcre2-8 -lssl -lcrypto -lz                                                                                  ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
Makefile:930: recipe for target 'ossec-maild' failed
make: *** [ossec-maild] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

What is the problem? How can I solve this?

**Comment by Renevant** [comment]
Experiencing the same issue - building on Ubuntu 20.04.3.
Any update on this?

**Comment by Renevant** [comment]
Answered by @trietphm here: https://github.com/ossec/ossec-hids/issues/1950

Don't know what OS @Azwaliyana is running, but on Ubuntu 20.04, the solution was to **apt install -y libsystemd-dev**

Once I did so, installation proceeded without the above error.

**Comment by hb9fbl** [comment]
On RedHat 7 based systems:     yum install  systemd-devel.x86_64
