### ISSUE TITLE
Publish 3.7 on atomicorp mirror?

### ISSUE THREAD

**Issue by m-terlinde** [ossec/ossec-hids#2041]
Hey guys,

at least for my CentOS installations, the current published version on the [archive ](https://updates.atomicorp.com/channels/atomic/centos/8/x86_64/RPMS/) is 3.6.

Is there any chance, that the 3.7 version will be pushed there as well?

Thanks,
Matthias

**Comment by Nono-m0le** [comment]
Is 3.7 even considered as stable ? 
On the website (https://www.ossec.net/download-ossec/) it's indeed the 3.6 which is marked as latest/stable.

**Comment by m-terlinde** [comment]
But otherwise it wouldn't be released, right?

**Comment by Nono-m0le** [comment]
as a Realease Candidate ? or without LTS ? I don't know ... just raising the question here

**Comment by titleistfour** [comment]
It appears that 3.7.0 is marked as stable.  Why are there no RPM packages published for that version yet?

**Comment by m-terlinde** [comment]
Maybe @atomicturtle could help us out?

**Comment by atomicturtle** [comment]
omg I can't believe I missed that everyone. So sorry!
