### ISSUE TITLE
Unable to compile source with  aarch64 (graviton processors) in AWS

### ISSUE THREAD

**Issue by akhilmudgal** [ossec/ossec-hids#2055]
While trying to compile agent on gravtion processor provided by AWS, Getting the following error:

/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
make: *** [Makefile:1018: ossec-agentd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
 
 OS: Ubuntu 20.04.4 LTS

**Comment by ddpbsd** [comment]
Please add the libsystemd-devel package (might be libsystemd-dev?)

**Comment by atomicturtle** [comment]
Closing this as out of date. I was able to build this on rocky/rhel 8/9, amazon linux 2023, and u20-24 arm systems
