### ISSUE TITLE
Migration Ossec 2.9

### ISSUE THREAD

**Issue by alix-corp** [ossec/ossec-hids#2067]
We have installed ossec 6 years ago , and the installed version is 2.9, the questions are : 

Is it possible migrate from 2.9 to 3.7 version ? 
if  it was possible , what is the best way to do(steps to do)?
if wasen't posible, what i could do it to have one ossec with the same agents and the data migrate?

Many thanks in advance for your help !!!

**Comment by libellux** [comment]
If I was you @alix-corp i'd take a snapshot of your current setup and then just test with the normal approach of update, If you then find issues upgrading from 2.9 to 3.7 you can go from there.
