### ISSUE TITLE
3.6.0 install fails with ftp failure

### ISSUE THREAD

**Issue by ahbrown1** [ossec/ossec-hids#2071]
Maybe this is old news since I'm using open-source OSSEC 3.6.0 on Ubuntu 20.04.5 LTS. 

For the agent install.sh file that comes with open source OSSEC  the ftp address is apparently no longer vald. (ref: https://groups.google.com/g/openresty-en/c/6zoTVufQsoo?pli=1)

I modified it to work with:

```
RESTY_PCRE_VERSION="8.45"
tar -zxvf 3.6.0.tar.gz && cd ossec-hids-3.6.0/ && \
curl -fSL https://downloads.sourceforge.net/project/pcre/pcre/${RESTY_PCRE_VERSION}/pcre-${RESTY_PCRE_VERSION}.tar.gz -o pcre-${RESTY_PCRE_VERSION}.tar.gz
#wget https://ftp.pcre.org/pub/pcre/pcre2-10.32.tar.gz && \
tar -zxvf pcre-${RESTY_PCRE_VERSION}.tar.gz -C src/external/ && \
sudo PCRE2_SYSTEM=yes ./install.sh
```

**Comment by libellux** [comment]
Hello @ahbrown1 you can find the releases here: https://github.com/PCRE2Project/pcre2/releases
