### ISSUE TITLE
/usr/bin/Id: cannot find -lsystemd: No such file or directory

### ISSUE THREAD

**Issue by Andtress** [ossec/ossec-hids#2072]
Holaa, estaba intentando hacer una practica en la instalacion en un ubuntu 22.04, hice una update del apt-get e la instalacion de las dependencias pero me surgio dicho error

**Comment by libellux** [comment]
Hola! vos tenho mas informacion que error? donde voce encountrar esta? also my spanish (portuguse?) isn't the best but sounds like a symbolic link error.

**Comment by Andtress** [comment]
Olá Fredrik, tudo bem?
Não, porque eu estava realmente tentando instalá-lo em um raspberry pi 3 com o ubuntu 22.04, o erro que recebo é o mesmo que te falei, poderia dizer que também tentei instalar o wazuh mas me dá um problema , não sei se posso te ajudar com isso

________________________________



De: Fredrik Hilmersson ***@***.***>
Enviado: viernes, 23 de diciembre de 2022 9:35 p. m.
Para: ossec/ossec-hids ***@***.***>
Cc: Andtres ***@***.***>; Author ***@***.***>
Asunto: Re: [ossec/ossec-hids] /usr/bin/Id: cannot find -lsystemd: No such file or directory (Issue #2072)


Hola! vos tenho mas informacion que error? donde voce encountrar esta? also my spanish (portuguse?) isn't the best but sounds like a symbolic link error.

**Comment by libellux** [comment]
Oi Andtress, as i said my portugues isn't the best, but this is not a ossec issue this is an issue on ur ARM side, you need to make sure that your OS is running systemd. I would suggest you use Raspbian (jesse or up) instead and try to install OSSEC.

**Comment by Andtress** [comment]
Oi Frederick, acho que você está certo, muito obrigado pela atenção. Eu estava mexendo e se eu conseguir isso, hehe, embora eu tenha descoberto que o serviço realmente não existe, você poderia determinar o serviço específico que deveria ser incluído nele?

________________________________
De: Fredrik Hilmersson ***@***.***>
Enviado: jueves, 29 de diciembre de 2022 6:24 p. m.
Para: ossec/ossec-hids ***@***.***>
Cc: Andtres ***@***.***>; Author ***@***.***>
Asunto: Re: [ossec/ossec-hids] /usr/bin/Id: cannot find -lsystemd: No such file or directory (Issue #2072)


Oi Andtress, as i said my portugues isn't the best, but this is not a ossec issue this is an issue on ur ARM side, you need to make sure that your OS is running systemd. I would suggest you use Raspbian (jesse or up) instead and try to install OSSEC.

**Comment by libellux** [comment]
Oi Andtress, uso Raspbian (jesse or up) ~ and it should work (portuguese isn't my main language). Test it and if it doesn't work then I'll try to install it myself and update you.

**Comment by Practicalbutterfly5** [comment]
Try this
```
apt install libsystemd-dev
```
