### ISSUE TITLE
Not getting a full gui of ossec web-ui

### ISSUE THREAD

**Issue by ashifly** [ossec/ossec-hids#2077]
![image](https://user-images.githubusercontent.com/76905413/217278707-ead0085f-52a3-4043-b1bc-2cbb7f510b10.png)
I am only getting this much on screen. I am using ssh to connect to this IP. What could be the issue related to?

**Comment by wolle604** [comment]
The web ui isn't maintained and deprecated.
https://github.com/ossec/ossec-wui
Use something different, maybe grafana.

**Comment by romaind43** [comment]
hi, i have the same problem as you. I'll try to install another version I'll come back to you if it doesn't work :).
thanks for the help wolle604

**Comment by RinKC** [comment]
Having the same issue. Was wondering if anyone solved it?

**Comment by bigtrucker89** [comment]
webUI is no longer maintained.

**Comment by MohamedAakif** [comment]
Purge and reinstall apache 5.0 or less it worked for me:

sudo add-apt-repository -y ppa:ondrej/php
sudo apt update
sudo apt install php5.6
