### ISSUE TITLE
No ossec-hids packages in repo for Amazon Linux 2

### ISSUE THREAD

**Issue by omelnyk1** [ossec/ossec-hids#2081]
Hello guys,

We noticed that for Amazon Linux 2 OS RPM packages ossec-hids and ossec-hids-server 3.7.0 packages are not available.
Repository was installed according to this manual https://www.ossec.net/download-ossec/. However, yum search doesn't show package for version 3.7.0:
```sh
yum search --showduplicates ossec-hids-server
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
67 packages excluded due to repository priority protections
================================================================================== N/S matched: ossec-hids-server ==================================================================================
1:ossec-hids-server-3.4.0-9608.amzn2.art.x86_64 : The OSSEC HIDS Server
1:ossec-hids-server-3.5.0-9609.amzn2.art.x86_64 : The OSSEC HIDS Server
1:ossec-hids-server-3.5.0-10635.amzn2.art.x86_64 : The OSSEC HIDS Server
1:ossec-hids-server-3.6.0-11279.amzn2.art.x86_64 : The OSSEC HIDS Server
1:ossec-hids-server-3.6.0-14954.amzn2.art.x86_64 : The OSSEC HIDS Server

  Name and summary matches only, use "search all" for everything.
```

Could you please fix that?

Thank you.

**Comment by atomicturtle** [comment]
Should be good to go now, thanks for the report. Related, we did start working on amzn2023 packages but they dont have a working mock environment yet. Regular source builds are fine on it

**Comment by toncid** [comment]
@atomicturtle Thanks, but the version 3.7.0 is still missing from the AL2 yum repo:

```
$ sudo yum list ossec-hids
Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
248 packages excluded due to repository priority protections
Available Packages
ossec-hids.x86_64                                                    1:3.6.0-14954.amzn2.art                                                    atomic
```

Repo config looks fine to me:

```
Repo-id      : atomic
Repo-name    : Atomicorp Amazon Linux - atomic
Repo-revision: 1692367745
Repo-updated : Fri Aug 18 14:09:05 2023
Repo-pkgs    : 76
Repo-size    : 51 M
Repo-mirrors : https://updates.atomicorp.com/channels/mirrorlist/atomic/amazon-2-x86_64
Repo-baseurl : https://updates.atomicorp.com/channels/atomic/amazon/2/x86_64/
Repo-expire  : 21600 second(s) (last: Mon Aug 21 10:48:41 2023)
  Filter     : read-only:present
Repo-excluded: 1
Repo-filename: /etc/yum.repos.d/atomic.repo
```

**Comment by toncid** [comment]
@atomicturtle Could you check the above, please?

**Comment by toncid** [comment]
@atomicturtle Could you confirm the above, please?

**Comment by atomicturtle** [comment]
A ha! It was Epoch shennanigans:

Dependencies Resolved

========================================================================================================
 Package                          Arch        Version                             Repository       Size
========================================================================================================
Installing:
 ossec-hids-agent                 x86_64      1:3.7.0-30866.amzn2.art             atomic          290 k
Installing for dependencies:

**Comment by toncid** [comment]
Thank you for fixing this!
