### ISSUE TITLE
XML rules and special chars

### ISSUE THREAD

**Issue by rnbwkat** [ossec/ossec-hids#209]
Command monitoring using commands with special chars breaks from 2.7 to 2.8:
Command ---
awk -F":" 'list[$3]++{print $3}' /etc/passwd

and this rule used to match: 

<match>ossec: output: 'awk -F"\" 'list[$3]++{print $3}' /etc/passwd': </match>

Now it returns - 
ossec-analysisd(1227): ERROR: Error applying XML variables 'rules//local_rules.xml': XMLERR: Unknown variable: '3]++{print'..

**Comment by ddpbsd** [comment]
Since at least one particularly awesome user reported this to be working, closing the issue.
