### ISSUE TITLE
incorect layout for debian bookworm and bullseye repos

### ISSUE THREAD

**Issue by macrotex** [ossec/ossec-hids#2098]
The directory layout at https://updates.atomicorp.com/channels/atomic/debian/ is broken for Debian bullseye and bookworm.

The distributions should go under the dists/ directory. Furthermore, there should be a "section" directory under each one of those. This is what is there now:
```
https://updates.atomicorp.com/channels/atomic/debian/bookworm/amd64/
```
This is how it _should_ be:
```
https://updates.atomicorp.com/channels/atomic/debian/dists/bookworm/main/binary-amd64/
```

apt commands as well as mirroring commands do not work with the current layout.

**Comment by stevegilbert23** [comment]
I discovered this today while attempting to upgrade to bookworm.

It seems that ossec is now unmaintained based on the lack of commits and lack of anyone responding to any issues.

**Comment by stevegilbert23** [comment]
@ossec Is a fix for this issue planned?

**Comment by atomicturtle** [comment]
Yup, its in progress. Already done for the atomic ossec users

**Comment by atomicturtle** [comment]
Should be good to go now
