### ISSUE TITLE
Support for ossec in AmazonLinux2023

### ISSUE THREAD

**Issue by kumudAtDuo** [ossec/ossec-hids#2116]
We are trying to get ossec in AL2023. Looks like the repo provided here https://www.ossec.net/download-ossec/ works in AL2. Is there going to be support for AL2023 as well? I read this https://github.com/ossec/ossec-hids/issues/2090#issuecomment-1671677616 but is compiling the only way at this time to get ossec in AL2023?

**Comment by AshishDash** [comment]
When can we expect OSSEC support for AL2023?

**Comment by atomicturtle** [comment]
x86_64 and aarch64 packages are available now
