### ISSUE TITLE
[Request] Provide binaries for arm64 Debian Bookworm/Trixie/Sid

### ISSUE THREAD

**Issue by FPVogel** [ossec/ossec-hids#2119]
Hello everyone,

I've seen that there have been a few issues/ PRs in the past about providing arm support. (aarch64/armv7) Some of those have also been merged. Most notably #1809.

Are there any plans to provide binaries at https://updates.atomicorp.com/channels/atomic/debian bookworm/arm64/ ?

Debian would be optimal to support as they have among the best compatibility for arm64, as well as the biggest arm repos, and are upstream for Ubuntu.

With more and more infrastructure moving over to arm CPUs like Ampere and the support from a technical perspective being there this ~should~(sigh) not be too much of a hassle.

As it stands there are no warnings in the install script telling me arm is not supported neither is there any mention of it in the docs. 

Any help (other than compiling myself) would be greatly appreciated. (or at least a note in the docs saying compile arm yourself)

Merlin

**Comment by atomicturtle** [comment]
So definitely can do on Rocky and Amazon linux without a lot of setup work. Mock natively supports cross architecture building, which makes those builds  pretty easy. Ive done .deb based builds before, they just take a lot longer and involve more steps. 

So probably in order I'd expect to first see aarch64 on rocky 8/9 (and by proxy rhel 8/9), then amzn2, amzn2023, and then switching to the .deb builds with ubuntu 24/Debian 12 (or 13 if its out by then)  for the ossec 3.8 release.

**Comment by atomicturtle** [comment]
ARM builds are done now for:

- Rocky/RHEL 8
- Rocky/RHEL 9
- Amazon Linux 2023
- Ubuntu 20
- Ubuntu 22
- Ubuntu 24

Pending:

- Amazon linux 2
- Debian 12

**Comment by atomicturtle** [comment]
Debian 11 and 12 arm packages are out now. I think Ill wait for trixie to go prod though, we dont normally do them for the rawhide branches

**Comment by FPVogel** [comment]
Thanks very much, that's awesome!
