### ISSUE TITLE
Building from source on a staging server. How to transfer the build package to a production server?

### ISSUE THREAD

**Issue by Danrancan** [ossec/ossec-hids#2120]
I have built OSSEC on the Raspbery Pi 4 staging server running Ubuntu Server 22.04. I did this so I don't have to litter my production server's OS with build files. In the install script, I selected the "Build Local" option from the build script since my production server is the only machine I will be monitoring. 

Now, I need to transfer the built application from my staging server to my production server. What are the files on my staging server that need to be copied over to the production server in order for OSSEC to be properly installed on the production server?

Is /ver/ossec the only folder I have to copy over? Or is there more?

Thanks for any answers and help.

**Comment by atomicturtle** [comment]
There are ARM binary builds for U22 in the repo now. Closing this one out since we covered it in slack too
