### ISSUE TITLE
INSTALLATION OF OSSEC ERROR MAKEFILE:1017

### ISSUE THREAD

**Issue by DJAMALFHAAR** [ossec/ossec-hids#2124]
-DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./external/cJSON/ os_execd/config.o os_execd/exec.o os_execd/execd.o os_execd/win_execd.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a libcJSON.a -lm  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz -o ossec-execd
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/config.c -o logcollector/config.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/logcollector.c -o logcollector/logcollector.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/main.c -o logcollector/main.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_audit.c -o logcollector/read_audit.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_command.c -o logcollector/read_command.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_djb_multilog.c -o logcollector/read_djb_multilog.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_fullcommand.c -o logcollector/read_fullcommand.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_mssql_log.c -o logcollector/read_mssql_log.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_multiline.c -o logcollector/read_multiline.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_multiline_indented.c -o logcollector/read_multiline_indented.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_mysql_log.c -o logcollector/read_mysql_log.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_nmapg.c -o logcollector/read_nmapg.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_ossecalert.c -o logcollector/read_ossecalert.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_postgresql_log.c -o logcollector/read_postgresql_log.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_snortfull.c -o logcollector/read_snortfull.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_syslog.c -o logcollector/read_syslog.o
logcollector/read_syslog.c: In function ‘read_syslog’:
logcollector/read_syslog.c:91:37: warning: ‘%s’ directive output may be truncated writing up to 6144 bytes into a region of size 4096 [-Wformat-truncation=]
   91 |             snprintf(buf, OUTSIZE, "%s", str);
      |                                     ^~   ~~~
logcollector/read_syslog.c:91:13: note: ‘snprintf’ output between 1 and 6145 bytes into a destination of size 4096
   91 |             snprintf(buf, OUTSIZE, "%s", str);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_win_el.c -o logcollector/read_win_el.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-logcollector\" -c logcollector/read_win_event_channel.c -o logcollector/read_win_event_channel.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ logcollector/config.o logcollector/logcollector.o logcollector/main.o logcollector/read_audit.o logcollector/read_command.o logcollector/read_djb_multilog.o logcollector/read_fullcommand.o logcollector/read_mssql_log.o logcollector/read_multiline.o logcollector/read_multiline_indented.o logcollector/read_mysql_log.o logcollector/read_nmapg.o logcollector/read_ossecalert.o logcollector/read_postgresql_log.o logcollector/read_snortfull.o logcollector/read_syslog.o logcollector/read_win_el.o logcollector/read_win_event_channel.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz -o ossec-logcollector
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/ar-forward.c -o remoted/ar-forward.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/config.c -o remoted/config.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/main.c -o remoted/main.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/manager.c -o remoted/manager.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/remoted.c -o remoted/remoted.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/secure.c -o remoted/secure.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/sendmsg.c -o remoted/sendmsg.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/syslog.c -o remoted/syslog.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./remoted  -DARGV0=\"ossec-remoted\" -c remoted/syslogtcp.c -o remoted/syslogtcp.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/  remoted/ar-forward.o remoted/config.o remoted/main.o remoted/manager.o remoted/remoted.o remoted/secure.o remoted/sendmsg.o remoted/syslog.o remoted/syslogtcp.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz -o ossec-remoted
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/agentd.c -o client-agent/agentd.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/config.c -o client-agent/config.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/event-forward.c -o client-agent/event-forward.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/intcheck_op.c -o client-agent/intcheck_op.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/main.c -o client-agent/main.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/notify.c -o client-agent/notify.o
client-agent/notify.c: In function ‘run_notify’:
client-agent/notify.c:124:58: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size between 984 and 1016 [-Wformat-truncation=]
  124 |         snprintf(tmp_msg, OS_SIZE_1024, "#!-%s / %s\n%s\n%s",
      |                                                          ^~
  125 |                  uname, md5sum, shared_files, keep_alive_random);
      |                                               ~~~~~~~~~~~~~~~~~
client-agent/notify.c:124:9: note: ‘snprintf’ output 9 or more bytes (assuming 1064) into a destination of size 1024
  124 |         snprintf(tmp_msg, OS_SIZE_1024, "#!-%s / %s\n%s\n%s",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  125 |                  uname, md5sum, shared_files, keep_alive_random);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client-agent/notify.c:127:53: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1019 [-Wformat-truncation=]
  127 |         snprintf(tmp_msg, OS_SIZE_1024, "#!-%s\n%s\n%s",
      |                                                     ^~
  128 |                  uname, shared_files, keep_alive_random);
      |                                       ~~~~~~~~~~~~~~~~~
client-agent/notify.c:127:9: note: ‘snprintf’ output 6 or more bytes (assuming 1029) into a destination of size 1024
  127 |         snprintf(tmp_msg, OS_SIZE_1024, "#!-%s\n%s\n%s",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  128 |                  uname, shared_files, keep_alive_random);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/receiver.c -o client-agent/receiver.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/receiver-win.c -o client-agent/receiver-win.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/sendmsg.c -o client-agent/sendmsg.o
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ -I./client-agent   -DARGV0=\"ossec-agentd\" -c client-agent/start_agent.c -o client-agent/start_agent.o
client-agent/start_agent.c: In function ‘start_agent’:
client-agent/start_agent.c:196:58: warning: ‘%s’ directive output may be truncated writing up to 6145 bytes into a region of size 6136 [-Wformat-truncation=]
  196 |                         snprintf(fmsg, OS_MAXSTR, "%c:%s:%s", LOCALFILE_MQ,
      |                                                          ^~
  197 |                                  "ossec", msg);
      |                                           ~~~             
client-agent/start_agent.c:196:25: note: ‘snprintf’ output between 9 and 6154 bytes into a destination of size 6144
  196 |                         snprintf(fmsg, OS_MAXSTR, "%c:%s:%s", LOCALFILE_MQ,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  197 |                                  "ossec", msg);
      |                                  ~~~~~~~~~~~~~
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/  client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver.o client-agent/receiver-win.o client-agent/sendmsg.o client-agent/start_agent.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz  -levent ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-agentd
/usr/bin/ld : client-agent/config.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/event-forward.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/intcheck_op.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/main.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/notify.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/receiver.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/sendmsg.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : client-agent/start_agent.o:(.bss+0x0) : définitions multiples de « server_ibuf »; client-agent/agentd.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : os_net.a(os_net.o):(.bss+0x0) : définitions multiples de « agt »; client-agent/config.o:(.bss+0x10088) : défini pour la première fois ici
collect2: error: ld returned 1 exit status
make: *** [Makefile:1017 : ossec-agentd] Erreur 1

 Error 0x5.
 Erreur de compilation. Impossible de finir l'installation.

**Comment by atomicturtle** [comment]
What distribution and architecture is this on?

**Comment by gerorymo-mtm** [comment]
So I have the same issue here. What is the probable cause and resolution? Any hints?
