### ISSUE TITLE
False Positives from rule 18138 Logon Failure - Account locked out.

### ISSUE THREAD

**Issue by martindiv** [ossec/ossec-hids#293]
msauth_rules.xml has rule number 18138.

This rule looks for events ids 539 and 4625. Event id 4625 is a standard log on failure and not a lock out notification. This is generating a large number of false positives for this rule.

Thanks.

**Comment by mstarks01** [comment]
I have no plans to submit any more pull requests or direct contributions to OSSEC, other than maybe bug reports. Please use the info I provided in my initial response and use it to create a rule if you like.

**Comment by awiddersheim** [comment]
That is unfortunate.

**Comment by lostinthetubez** [comment]
This seems like an easy fix. ID# 4625 is "Unknown username or bad password." It is simply included under the wrong rule. In msauth_rules.xml, it should be removed from 18138 and added to 18130. It is already a part of parent rule 18106, so it seems like it was just added to the wrong child rule. Here is a log sample from Windows Server 2008:

2015 Jan 26 06:59:41 WinEvtLog: Security: AUDIT_FAILURE(4625): Microsoft-Windows-Security-Auditing: (no user): no domain: hostname.domain.com: An account failed to log on. Subject:  Security ID:  S-1-5-18  Account Name:  HOSTNAME$  Account Domain:  DOMAIN  Logon ID:  0x3e7  Logon Type:   10  Account For Which Logon Failed:  Security ID:  S-1-0-0  Account Name:  EXAMPLE_USER  Account Domain:  DOMAIN  Failure Information:  Failure Reason:  %%2313  Status:   0xc000006d  Sub Status:  0xc0000064  Process Information:  Caller Process ID: 0x2b70  Caller Process Name: C:\Windows\System32\winlogon.exe  Network Information:  Workstation Name: HOSTNAME  Source Network Address: 1.2.3.4  Source Port:  54180  Detailed Authentication Information:  Logon Process:  User32   Authentication Package: Negotiate  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon request fails. It is generated on the computer where access was attempted.

**Comment by awiddersheim** [comment]
@lostinthetubez Thanks for looking into this. Would you be able to provide a pull request to fix? If not I can look at coming up with something.

**Comment by awiddersheim** [comment]
Also, @martindiv and @labrown, do you have any input on @lostinthetubez analysis?

**Comment by awiddersheim** [comment]
This should now be fixed in #527.
