### ISSUE TITLE
report_changes doesn't work

### ISSUE THREAD

**Issue by sakalajuraj** [ossec/ossec-hids#294]
I have problem with report_changes. 
I use Centos 6.5 with ossec 2.8.1 (server) installed. My configuration is like this:
....
<directories check_all="yes" realtime="yes" report_changes="yes">/var/spool/cron,/etc</directories>
...
I can see changes detected in /var/ossec/queue/diff/... directory, but no alerts are generated.
When I erase report_changes directive from configuration and restart ossec, I can see alerts generated after changing files.
Anyone with this problem?

**Comment by atomicturtle** [comment]
Yes that is the correct configuration, closing this issue out as resolved.

**Comment by jsmucr** [comment]
Why is this issue closed? I can't see how was the problem resolved. I experience it too on RHEL 5.1 with OSSEC 2.8.0.

**Comment by axot** [comment]
Yes, this issue also happened with realtime option. Please fix it.
