### ISSUE TITLE
Tunable Agent Disconnect Timeout

### ISSUE THREAD

**Issue by theckman** [ossec/ossec-hids#30]
Quick feature request. It looks like OSSEC won't recognize an Agent disconnect until 1830 seconds after the last keep alive. Would it be possible to make the disconnect time a tunable number in the OSSEC configuration?

I believe I saw mention of this in the past on the mailing list, but I've lost the thread and it doesn't look like it ever made it in to OSSEC.

Cheers!

**Comment by jrossi** [comment]
Looks like not enough call for this change.
