### ISSUE TITLE
Windows agent 2.8 can't start and configure because of permissions

### ISSUE THREAD

**Issue by dsvetlov** [ossec/ossec-hids#303]
Hi!

When I try to configure fresh install of OSSEC Agent 2.8 or 2.8.1 for Windows, agent can't write our new configuration file and start. It shows 2 errors: "Unable to set permissions on new configuration file" and "Unable to set permissions on auth key file". 

I have try to install agent 2.7.1, configure it with key and server IP, then update it to version 2.8.1 and it works fine,

**Comment by FatmaG** [comment]
Has no updates been released yet?

**Comment by awiddersheim** [comment]
This fix should be in the 2.9 beta. You can download it here:

https://github.com/ossec/ossec-hids/releases/tag/2.9.0-beta02

Testing would be greatly appreciated.

**Comment by FatmaG** [comment]
Thank you for your kind help, I have been able to surpass this error "Unable to set permissions on new configuration file" using icalcs regarding Windows7(using Administrative permission).
However the error of the "auth key file" still persisted.
my ossec.log > 
I had to use the previous version ossec 2.7.1 in order to connect to the server.

**Comment by awiddersheim** [comment]
You tried the beta and it did not work? What were the errors in the logs?

**Comment by FatmaG** [comment]
Thaks for the quick response , i have updated my answer

**Comment by awiddersheim** [comment]
And these errors were with the beta I linked or OSSEC 2.8?

**Comment by FatmaG** [comment]
Yes , i have included the beta with ossec2.8 folder including the ossec-rootcheck.exe and win32ui.exe

**Comment by awiddersheim** [comment]
I'm sorry but I am still very confused as to what you did.

**Comment by FatmaG** [comment]
I have deleted the ossec-agent2.8 and replaced it with the beta in the same folder

**Comment by sergunz** [comment]
Hmm...I got 2.9 beta from https://github.com/ossec/ossec-hids/releases/tag/2.9.0-beta02, try to install it, but have no luck! 
Ossec dosnt install, txt file appears with this:
"2015/02/25 18:13:23 ossec-agent: INFO: Unable to set service information."

I try on some servers with Win 2008 R2 - same problem.

**Comment by awiddersheim** [comment]
Hrm, I just noticed the `ossec-agent.exe` download in that link isn't the installer. Let me get it fixed so the installer is given as the download instead of just the agent executable in the next OSSEC beta release.

This will make testing and troubleshooting a bit easier.

**Comment by miconx** [comment]
i have exactly the same problem with version 2.8.3 of the windows agent

**Comment by tjweg007** [comment]
Just wanted to add I had the same issue when configuring the agent on Windows via the OSSEC agent manager GUI, was able to get around the problem by running the program as administrator.
