### ISSUE TITLE
ossec with pgsql error

### ISSUE THREAD

**Issue by sechacking** [ossec/ossec-hids#308]
2014/09/23 19:03:01 ossec-dbd: Connected to database 'ossecdb' at '127.0.0.1'.
2014/09/23 19:03:01 ossec-dbd(5204): ERROR: Database error. Unable to run query.
2014/09/23 19:03:01 ossec-dbd(5203): ERROR: Error executing query 'INSERT INTO alert(server_id,rule_id,level,timestamp,location_id,src_ip,src_port,dst_ip,dst_port,alertid,user,full_log) VALUES ('1', '5501','3','1411470181', '3', '0', '0', '0', '0', '1411470180.1897', '(null)', 'Sep 23 19:03:00 seclogs sshd[4970]: pam_unix(sshd:session): session opened for user root by (uid=0)')'. Error: 'ERROR:  syntax error at or near "user"
LINE 1: ...cation_id,src_ip,src_port,dst_ip,dst_port,alertid,user,full_...
                                                             ^
'.
2014/09/23 19:03:01 ossec-dbd(5209): INFO: Closing connection to database.
2014/09/23 19:03:01 ossec-dbd(5210): INFO: Attempting to reconnect to database.
2014/09/23 19:03:01 ossec-dbd: Connected to database 'ossecdb' at '127.0.0.1'.
2014/09/23 19:03:01 ossec-dbd(5204): ERROR: Database error. Unable to run query.

**Comment by gjocher** [comment]
@sechacking, @jrossi this issue is already resolved by commit cc83f1edd1a7923102e4b6c53f97d0a1bd3a2b87
