### ISSUE TITLE
Add checksum to default alert "New file added to the file system"

### ISSUE THREAD

**Issue by mmohylko** [ossec/ossec-hids#314]
It would be nice if the message about the new file immediately recorded with check-sum of the file on the file system (for example, the emergence of malware). When using the standard rule <alert_new_files> you are notified only about the name of the file and its path. In order to analyze this file, you need to go to the server, see the check-sum of the file and then analyze this file. But if these files will be a lot (in proportion to the number of agents), the work becomes more complicated.

**Comment by Astaruf** [comment]
Did you find a solution or workaround to this issue?

**Comment by swindmill** [comment]
@mmogilko @mstarks01 @Astaruf this is now implemented in https://github.com/ossec/ossec-hids/commit/cb10d7f8cd44de078e8c5942079b39a49a6ac08c

**Comment by swindmill** [comment]
@ddpbsd should this issue now be closed as resolved?

**Comment by atomicturtle** [comment]
Yup, closed by #1940
