### ISSUE TITLE
SSL POODLE

### ISSUE THREAD

**Issue by cgzones** [ossec/ossec-hids#370]
Should we disable SSLv3, due to the latest bug https://www.openssl.org/~bodo/ssl-poodle.pdf via:

https://github.com/ossec/ossec-hids/blob/master/src/os_auth/ssl.c#L117

```
SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3);
```

?

**Comment by wclarie** [comment]
The concern about building against an OpenSSL version that does not support TLS 1.2 is valid for OS X. Why don't we allow TLS 1.0? The alternative is indeed to require Mac users to install a recent OpenSSL, but then the build infrastructure needs to be smart enough to find it. (It currently defaults to the system OpenSSL.)

**Comment by jrossi** [comment]
https://www.howsmyssl.com/s/about.html Is a good start sense we could kill 1.0 and 1.2 we did :)

**Comment by wclarie** [comment]
Well yes I know that, but a lot of these threats to TLS 1.0 are theoretical. I will look into the details a bit more and report back later.
