### ISSUE TITLE
Release 2.9.0

### ISSUE THREAD

**Issue by jrossi** [ossec/ossec-hids#375]
I am planning on releasing 2.9.0 with a much longer alpha/beta cycle.  

This is the issue for work related to it.  

As always input is requested. 
# Items left

Thing that need to be tested before release: 
### build system
- [ ] Test build on AIX ( build agent only, unless someone has root access to test with)
- [ ] test build on Solaris ( build agent only, unless someone has root access to test with)
- [ ] test build on hpux ( build agent only, unless someone has root access to test with)
- [ ] test build on mac osx 
- [ ] test build pn openbsd 
- [ ] test build on freebsd
- [ ] test build on netbsd 
- [ ] test build on ubuntu
- [ ] test build on centos
- [ ] test build on debian
- [ ] test build on arch 
### version updates
- [ ] Find all the locations of 2.8 and fix that. 
### Release notes
- [ ] Notifications about changes in build 
- [ ] Notification about future change in windows paths and syscheck 
- [ ] write them 
### document release process
- [ ] git release
- [ ] package: tar.gz
- [ ] package: deb
- [ ] package: rpm
- [ ] package: vm appliance 
- [ ] release notes format 
- [ ] tooling 
- [ ] blog update
### Lua support for decoders and rules

Not happening this release 
### srandom on more platforms
- [x] more testing
- [x] Review for chroot issues
- [ ] doulble check util applications
### atomic and src release should be same

i would like get atomic release inline with the source releases. need the following:
- [ ]  break up decoders 
- [ ]  Other stuff???
### astyle

I would very much like to see the completion of oRFC:2 and something like: 
https://github.com/jrossi/ossec-hids/compare/astyle-again 
- [ ]  oRFC:2 completed and accepted
- [ ]  astyle run and merged into master: #60 
### IPv6
- [ ] Code and rules for IPv6 
- [ ] Anything else?

**Comment by jrossi** [comment]
Removed lua from this release

**Comment by FunTimeCoding** [comment]
I'm trying to build ossec-hids on OS X. Currently I'm stuck here:

```
Undefined symbols for architecture x86_64: "__jflog", referenced from: _jsonout_output_event in jsonout.o
```

Build commands:

```sh
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
make PREFIX=/var/ossec DATABASE=mysql TARGET=server settings
make PREFIX=/var/ossec DATABASE=mysql TARGET=server build
```

I use openssl from brew.

**Comment by aremai** [comment]
Will test and provide builds for all Solaris releases (10 & 11, for x86 and sparc)
Is the current source code on github considered as 2.9.0? How much will change until the final release?

**Comment by aremai** [comment]
And release_instructions.txt sounds like a very good idea to me 👍

**Comment by ChristianBeer** [comment]
I didn't follow along since my last contribution and need to get up to date with the mailing list too. But what's the holdup for the 2.9 release?

**Comment by ddpbsd** [comment]
@ChristianBeer Time and energy mostly. I'm also wondering if we should start over with 2.9 and use the current code as the 2.9 beta. Or just skip 2.9 and release 3.0.

**Comment by ChristianBeer** [comment]
The CI tests are failing, would it be helpful if I invest some time to find out what's the issue?

**Comment by ddpbsd** [comment]
If the failures come from something not covered in PR #774 that would be great!

**Comment by ChristianBeer** [comment]
That should fix it. I would really like some guidance on what to prioritize in order to get the 2.9 release out of the door.

**Comment by aremai** [comment]
maybe @jrossi can answer this other than below issues?
https://github.com/ossec/ossec-hids/milestones/ossec-hids-2.9

**Comment by marcRBD** [comment]
Test build on OpenBSD--> ok on openBSD 6.0 amd64 as a server

**Comment by cgulliver** [comment]
Successfully tested build on FreeBSD 10.1-RELEASE i386 as a local type install.
