### ISSUE TITLE
Windows Agent Not Connecting when Server Restarts

### ISSUE THREAD

**Issue by ccx004** [ossec/ossec-hids#415]
Agent is running on Linux Kernel version 3.16.1. Ossec version is 2.8.1
Agent installed on Windows Server 2012R2. Agent and server can communicate as expected. However, if the server is restarted, the agent never reconnects completely. In the agent logfile the following error appears every 10 minutes:

More than 600 seconds without server response...sending win32info

I've left it for 8 hours but it never establishes a connection again. However, if I restart the agent on the windows server it connects straight away. I can also restart it from the server using agent-control so the server can get to the agent.

For both the server and the agent I have used the distributed binaries.

**Comment by nikhilve99** [comment]
Hi ,
i am also facing the same error, have you got any solution for this error.
kindly help.

Regards
Nikhil

**Comment by ccx004** [comment]
Dear Nikhil,

 

I’m afraid not. It is still an issue in 2.8.3. though as I checked that recently. 

 

Best wishes….

Colin

**Comment by nikhilve99** [comment]
Which version are you using now?

Regards
Nikhil
