### ISSUE TITLE
Windows Agents Do Not Report Their OS Type and Version Correctly

### ISSUE THREAD

**Issue by ccx004** [ossec/ossec-hids#416]
The server is running on Linux 3.16.1 and the OSSec version is 2.8.1. The agent is running on Windows Server 2012R2.

When an agent starts it makes a record of the OS type etc. in its local log file. In this case it is:

"INFO: System is Vista or newer (Microsoft Windows Server 2012 Standard Edition  (Build 9200) - OSSEC HIDS v2.8)."

However, if I run agent-control -I 001 on the server I get the correct information about the IP address and status but I also get:

Operating system:           Unknown
Client version:                 Unknown

I suspect this is not correct.

**Comment by awiddersheim** [comment]
@ccx004 I am not seeing this problem in my environment or able to really replicate this. @janaka are you just staying that 2012 (none R2) works fine and 2012R2 is not working and confirminng the issue or that you are also seeing the same thing as @ccx004 and 2012R2 is coming back as "unknown"?

Apologies, when I first read this bug I thought you were saying that 2012R2 was reporting as just 2012 (none R2) which is a bug I can confirm and will work toward fixing in a future release. This other bug where information is not coming back is news to me.

You sure the agent has connected properly? If the agent hasn't ever connected no OS version information would have made it back.

**Comment by awiddersheim** [comment]
Haven't heard back from @ccx004 on this issue and I'm not seeing this problem. Closing for now but feel free to post any details about the problem and I'll be happy to take a look.
