### ISSUE TITLE
Error in headers\shared.h

### ISSUE THREAD

**Issue by ccx004** [ossec/ossec-hids#419]
On line 86 or shared.h there is a line which reads #include <ws2tcpip.h>. However, gcc version 4.8.1 complains when any files that include this header. The error is:

"ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."

Winsock2.h is included in shared.h already.

**Comment by ddpbsd** [comment]
I'm no longer seeing this issue, all I see in a recent build is:
```
In file included from ./headers/shared.h:86:0,
                 from syscheckd/run_check.c:24:
/usr/share/mingw-w64/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
```
Which it is, in that file.
