### ISSUE TITLE
Add option to use unaltered hashes with Windows syscheck

### ISSUE THREAD

**Issue by denied39** [ossec/ossec-hids#42]
I use OSSEC in a mostly Windows environment and find it difficult to trace back files using MD5 hashes. I know that OSSEC concatenates the MD5 and SHA1 hashes, but it seems to do that only with Windows agents. The Linux agents in use produce the correct MD5 hashes which can be verified using third-party tools. 

Having the OSSEC Windows agent produce the same verifiable MD5/SHA1 hashes would enhance the forensic capabilities by allowing for a quick lookup of a file hash in a database or via the internet. Plus, it would eliminate the need to pull the same data twice from a computer.

Regards,
Mike

**Comment by santiago-bassett** [comment]
As reported in the mailing list this is still a problem. We will try to fix it and submit a pull request

**Comment by vikman90** [comment]
Windows doesn't appear to change intencionally the hash, but I found that OSSEC opens the files in text mode, and they should be opened in binary mode to work properly. I fixed this problem and sent the pull request, hoping that this solves the issue.

**Comment by mschilt** [comment]
Can this bug be closed since the fix was merged?
