### ISSUE TITLE
system_name inconsistency with hostname

### ISSUE THREAD

**Issue by mstarks01** [ossec/ossec-hids#444]
ossec-logtest presents the decoded hostname as 'system_name', but 'system_name' is not a decoded option. It would be best to label this 'hostname' so as to be consistent with other labels that do represent the actual decoded field name.

**Comment by ddpbsd** [comment]
Looks like this was changed a while back.
```
**Phase 1: Completed pre-decoding.
       full event: 'Dec 26 12:38:25 ix /bsd: atascsi_passthru_done, timeout'
       hostname: 'ix'
       program_name: '/bsd'
       log: 'atascsi_passthru_done, timeout'
```
