### ISSUE TITLE
manage_agent bulk load fails

### ISSUE THREAD

**Issue by ccx004** [ossec/ossec-hids#454]
manage_agents -f /tmp/agents fails with "file not found". I have since worked out that it does a chroot to /var/ossec and that is why it cannot find the files. So this is a query and a suggestion. The query is, is there any need for this program to do a chroot? The suggestion is to add some text to the help message that manage_agents -? produces to say that the file must be stored in the /var/ossec file structure somewhere.

Best wishes...
Colin

**Comment by awiddersheim** [comment]
This is a big breaking fix if bulk loads don't work in 2.9. Probably should fix this before it's released.

**Comment by coffmant** [comment]
There is a similar (same?) issue on the client side.

manage_agents(1128): ERROR: Could not create temporary file
'tmp/client.keys55sUAS' due to [(2)-(No such file or directory)].

**Comment by Fadavvi** [comment]
Any word around??

**Comment by sarah336** [comment]
Circle :)

**Comment by Fadavvi** [comment]
:)))
