### ISSUE TITLE
Rule 31533 might need an update

### ISSUE THREAD

**Issue by deajan** [ossec/ossec-hids#461]
Hi,

I'm running ossec 2.8.1 on multiple servers and usually get trouble with rule 31533 on multiple software that uses a lot of ajax POST commands (drupal, zarafa, etc).

The original rule says <rule id="31533" level="10" timeframe="20" frequency="6"> which as of my understandings means no more than 12 POST requests in 20 seconds.
As with modern software ajax is more and more used widely, shouldn't frequency be set to a much higher value like 50 ? (I actually tried 20 with Zarafa Webmail, still get that rule fired).

Regards,
Ozy.

**Comment by jrossi** [comment]
Thanks if you think this feature is important please submit a pull request..
