### ISSUE TITLE
segfault in analysisd caused by rule level change

### ISSUE THREAD

**Issue by mjeffe** [ossec/ossec-hids#463]
I recently upgraded OSSEC from version 2.7.1 to 2.8.1. The new version of analysisd kept segfaulting.  After a couple of weeks of working with it, I've narrowed it down to a simple rule override in `local_rules.xml` where I downgrade the level. Below I describe my test scenario where I can consistently reproduce the segfault with a bare minimum.

Current environment is Amazon AWS VPC. All servers are running Amazon Linux 64-bit AMI's (based on RHEL/CentOS).
```
[root@ossectst ossec]# uname -a
Linux ossectst 3.14.23-22.44.amzn1.x86_64 #1 SMP Tue Nov 11 23:07:48 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Here is what I did:

1) I spun up a brand new server (clone of my current ossec server), installed a fresh 2.8.1 ossec server. Modified local_rules.xml to look like this:

```
<!-- @(#) $Id: ./etc/rules/local_rules.xml, 2011/09/08 dcid Exp $
<group name="local,syslog,">
  <!-- downgrade from level 7 to level 5 -->
  <rule id="533" level="5" overwrite="yes">
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat -tan</match>
    <check_diff />
    <description>Listened ports status (netstat) changed (new port opened or closed).</description>
  </rule>
</group> <!-- SYSLOG,LOCAL -->
```
I did NOT add any agents, but let that run for about an hour (may not be necessary).

2) I then stopped the ossec server, ran manage_agents, added one agent and restarted the ossec server. NOTE, I did not transfer the agent key, so the agent was not trying to communicate yet. I let that run for about an hour (again, may not be necessary).

3) I transferred the key to the agent - this is an existing agent, I just added the new key and change the `<server-ip>` to point to my new test server and restarted the agent and server. I begin to see communication between server and agent. I let it run it's initial scans - about 10 minutes.

4) Then I opened a new listen port to try and trigger the `netstat -tan` rule using `nc -l 7777` on the agent.

5) ossec-analysisd segfaulted after about 7 minues.

Let me know if you want any of the output or if you want me to run any other tests.

Note, I initially posted this to https://groups.google.com/forum/#!topic/ossec-list/WM3v7fmaS6I with the same subject title.  *dan (ddpbsd)* was able to reproduce the segfault using the above information, but there was no resolution, so it was suggested I post here.

**Comment by jrossi** [comment]
@mjeffe did you by chance get time to test out @ddpbsd potential fix?

**Comment by mjeffe** [comment]
I did not look into it over the christmas break. I've got a current workaround so my production system is functional.  I still want to help with this issue however, so I will try to test the fix this week.

**Comment by mjeffe** [comment]
For some reason src/header/zlib.h and zconf.h were missing from the diff_overwrite branch.  I grabed them from my current  2.8.1 src/header dir and was then able to complie and install.

```
In file included from os_crypto/shared/keys.c:21:0:
./os_zlib/os_zlib.h:14:18: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
                  ^
```

Now I'll try to crash it...

**Comment by mjeffe** [comment]
Well, it's been running all day with no segfault. I'll let it run over the weekend and then report back.

**Comment by mjeffe** [comment]
It ran all weekend with no segfaults. Anything else you guys need me to try?

**Comment by ddpbsd** [comment]
@mjeffe Thanks for testing.I'll open a pull request.

**Comment by jrossi** [comment]
@mjeffe Accepted into master. Closing ticket.
