### ISSUE TITLE
ossec blocks reverse dns instead of IP address

### ISSUE THREAD

**Issue by deajan** [ossec/ossec-hids#469]
Running ossec 2.8.1 plus latest firewalld-drop.sh script from github on CentOS 7 x64.

I have multiple /var/log/secure entries like
```
vsftpd[25686]: pam_unix(vsftpd:auth): authentication failure; logname= uid=0 euid=0 tty=ftp ruser=test1@someofmydomains.com rhost=XX.XXX.XXX.XXX.thebadguysdomain.telecom.kz
```

ossec log files show the following:
```
Tue Dec 23 08:36:52 CET 2014 /var/ossec/active-response/bin/host-deny.sh add - XX.XXX.XXX.XXX.thebadguysdomain.telecom.kz 1419320212.127445 5551
Tue Dec 23 08:36:52 CET 2014 /var/ossec/active-response/bin/firewalld-drop.sh add - XX.XXX.XXX.XXX.thebadguysdomain.telecom.kz 1419320212.127445 5551
```

Indeed /etc/hosts.deny file shows
```
ALL:XX.XXX.XXX.XXX.thebadguysdomain.telecom.kz
```

As of my understandings, reverse dns aren't allowed in this file.
Also, i happen to get ossec notifications from /var/log/secure with vsftpd complaining about this:

```
vsftpd[24549]: warning: /etc/hosts.deny, line 1: can't verify hostname: gethostbyname(XX.XXX.XXX.XXX.thebadguysdomain.telecom.kz) failed
```

Anything i missed in my config ?

**Comment by jrossi** [comment]
Decoding DNS is something I would suggest doing very very selectively and on the backend.  If this is really some import I would suggest writing a simple process that listens via ZeroMQ and processes the event and does DNS lookups it's self.  Start here: http://ossec-docs.readthedocs.org/en/latest/syntax/head_ossec_config.global.html#element-zeromq_uri and here:  https://github.com/ossec/ossec-hids/blob/master/contrib/zeromq_pubsub.py

If you think this is a really important feature for the core of ossec. Please create a pull request.
