### ISSUE TITLE
Ossec do not read Windows 2012 Logs

### ISSUE THREAD

**Issue by Barns1988** [ossec/ossec-hids#470]
Running ossec 2.7.1 or 2.8 on windows 2012 R2

Part of ossec.conf
<localfile>
  <loation>System</location>
  <log_format>eventlog</log_format>
</localfile>

OK... ossec-agent logs looks ok...
Starting Ossec and check archive-file on server-side: there is no event from Security-log

Running ossec in debug mode "1" do not show any problems in log file...

Any idea why it happens?

**Comment by jrossi** [comment]
Are you sure they are eventlog and not eventchannel (I don't know mich about windows but i do read MSDN docs sometimes).

**Comment by Barns1988** [comment]
Oh...
If in config I write eventlog - there is no events, work only with eventchannel :-)
About not all logs - it was some windows-problems
After some reboots and updates it work fine
