### ISSUE TITLE
Notifications would be more helpful if they contained "whois" abuse-mailbox contact for <srcip>

### ISSUE THREAD

**Issue by furriephillips** [ossec/ossec-hids#475]
If you want to act on the "OSSEC HIDS Notification" emails regarding network abuse, by submitting abuse reports to the organization responsible for the source IP, you have to check the "whois" records of the IP address, for "abuse-mailbox", or other "abuse" records (or if none are found, give up & move on).

It'd be much simpler and easier to report abuse (or save time on a lost cause), if OSSEC would do the grunt work & include the relevant whois records after the "Portion of the log" and before the "--END OF NOTIFICATION".

Compiled code is not my forte, or I'd have a go at modifying the source myself & offering a patch, so I hope that the following shell example shows the sort of thing I'm suggesting - basically that the notification emails include the output of this string of command (made it multi-line for easier reading): -

    srcip='93.184.216.34' \
        ; whois ${srcip} | grep "^abuse-mailbox" \
        || whois ${srcip} | grep -i abuse \
        || whois ${srcip}

I hope this is an acceptable post - it's my first, please be gentle :)

**Comment by jrossi** [comment]
Doing this directly inline would be problematic, but doing it via zeromq and your programming lang of choice you could do this.  Something things in contrib might give good hints.

https://github.com/ossec/ossec-hids/blob/master/contrib/zeromq_pubsub.py is a good place to start. You will need to make sure Zeromq is enabled and setup and compiled it but start here with the following two links: 

* https://ossec-docs.readthedocs.org/en/latest/syntax/head_ossec_config.global.html?highlight=zeromq#element-zeromq_output
* https://www.mehmetince.net/cyber-threat-monitoring-system-with-ossec-zeromq-logstash-elasticsearch-and-kibana/

Doing this in python would be simple: 

```
import zmq
import pythonwhois

context = zmq.Context()
s = context.socket(zmq.SUB)
s.connect("tcp://localhost:11999")
s.setsockopt(zmq.SUBSCRIBE, "")
while 1:
    d = s.recv_json()
    if "srcip" in d: 
         x = pythonwhois.get_whois(d["srcip"])
         if len(x.contact) > 1:
               print x.contact # do other stuff here. 
    
```

Doing this OUTSIDE of ossec is the key to make sure ossec is simple and fast.  I am going to close this as I don't know what else to do with this ticket after giving the above examples.  Also; You might alway want to check out the mailing list.
