### ISSUE TITLE
Parse date and time from logs

### ISSUE THREAD

**Issue by Barns1988** [ossec/ossec-hids#487]
Hello!
I have some software, which ha logs formatted '2014-01-01 12:00 Some_event'
In ossec books (http://www.ossec.net/ossec-docs/OSSEC-book-ch4.pdf) I read how to decode date/time from logs, but... OSSEC server 2.8.1 always return errors in decoder.
Can you tell me, maybe this book is old and not actual?

**Comment by ddpbsd** [comment]
What do you want to do with the date/time? How does ossec-logtest currently decode the log message?
This might work:
```
<prematch>^\d\d\d\d-\d\d-\d\d \d\d:\d\d </prematch>
```

This issue would probably also be easier to deal with on the mailing list.

**Comment by Barns1988** [comment]
This is my test decoder
```
<decoder name="test">
    <prematch>testlog</prematch>
    <regex>(\d+.\d+.\d+)</regex>
    <order>time(/order>
</decoder>
```
logtest return:
decode-xml: Wrong field 'time' in the order of decoder 'test'

No matter name of field (time, date, date/time, etc.) it return error

**Comment by ddpbsd** [comment]
Here's a list of the possible "order" field names:
http://ossec-docs.readthedocs.org/en/latest/syntax/head_decoders.html#element-decoder.order

extra_data might be the best option for this.

**Comment by Barns1988** [comment]
Thanks...
I had read sources and found it...
Now I`m workind on decoder to make it parse date/time
Later I try to share my customization

**Comment by Barns1988** [comment]
Well
It is done - ossec parse date and time correctly
How to share it?

**Comment by ddpbsd** [comment]
Either provide it here, issue a pull request, or send it to the mailing list
