### ISSUE TITLE
Request to have check_rc_sys.c skip comparison between directory entry count and link count on Unionfs hosts

### ISSUE THREAD

**Issue by GitHubEmail** [ossec/ossec-hids#490]
Hi,

I've noticed a large number of "Link count does not match number of files" events on hosts that are using Unionfs (unionfs.filesystems.org). While I strongly suspect that Unionfs is the culprit, I should state up front that I have not investigated a reproducible test case for this at this time. However, I believe that I can demonstrate the issue sufficiently to support this request.

On the ext4 fs, we observe the expected link count of 2 for a freshly created directory, and a link count of 3 once a subdirectory of has been created in the parent directory:

`$ mkdir a ; stat a | grep Links:`
`Device: 801h/2049d Inode: 268367      Links: 2`
`$ mkdir a/b ; stat a | grep Links:`
`Device: 801h/2049d Inode: 268367      Links: 3`

However, observe the following on a host using Unionfs:

`$ mkdir a ; stat a | grep Links:`
`Device: eh/14d Inode: 25555      Links: 1`
`$ mkdir a/b ; stat a | grep Links:`
`Device: eh/14d Inode: 25555      Links: 1`

I have OSSEC installed on a sufficient number of hosts using Unionfs as well as hosts not using it that a correlation seems plausible, given that only the Unionfs hosts are reporting this behavior. Each Unionfs host may trigger several hundred alerts for various directories, including:

`/usr/lib/python2.6/dist-packages`
`/usr/lib/python2.5`
`/usr/lib/pkgconfig`
`/usr/lib/perl5/auto/Term/ReadKey`
`/usr/lib/perl5/auto/File/Sync`

and many, many more. I have the utmost confidence that while OSSEC is accurately reporting its findings, the alerts themselves are not indicative of a security issue, but are a result of the link count data returned by the OS/filesystem. As such, I'd like to simply request the ability to disable this check for hosts using Unionfs.

Thanks.

**Comment by ddpbsd** [comment]
Do you know of an easy way to determine if the mount is a unionfs mount in C?

**Comment by GitHubEmail** [comment]
Unfortunately I do not. Thinking about it, rather than only looking for Unionfs, an even better idea might be to have OSSEC do a more generic check on each local fs. For example, it could obtain a list of filesystems from /etc/fstab, then create a randomly named temporary directory on each, and check the link count. If it's not 2, the link count check for that particular filesystem could be disabled (unless there was an issue creating the directory, such as the fs being read-only).

This check could be done when OSSEC is first installed. It could also be a user configurable option (disabled by default).

The benefit is that this would catch Unionfs as well as any other unorthodox filesystems that may exhibit the same unexpected link count behavior.

**Comment by jrossi** [comment]
Have you seen #471 looks like this would be what you are looking for?  I don't know about unionfs itself, but should follow the same path.

**Comment by GitHubEmail** [comment]
That could be one solution, yes. However, I think that possibly a more generic check could be an even better blanket solution (see my previous comment above). Thanks.

**Comment by mschilt** [comment]
Hi. any news here? just run into the same issue with a honeypot for Mirai.
