### ISSUE TITLE
make ossec user not be able to login

### ISSUE THREAD

**Issue by sedrubal** [ossec/ossec-hids#498]
After I installed ossec, the ossec  user appeared at login screen. Please make these users not be able to login.

**Comment by ddpbsd** [comment]
The password field on my system was set to "!!" which should prevent logins via password, and the shell is set to /sbin/nologin. How are you logging onto the system as the ossec user?

**Comment by sedrubal** [comment]
ok thats strange.

I didn't try to login, but they appeared at lightdm login screen.

Unfortunately I removed ossec, so I can't search for more details.

**Comment by atomicturtle** [comment]
Did you build it from source or use the .deb packages?

**Comment by sedrubal** [comment]
yes I ran the installation.sh script (this is a very enterprise script ;) )

**Comment by jrossi** [comment]
http://askubuntu.com/questions/92349/how-do-i-hide-a-particular-user-from-the-lightdm-login-screen 

The install cannot take this into account.  Going to close unless someone knows a simple way across all distros.
