### ISSUE TITLE
Active Response with firewall-drop doesn't work

### ISSUE THREAD

**Issue by tvidal-34** [ossec/ossec-hids#503]
Dear OSSEC team,

I am using both on Ossec server&clients the last 2.8.1 Ossec version on debian Wheezy.
Copy and Paste event in ossec-logtest give me good output.
When agent.conf is modified the active response to restart all client is working fine.
Server and clients are using up to date and same agent.conf, ar.conf and merge.mg files.
All clients and md5sum of agent.con on the server are the same.
Dropping an IP by using on the server "firewall-drop.sh add -u toto x.x.x.x" is working fine and all clients drop the given IP and add a line in active-response.log
As this came from my last update at the end of december I am thinking this is a bug...

Many thanks and all the best

Thomas

**Comment by ddpbsd** [comment]
Troubleshooting is best done on the mailing list. More details would be necessary to classify this as an issue.
