### ISSUE TITLE
OSSEC 2.8.1 not reporting file deletions on FreeBSD 10.1

### ISSUE THREAD

**Issue by finid** [ossec/ossec-hids#505]
I have OSSEC 2.8.1 installed on FreeBSD 10.1 via pkg. OSSEC is alerting on file modifications and new files, but not on file deletions.

Is this a known issue on FreeBSD 10.1?

**Comment by jrossi** [comment]
We don't support Real Time on anything other then Windows and Linux.  It would take some work to make this work on *bsd using Kqueue or maybe http://blog.netbsd.org/tnf/entry/gsoc_2011_roundup_add_kqueue .

**Comment by finid** [comment]
The question does not partain to real-time alerting, just on normal alerting on file deletions. I think those are two different issues.

**Comment by finid** [comment]
I know that libinotify can be installed on FreeBSD. Is it necessary to install it. In other words, does installing it mae any difference to the functionality of OSSEC on FreeBSD 10.1?

**Comment by jrossi** [comment]
I understand but the feature set you are looking for is only available currently using realtime options.  If you have time you could try using libinotify to see if you can get this going on FreeBSD.  If you do please let us know and submit a Pull Request so that we can make it available to everyone.

**Comment by finid** [comment]
Ok, I  didn't know that alerting on file deletions worked together with real-time alerts.

I tried libinotify on another installion of 2.8.1 on FreeBSD 10.1, but I never got any alerts on file deletions, so I don't think it works.

**Comment by jrossi** [comment]
It will not work with out driving into the makefiles and maybe some headers files.  

https://github.com/dmatveev/libinotify-kqueue
> To use the library, all you need to do is to link your application
with it (adding -linotify to LDFLAGS works in almost all cases).
Of course, you will need to have include (-I) and linker (-L)
directories to be properly set in your project.
