### ISSUE TITLE
repeated_offenders does not work in windows agents

### ISSUE THREAD

**Issue by mfbiux** [ossec/ossec-hids#520]
I have 1 server and 6 agents, 3 centos and 3 Windows 2008. Active response is correctly operating for all agents and the repeated_offenders option is also configured in each agent.

The problem I'm facing is that while the linux servers are actually triggering the repeated_offenders option, the windows machines keep sending the delete command after the default timeout of 600 seconds. Is this happening to someone else?

**Comment by jrossi** [comment]
Trouble shooting ossec issues of this nature is best done on the mailing this.  This is for a few reason, but mostly due to the larger audience to help out with the issue.
