### ISSUE TITLE
Wrong port number in server installation message

### ISSUE THREAD

**Issue by finid** [ossec/ossec-hids#523]
After installing an OOSEC server on Ubuntu 14.04, I got the following about enabling remote syslog:

> Do you want to enable remote syslog (port 514 udp)? (y/n) [y]:

Isn't it supposed to be udp port 1514?

**Comment by jrossi** [comment]
Remote syslog is port is 514. http://en.wikipedia.org/wiki/Syslog#Protocol this this is what this question is asking about.
