### ISSUE TITLE
Fix vista_sec.csv

### ISSUE THREAD

**Issue by awiddersheim** [ossec/ossec-hids#525]
Fix formatting issue with https://github.com/ossec/ossec-hids/blob/master/src/win32/vista_sec.csv

![image](https://cloud.githubusercontent.com/assets/3237256/6004742/f7666b64-aad2-11e4-8123-8ec075bdb57f.png)

**Comment by ChristianBeer** [comment]
There is another illegal quoting at line 63 in that file.

**Comment by awiddersheim** [comment]
Any idea if fixing them will break the translations it does?

**Comment by ChristianBeer** [comment]
I think it actually fixes the file because those are supposed to be line breaks.

**Comment by ChristianBeer** [comment]
It seems that there are other issues because it's not a clean csv format. In csv you have to enclose a field in double quotes. But OSSEC just recognizes the first separator and reads the rest of the line as one field ,ignoring all other separators.
