### ISSUE TITLE
Test seems to fail intermittently

### ISSUE THREAD

**Issue by awiddersheim** [ossec/ossec-hids#532]
Keep getting intermittent failures with the following test:

![image](https://cloud.githubusercontent.com/assets/3237256/6027033/2d243508-abad-11e4-9ba1-79b641f4335c.png)

This happened before on a differnet check I believe. I think @cgzones just increased the timeout of that test.

**Comment by cgzones** [comment]
i have never encountered such a failure. Also this is not the sam test, for which the timeout was increased (this was a gethost related test). What for a system are you using (OS) and is your system maybe a slow one?

**Comment by awiddersheim** [comment]
This is actually happen when travis-ci is running the tests. It has happened twice now.

**Comment by cgzones** [comment]
in #534 i increased the timeout from the default of 4 seconds to 7. Hopefully this will help

**Comment by awiddersheim** [comment]
Hopefully fixed in #534.
