### ISSUE TITLE
Regex does not seem to like single quotes

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#543]
While looking into the asterisk decoder issue I ran across an oddity. Using the following decoder (I have commented out all asterisk decoders past the "asterisk" decoder):
```
<decoder name="asterisk-denied">
  <parent>asterisk</parent>
  <regex>failed for (\S+)</regex>
  <order>srcip</order>
</decoder>
```
I get the following output:
```
**Phase 1: Completed pre-decoding.
       full event: 'May 19 11:42:17 asterisk asterisk[5200]:
NOTICE[14808]: chan_sip.c:15889 in handle_request_register:
Registration from ‘”355″<sip:355@192.168.1.60>’ failed for
‘192.168.210.48’ – No matching peer found'
       hostname: 'asterisk'
       program_name: 'asterisk'
       log: 'NOTICE[14808]: chan_sip.c:15889 in
handle_request_register: Registration from
‘”355″<sip:355@192.168.1.60>’ failed for ‘192.168.210.48’ – No
matching peer found'

**Phase 2: Completed decoding.
       decoder: 'asterisk'
       srcip: '‘192.168.210.48’'
```

I don't think the single quotes should still be around the srcip, so I modify the decoder:
```
<decoder name="asterisk-denied">
  <parent>asterisk</parent>
  <regex>failed for '(\S+)' </regex>
  <order>srcip</order>
</decoder>
```
This provides the output:
```
**Phase 1: Completed pre-decoding.
       full event: 'May 19 11:42:17 asterisk asterisk[5200]:
NOTICE[14808]: chan_sip.c:15889 in handle_request_register:
Registration from ‘”355″<sip:355@192.168.1.60>’ failed for
‘192.168.210.48’ – No matching peer found'
       hostname: 'asterisk'
       program_name: 'asterisk'
       log: 'NOTICE[14808]: chan_sip.c:15889 in
handle_request_register: Registration from
‘”355″<sip:355@192.168.1.60>’ failed for ‘192.168.210.48’ – No
matching peer found'

**Phase 2: Completed decoding.
       decoder: 'asterisk'
**Phase 3: Completed filtering (rules).
```
Escaping the single quotes doesn't help, and \p doesn't cover it either.

**Comment by ChristianBeer** [comment]
I think it's because those are not ordinary single quotes. There are three types of single quotes:
``` type 1: ' type 2: ` type 3: ´ ```

Those in the log message look to me suspiciously like type 3 not type 1.

**Comment by ddpbsd** [comment]
Even copy/pasting the quotes from the log message into the decoder didn't help.

**Comment by ChristianBeer** [comment]
Yes, because those quotes are unicode quotes (UTF-8). The codes are: 0x2018 and 0x2019 and because they are two byte long the regex engine may not detect them. I had a similar issue with utf8 encoded log lines in analysisd some time ago.

**Comment by ddpbsd** [comment]
Cool, thanks. Must have been a gmail translation issue or something.

**Comment by ChristianBeer** [comment]
What about this log sample:
```
Dec 17 22:37:25 new asterisk[20110]: NOTICE[20127]: chan_sip.c:25030 in handle_request_register: Registration from '"6100" <sip:6100@127.0.0.1>' failed for '85.25.110.243:5188' - Wrong password
```

**Comment by ddpbsd** [comment]
I replaced the quotes in the sample I had with regular quotes and it worked fine.
