### ISSUE TITLE
Uid/gid conflict with qemu (libvirt) user.

### ISSUE THREAD

**Issue by ericv5** [ossec/ossec-hids#557]
Latest ossec install takes uid/gid 107, which is reserved for "qemu" (the libvirt) user.  

Accounts should not be created with uid/gid's below 500 as those are reserved for system accounts.  Reserved accounts are listed on any system in the file "/usr/share/doc/setup-*/uidgid".  

Please update the uid/gid.

**Comment by maus-** [comment]
I second this, I've been running into this issue for a while now. Its frustrating that things like the users and install paths are hardcoded into the binary.

**Comment by ddpbsd** [comment]
I don't think ossed chooses its uid. Doesn't it let the os assign one?

**Comment by maus-** [comment]
In my experienceossec has had the same static UID/GID assignment since 1.6 I'd pretty much always get  UID/GID 106-107

**Comment by mstarks01** [comment]
Are you guys installing from packages? My installs always seem to have >=500 UIDs.

**Comment by ddpbsd** [comment]
What os/distro are you using?

**Comment by maus-** [comment]
Linux/CentOS6.  I've always installed from the atomiccorp repos. https://www6.atomicorp.com/channels/atomic/centos/6/x86_64/RPMS/

**Comment by mstarks01** [comment]
Then this is likely a packaging/mainainer issue. I always install from source on CentOS and don't have this issue.

**Comment by ddpbsd** [comment]
Try a source install. If it happens from source, report back. If not,
report the issue to atomic.

Linux/CentOS6. I've always installed from the atomiccorp repos.
https://www6.atomicorp.com/channels/atomic/centos/6/x86_64/RPMS/

--
Reply to this email directly or view it on GitHub
<https://github.com/ossec/ossec-hids/issues/557#issuecomment-76531879>.

**Comment by ericv5** [comment]
This is unrelated to the source install from Github.  Closing issue.  

Thanks
