### ISSUE TITLE
Email alerts not working on OSSEC 2.8.1 Ubuntu

### ISSUE THREAD

**Issue by finid** [ossec/ossec-hids#558]
I'm running a local installation  of OSSEC on Ubuntu 14.04. I have SSMTP as the SMTP server and I can send test emails using `ssmtp`. 

I have the following email settings in `ossec.conf`.

```
<global>
    <email_notification>yes</email_notification>
    <email_to>14test@gmail.com</email_to>
    <smtp_server>localhost</smtp_server>
    <email_from>14test@gmail.com</email_from>
  </global>
```

But email alerts are not being sent. The lines in `ossec.log` are:

```
ossec-maild(1223): ERROR: Error Sending email to 127.0.0.1 (smtp server)
```
Is this a known issue or is it just my settings that are off?

**Comment by ChristianBeer** [comment]
Please take a look at the ssmtp log file. It seems to me that it refuses to accept the mail. Perhaps the wrong HELO line. This is hardcoded in ossec <= 2.8.1 to notify.ossec.net

**Comment by finid** [comment]
There's nothing in the system-wide mail error log, just those lines in `ossec.log`. 

Where is it hardcoded in OSSEC?

**Comment by santiago-bassett** [comment]
It's here:

src/error_messages/error_messages.h:#define SNDMAIL_ERROR   "%s(1223):
ERROR: Error Sending email to %s (smtp server)"

And here you have where that variable is used:

santiago@Shark:~/Desktop/Github/ossec-hids$ grep -i -R SNDMAIL_ERROR *

src/error_messages/error_messages.h:#define SNDMAIL_ERROR   "%s(1223):
ERROR: Error Sending email to %s (smtp server)"

src/os_maild/maild.c:                    merror(SNDMAIL_ERROR, ARGV0,
mail->smtpserver);

src/os_maild/maild.c:                    merror(SNDMAIL_ERROR, ARGV0,
mail->smtpserver);

src/os_maild/maild.c:                    merror(SNDMAIL_ERROR, ARGV0,
mail->smtpserver);

src/os_maild/maild.c:                merror(SNDMAIL_ERROR, ARGV0,
mail->smtpserver);

If I had to guess that doesn't look like a bug, but an issue with your SMTP
server configuration. I would use tcpdump to see if there is traffic sent
to the smtp server.

I hope it helps,

Santiago.

**Comment by finid** [comment]
Thanks. I'll take a closer look at tit.

**Comment by jblaine** [comment]
Please come back and close this issue, finid, if you found a solution. It looks very much like an issue with your host and not OSSEC 2.8.1 on Ubuntu (which works fine for us).

**Comment by awiddersheim** [comment]
As mentioned by @jblaine this is likely an issue with @finid host. Better discussed on mailing list.

https://groups.google.com/forum/#!forum/ossec-list

**Comment by anhdt1987vn** [comment]
I have same problem.
On my Ubuntu 14.04
ssmtp/sendmail/mailx are successful.

**ssmtp xxxxx@gmail.com < /var/mail/root
echo test | mail -v -s "testing ssmtp setup" xxxxx@gmail.com**

But, I got same error with OSSEC
 ```
<email_notification>yes</email_notification>
 <email_to>xxxx@gmail.com</email_to>
 <smtp_server>localhost</smtp_server>                                                                                                                              
 <email_from>xxxx@gmail.com</email_from>
 <email_maxperhour>100</email_maxperhour>
```

error from ossec.log
ossec-maild(1223): ERROR: Error Sending email to 127.0.0.1 (smtp server)

Please help me on this problem!
Thanks

**Comment by ddpbsd** [comment]
@anhdt1987vn Are there any errors in your smtpd's log file?

**Comment by anhdt1987vn** [comment]
@ddpbsd 
Thanks for quick reply!.

I have just removed ssmtp pakage.

I'm using postfix.

--
OSSEC config.
```
 <global>
       <email_notification>yes</email_notification>
       <email_to>duycuongxxx@gmail.com</email_to>
       <smtp_server>localhost</smtp_server>
       <email_from>service.XXX@gmail.com</email_from>                                                                                                                 
       <email_maxperhour>100</email_maxperhour>
    </global>
```

Results after run.
**/var/ossec/bin/ossec-control restart**

-->
/var/log/mail.log 
`
duycuong postfix/smtpd[19644]: connect from localhost[127.0.0.1]
duycuong postfix/smtpd[19644]: 50E8A2AFEA7: client=localhost[127.0.0.1]
duycuong postfix/cleanup[19647]: 50E8A2AFEA7: message-id=<20160906103716.50E8A2AFEA7@duycuong>
duycuong postfix/qmgr[16771]: 50E8A2AFEA7: from=<service.XXX@gmail.com>, size=631, nrcpt=1 (queue active)
duycuong postfix/smtpd[19644]: disconnect from localhost[127.0.0.1]
duycuong postfix/smtp[19648]: 50E8A2AFEA7: to=<duycuongxxx@gmail.com>, relay=smtp.gmail.com[64.233.187.109]:587, delay=1.3, delays=0.11/0.04/0.98/0.     18, dsn=5.5.1, status=bounced (host smtp.gmail.com[64.233.187.109] said: 530-5.5.1 Authentication Required. Learn more at 530 5.5.1  https://support.google.com/mail/answer/14257 t17sm30699194pfi.17 - gsmtp (in reply to MAIL FROM command))
postfix/cleanup[19647]: CB1252AFEB8: message-id=<20160906103717.CB1252AFEB8@duycuong>

duycuong postfix/bounce[19649]: 50E8A2AFEA7: sender non-delivery notification: CB1252AFEB8
duycuong postfix/qmgr[16771]: CB1252AFEB8: from=<>, size=2701, nrcpt=1 (queue active)
duycuong postfix/qmgr[16771]: 50E8A2AFEA7: removed

duycuong postfix/smtp[19648]: CB1252AFEB8: to=<service.XXX@gmail.com>, relay=smtp.gmail.com[173.194.72.108]:587, delay=1.2, delays=0.04/0/0.99/0.1     9, dsn=5.5.1, status=bounced (host smtp.gmail.com[173.194.72.108] said: 530-5.5.1 Authentication Required. Learn more at 530 5.5.1  https://support.google.com/mail/answer/14257 vt5sm4318759pab.43 - gsmtp (in reply to MAIL FROM command))
postfix/qmgr[16771]: CB1252AFEB8: removed   `


**netstat -nutlap | grep 25**
`tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      16767/master`

vim /etc/postfix/main.cf


```
 myhostname = duycuong
 alias_maps = hash:/etc/aliases
 alias_database = hash:/etc/aliases
 mydestination = root@duycuong, duycuong, localhost.localdomain, localhost
 relayhost = [smtp.gmail.com]:587
 mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128                                                                                                             
 mailbox_size_limit = 0
 recipient_delimiter = +
 inet_interfaces = all
 smtp_tls_security_level = encrypt
 inet_protocols = ipv4
 smtp_sasl_auth_enable = yes
 smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
 smtp_sasl_security_options =
```


cat /etc/postfix/sasl_passwd

`smtp.gmail.com:587    service.XXX@gmail.com:PWDHERE`

**Comment by ddpbsd** [comment]
From your logs:
```
duycuong postfix/smtp[19648]: 50E8A2AFEA7: to=duycuongxxx@gmail.com, relay=smtp.gmail.com[64.233.187.109]:587, delay=1.3, delays=0.11/0.04/0.98/0. 18, dsn=5.5.1, status=bounced (host smtp.gmail.com[64.233.187.109] said: 530-5.5.1 Authentication Required. Learn more at 530 5.5.1 https://support.google.com/mail/answer/14257 t17sm30699194pfi.17 - gsmtp (in reply to MAIL FROM command))
```

**Comment by anhdt1987vn** [comment]
@ddpbsd 
got it, 

```
[smtp.gmail.com]:587 servicexxx@gmail.com:xxxxxx         <----- correct
smtp.gmail.com:587 servicexxx@gmail.com:xxxxxx         <----- incorrect
```

Thanks!
