### ISSUE TITLE
End of DATA not accepted by server

### ISSUE THREAD

**Issue by finid** [ossec/ossec-hids#559]
I've searched  for this,   but did not find anything useful, so I'm posting here.

I have a local installation on Fedora 21. When it is configured to send alerts to a GMail account, using a GMail SMTP server, sending alerts fail with the following in the error log:

```
os_sendmail(1767): WARN: End of DATA not accepted by server
ossec-maild(1223): ERROR: Error Sending email to 74.125.24.27 (smtp server)
```

The **From** address  uses a FQDN. Also, there's no email server or software installed locally, so no other error log to look at. What could be wrong?

TIA

**Comment by ddpbsd** [comment]
Use tcpdump to see if there is a more detailed error provided by google's server, or install a local smtpd to handle the mail exchange better. People have had this working before, so I don't think it's a bug and would probably be easier to troubleshoot on the mailing list.

**Comment by awiddersheim** [comment]
Closing. Better discussed on the mailing list as mentioned by @ddpbsd.

https://groups.google.com/forum/#!forum/ossec-list
