### ISSUE TITLE
Investigate eventchannel XPATH query not working

### ISSUE THREAD

**Issue by awiddersheim** [ossec/ossec-hids#568]
Relevant information:

https://ossec-docs.readthedocs.org/en/latest/manual/monitoring/index.html#element-query
https://groups.google.com/forum/#!topic/ossec-list/ptxY3iTa0bg

**Comment by jbcheng** [comment]
From ossec-hids/src/Makefile it shows an EXE file should be built ( ossec-agent-eventchannel.exe ). However, the installation file (http://www.ossec.net/files/ossec-agent-win32-2.8.exe) does not seem to contain this file.  Two questions: 
1. Is ossec-agent-eventchannel.exe required ?
2. If yes, did we forget to pack it?

**Comment by awiddersheim** [comment]
The `ossec-agent-eventchannel.exe` actually gets renamed to `ossec-agent.exe` or completely deleted depending on platform. See the following:

https://github.com/ossec/ossec-hids/blob/master/src/win32/ossec-installer.nsi#L176-L181

**Comment by jbcheng** [comment]
OK, that answered the file name question. However, I cannot verify whether the http://www.ossec.net/files/ossec-agent-win32-2.8.exe contains the renamed ossec-agent-eventchannel.exe with or the ossec-agent.exe without EVENTCHANNEL_SUPPORT. 
Since there are multiple ways to build Windows agent, (Makefile / make.sh / make.bat ), I am not sure all the make scripts are in sync.

**Comment by awiddersheim** [comment]
I'd like to think the agent would tell you when it starts if you have eventchannel support or not based on what you've configured. For example, if you specify the following and no errors show up in the event logs than it's probably safe to assume you have an agent running with eventchannel support:

```
<localfile>
  <location>System</location>
  <log_format>eventchannel</log_format>
</localfile>
```

You can test this by putting in something incorrect in the `log_format` field like:

```
<localfile>
  <location>System</location>
  <log_format>foobar</log_format>
</localfile>
```

That said, we've done our best, especially recently is 2.9 to get rid of all those make options and unify things to just use Makefile. I'd stick to the release builds as well since they *SHOULD* have the eventchannel support.

**Comment by awiddersheim** [comment]
I believe this was fixed in https://github.com/ossec/ossec-hids/pull/745.
