### ISSUE TITLE
RPM spec files

### ISSUE THREAD

**Issue by nigelhorne** [ossec/ossec-hids#574]
When will the spec files for the server be updated from 2.7 to 2.8?

**Comment by awiddersheim** [comment]
I'm not sure anyone really maintains these SPEC files. Most people just use atomic's repository and RPMs for OSSEC:

https://www5.atomicorp.com/channels/atomic/

Pull requests are welcome if you'd like to update and maintain these other wise I'd suggest using atomic's version of the RPMs.

@ossec Maybe we should consider removing these.

**Comment by dsvetlov** [comment]
Hi, all!

I was very surprised, when saw this issue. I have try to find specs in last year and it was unsuccessful. In finish I just take Atomic's src.rpm, unpack it, disable Atomic's patches and build vanilla OSSEC rpms. 

I think it'll be better to keep specs inside OSSEC project. How knows what will happen with Atomic. Anyway I'll prefer to use original specs.

I hope, I'll find time in next weekend to check what is wrong with current SPECS, and how to use it. Then I will make pull request.

**Comment by atomicturtle** [comment]
@awiddersheim agreed here, we should just drop this from the package

**Comment by nigelhorne** [comment]
On 4/11/15 12:07 PM, Andrew Widdersheim wrote:
>
> I'm not sure anyone really maintains these SPEC files. Most people 
> just use atomic's repository and RPMs for OSSEC:
>
> https://www5.atomicorp.com/channels/atomic/
>
> Pull requests are welcome if you'd like to update and maintain these 
> other wise I'd suggest using atomic's version of the RPMs.
>
> @ossec <https://github.com/ossec> Maybe we should consider removing these.
>

Some of the parameters of ossec (e.g. maximum number of agents) can only 
be tweaked by rebuilding, so using a pre-built RPM is not an option.

KR,

-Nigel
