### ISSUE TITLE
SPEC files don't work in a Mock build enviroment

### ISSUE THREAD

**Issue by nigelhorne** [ossec/ossec-hids#575]
They assume that the target area on the machine where the server is to be deployed is the same as on the machine where you're creating the RPM.

**Comment by awiddersheim** [comment]
See #574.

**Comment by SoftWarrior** [comment]
Great job though...can I know what
U ppl are working on?

**Comment by atomicturtle** [comment]
Merging this with #574

**Comment by SoftWarrior** [comment]
True
