### ISSUE TITLE
Install.sh reads from stdin

### ISSUE THREAD

**Issue by nigelhorne** [ossec/ossec-hids#576]
Doesn't allow you to pass the answers in as arguments, e.g. --prefix=/var/ossec.

**Comment by jrossi** [comment]
The current version can be setup two was to make this non-interactive: 

https://github.com/ossec/ossec-hids/tree/master/etc the file preloaded-vars.conf.example can be renamed to preloaded-vars.conf and modified to answer all questions and prompts.  If you just need to do a simple install you can use the src/Makefile directly.
