### ISSUE TITLE
report_changes is not reporting changes

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#590]
As reported on the user-list and through my limited, report_changes does not appear to be functional at the moment.
I have tried with and without realtime so far, and am still looking into the issue.

**Comment by dsvetlov** [comment]
Hi!

Where are you check report about changes?
Yiu need to check it in /var/ossec/log/alertls.log

If you are sending alerts via syslog, ossec not send changes in it.

пт, 17 апр. 2015, 17:57, ddpbsd <notifications@github.com>:

**Comment by ddpbsd** [comment]
Thanks for the reply @dsvetlov . I am checking in the alerts.log file. Going through the source now to see if I can find the issue.

**Comment by ScatteredThoughts** [comment]
I'm experiencing a similar issue. I have report_changes set, but am not seeing the diffs in the syslog output nor in the alerts.log file. Is this a known issue which is on a roadmap for being resolved?

**Comment by atomicturtle** [comment]
We would need more information on your environment. I can confirm that its functional, and there are no known issues with it at this time. That said, a number of factors can affect your test case (are you using real time? Did the syscheck process complete startup? how was it built? etc).

**Comment by ScatteredThoughts** [comment]
Hi,

The agent is on Ubuntu 14.04, installed using the instructions from this page: http://ossec.github.io/downloads.html

The manager is running on Debian 8 (Jessie) also installed via the directions from the page above.

Syscheck is starting and completing on the agent machine without any issue:

`
2016/09/09 09:53:27 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2016/09/09 09:53:27 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2016/09/09 09:55:27 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2016/09/09 09:55:38 ossec-syscheckd: INFO: Ending syscheck scan (forwarding database).
2016/09/09 09:56:09 ossec-syscheckd: INFO: Ending syscheck scan.
`

I have been testing with a file in /tmp. I see that the file has changed in syslog and the alerts.log file, but there is not any diff information. Real time is not being used.

<directories report_changes="yes" check_all="yes">/home,/tmp</directories>

An example from alerts.log

`
** Alert 1473431451.3804: mail  - ossec,syscheck,
2016 Sep 09 10:30:51 (webserver) 10.x.x.x->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/tmp/ossec_test_1'
Size changed from '0' to '17'
Old md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'
New md5sum is : '5cff41e0087aa4a3f5b8f5dab2c3e2e7'
Old sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'
New sha1sum is : '56a88d8e9c0fbedf019bd7514686e8a70a8eab94'
`

The entry for syslog output:

`
  <syslog_output>
    <level>0</level>
    <server>10.x.x.x</server>
  </syslog_output>
`

Other than not getting the diff output, things seem to be working normally.

**Comment by ddpbsd** [comment]
I managed to get report_changes working on a standalone testbed. I'll try adding an agent to see if that changes anything.
@ScatteredThoughts Is /var/ossec/queue/diff populated on the OSSEC server?

**Comment by ScatteredThoughts** [comment]
@ddpbsd /var/ossec/queue/diff is empty on the manager server.  However, there are files in the /var/ossec/queue/diff/local directory on the agent server, and I see numerous state files for the file I have been modifying during my attempts to get output from report_changes.

**Comment by ddpbsd** [comment]
I've just gotten a chance to check my test setup, and report_changes is working for me.

**Comment by ScatteredThoughts** [comment]
Okay. Can you share the details of your test configuration?

 Nothing stands out to me which should keep report_changes from working. Do you see any issues with the details I gave about my systems and configuration? I saw another post where someone expressed concerns about how ossec behaved with Debian 8. I'm starting to think there might be some other subtle underlying bug at play.

**Comment by ddpbsd** [comment]
ossec.conf on the OSSEC server:
```
  <syscheck>
    <!-- Frequency that syscheck is executed - default to every 22 hours -->
    <frequency>600</frequency>
    <!-- Directories to check  (perform all possible verifications) -->
    <directories check_all="yes" report_changes="yes">/var/test</directories>
    <!-- Files/directories to ignore -->
```
ossec.conf on the agent:
```
  <syscheck>
    <!-- Frequency that syscheck is executed - default to every 22 hours -->
    <frequency>600</frequency>
    <!-- Directories to check  (perform all possible verifications) -->
    <directories check_all="yes" report_changes="yes">/var/test</directories>
    <!-- Files/directories to ignore -->
```

I don't know of any specific issues with Debian 8, I haven't tried it. I'm using Ubuntu 14.04 LTS.
