### ISSUE TITLE
Ossec resolving on hostname via hosts file fails

### ISSUE THREAD

**Issue by Namsep** [ossec/ossec-hids#592]
When using a hostname in ossec.conf on an agent and the DNS server cannot resolve the hostname but there is an entry in the hosts file, Ossec fails.

IPv4:
2015/04/19 10:15:37 ossec-agentd: INFO: Trying to connect to server (ossec.domain.com:1514).
2015/04/19 10:15:38 getaddrinfo: Name or service not known
2015/04/19 10:15:38 ossec-agentd(1216): ERROR: Unable to connect to 'ossec.domain.com/invalid_ip'.

IPv6:
2015/04/19 10:03:08 ossec-agentd: INFO: Trying to connect to server (ossec.domain.com:1514).
2015/04/19 10:03:08 getaddrinfo: Name or service not known
2015/04/19 10:03:08 ossec-agentd(1216): ERROR: Unable to connect to 'ossec.domain.com/2001:db8:1001:111::ab'.

Using IP adresses in the ossec.conf works for both IPv4 and IPv6.

**Comment by ddpbsd** [comment]
Documenting this in https://github.com/ossec/ossec-docs/pull/96
Thanks to @aquerubin for looking into it.

**Comment by awiddersheim** [comment]
This seems like a good resolution to me. Closing.
