### ISSUE TITLE
ossec installation rhel7 / centos 7 native service

### ISSUE THREAD

**Issue by Namsep** [ossec/ossec-hids#594]
After installation the service is not native, just registering. Possibly I will look into this myself.

 systemctl enable ossec.service
ossec.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig ossec on
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).

**Comment by Namsep** [comment]
I can't program this myself as I'm not a programmer and worked mostely on Windows (linux just recently started).

But here are my 2 cents.
Newer linux systems use systemd which use systemctl as init system, however that does not mean that they do and detecting which init system is used can be tricky as I understand from http://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell

Files that I think need a change are:
https://github.com/ossec/ossec-hids/blob/5558a677d4d0670747ba36d10ea77f5168198b1a/contrib/specs/local/ossec-hids-local.spec
https://github.com/ossec/ossec-hids/blob/5558a677d4d0670747ba36d10ea77f5168198b1a/contrib/specs/server/ossec-hids-server.spec
https://github.com/ossec/ossec-hids/blob/5558a677d4d0670747ba36d10ea77f5168198b1a/contrib/specs/agent/ossec-hids-agent.spec
Maybe also the un-install script.

The systemd / systemctl wants a unit file, on Centos 7 they are in: /usr/lib/systemd/system/
Example of a unit file: https://github.com/fail2ban/fail2ban/blob/954075449d2dc70d05c7036c067e3b98eca11d25/files/fail2ban.service

Enabling a service in Centos results in:
systemctl enable fail2ban.service
ln -s '/usr/lib/systemd/system/fail2ban.service' '/etc/systemd/system/multi-user.target.wants/fail2ban.service'

systemctl disable fail2ban.service
rm '/etc/systemd/system/multi-user.target.wants/fail2ban.service'

Hope this helps lowering the barrier to get this issue tackled

**Comment by dsvetlov** [comment]
Hi! 
@jrossi, volunteer here!) Just pushed units for systemd.

@Namsep, it will be good if you will test that units.

**Comment by Namsep** [comment]
Will test this week, currently not able to.

**Comment by awiddersheim** [comment]
This should be completed in https://github.com/ossec/ossec-hids/pull/619 if I'm not mistaken. Closing for now.
