### ISSUE TITLE
sid 5402 incorrectly alerts for less than 3 failed attempts

### ISSUE THREAD

**Issue by mikedowney01** [ossec/ossec-hids#603]
When running sudo, if a user fails to authenticate only once or twice and exits without attempting authentication again, sid 5402 will incorrectly alert that "Successful sudo to ROOT executed". This does not alert for 3 failed attempts, due to sid 5401 matching first. Matching "incorrect password attempt" will solve this problem. I would be more than happy to submit a pull request, but I'm not sure if the better solution would be to edit rule 5401 so that it alerts for any number of incorrect password attempts, or to add another rule before 5402, changing it's sid to 5403 and potentially causing issues with local_rules.

**Comment by ddpbsd** [comment]
This is definitely a tricky one. I think the easiest answer is to change 5401 to log all failed attempts, and create a rule looking for 3 instances of 5401, but I'd love to hear other opinions on this.

**Comment by mikedowney01** [comment]
I think you're right. The referenced pull request will take care of the problem. I kept the old rule pretty much the same, just changed the sid and added an <if_sid> for the new 5401. I think it's important to keep this rule as is, instead of matching for three instances of 5401. The reason being that 3 failed sudo attempts will only generate one log, which this rule is matching with "3 incorrect password attempts".
