### ISSUE TITLE
sid 5300 incorrectly alerts on OS X

### ISSUE THREAD

**Issue by mikedowney01** [ossec/ossec-hids#604]
I've noticed sid 5300 alerting for successful authentication when the "Open Directory - Membership cache TTL..." log is generated. This is being triggered due to " - " being matched in the rule.

**Comment by ddpbsd** [comment]
Can you provide a log sample?

**Comment by mikedowney01** [comment]
Sure.
The following logs are generated:

su[734]: in pam_sm_authenticate(): authentication succeeded
su[734]: in pam_sm_acct_mgmt(): The root_only option means root only.
su[734]: in pam_sm_acct_mgmt(): OpenDirectory - Membership cache TTL set to 1800.
AccountPolicyHelper[256]: (73.22) AuthenticationAllowed completed: record “test”, result: Success (0).

Which in turn generates the following alert:

Rule: 5301 fired (level 5) -> "User missed the password to change UID (user id)."
Portion of the log(s):

Apr 30 11:19:09 test-mac su[734]: in pam_sm_acct_mgmt(): OpenDirectory - Membership cache TTL set to 1800.

**Comment by mikedowney01** [comment]
Thanks for the correction. I was hesitant to submit a pull request in case "-" was alerting for logs on older systems.

**Comment by ddpbsd** [comment]
It could be, but I don't have any evidence that it does. I can only work
with the information I have. :-)
