### ISSUE TITLE
No active response to sshd reporting multiple PAM login failures 

### ISSUE THREAD

**Issue by prokaryont** [ossec/ossec-hids#621]
The affected OSSEC version is 2.8.1.
The OSSEC server and the machine running the agent are both ubuntu 14.04 servers.

When simulating a break-in attempt into the agent machine via `ssh existinguser@target.example.com` and supplying wrong passwords 3 times, I see the following alert on the server:

> *\* Alert 1433862366.87857: mail  - syslog,access_control,authentication_failed,
> 2015 Jun 09 17:06:06 (target) 1.1.1.1->/var/log/auth.log
> Rule: 2502 (level 10) -> 'User missed the password more than one time'
> Jun  9 17:06:05 target sshd[32557]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=1.1.1.1  user=existinguser

It seems that the log message is not decoded completely. `sricp` and `user` are not extracted and therefore no active response is executed.

I fixed the issue by cloning the `pam-host-user` decoder and setting `sshd` as parent decoder instead of `pam`. 

``` xml
<decoder name="sshd-pam-host-user">
  <parent>sshd</parent>
  <prematch>rhost=\S+\s+user=\S+</prematch>
  <regex>rhost=(\S+)\s+user=(\S+)</regex>
  <order>srcip, user</order>
</decoder> 
```

**Comment by erenfro** [comment]
I have confirmed this as well. I duplicated the same thing as I was wondering why it was taking 9 attempts before the active-response kicked in, and it's because this particular decoder was checking pam, not sshd.

**Comment by ddpbsd** [comment]
I've added this decoder to my decoders_and_rules branch. it should be added to PR #653 automagically.
