### ISSUE TITLE
shared/agent.conf not loaded on windows

### ISSUE THREAD

**Issue by deunger** [ossec/ossec-hids#625]
Hello,
i compiled beta04 today and installed an new windows agent.
Unfortunately the agent does not fetch its config from shared/agent.conf. The agent id is correct.

**Comment by awiddersheim** [comment]
I don't believe anything was changed in this area. Any errors or anything relevant in the logs?

**Comment by spookerlabs** [comment]
Did you enable active response ? If its disable it won't restart and fetch new content.

**Comment by deunger** [comment]
@spookerlabs : yes, active response is  activated ( disabled=no)
@awiddersheim: nothing special in the log. which debug flags would help?

**Comment by awiddersheim** [comment]
This recent change might help which would not have made it into beta04:

https://github.com/ossec/ossec-hids/commit/0b6e24b124b58230763385491c2e433cc27b0ca7

**Comment by deunger** [comment]
@awiddersheim Thnx for the hint. After recompile, the agent pulled its config  from shared/agent.conf.

**Comment by awiddersheim** [comment]
@deunger Great news. Thanks for the update.
