### ISSUE TITLE
win agents fails to install on non english system due to missing group administrators

### ISSUE THREAD

**Issue by deunger** [ossec/ossec-hids#626]
hello,
switching to 2.9 b04 i was happy to see that most of the hardcoded cacls stuff was removed. There is only one reference left. I am not sure if it will vanish too. I replaced the call with icacsl.exe which also accepts one of the documented well known sids for the built in group administrators. This makes the installer even more system language independent.

**Comment by nbuuck** [comment]
https://github.com/ossec/ossec-hids/pull/1137
