### ISSUE TITLE
Event UUID and timestamp in alert.json

### ISSUE THREAD

**Issue by buzztroll** [ossec/ossec-hids#627]
Would it be possible to get UUID associated with ever event and have this ID written to alert.json along with the other information in it?  This would allow applications consuming that information to know in an idempotent way if they had consumed that particular event or not.

If this is not possible or difficult could a timestamp be included in the JSON output?  Perhaps the format of the JSON documents could be controlled in configuration?

**Comment by jrossi** [comment]
https://github.com/ossec/ossec-hids/blob/eb69de7918e33ae7d806a5a14c7d5ca2f0947ad5/src/analysisd/format/to_json.c#L18 

Is a great location to start.  We would be happen to accept a pull request for this feature.

**Comment by dvas0004** [comment]
This is now fixed... current latest version outputs it in string format, proposed alternative method to output timestamp in UNIX time here:

https://github.com/ossec/ossec-hids/pull/1102
