### ISSUE TITLE
OSSEC authd with no -i option registers with IP 'any'

### ISSUE THREAD

**Issue by dgeebs** [ossec/ossec-hids#641]
Hello all,

I've been working with ossec-authd and agent-auth for a while now and I notices an issue that has caused a little frustration from an AlienVault usage side and found a possible solution that may benefit more than just us AlienVault users.

The issue is that ossec-authd is currently using ‘any’ when registering agents without the –i  flag for DHCP environments I have deployed to (ex. running  /var/ossec/bin/ossec-authd). This typically creates the issue that the agent reporting back to the server reports its IP as 'any'

Ex.
(testing123) any->WinEvtLog
Event source and destination ip gets set as 0.0.0.0 in SIEM events for AlienVault users and current IP also cannot get updated.

However, if the agent is created manually with manage_agents and uses 0.0.0.0/0 as it’s IP the agent will still report it’s current IP regardless of it’s network location, meaning that it’s src and/or dst ip can be correctly parsed.

Ex.
(testing123) 10.1.12.57->WinEvtLog
Event source and/or destination ip’s get set correctly in SIEM events and the current IP can be updated.

I’ve found the location in the source code where adjustments can be made to have the default action of ossec-authd be to register with 0.0.0.0/0 instead of ‘any’ thus resolving the current IP and parsing issues of using authd without registering with static IP’s with the -i flag.

The change can be made in either of 2 places to make this work.
1.  In the ossec-authd code itself
   Line 368 of src/os_auth/main-server.c
   Change:
   finalkey = OS_AddNewAgent(agentname, NULL, NULL);
   To:
   finalkey = OS_AddNewAgent(agentname, "0.0.0.0/0", NULL);
   
   ```
                                           AND/OR
   ```
2.  In the validate function of the manage_agents program
   Line 61 of /src/addagent/validate.c
   Change
    snprintf(finals, 2048, "%s %s any %s%s", id, name, md1, md2);
   To:
    snprintf(finals, 2048, "%s %s 0.0.0.0/0 %s%s", id, name, md1, md2);

**Comment by plastikman** [comment]
Same issue here. 

Seem that this should probably be merged with #190?
