### ISSUE TITLE
Could not possible to add agents more than 3999 with ossec-authd

### ISSUE THREAD

**Issue by netman2k** [ossec/ossec-hids#642]
Dear users and developers

I've been using OSSEC in my company for almost 2 years now.

I modified the ossec-authd to check client SSL certification for security reason last year.
My company has got almost 6000 agents now. but at that time I found some of problem with it.
The problem was that I couldn't add more agents more than 3999. 
To solve this problem, I looked into the code and found it.

as you can see the below code which is the part of the file, src/addagent/validate.c

    nid[8] = '\0';
    if (id == NULL) {
        int i = 1024;
        snprintf(nid, 6, "%d", i);
        while (IDExist(nid)) {
            i++;
            snprintf(nid, 6, "%d", i);
            if (i >= 4000) {
                return (NULL);
            }
        }
        id = nid;

Can you see it? there is 4000!!!.

So I changed it with this:

if (i >= (MAX_AGENTS + 1024)){

Please correct me If I did wrong and that the way.
Thanks for reading

**Comment by jer-gentoo** [comment]
Are you sure about the 3999 is? Looks like 3999 - 1024 to me.

**Comment by kefkii** [comment]
Having similar issue, can you comment if your change fixed your problem of being able to add additional agents via agent-auth?

**Comment by netman2k** [comment]
Currently, Our ossec server manages all most 6000 servers at this time. 
also we do not create any key manually. we use agent-auth method to register the servers without any problems.

**Comment by netman2k** [comment]
Dear jer-gentoo, I re-downloaded the ossec file from this url.
https://bintray.com/artifact/download/ossec/ossec-hids/ossec-hids-2.8.3.tar.gz
I found that it still contains this lines of codes.

    nid[8] = '\0';
    if(id == NULL)
    {
        i = 1024;
        snprintf(nid, 6, "%d", i);
        while(IDExist(nid))
        {
            i++;
            snprintf(nid, 6, "%d", i);
            if(i >= 4000)
            {
                return(NULL);
            }
        }
        id = nid;
    }

Did I understand what you asking for?
