### ISSUE TITLE
Missing rule for rootcheck messages

### ISSUE THREAD

**Issue by ChristianBeer** [ossec/ossec-hids#645]
I just upgraded one productive installation to current master and noticed that rootcheck produces some errors when checking for well known directories that don't exist.

See ossec.log:
```
2015/08/04 14:57:06 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2015/08/04 14:57:18 ossec-syscheckd: INFO: Ending syscheck scan (forwarding database).
2015/08/04 14:57:38 rootcheck: INFO: Starting rootcheck scan.
2015/08/04 14:57:40 ERROR: statfs('/var/htdocs') produced error: No such file or directory
2015/08/04 14:57:40 ERROR: statfs('/home/httpd') produced error: No such file or directory
<snip 30-something lines>
2015/08/04 14:57:47 ERROR: statfs('/usr/local/apache2') produced error: No such file or directory
2015/08/04 14:57:47 ERROR: statfs('/usr/local/www') produced error: No such file or directory
2015/08/04 15:03:43 rootcheck: INFO: Ending rootcheck scan.
```

They all show up as rule 1002. The origin is a shared function: https://github.com/ossec/ossec-hids/blob/master/src/shared/fs_op.c

We don't use any NFS on this host. Should I just build a rule for this specific message? Is this security related?

**Comment by ddpbsd** [comment]
I believe this pull request ahould take care of the errors:
https://github.com/ossec/ossec-hids/pull/589

**Comment by ChristianBeer** [comment]
I knew I saw something about this but I couldn't remember and just looked through the open issues not the PRs. Sorry, I'm closing this and reference it to PR #589

**Comment by ddpbsd** [comment]
No worries. It's an old PR. I couldn't even remember if I submitted it.
