### ISSUE TITLE
Downloading ossec 2.8.2 returns forbidden

### ISSUE THREAD

**Issue by kristianpaul** [ossec/ossec-hids#647]
~$ wget http://www.ossec.net/files/ossec-hids-2.8.2.tar.gz
--2015-08-08 19:35:32--  http://www.ossec.net/files/ossec-hids-2.8.2.tar.gz
Resolving www.ossec.net (www.ossec.net)... 150.70.191.237
Connecting to www.ossec.net (www.ossec.net)|150.70.191.237|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-08 19:35:32 ERROR 403: Forbidden.

**Comment by santiago-bassett** [comment]
Try  specifying another user agent. Not in my computer right now but I think with wget -U 

Santiago Bassett
@santiagobassett

**Comment by ddpbsd** [comment]
@kristianpaul Do the instructions leave off the "-U" for wget? I remember changing them a while back, but could have easily missed an instance.
