### ISSUE TITLE
compiling on OS X fails: undefined symbol jflog

### ISSUE THREAD

**Issue by FunTimeCoding** [ossec/ossec-hids#667]
I tried to trace down jflog, but couldn't figure out why it fails and yet compiles just fine on a Debian Wheezy machine. I also mentioned my problem in #375 since it seemed relevant to compile on OS X for that next version.

Heres the end of my compile output:

```
cc -I/usr/local/opt/openssl/include -O2 -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DDarwin -DDarwin -DHIGHFIRST -DPICVIZ_OUTPUT_ENABLED -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ analysisd/makelists-live.o analysisd/accumulator-live.o analysisd/active-response-live.o analysisd/cleanevent-live.o analysisd/config-live.o analysisd/dodiff-live.o analysisd/eventinfo-live.o analysisd/eventinfo_list-live.o analysisd/fts-live.o analysisd/lists-live.o analysisd/lists_list-live.o analysisd/lists_make-live.o analysisd/rules-live.o analysisd/rules_list-live.o analysisd/stats-live.o analysisd/output/jsonout.o analysisd/output/picviz.o analysisd/output/prelude.o analysisd/output/zeromq.o analysisd/format/to_json.o alerts.a cdb.a decoders-live.a os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a external/zlib-1.2.8/libz.a libcJSON.a  -lm -L/usr/local/opt/openssl/lib -lssl -lcrypto -o ossec-makelists
Undefined symbols for architecture x86_64:
  "__jflog", referenced from:
      _jsonout_output_event in jsonout.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ossec-makelists] Error 1
```

**Comment by FunTimeCoding** [comment]
If I add `analysisd/alerts/getloglocation.o` manually to that last cc command, it seems to link it.

```
cc -I/usr/local/opt/openssl/include -O2 -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DDarwin -DDarwin -DHIGHFIRST -DPICVIZ_OUTPUT_ENABLED -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ analysisd/makelists-live.o analysisd/accumulator-live.o analysisd/active-response-live.o analysisd/cleanevent-live.o analysisd/config-live.o analysisd/dodiff-live.o analysisd/eventinfo-live.o analysisd/eventinfo_list-live.o analysisd/fts-live.o analysisd/lists-live.o analysisd/lists_list-live.o analysisd/lists_make-live.o analysisd/rules-live.o analysisd/rules_list-live.o analysisd/stats-live.o analysisd/output/jsonout.o analysisd/output/picviz.o analysisd/output/prelude.o analysisd/output/zeromq.o analysisd/format/to_json.o alerts.a cdb.a decoders-live.a os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a external/zlib-1.2.8/libz.a libcJSON.a analysisd/alerts/getloglocation.o -lm -L/usr/local/opt/openssl/lib -lssl -lcrypto -o ossec-makelists
```

**Comment by FunTimeCoding** [comment]
When I build it on linux, this particular cc command is exactly the same as on osx, but it doesn't fail despite the `analysisd/alerts/getloglocation.o` missing.

**Comment by FunTimeCoding** [comment]
I installed gcc 5 using brew and added the following aliases and shell variables:

```
export CC=/usr/local/bin/gcc-5
export CXX=/usr/local/bin/g++-5
export CPP=/usr/local/bin/cpp-5
export LD=/usr/local/bin/gcc-5
alias c++=/usr/local/bin/c++-5
alias g++=/usr/local/bin/g++-5
alias gcc=/usr/local/bin/gcc-5
alias cpp=/usr/local/bin/cpp-5
alias ld=/usr/local/bin/gcc-5
alias cc=/usr/local/bin/gcc-5
```

The problem is the same. I believe that means it's not a matter of gcc vs clang.

**Comment by reyjrar** [comment]
I can confirm I'm seeing the same thing.  I'm looking into it now.

**Comment by reyjrar** [comment]
Replicated your experience with the analysisd/alerts/getloglocation.o during linking.

**Comment by snaow** [comment]
It is working for me too.

**Comment by vichargrave** [comment]
I'm getting a different issue.  It seems to be in the link phase:

Undefined symbols for architecture x86_64:
  "_TLSv1_2_method", referenced from:
      _get_ssl_context in ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)

**Comment by snaow** [comment]
Hey Vic,

I believe your error is not related to _jflog error.

I think you need to update openssl packages to > 1.0 version.
Or maybe you don't have openssl-devel package installed.

Just guessing.

**Comment by vichargrave** [comment]
Right, it has to do with the agent.  To correct it I had to update the
libssl with macports then add symboilic links from /opt/local/lib to
/usr/lib.

Now that I'm trying to compile the server, I'm getting the same error.

**Comment by vichargrave** [comment]
In the following line in the Makefile:

ossec-makelists: analysisd/makelists-live.o ${analysisd_live_o} ${output}
${format_o} alerts.a cdb.a decoders-live.a ${ossec_libs} ${ZLIB_LIB}
${JSON_LIB}
${OSSEC_CCBIN} ${OSSEC_CFLAGS} $^ ${OSSEC_LDFLAGS} -o $@

if I remove the ${output}

ossec-makelists: analysisd/makelists-live.o ${analysisd_live_o} ${format_o}
alerts.a cdb.a decoders-live.a ${ossec_libs} ${ZLIB_LIB} ${JSON_LIB}
${OSSEC_CCBIN} ${OSSEC_CFLAGS} $^ ${OSSEC_LDFLAGS} -o $@

the links succeeds.

**Comment by snaow** [comment]
That last things worked for me and it makes more sense, as far as i know, ossec-makelist doesn't use anything from analysid/output.

**Comment by vichargrave** [comment]
Ok perhaps I'll submit a pull request later today then.

**Comment by reyjrar** [comment]
On OSX, due to the version of OpenSSL you need to use:

     make USE_OPENSSL=no TARGET=local

**Comment by vichargrave** [comment]
Note you can also get the correct version of OpenSSL from MacPorts, if you have it installed.  Then you set up symbolic links to libssl in /usr/lib.  Here's what you do:

1. sudo port install openssl
2. sudo rm /usr/lib/libssl.dylib (this is a symbolic link)
3. ln -s /opt/local/lib/libssl.dylib /usr/lib/libssl.dylib (assuming /opt/local is where your MacPorts stuff is)

Then recompile everything and life will be good.

**Comment by FunTimeCoding** [comment]
I just tried to compile it again and it works now. Thank you very much. Should I close the issue?
