### ISSUE TITLE
integrate /boot into the syscheck

### ISSUE THREAD

**Issue by aremai** [ossec/ossec-hids#675]
please integrate /boot into the directories to check for the syscheck module.
i think it's important to also scan /boot

thanks,
t.

**Comment by aremai** [comment]
any reason why this is still open?
if it's any easier, I'm happy to send a PR with the updated ossec.conf ...

**Comment by aremai** [comment]
thank you @ddpbsd :)

**Comment by ddpbsd** [comment]
No problem. I think further discussion can/should happen in the PR, so I'll be closing this issue.
