### ISSUE TITLE
Ossec agent installation error on AIX 7.1

### ISSUE THREAD

**Issue by renjith1234** [ossec/ossec-hids#681]
Hi ,

I am trying to build ossec on Aix 7.1. But I couldn't succeed on it. I have tried to install 3 versions of GCC compiler and all failed
 gcc-c++-4.8.3-1.  Is the last version I tried. 

It would be very helpful if you could help me on this

Error got during compilation

5- Installing the system
- Running the Makefile

**\* Making zlib (by Jean-loup Gailly and Mark Adler)  ***
        cd zlib-1.2.8/; ./configure; make libz.a;
Checking for gcc...
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
*\* ./configure aborting.
make: 1254-004 The error code from the last command is 1.

Stop.

Error Making zlib
make: 1254-004 The error code from the last command is 1.

Stop.

Error 0x5.
Building error. Unable to finish the installation

**Comment by earth2baz** [comment]
I got that exact error when gcc wasn't installed on AIX 7.1. You sure you have it installed? What is the output of "rpm -qa | grep gcc"?

**Comment by renjith1234** [comment]
You are right..There was an issue with gcc..I reinstalled gcc and all the required libraries..after that I could install ossec..
Thank You

**Comment by aremai** [comment]
Hi,
would you mind sharing the binaries?

**Comment by renjith1234** [comment]
I don't have the binary with me..You can easily install it if you have all the required libraries

**Comment by ggapy** [comment]
I got the same error.
Output of "rpm -qa | grep gcc" is:
gcc-4.6.1-1
libgcc-4.6.1-1
Please advise.

**Comment by renjith1234** [comment]
Please install all the dependency files. You can refer this URL

[](https://www.ibm.com/developerworks/community/blogs/mhhaque/entry/how_to_use_gcc_or_g_compiler_on_aix_7?lang=en)

**Comment by ggapy** [comment]
Way to go renjith1234. Thanks. Might I add, that after following your URL I had to add:
ln -s /usr/bin/gcc /usr/bin/cc
Everything worked.

**Comment by aremai** [comment]
hi,

out of curiosity, is there anything specific that you are monitoring on AIX (compared to other UNIX systems), specific log files or commands? specific directories for syscheck?
just wondering....

**Comment by ggapy** [comment]
Actually I was about to ask for suggestions on what to monitor in an AIX
system. My previous experience has been with linux only. I've been asked to
monitor AIX configured in clusters, with database engines (Oracle and
Informix) running on top of them. I'll be focusing my research on that.
Tips wellcome...

On Fri, Apr 22, 2016 at 11:01 AM, Theresa Meiksner <notifications@github.com
