### ISSUE TITLE
file change on Osssec client was lately sent to Ossec server

### ISSUE THREAD

**Issue by samz-github** [ossec/ossec-hids#688]
Hello, 

This issue happens sometime but not often. 

OS:  CentOS6.5
Ossec version: ossec-hids-2.8.1
Backgroup: 1 ossec server and several Ossec client 

Issue: The integrity changed alert on Ossec client sometime would send to Ossec server with latency, almost 2 days latency.

Example:
file /etc/example.cfg on Ossec client (named with ossecclient01, for security reason I use the alias)changed on 2015-11-06 19:46:40

But after almost 2 days,  on 2015 Nov 08 07:51:32, this change alert was sent to Ossec server(named with osssecserver01).It's so late!

```
/var/ossec/logs/alerts on osssecserver01:
2015 Nov 08 07:51:32 (ossecclient01) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/etc/example.cfg'
Size changed from '2197' to '2205'
Old md5sum was: 'd9387298c66e8c16ce7188c1f1a64c2a'
New md5sum is : '9dc0c9a2d330974871ac6f1e065b4337'
Old sha1sum was: '9ddf85189354d8b443662d9f95ae5cb02a632391'
New sha1sum is : '33906b2734ec413df25eb4643ba4d40f09f33f96'
```

ossec.log on ossecclient01 at that time:

```
2015/11/05 02:27:57 ossec-rootcheck: INFO: Ending rootcheck scan.
2015/11/05 02:27:57 ossec-syscheckd: INFO: Starting syscheck scan.
2015/11/06 06:27:09 ossec-agentd: INFO: Event count after '20000': 5518805->4820960 (87%)
2015/11/06 16:42:08 ossec-syscheckd: INFO: Ending syscheck scan.
2015/11/06 16:47:08 ossec-rootcheck: INFO: Starting rootcheck scan.
2015/11/06 17:03:12 ossec-rootcheck: INFO: Ending rootcheck scan.
2015/11/06 17:03:12 ossec-syscheckd: INFO: Starting syscheck scan.
2015/11/08 07:15:07 ossec-syscheckd: INFO: Ending syscheck scan.
2015/11/08 07:20:07 ossec-rootcheck: INFO: Starting rootcheck scan.
2015/11/08 07:36:00 ossec-rootcheck: INFO: Ending rootcheck scan.
2015/11/08 07:36:00 ossec-syscheckd: INFO: Starting syscheck scan.
2015/11/09 21:45:40 ossec-syscheckd: INFO: Ending syscheck scan.
2015/11/09 21:50:40 ossec-rootcheck: INFO: Starting rootcheck scan.
```

**Comment by snaow** [comment]
Syscheck run every 22 hours, depends of your agent system the scan will take from 10 minutes to several hours to complete (in your case, 14 hours).
So in your case i can imagine the total process takes about 36 hours.
If your file changes just after syscheck ends, then it will take another 22+14 hours to be detected.
Try "real_time" options to get instant alerts when a file has changed and "scan_on_start".

You can restart syscheck database, restart the agent and generate the alert manually, then check when syscheck scan ends and check alerts.log for the integrity checksum alert.

```
/var/ossec/bin/syscheck_control -u IDAGENT
/var/ossec/bin/agent_control -R IDAGENT
```

**Comment by santiago-bassett** [comment]
In addition to what Snaow mentioned, try enabling debug on the agent. You should be able to see each one of the messages that are generated every time a file hash is created, given you an idea on why it takes so long to complete. That can be done in internal_options.conf

**Comment by samz-github** [comment]
@snaow @santiago-bassett  , Thank you! You give me the right answer and good advice. Let me try to debug more info about why it takes 36 hours to complete syscheck scan.
