### ISSUE TITLE
Disabling one active-response disables them all!

### ISSUE THREAD

**Issue by erenfro** [ossec/ossec-hids#692]
I had tried to disable a single active-responce handler, in my case, specifically from the default configuration, provided by ossec-configure, I tried to disable host-deny, and when doing so, none of the active-responses worked anymore.

It seems disabling one means disabling all of them.

**Comment by ddpbsd** [comment]
How did you disable that AR?

**Comment by Jonybat** [comment]
I was trying to figure out why my newly created active response entry was not working. After reading this, i tried removing all the default ar's (that are disabled by default) from the config file, and my custom ar started working.

Using v2.8.3 ubuntu package

**Comment by erenfro** [comment]
I had disabled one of the two default ones (generated by ossec-configure script) using <disabled>yes</disabled> which caused all active-responce methods to not run. Removing the <disabled>yes</disabled> re-enabled them to work again. Simultaneously (host-deny and firewall-drop).

**Comment by ddpbsd** [comment]
How exactly did you disable the individual active response entry? Delete or comment out the configuration in the ossec.conf? Delete the script?

**Comment by Jonybat** [comment]
He said he used yes, so i assume it was <disabled>yes</disabled>. From my experiences, having one ar block with "<disabled>yes</disabled>" causes all other ar's to not run also, regardless of whether they have "<disabled>no</disabled>" or no disabled tag at all. Both commenting or removing the ar blocks to disable in the ossec.conf file fix the issue.

**Comment by ddpbsd** [comment]
I understand that he said he used "yes," but that's not an option. So clarification is necessary. Did he use 
```
<disabled>yes</disabled>
```
Did he use it in a command? Or in an "active-response" block? Either way, that's not how you disable individual ARs. The better I understand the problem, the better I can make the documentation to prevent the misunderstanding in the future.

If you don't want an AR to be triggered, comment out the "active-response" block that configures it.

**Comment by Jonybat** [comment]
So, what you are saying is that the \<disabled>yes</disabled> tag is a global option for all ar's? If that is the case, then either the docs need clarification or the code needs to be changed to be less confusing.

http://ossec-docs.readthedocs.org/en/latest/manual/ar/ar-unix.html#responses-configuration

Plus, my default config file is as follows:
```
  <!-- Active Response Config -->
  <active-response>
    <!-- This response is going to execute the host-deny
       - command for every event that fires a rule with
       - level (severity) >= 6.
       - The IP is going to be blocked for  600 seconds.
      -->
    <disabled>yes</disabled>
    <command>host-deny</command>
    <location>local</location>
    <level>6</level>
    <timeout>600</timeout>
  </active-response>

  <active-response>
    <!-- Firewall Drop response. Block the IP for
       - 600 seconds on the firewall (iptables,
       - ipfilter, etc).
      -->
    <disabled>yes</disabled>
    <command>firewall-drop</command>
    <location>local</location>
    <level>6</level>
    <timeout>600</timeout>
  </active-response>
```

Which again, gives the idea that they can be disabled individually.

**Comment by ddpbsd** [comment]
I thought it was global, but if that's working for you maybe it isn't. I'll have to investigate.

**Comment by Jonybat** [comment]
No, it isn't. It is working exactly as you are saying. To have it working i have to comment/remove the ar's that i do not want enabled. What i provided above was what came in the default config file.

**Comment by ddpbsd** [comment]
Then I'll update the documentation. Thanks for the clarification.

**Comment by erenfro** [comment]
Hmm.. Why would... It handle active-response globally, when it's a subset of the <active-response> block in the first place? That to me is already kind of odd, and yes.. While commenting out a block of active-response does "disable" it, by simply not having it defined. hehe. It's just a bit odd.

Either way. If it's global, it should be in the <global> section, instead of in one of any number of potential <active-response> blocks. 

<global>
    <active-response_enable>yes|no</active-response_enable> or something to that effect. 
    ...
</global>
