### ISSUE TITLE
Max message length in alerts log

### ISSUE THREAD

**Issue by simpleuser99** [ossec/ossec-hids#693]
Hello.
How can I change message length in alerts log?
I have very big messages from my web access log and those do not fit in the alerts log

**Comment by ddpbsd** [comment]
Are these messages only truncated in alerts.log? You'll probably have to modify the source, and increase some buffers.

**Comment by simpleuser99** [comment]
Yes, I'm sure that messages are truncated only in alerts.log.
please, tell me what i must change in OSSEC for fix it?

**Comment by simpleuser99** [comment]
Yes, I'm sure that messages are truncate in alerts.log. 
Please, tell me what I may change in OSSEC fo fix my issue? It's very important for me.

**Comment by mstarks01** [comment]
I can confirm this. It's not uncommon for Windows 2008+ logs to be 800 bytes or more.

**Comment by simpleuser99** [comment]
Does anyone have a solution?
It's very important for me

**Comment by ddpbsd** [comment]
I'm guessing you would have to raise OS_MAXSTR, but I don't know what consequences that would have.

**Comment by simpleuser99** [comment]
Yes, it wirk for me. I OS_MAXSTR, andI have the desired length of the message. Thanks
