### ISSUE TITLE
 skip_nfs is missing from releases

### ISSUE THREAD

**Issue by djcross** [ossec/ossec-hids#694]
The `skip_nfs` option does not seem to have made it into the release packages, despite being in both `stable` and `master` branches.  I've looked at 2.8.2 and 2.8.3 releases.  Will this be in the next release?  It looks like it's been in the repo since February.

Is there any info on how the releases are put together?  I'd have thought that `stable` would end up as your release?

**Comment by ddpbsd** [comment]
Was it in 2.8.1? I'm not sure why it isn't in 2.8.3 if it was.

**Comment by djcross** [comment]
Looking further, it hasn't been in any 2.8 releases, but is in the 2.9 beta, and the `2_9_b` branch.  So from this I guess `master` and `stable` are actually towards 2.9, and 2.8 releases are now for bugfixes and security updates?  

The use of a stable branch for a beta release is a little weird to me, as is the mention of this functionality in the [docs for 2.8.1](http://ossec-docs.readthedocs.org/en/latest/syntax/head_ossec_config.rootcheck.html).

Will this be pulled into 2.8 releases, or delegated strictly to 2.9?

**Comment by ddpbsd** [comment]
2.8.x is for major bug fixes. It's labeled in the 2.8 documentation as coming in 2.9. Because of the confusion of adding and labeling future features, I'm planning on changing the way the documentation gets done after 2.9 is released.

**Comment by doke2** [comment]
Is skip_nfs too limited?  Would it make sense to optionally skip all
non-local, or non-real, filesystems, ie nfs, cifs, sshfs, webdav, /proc,
/sys, /device, etc? 

                                               Cheers,
                                               Doke

**Comment by djcross** [comment]
+1 for @doke2 suggestion, although probably better as another issue.

@ddpbsd Thanks for the update.  Are you able to say when 2.9 may be released?  For now we've backported skip_nfs to our 2.8 installs.

**Comment by ddpbsd** [comment]
@djcross Not at this time. With the holidays I'm not too keen on trying to get something out before the new year.
