### ISSUE TITLE
2.8.1, 2 and 3 tarballs missing use_fqdn option in csyslogd-config.c

### ISSUE THREAD

**Issue by sandinak** [ossec/ossec-hids#708]
Not sure how this happened .. it is in the 2.9.0 beta, but still documented in http://ossec-docs.readthedocs.org/en/latest/syntax/head_ossec_config.syslog_output.html which has it's heading as 2.8.1 as the documented version... and I am fairly sure i used it prior to today?

**Comment by ddpbsd** [comment]
Looks like 2.8 was released in 2014, and this option was added in Jan 2015. It's a documentation bug.
