### ISSUE TITLE
Error with syslog predecoder

### ISSUE THREAD

**Issue by jesuslinares** [ossec/ossec-hids#712]
Right now, windows decoder is not working:

    2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test
    
    **Phase 1: Completed pre-decoding.
           full event: '2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
           hostname: 'LinMV'
           program_name: 'WinEvtLog'
           log: 'Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
    
    **Phase 2: Completed decoding.
           No decoder matched.

before this commit (https://github.com/ossec/ossec-hids/commit/217e6dddfd2da6887614ae59ba7ce9f48ba379f8), it was working fine:

    2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test
    
    
    **Phase 1: Completed pre-decoding.
           full event: '2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
           hostname: 'LinMV'
           program_name: '(null)'
           log: '2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
    
    **Phase 2: Completed decoding.
           decoder: 'windows'
           status: 'INFORMATION'
           id: '1'
           extra_data: 'My Script'
           dstuser: '(no user)'
           system_name: 'demo1.foo.example.com'

This is because *windows decoder* doesn't use the **program_name** tag because it was *(null)*, but now it is *WinEvtLog*.

It could be solved replacing:

    <prematch>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: |^WinEvtLog: </prematch>

for

    <program_name>^WinEvtLog</program_name>

But, I think the modifications in the syslog predecoder are wrong. Why a windows event is considered as syslog event if the windows event has not Host field?:

2015 Nov 13 HH:MM:SS **Host Program:** Message
2013 Oct 09 17:09:04 **WinEvtLog:** Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test

**Comment by jesuslinares** [comment]
Hi,

I really think that the _Windows decoder fix_ #809 must be merged. Right now, all windows logs are failing:

> 2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test
> 
> **Phase 1: Completed pre-decoding.
>        full event: '2013 Oct 09 17:09:04 WinEvtLog: Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
>        hostname: 'ip-10-0-0-223'
>        program_name: 'WinEvtLog'
>        log: 'Application: INFORMATION(1): My Script: (no user): no domain: demo1.foo.example.com: test'
> 
> **Phase 2: Completed decoding.
>        No decoder matched.

Regards.

**Comment by ddpbsd** [comment]
Does #880 also solve the problems?

**Comment by ddpbsd** [comment]
I've merged #880. Please re-open this (or open a new issue) if it doesn't solve the problem. Thanks again for all the help!

**Comment by jesuslinares** [comment]
All the unit tests are working and I'm doing some tests. Everything seems to work properly. It is necessary in order to capture windows logs.

Thanks.
Regards.
