### ISSUE TITLE
2.9-beta-20151211 release 

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#713]
I'm trying something new, and definitely interested in feedback (not in this issue necessarily).

This issue is for the 2.9-beta-20151211 release. Any issues with this release should be posted here. This includes, but is not limited to: bugs, bugs, bugs, and bugs.

Features included in master may not be here. Things have been added that were not planned for 2.9, we just wanted to get them in so people could work on/with them while we figured out the release.

For now the code can be downloaded from the 2_9_b branch: https://github.com/ossec/ossec-hids/tree/2_9_b
I will comment with tarball/windows download links when I get the chance to make them.

**Comment by ddpbsd** [comment]
Downloads should be available here: https://bintray.com/ossec/ossec-hids/ossec-hids/2.9.0_beta_20151211/view
Checksums should be available shortly: https://ossec.github.io/docs/whatsnew/checksums/index.html

**Comment by finid** [comment]
Thank you. I think I can do a test installation within the next few days.
