### ISSUE TITLE
Agent disconnected after restarted CentOS 6.5 on Ossec agent

### ISSUE THREAD

**Issue by samz-github** [ossec/ossec-hids#719]
OS: Centos 6.5
OSSEC version: ossec-hids-2.8.1-47.el6

I have Ossec agent which happen agent disconnected with Ossec master after I restarted CentOS on Ossec agent. It happens on another Ossec agent before for same situation.

After checked, I found there was not any network issue between Ossec agent with Ossec client.

In the end, after I remove Ossec agent on Ossec master, and then register agent again to Ossec master, this issue is fixed.

Can you help to debug what's the root cause for this case? Thanks in advance.

Here it's ossec.log on my ossec agent. 192.168.1.2(alias) is the IP address of OSSEC server.

2015/12/19 01:12:26 ossec-agentd: INFO: Trying to connect to server (192.168.1.2:1514).
2015/12/19 01:12:26 ossec-agentd: INFO: Using IPv4 for: 192.168.1.2 .
2015/12/19 01:12:47 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '192.168.1.2'.
2015/12/19 01:16:25 ossec-agentd: INFO: Trying to connect to server (192.168.1.2:1514).
2015/12/19 01:16:25 ossec-agentd: INFO: Using IPv4 for: 192.168.1.2 .
2015/12/19 01:16:46 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '192.168.1.2'.

**Comment by ddpbsd** [comment]
Turn on debug on the OSSEC server
```
/var/ossec/bin/ossec-control enable debug && /var/ossec/bin/ossec-control restart
```
And check the ossec.log there.
