### ISSUE TITLE
ossec-remoted segfault

### ISSUE THREAD

**Issue by herrwamm** [ossec/ossec-hids#725]
Debian 8.2 LXC container
Linux ossec 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux

OSSEC HIDS Notification.
2015 Dec 28 10:47:09

Received From: ossec->/var/log/syslog
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Dec 28 10:47:08 ossec kernel: [800383.371624] ossec-remoted[27624]: segfault at 7f2500000018 ip 00007f2535db7fa8 sp 00007fff4e0fee40 error 6 in libc-2.19.so[7f2535d3e000+19f000]

**Comment by ddpbsd** [comment]
What version of OSSE Care you running?
Can you try running remoted under gdb?
```
gdb /var/ossec/bin/ossec-remoted 
set follow-fork-mode child
run -df
```

**Comment by herrwamm** [comment]
ossec-hids 2.8.3-3jessie

root@ossec:~# gdb /var/ossec/bin/ossec-remoted
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /var/ossec/bin/ossec-remoted...(no debugging symbols found)...done.
(gdb) set follow-fork-mode child
(gdb) run -df
Starting program: /var/ossec/bin/ossec-remoted -df
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2015/12/28 12:16:44 ossec-remoted: DEBUG: Starting ...
2015/12/28 12:16:44 ossec-remoted: INFO: Started (pid: 12223).
[New process 12227]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2015/12/28 12:16:44 ossec-remoted: DEBUG: Forking remoted: '0'.
2015/12/28 12:16:44 ossec-remoted: INFO: Started (pid: 12227).
2015/12/28 12:16:44 ossec-remoted: ERROR: Unable to create merged file: '/etc/shared/merged.mg'.
2015/12/28 12:16:44 ossec-remoted: Error opening directory: '/etc/shared': Permission denied
2015/12/28 12:16:44 ossec-remoted: DEBUG: Running manager_init
[New Thread 0x7ffff6fde700 (LWP 12228)]
[New Thread 0x7ffff67dd700 (LWP 12229)]
2015/12/28 12:16:47 ossec-remoted(1210): ERROR: Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2015/12/28 12:16:47 ossec-remoted(1211): ERROR: Unable to access queue: '/queue/ossec/queue'. Giving up..
[Thread 0x7ffff6fde700 (LWP 12228) exited]
[Thread 0x7ffff7fed700 (LWP 12227) exited]
[Inferior 2 (process 12227) exited with code 01]

**Comment by ddpbsd** [comment]
Well in this case it looks like the other processes weren't running.

**Comment by snaow** [comment]
Maybe permission-related issue?

*ossec-remoted: ERROR: Unable to create merged file: '/etc/shared/merged.mg
<http://merged.mg/>'.*
*ossec-remoted: Error opening directory: '/etc/shared': Permission denied*

2015-12-28 18:21 GMT+01:00 Dan Parriott <notifications@github.com>:

**Comment by herrwamm** [comment]
'/etc/shared': Permission denied* this path not exist
ossec's home dir is /var/ossec

**Comment by snaow** [comment]
That's normal, OSSEC always works with a chroot on /var/ossec so
/etc/shared means /var/ossec/etc/shared.

Check permissions and groups are valid.

Anyways a segfault error should not be related with permisisions but it is
always good to check.


Have you some agents added? Add at least 1 agent (or fake agent if you
don't have other host to test)

2015-12-28 18:49 GMT+01:00 herrwamm <notifications@github.com>:

**Comment by herrwamm** [comment]
Sorry for late update. 
Problem was only permissions related.
Thanks all.

**Comment by snaow** [comment]
Glad to hear.

**Comment by ddpbsd** [comment]
Which permissions?

**Comment by herrwamm** [comment]
chown -R ossec:ossec /var/ossec

**Comment by ddpbsd** [comment]
I meant, which files were incorrectly owned by another user? (And I think
some of the files in /var/ossec are owned by root)
