### ISSUE TITLE
File integrity monitoring - Source user and what change

### ISSUE THREAD

**Issue by junedmirza1** [ossec/ossec-hids#729]
Hi All,

For File Integrity monitoring peice of Ossec, does the latest ossec agent is able to detect who did the change and what was the change done ??

In the earlier verisons it was not able to detect these things.. Just the old & new MD5 and SHA hashes were detected.

**Comment by ddpbsd** [comment]
Nope, it still does not. I'd still be interested in a cross platform way to program this
