### ISSUE TITLE
Coverity tests - need a home

### ISSUE THREAD

**Issue by jrossi** [ossec/ossec-hids#731]
I am shutting down my linode server Thursday.  With this buildbot.jeremyrossi.com will not have a host.  I have the scripts and configuration but no place to run it.  We should move it to Travis or some other CI service.

**Comment by jrossi** [comment]
Ok I have shutdown the server. I pull the keys out of the config of build it and check it in to github for others.

**Comment by jrossi** [comment]
https://github.com/ossec/ossec-buildbot i have checked this into github.

**Comment by ddpbsd** [comment]
I think I saw that Travis or github and Coverity have some integration options available. Would those solve this issue?
