### ISSUE TITLE
Can we limit the client-server communication to use just the port 1514 (inbound/outbound)

### ISSUE THREAD

**Issue by mak2016** [ossec/ossec-hids#732]
Is it possible to limit the OSSEC client server communication to use only the port 1514. Various forums are saying that the client initiates the communication on some random higher port and then server replies on the port 1514. Can we limit the clients to use just port 1514 instead of some random higher port. Appreciate your help on this. 
Thanks

**Comment by snaow** [comment]
i believe OSSEC just use 1514 by default, it does not try with a higher
port first (it does not make any sense, isn't it?). I don't know either
some way to disable the behavior you are saying.

You have to know that port behavior is to open a random port on the
outbound and the inbound port is what you set, that's related to TCP/IP
networking knowledge, i'm not going to go deep into that.

**Comment by ddpbsd** [comment]
On Jan 12, 2016 6:20 AM, "mak2016" <notifications@github.com> wrote:
>
> Is it possible to limit the OSSEC client server communication to use only
the port 1514 Various forums are saying that the client initiates the
communication on some random higher port and then server replies on the
port 1514 Can we limit the clients to use just port 1514 instead of some
random higher port Appreciate your help on this
> Thanks
>

I think there's a PR to allow this, or the PR was merged recently (ish). If
not, I think we'd accept a patch to add thia optional behavior.

**Comment by mak2016** [comment]
thanks for the replies snaow and ddpbsd, sorry I don't understand the PR. can you please explain ?

**Comment by ddpbsd** [comment]
PR = pull request. Ijust looked through them, and I was thinking of the one that allowed you to specify an IP address. So you'd have to write the code to use specific ports instead of properly choosing a random high port

**Comment by mak2016** [comment]
okay, thanks for the clarification, Any ideas which configuration file(s) i need to modify for the coding ?

**Comment by ddpbsd** [comment]
ossec.conf, but the harder part is figuring out which source files need to
be modified.

On Jan 12, 2016 6:54 AM, "mak2016" <notifications@github.com> wrote:
>
> okay, thanks for the clarification, Any ideas which configuration file(s)
i need to modify for the coding ?

**Comment by mak2016** [comment]
thanks ddpbsd, never mind, I will look into the ossec.conf to see if I can tweak it :)
Cheers

**Comment by salderma** [comment]
This perhaps a slightly off-topic comment.  

**Could the Official Documentation be updated to reflect what ports and protocols are used for OSSEC servers and agents?**  

This would be a great help for network policy documentation in secure environments or when ensuring that agents can deliver data through firewall'd networks.  As of the time of this posting Internet and Documentation searches have only produced references to UDP/1514 on the ossec-list mailing list and external blogs/forums.  Nothing that could be considered definitive documentation from the source project.

Thanks.

**Comment by ddpbsd** [comment]
@salderma How's this: https://github.com/ossec/ossec-docs/pull/198

**Comment by salderma** [comment]
Thank you sir, apologies for not noticing the docs project.

**Comment by ddpbsd** [comment]
No problem. I like it when people look at the documentation and have constructive criticism. :-)
