### ISSUE TITLE
Exporting keys in bulk

### ISSUE THREAD

**Issue by dkade** [ossec/ossec-hids#734]
Hello

Could we have a way to export all the agent keys? 

Like the manage_agents -f for bulk agent creation, after issuing this command we should be able to retrieve the key list of the agents created.

Thank you,
Best regards

**Comment by santiago-bassett** [comment]
Hi dkade,

what would be this for? Isn't it enough copying the client.keys file?

**Comment by dkade** [comment]
Humm I will test this! :) Thank you
