### ISSUE TITLE
Show ID used by the agent, when reported as invalid (not only the IP)

### ISSUE THREAD

**Issue by santiago-bassett** [ossec/ossec-hids#739]
Requested in the mailing list.

src/error_messages/error_messages.h:#define ENC_IP_ERROR    "%s(1408): ERROR: Invalid ID for the source ip: '%s'."

It would make troubleshooting easier. 

Best

**Comment by irctrakz** [comment]
Even including the agent key/ID hash that was unable to resolve would be an awesome step forward.

**Comment by santiago-bassett** [comment]
Implemented here:

https://github.com/wazuh/ossec-wazuh/commit/b277f0b159a0145d7501d446c429db19a50f922a

Vikman will do a pull request

**Comment by irctrakz** [comment]
Awesome! Thank you.
