### ISSUE TITLE
Include systemd unit files in RPMs

### ISSUE THREAD

**Issue by phemmer** [ossec/ossec-hids#741]
PR #619 added the systemd unit files for the ossec services, but they are not currently included in the RPMs for RHEL7.

Can we get these files added to the RPM specs?

**Comment by aremai** [comment]
this can be closed, aye?!

**Comment by phemmer** [comment]
No. Nothing has been done.

**Comment by aremai** [comment]
@atomicturtle can you verify this? is this still open?

**Comment by atomicturtle** [comment]
Yeah we're waiting on a 3rd party to test/confirm Pull request #801
