### ISSUE TITLE
req: whitelist description

### ISSUE THREAD

**Issue by Namsep** [ossec/ossec-hids#742]
I would like to suggest to add the possibility to add a comment to a whitelist IP. I have a bunch of them in there now and am sometimes confused where they are from. Having both IPv4 and IPv6 addresses in there.

ossec.conf / < global >< white_list >

**Comment by ddpbsd** [comment]
You should be able to add comments.
```
<!-- comment -->
```

**Comment by Namsep** [comment]
I totally missed that, was focusing so on code that I missed the obvious. Sorry and thanks.
