### ISSUE TITLE
The interval of Process Monitoring

### ISSUE THREAD

**Issue by axot** [ossec/ossec-hids#764]
I can not find the interval setting of Process Monitoring in docs. How to set monitor `netstat -tan |grep LISTEN|grep -v 127.0.0.1` every 10 mins? The default interval seems set as 360 seconds.

Thank you.

**Comment by ddpbsd** [comment]
You should be able to use the _frequency_ option to change how often it is run:
http://ossec.github.io/docs/syntax/head_ossec_config.localfile.html?highlight=command#element-frequency

**Comment by axot** [comment]
Thank you
