### ISSUE TITLE
Migrate Agents to new ossec server

### ISSUE THREAD

**Issue by jim-peters646** [ossec/ossec-hids#766]
Is there a way to migrate agents to new ossec server? Does someone have this documented? Is this possible or do we need to uninstall & reinstall agents to point to new server?

**Comment by ddpbsd** [comment]
It should be pretty simple, but I haven't tested it.
Stop the server processes.
Copy the configurations and rids files to a new server installation.
Adjust the server-ip setting on the agents, if necessary.
Start the server processes on the new system.

**Comment by jim-peters646** [comment]
Thanks Dan- what are the configuration and rids files I need to copy over?



Also don’t I need to re-add the agents to the new server with new security
keys so they register with new database?



Thanks-



*From:* Dan Parriott [mailto:notifications@github.com]
*Sent:* Wednesday, March 09, 2016 7:31 AM
*To:* ossec/ossec-hids
*Cc:* James Peters
*Subject:* Re: [ossec-hids] Migrate Agents to new ossec server (#766)



It should be pretty simple, but I haven't tested it.
Stop the server processes.
Copy the configurations and rids files to a new server installation.
Adjust the server-ip setting on the agents, if necessary.
Start the server processes on the new system.

—
Reply to this email directly or view it on GitHub
<https://github.com/ossec/ossec-hids/issues/766#issuecomment-194274416>.[image:
Image removed by sender.]

**Comment by ddpbsd** [comment]
The idea is to copy enough files over that you should not have to re-add the agents. The _/var/ossec/etc/client.keys_ should take care of most of that.

I think you'll need (again untested, so test test test):

- /var/ossec/etc/ossec.conf
- /var/ossec/etc/internal_options.conf
- /var/ossec/etc/client.keys
- /var/ossec/etc/local_decoder.xml
- /var/ossec/etc/ossec-init.conf
- /var/ossec/etc/shared/agent.conf
- /var/ossec/queue/rids/*
- /var/ossec/rules/local_rules.xml

If there are ssl certs (for authd), make sure to grab them as well.

If you don't want first time seen type alerts to reappear, grabbing 
- /var/ossec/queue/fts
might be doable.
Same with
- /var/ossec/queue/syscheck
- /var/ossec/queue/diff`

The following should all be installed during an installation, and shouldn't have been modified really:
- /var/ossec/etc/localtime
- /var/ossec/etc/decoder.xml
- /var/ossec/rules/*_rules.xml

One day I'll get around to trying it and adding something to the documentation (or someone will send me explicit instructions, or submit a PR on the documentation repo).

**Comment by ddpbsd** [comment]
I've opened the following issue in the ossec-docs repo to follow up on this in the future, but this issue seems resolved: https://github.com/ossec/ossec-docs/issues/154
