### ISSUE TITLE
MAX_AGENTS in ossec-hids-art.spec seems not working

### ISSUE THREAD

**Issue by axot** [ossec/ossec-hids#769]
I tested the latest ossec-hids-2.8.3-52.art.src.rpm
It seems the setting
`echo "HEXTRA=-DMAX_AGENTS=16384" >> ./Config.OS`
not working for server, the `MAX_AGENTS` is using default 256.

make[1]: Entering directory `rpmbuild/BUILD/ossec-hids-2.8.3/src/os_auth'
cc -g -Wall -I../ -I../headers   -DUSE_OPENSSL -DUSEINOTIFY     -DGEOIP -DARGV0=\"ossec-authd\" -DOSSECHIDS -D_FORTIFY_SOURCE=2 -O2 -fexceptions -fstack-protector -fPIE -pie -Wl,-z,relro,-z,now  main-server.c ssl.c  ../addagent/validate.c ../config/lib_config.a ../shared/lib_shared.a ../os_net/os_net.a ../os_regex/os_regex.a ../os_crypto/os_crypto.a ../os_zlib/os_zlib.c ../external/libz.a -lssl -lcrypto -o ossec-authd

**Comment by atomicturtle** [comment]
This should be resolved in ossec-hids-server-2.8.3-53, thanks for the report!
