### ISSUE TITLE
If rids file(s) gets truncated it allows the client(s) to talk to server 

### ISSUE THREAD

**Issue by avisri** [ossec/ossec-hids#772]
Reproduce the issue: 

*Rids is enabled 
*stop the server
*cp /dev/null  [ rids_file ]   #simulate truncate
*start  server                    #  to ensure the the file is not written from memory 

The client will be able to send logs/traffic to server , the server knows nothing about the client rids number . 

Should there be a mechanism to ensure if the file is null then not to allow  the client to talk as the rids number has been wiped off  ?

**Comment by dcid** [comment]
Tricky one. Whatever method we use can be bypassed if someone can modify files on the manager. 

The rids file is the method to prevent log tampering/reuse. Setting it to empty or 1, will restart the counter again.

**Comment by avisri** [comment]
Thanks . Make sense 

However counter didn't reset hence the concern of not able to detect it. Tested on 2.8.2 .

So perceive  this a as  feature / fix ( rids issue in a multi server env  ) / simply a limitation ?

**Comment by avisri** [comment]
are we in agreement in detecting this ( log a verbose message )  vs preventing this ?

**Comment by santiago-bassett** [comment]
I like this approach, detecting instead of preventing, just muy humble opinion. Lets wait and see also what Daniel thoughts are about this
