### ISSUE TITLE
Alert mail via Amazon SES

### ISSUE THREAD

**Issue by axot** [ossec/ossec-hids#775]
Is it possible to send alert mail via Amazon SES?

**Comment by ddpbsd** [comment]
It looks like SES requires authentication, so relaying the messages through your local smtp daemon should work just fine. Most smtp daemons have documentation on how to use a relay host and how to setup auth.

**Comment by mayankgarg8888** [comment]
Hi guys,

I have also same issue, but want to know more about how to setup username
and password for authentication of smtp server with ssl or tls in
ossec.conf file as some smtp daemons with no authentication, are blocking
my ip address for sending bulk emails.

Thanks in advance.

**Comment by ddpbsd** [comment]
@mayankgarg8888 _ossec-maild_ does not handle authentication. You'll need to run an smtp daemon locally to accept the mail and forward it on.

**Comment by mayankgarg8888** [comment]
Thank Dan.

Could you help me in resolving this, i got this when using google smtp
server without auth:

os_sendmail:  WARN: End of data not accepted by server.
ossec-maild: ERROR: Error sending mail to 74.125.130.27(smtp server)

Locally smtp daemon is working but i want to use some smtp server as above
with no auth.

**Comment by ddpbsd** [comment]
@mayankgarg8888 I believe google smtpd requires auth.

**Comment by mayankgarg8888** [comment]
No man, i am using this  "aspmx.l.google.com" smtp server with no auth.
Check out below link please.

https://support.google.com/a/answer/176600?hl=en

**Comment by ddpbsd** [comment]
Ok then. Use tcpdump to see if you can determine the smtp code returned by google's server.

**Comment by mayankgarg8888** [comment]
#. yeah, i did same and got message in packet as:

Our system has detected an unusual rate of .. solicited mail originating
from your ip address. To protect your users from spam, mail sent from your
ip address has been temporarily  rate limited. please visit "
https://support.google.com/mail/answer/81126" to review our bulk sender
guidelines.

**Comment by ddpbsd** [comment]
@mayankgarg8888 I'm not exactly sure how I can help with that. Google seems to think you're sending too much mail. Cut down on the mail or use a better service (perhaps authenticating would be easier?).

**Comment by mayankgarg8888** [comment]
#. Could you suggest me how do i configure auth with smtp server in
ossec.conf?

**Comment by ddpbsd** [comment]
@mayankgarg8888 You cannot configure auth for ossec-maild in the ossec.conf. ossec-maild does not support auth. That's why I keep suggesting that you configure ossec-maild to use an smtp daemon on the localhost, and configure that smtpd to relay the emails through an external server (with auth/tls/etc). I'm not making this recommendation because it's fun, I'm making it because it's the best solution I've seen.

**Comment by mayankgarg8888** [comment]
Thanks a lot, i will try to implement such smtp daemon with some external
server with auth/tls/etc.

**Comment by axot** [comment]
Setup postfix as relay smtpd should work, we want use SES APIs to send mail before.
Thank you

**Comment by Emerson** [comment]
As an end user of this software, not supporting SMTP authentication is a real pain. Know you folks don't want to bloat your codebase, but it would be much much nicer to have this functionality out of the box rather than needing to figure out SMTP relays.

**Comment by ddpbsd** [comment]
If you submit a pull request, I'll make grtting it merged my top priority. That's the best I can do for a feature I think is actively bad for the project.
