### ISSUE TITLE
ossec-logtest didn't phase 3

### ISSUE THREAD

**Issue by simpleuser99** [ossec/ossec-hids#777]
I update ossec-hids 2.8.1 to 2.8.3 and I dodn't view alert from web logs.
When I debug mu issue, I run ./ossec-logtest -v and I have next result:

Feb 14 18:00:05 anyhost nginx: www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-" 

**Phase 1: Completed pre-decoding.
       full event: Feb 14 18:00:05 anyhost nginx: www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-" '
       hostname: 'anyhost'
       program_name: 'nginx'
       log: 'www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-" '

**Phase 2: Completed decoding.
       No decoder matched.

**Rule debugging:
    Trying rule: 1 - Generic template for all syslog rules.
       *Rule 1 matched.
       *Trying child rules.
    Trying rule: 1003 - Non standard syslog message (size too large, more than 150000 (rule make by admin7)).
    Trying rule: 2100 - NFS rules grouped.
    Trying rule: 2507 - OpenLDAP group.
    Trying rule: 2550 - rshd messages grouped.
    Trying rule: 2701 - Ignoring procmail messages.
    Trying rule: 2800 - Pre-match rule for smartd.
    Trying rule: 5100 - Pre-match rule for kernel messages
    Trying rule: 5200 - Ignoring hpiod for producing useless logs.
    Trying rule: 2830 - Crontab rule group.
    Trying rule: 5300 - Initial grouping for su messages.
    Trying rule: 5400 - Initial group for sudo messages
    Trying rule: 9100 - PPTPD messages grouped
    Trying rule: 9200 - Squid syslog messages grouped
    Trying rule: 2900 - Dpkg (Debian Package) log.
    Trying rule: 2930 - Yum logs.
    Trying rule: 2931 - Yum logs.
    Trying rule: 2940 - NetworkManager grouping.
    Trying rule: 2943 - nouveau driver grouping
    Trying rule: 5700 - SSHD messages grouped.
    Trying rule: 4700 - Grouping of Cisco IOS rules.
    Trying rule: 9700 - Dovecot Messages Grouped.
    Trying rule: 3600 - Grouping of the imapd rules.
    Trying rule: 5500 - Grouping of the pam_unix rules.
    Trying rule: 12100 - Grouping of the named rules
    Trying rule: 3300 - Grouping of the postfix reject rules.
    Trying rule: 3320 - Grouping of the postfix rules.
    Trying rule: 3390 - Grouping of the clamsmtpd rules.
    Trying rule: 31300 - Nginx messages grouped.
    Trying rule: 30100 - Apache messages grouped.
    Trying rule: 50100 - MySQL messages grouped.
    Trying rule: 31404 - PHP Warning message.
    Trying rule: 31405 - PHP Fatal error.
    Trying rule: 31406 - PHP Parse error.
    Trying rule: 50500 - PostgreSQL messages grouped.
    Trying rule: 3500 - Grouping for the spamd rules
    Trying rule: 2301 - Excessive number connections to a service.
    Trying rule: 2502 - User missed the password more than one time
    Trying rule: 2504 - Illegal root login.
    Trying rule: 7101 - Problems with the tripwire checking
    Trying rule: 5901 - New group added to the system
    Trying rule: 5902 - New user added to the system
    Trying rule: 5904 - Information from the user was changed
    Trying rule: 12110 - Serial number from master is lower than stored.
    Trying rule: 12111 - Unable to perform zone transfer.
    Trying rule: 1007 - File system full.
    Trying rule: 30200 - Modsecurity alert.
    Trying rule: 1004 - Syslogd exiting (logging stopped).
    Trying rule: 1005 - Syslogd restarted.
    Trying rule: 1006 - Syslogd restarted.
    Trying rule: 1008 - Process exiting (killed).
    Trying rule: 2501 - User authentication failure.
    Trying rule: 2503 - Connection blocked by Tcp Wrappers.
    Trying rule: 2103 - Unable to mount the NFS directory.
    Trying rule: 2945 - rsyslog may be dropping messages due to rate-limiting.
    Trying rule: 5553 - PAM misconfiguration.
    Trying rule: 5554 - PAM misconfiguration.
    Trying rule: 12112 - Zone transfer error.
    Trying rule: 2505 - Physical root login.
    Trying rule: 2506 - Pop3 Authentication passed.
    Trying rule: 5555 - User changed password.
    Trying rule: 1001 - File missing. Root access unrestricted.
    Trying rule: 1002 - Unknown problem somewhere in the system.
    Trying rule: 5903 - Group (or user) deleted from the system

Why i didn't view phase 3 ? What is the pronlem?

**Comment by ddpbsd** [comment]
On Mar 16, 2016 6:48 AM, "simpleuser99" <notifications@github.com> wrote:
>
> I update ossec-hids 2.8.1 to 2.8.3 and I dodn't view alert from web logs.
> When I debug mu issue, I run ./ossec-logtest -v and I have next result:
>
> Feb 14 18:00:05 anyhost nginx: www.example.ru 212.153.115.23 -
[14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-"
0.000 "-"
>
> **Phase 1: Completed pre-decoding.
> full event: 'Feb 14 18:00:05 vm06.lb.rsl.loc nginx: www.roseltorg.ru
213.133.115.88 - [14/Feb/2016:18:00:05 +0300] "GET
/trade/future/?limit=100&q=%d0%9d%d0%b5%d1%82%d0%b1%d1%83%d0%ba HTTP/1.1"
444 "-" 0 "-" "-" "-" 0.000 "-" NGINX-CACHE-- "-" '
> hostname: 'vm06.lb.rsl.loc'
> program_name: 'nginx'
> log: 'www.roseltorg.ru 213.133.115.88 - [14/Feb/2016:18:00:05 +0300] "GET
/trade/future/?limit=100&q=%d0%9d%d0%b5%d1%82%d0%b1%d1%83%d0%ba HTTP/1.1"
444 "-" 0 "-" "-" "-" 0.000 "-" NGINX-CACHE-- "-" '
>
> **Phase 2: Completed decoding.
> No decoder matched.
>
> **Rule debugging:
> Trying rule: 1 - Generic template for all syslog rules.
> *Rule 1 matched.
> *Trying child rules.
> Trying rule: 1003 - Non standard syslog message (size too large, more
than 150000 (rule make by admin7)).
> Trying rule: 2100 - NFS rules grouped.
> Trying rule: 2507 - OpenLDAP group.
> Trying rule: 2550 - rshd messages grouped.
> Trying rule: 2701 - Ignoring procmail messages.
> Trying rule: 2800 - Pre-match rule for smartd.
> Trying rule: 5100 - Pre-match rule for kernel messages
> Trying rule: 5200 - Ignoring hpiod for producing useless logs.
> Trying rule: 2830 - Crontab rule group.
> Trying rule: 5300 - Initial grouping for su messages.
> Trying rule: 5400 - Initial group for sudo messages
> Trying rule: 9100 - PPTPD messages grouped
> Trying rule: 9200 - Squid syslog messages grouped
> Trying rule: 2900 - Dpkg (Debian Package) log.
> Trying rule: 2930 - Yum logs.
> Trying rule: 2931 - Yum logs.
> Trying rule: 2940 - NetworkManager grouping.
> Trying rule: 2943 - nouveau driver grouping
> Trying rule: 5700 - SSHD messages grouped.
> Trying rule: 4700 - Grouping of Cisco IOS rules.
> Trying rule: 9700 - Dovecot Messages Grouped.
> Trying rule: 3600 - Grouping of the imapd rules.
> Trying rule: 5500 - Grouping of the pam_unix rules.
> Trying rule: 12100 - Grouping of the named rules
> Trying rule: 3300 - Grouping of the postfix reject rules.
> Trying rule: 3320 - Grouping of the postfix rules.
> Trying rule: 3390 - Grouping of the clamsmtpd rules.
> Trying rule: 31300 - Nginx messages grouped.
> Trying rule: 30100 - Apache messages grouped.
> Trying rule: 50100 - MySQL messages grouped.
> Trying rule: 31404 - PHP Warning message.
> Trying rule: 31405 - PHP Fatal error.
> Trying rule: 31406 - PHP Parse error.
> Trying rule: 50500 - PostgreSQL messages grouped.
> Trying rule: 3500 - Grouping for the spamd rules
> Trying rule: 2301 - Excessive number connections to a service.
> Trying rule: 2502 - User missed the password more than one time
> Trying rule: 2504 - Illegal root login.
> Trying rule: 7101 - Problems with the tripwire checking
> Trying rule: 5901 - New group added to the system
> Trying rule: 5902 - New user added to the system
> Trying rule: 5904 - Information from the user was changed
> Trying rule: 12110 - Serial number from master is lower than stored.
> Trying rule: 12111 - Unable to perform zone transfer.
> Trying rule: 1007 - File system full.
> Trying rule: 30200 - Modsecurity alert.
> Trying rule: 1004 - Syslogd exiting (logging stopped).
> Trying rule: 1005 - Syslogd restarted.
> Trying rule: 1006 - Syslogd restarted.
> Trying rule: 1008 - Process exiting (killed).
> Trying rule: 2501 - User authentication failure.
> Trying rule: 2503 - Connection blocked by Tcp Wrappers.
> Trying rule: 2103 - Unable to mount the NFS directory.
> Trying rule: 2945 - rsyslog may be dropping messages due to rate-limiting.
> Trying rule: 5553 - PAM misconfiguration.
> Trying rule: 5554 - PAM misconfiguration.
> Trying rule: 12112 - Zone transfer error.
> Trying rule: 2505 - Physical root login.
> Trying rule: 2506 - Pop3 Authentication passed.
> Trying rule: 5555 - User changed password.
> Trying rule: 1001 - File missing. Root access unrestricted.
> Trying rule: 1002 - Unknown problem somewhere in the system.
> Trying rule: 5903 - Group (or user) deleted from the system
>
> Why i didn't view phase 3 ? What is the pronlem?
>

What rule did you expect to alert?

**Comment by simpleuser99** [comment]
I expected that work next rule
<group name="web,accesslog,">
  <rule id="31100" level="0">
    <category>web-log</category>
    <description>Access log messages grouped.</description>
  </rule>
<rule id="31101" level="5">
    <if_sid>31100</if_sid>
    <id>^4</id>
    <description>Web server 400 error code.</description>
  </rule>

from  web_rules.xml

because in /var/ossec/etc/ ossec-server.conf contains
<rules>
    <include>rules_config.xml</include>
    <include>syslog_rules.xml</include>
    <include>sshd_rules.xml</include>
<include>attack_rules.xml</include> 
    <include>cisco-ios_rules.xml</include>
    <include>dovecot_rules.xml</include>
    <include>imapd_rules.xml</include>
    <include>pam_rules.xml</include>
    <include>named_rules.xml</include>
    <include>postfix_rules.xml</include>
    <include>squid_rules.xml</include>
    <include>web_rules.xml</include>
    <include>nginx_rules.xml</include>
    <include>apache_rules.xml</include>
    <include>mysql_rules.xml</include>
    <include>php_rules.xml</include>
    <include>postgresql_rules.xml</include>
    <include>spamd_rules.xml</include>
  </rules>

I don't understant why web_rules don't work/

P.S. ddpbsd please delete quote from your post, because I accidentally post confidential information, I changed my first message and delete confidential data. I'm sorry

**Comment by ddpbsd** [comment]
The log message you posted is not in a format that any of the OSSEC decoders recognizes. The log message mentions nginx, but isn't in the format expected for our nginx decoders. The nginx decoders also don't seem to add the _web-log_ category. As you can see from rule 31100 that category is a requirement:

```  
  <rule id="31100" level="0">
    <category>web-log</category>
    <description>Access log messages grouped.</description>
  </rule>
```

I don't think writing a decoder for this would be difficult. Adding the following to local_decoder.xml gives me better output (copied [here:](https://gist.github.com/ddpbsd/73307253717a6e252c62) in case the formatting here is wonky):
```
<decoder name="nginx-syslog">
  <program_name>^nginx</program_name>
  <type>web-log</type>
</decoder>

<decoder name="nginx-syslog-2">
  <parent>nginx-syslog</parent>
  <regex>^(\S+) (\S+) - [\d\d/\S\S\S/\d\d\d\d:\d\d:\d\d:\d\d \S\d\d\d\d] "(\S+) (\S+) HTTP\S+" (\d\d\d) </regex>
  <order>extra_data, srcip, action, url, status</order>
</decoder>
```

Output:
```
ossec-testrule: Type one log per line.

Feb 14 18:00:05 anyhost nginx: www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-"


**Phase 1: Completed pre-decoding.
       full event: 'Feb 14 18:00:05 anyhost nginx: www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-"'
       hostname: 'anyhost'
       program_name: 'nginx'
       log: 'www.example.ru 212.153.115.23 - [14/Feb/2016:18:00:05 +0300] "GET /contacts HTTP/1.1" 444 "-" 0 "-" "-" "-" 0.000 "-"'

**Phase 2: Completed decoding.
       decoder: 'nginx-syslog'
       extra_data: 'www.example.ru'
       srcip: '212.153.115.23'
       action: 'GET'
       url: '/contacts'
       status: '444'

**Phase 3: Completed filtering (rules).
       Rule id: '31100'
       Level: '0'
       Description: 'Access log messages grouped.'
```

So now the log message gets tagged with web-log, and 31100 is triggered. Adjustments might have to be made for slightly different nginx logs though, so keep an eye out for variations.

**Comment by simpleuser99** [comment]
Ok. But when I used 2.8.1 version I don't have the problem. 
The 2.8.3 has other decoders than 2.8.1 ?

**Comment by ddpbsd** [comment]
No clue really, it's been a LONG time since I've used 2.8.1. Check the decoder.xml history, see what's changed. Do tests between 2.8.1 and 2.8.3 to see what made that stop working for you. Report your findings back.

**Comment by simpleuser99** [comment]
I don't want research difference between decoder. I use your recomendation and create custom new line in my current decoder. I have good result. Thank you
