### ISSUE TITLE
report_changes issue when realtime is on

### ISSUE THREAD

**Issue by axot** [ossec/ossec-hids#782]
One more thing about realtime monitor, with current `REALTIME_MONITOR_FLAGS`, 
```c
#define REALTIME_MONITOR_FLAGS  IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF
```
If set both `realtime="yes"` and `report_changes="yes"` in syscheck, the diff change report is not working properly when editing file use vim.

```bash
** Alert 1458817776.483341: mail  - ossec,syscheck,
2016 Mar 24 20:09:36 test->syscheck
Rule: 553 (level 7) -> 'File deleted. Unable to retrieve checksum.'
File '/home/admin/.ssh/authorized_keys' was deleted. Unable to retrieve checksum.

** Alert 1458817776.483591: mail  - local,syslog,syscheck,
2016 Mar 24 20:09:36 test->syscheck
Rule: 554 (level 11) -> 'File added to the system.'
File '/home/admin/.ssh/authorized_keys' was re-added.
```

It works using echo command etc. `echo hello world  >> .ssh/authorized_keys`
```bash
** Alert 1458817768.482841: mail  - ossec,syscheck,
2016 Mar 24 20:09:28 test->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/home/admin/.ssh/authorized_keys'
Size changed from '771' to '783'
Old md5sum was: '84a33161e4070e9f66213ffd9f914b0f'
New md5sum is : '6e7b41634f5e9c1317974389ac52a320'
Old sha1sum was: 'a8385138a38e5268dd624542a470bce48c0a2dc8'
New sha1sum is : '2d123fa27d29dddf0e24db1babf5f7408ee53c49'
What changed:
5a6
> hello world
```

Is there an easy method could solve this issue? Setting `nowritebackup` in `vimrc` will work, but it is not a happy solution for us.

**Comment by ddpbsd** [comment]
I thought a delay had been added to syscheck to handle this situation, but maybe it was never merged.

**Comment by axot** [comment]
Cloud you send me the commit id or PR url?

**Comment by axot** [comment]
`report_changes` function in agent need `/var/ossec/tmp` directory to store tmp files. But the ossec-hids-client-2.8.3-52.art.x86_64.rpm did not create this directory

**Comment by santiago-bassett** [comment]
you are right, this is an issue with the installer (I've seen this before)

**Comment by ddpbsd** [comment]
@axot I don't know a PR or commit off hand. I could also be misremembering it entirely, and it was just a discussion.

**Comment by atomicturtle** [comment]
/var/ossec/tmp has been added to the common file, ossec-hids-2.8.3-53. I think that closes out this report, if I'm wrong let me know and we'll reopen it.

**Comment by axot** [comment]
@atomicturtle Thank you, I'll check it out.
