### ISSUE TITLE
No mail being send, Ubuntu 15.10, ossec 2.8.3

### ISSUE THREAD

**Issue by scriptzteam** [ossec/ossec-hids#783]
2016/03/25 16:48:44 ossec-analysisd: INFO: White listing IP: '127.0.0.1'
2016/03/25 16:48:44 ossec-analysisd: INFO: White listing IP: '62.210.16.6'
2016/03/25 16:48:44 ossec-analysisd: INFO: White listing IP: '62.210.16.7'
2016/03/25 16:48:44 ossec-analysisd: INFO: 3 IPs in the white list for active response.
2016/03/25 16:48:44 ossec-analysisd: INFO: White listing Hostname: 'localhost.localdomain'
2016/03/25 16:48:44 ossec-analysisd: INFO: 1 Hostname(s) in the white list for active response.
2016/03/25 16:48:44 ossec-analysisd: INFO: Started (pid: 23024).
2016/03/25 16:48:45 ossec-monitord: INFO: Started (pid: 23036).
2016/03/25 16:48:47 ossec-analysisd: INFO: Connected to '/queue/alerts/execq' (exec queue)
2016/03/25 16:48:49 ossec-syscheckd: INFO: Started (pid: 23032).
2016/03/25 16:48:49 ossec-rootcheck: INFO: Started (pid: 23032).
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/etc'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/bin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/sbin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/home/'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Monitoring directory: '/var/'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/etc'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/usr/bin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/usr/sbin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/bin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/sbin'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/home/'.
2016/03/25 16:48:49 ossec-syscheckd: INFO: Directory set for real time monitoring: '/var/'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/auth.log'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/syslog'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/vsftpd.log'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/dpkg.log'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/apache2/error.log'.
2016/03/25 16:48:50 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/apache2/access.log'.
2016/03/25 16:48:50 ossec-logcollector: INFO: Monitoring output of command(360): df -h
2016/03/25 16:48:50 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
2016/03/25 16:48:50 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 5
2016/03/25 16:48:50 ossec-logcollector: INFO: Started (pid: 23030).
2016/03/25 16:49:12 os_sendmail(1767): WARN: End of DATA not accepted by server
2016/03/25 16:49:12 ossec-maild(1223): ERROR: Error Sending email to 64.233.161.27 (smtp server)
2016/03/25 16:49:51 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2016/03/25 16:49:51 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2016/03/25 16:49:51 ossec-syscheckd: INFO: Initializing real time file monitoring (not started).
2016/03/25 16:50:55 os_sendmail(1767): WARN: End of DATA not accepted by server
2016/03/25 16:50:55 ossec-maild(1223): ERROR: Error Sending email to 64.233.161.27 (smtp server)
2016/03/25 16:51:05 os_sendmail(1767): WARN: End of DATA not accepted by server
2016/03/25 16:51:05 ossec-maild(1223): ERROR: Error Sending email to 64.233.161.27 (smtp server)

**Comment by ddpbsd** [comment]
Does your mailserver require authentication?
You can try running tcpdump to try and capture an error message from the mailserver.

**Comment by atomicturtle** [comment]
Since this isn't really a bug, lets move this to the mailing list, or I'd be happy to help you on this from the irc channel. #ossec on irc.freenode.net

**Comment by scriptzteam** [comment]
okay sending mail rly not working for me now, i can try send it via php, which line sending mails in your code? sendmail+php will work
