### ISSUE TITLE
failed to integrate with slack

### ISSUE THREAD

**Issue by ohadpartuck** [ossec/ossec-hids#784]
@dcid hi, 
I'm struggling with installing ossec. gave up on email notification, slack is much more convenient, anyway.

Followed your guide [here](https://blog.sucuri.net/2016/01/server-security-integrating-ossec-with-slack-and-pagerduty.html)
i'm getting this 
```
tail -f /var/ossec/ossec.log
2016/03/28 13:17:22 ossec-analysisd(2302): ERROR: Invalid definition for analysisd.stats_maxdiff: '999000'.
....
Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'

```

my ossec version  isV2015-12

help please

**Comment by ohadpartuck** [comment]
ok, figured it out. 

after installing the stable version,
changed the config in this file
`/var/ossec/etc/internal_options.conf`

`analysisd.stats_maxdiff=25000`

**Comment by dcid** [comment]
This code is not merged yet into this repository. Ping me privately and I can help if you are still having issues.

**Comment by ohadpartuck** [comment]
Thanks integration was solved
