### ISSUE TITLE
Can't automatically add agents to the server ERROR: Not compiled. Missing OpenSSL support.

### ISSUE THREAD

**Issue by ohadpartuck** [ossec/ossec-hids#793]
@dcid 
version installed https://bitbucket.org/dcid/ossec-hids/downloads - @ tag tip
OS used is debian 8.3

after reading [this](http://ossec-docs.readthedocs.org/en/latest/programs/agent-auth.html)
trying to run the 
/var/ossec/bin# ./ossec-authd
ERROR: Not compiled. Missing OpenSSL support.

read the https://github.com/ossec/ossec-hids/issues/194
```
sudo apt-get install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl-dev is already the newest version.
```
any ideas?

**Comment by dcid** [comment]
What operating system are you using? I will check.

*for ubuntu,centos,redhat, you need openssl-devel.

thanks,

**Comment by ohadpartuck** [comment]
debian

**Comment by ohadpartuck** [comment]
OS used is debian 8.3

**Comment by dcid** [comment]
I will try to install Debian here to try to duplicate it. Give me a few hours :)

**Comment by dcid** [comment]
Try now. Should be good (you need to re-download it). Plus, for things specific to my repository, that have not been merged yet, please ping me through here:

https://github.com/dcid/ossec-hids

As it avoids confusion here.

**Comment by ohadpartuck** [comment]
wget http://dcid.me/ossec-packages/ossec-hids-latest.tar.gz ?
