### ISSUE TITLE
Upgraded Ossec from 2.7.1 to 2.8.3 Agents no longer connecting

### ISSUE THREAD

**Issue by alaquerre** [ossec/ossec-hids#794]
Hi everyone, I have upgraded the Ossec version to 2.8.3 and well our client didn't want to upgrade the agents to 2.8.3 yet. I have noticed for the last few days that agents are going from active to disconnected and so and and so forth. When trying to verify the error i am noticing a huge number of errors in my logs such as : 
Duplicate error:  global: 3, local: 5456, saved global: 6, saved local:9637
2016/04/05 14:18:19 ossec-remoted(1407): ERROR: Duplicated counter for 
ERROR: Invalid ID for the source ip: 
I have cleared the RIDS on the server and noticed that the agent connection are unstable. As we have 3000 clients I am not sure what would be the most efficient solution here.

thank you,

**Comment by ddpbsd** [comment]
Upgrading the agents to match the server is probably the first step.

**Comment by alaquerre** [comment]
Very well ,

I will plan the update and let you know.

Thank you,

Alexandre Laquerre
Analyste Sécurité
[http://cybercan.com/images/iso20000.jpg]----------------------------------------------------------------------------------------
LINKBYNET
Performance | Innovation | Qualité
----------------------------------------------------------------------------------------
Suivez-nous  sur les médias sociaux !
[cid:image001.jpg@01CEE08C.10B406C0]<http://www.linkedin.com/company/LINKBYNET>- [cid:image002.jpg@01CEE08C.10B406C0] <https://twitter.com/#!/@LINKBYNET>  - [1331824224_FaceBook_24x24] <http://www.facebook.com/LINKBYNET>  - [1384399169_Flurry_Google_Alt] <https://plus.google.com/b/104214152964322174793/104214152964322174793/posts>
1255 Place Phillips, Suite 700, Montréal, QC H3B 3G1
Standard : +1 800 258 0820
Pôle Sécurité : +1 514 667 0554
Web : www.linkbynet.com<http://www.linkbynet.com/>
[cid:image019.jpg@01CF0ADF.D085FB20]
Avant d'imprimer cet e-mail, pensez à l'environnement.
LINKBYNET, 1er hébergeur des environnements en haute disponibilité – Source 01net|IPLabel<http://pro.01net.com/rub/01business/10403/01business/indicateurs/hebergeurs-environnement-haute-disponibilite/>

**Comment by atomicturtle** [comment]
Closing this one out as not-a-bug
