### ISSUE TITLE
rootcheck-config.c -- old legacy options?!

### ISSUE THREAD

**Issue by aremai** [ossec/ossec-hids#795]
just had a look at https://github.com/ossec/ossec-hids/blob/a7ca63d6d074f2f6bdb49f4bc79a054c31dcafc7/src/rootcheck/rootcheck-config.c

and saw those <daemon> and <notify> tags, are they still used? if so, what's their purpose? I couldn't find them in the docs either.... using them in my ossec.conf makes ossec go belly-up.

I found them by stumbling upon this
https://github.com/ossec/ossec-hids/blob/a7ca63d6d074f2f6bdb49f4bc79a054c31dcafc7/src/rootcheck/rootcheck.conf

so, yeah my question....or those options still valid for 2.9.x ?
if not, would it be a major problem to get rid of this in the code for future releases to avoid confusion like this?

thanks!

**Comment by ddpbsd** [comment]
To the best of my knowledge they should be valid. The lack of documentation is probably because whoever submitted the PR didn't document the options, and I don't pay much attention to rootcheck.

**Comment by ddpbsd** [comment]
And please define "go belly-up." I just added the options to my rootcheck section in my ossec.conf and had no issues (OpenBSD and Ubuntu something.something_else).

**Comment by aremai** [comment]
ok, sorry, by "go belly-up" I essentially meant that it threw an configuration error

`2016/04/08 12:25:04 ossec-syscheckd(1230): ERROR: Invalid element in the configuration: 'notify'.
2016/04/08 12:25:04 ossec-syscheckd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
2016/04/08 12:25:04 rootcheck(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
ossec-syscheckd did not start correctly.
`

seems like it doesn't like the notify tag in my ossec configuration
using
CentOS 6.7
OSSEC 2.8

`  <rootcheck>
    <frequency>3600</frequency>
    <notify>syslog</notify>
    <daemon>yes</daemon>
    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>
    <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_rhel6_linux_rcl.txt</system_audit>
    <check_files>yes</check_files>
    <check_trojans>yes</check_trojans>
    <check_unixaudit>yes</check_unixaudit>
    <check_dev>yes</check_dev>
    <check_sys>yes</check_sys>
    <check_pids>yes</check_pids>
    <check_ports>yes</check_ports>
    <check_if>yes</check_if>
  </rootcheck>
`

**Comment by aremai** [comment]
same goes for the <daemon> option, the rest <check_*> is fine....
maybe I need to finally upgrade to ossec 2.9

**Comment by ddpbsd** [comment]
I didn't try daemon or notify. I'm guessing those are options from when rootcheck was a separate process instead of wrapped up in syscheckd. They don't make any sense inside syscheckd.

**Comment by aremai** [comment]
oh yeah, sorry I should have been a little more specific earlier...
do you think it would be a big deal getting rid of those for upcoming releases?
I'm happy to send a PR with an updateed rootcheck.conf template to remove those two options... though not really sure about the C source code.

**Comment by ddpbsd** [comment]
A PR would be great, even better if it gets rid of the extra C as well.

**Comment by aremai** [comment]
a first clumsy attempt... #797

**Comment by aremai** [comment]
@ddpbsd Dan, can we close this? If I recall correctly, you have merged it right?
