### ISSUE TITLE
2.9.0 binary installation?

### ISSUE THREAD

**Issue by jimmysharrrison** [ossec/ossec-hids#807]
I have some servers that do not have make or gcc installed.  Having issues getting 2.9.0 beta04 to install on them because of the make call in the install.sh script.  Is there an install script for precompiled binaries like Ossec 2.8.1 http://ossec-docs.readthedocs.org/en/latest/manual/installation/installation-binary.html

I ran make clean, make local in the src directory as these are local installs, but the install script still tries to call make on line 116.

**Comment by jimmysharrrison** [comment]
Solved this issue by packaging a statically complied make binary for the systems I needed to deploy to, then editing the install.sh script to use that binary.

**Comment by ddpbsd** [comment]
Thanks for bringing this to our attention, we will definitely have to look into this.

**Comment by dbgdngit** [comment]
@jimmysharrrison  would this approach work for agent installs where make setagent call is required. Have tried pre-compiled static binary but it only seems to install /var/ossec/etc branch

**Comment by dbgdngit** [comment]
I got this working with "make TARGET=agent build"

**Comment by marcRBD** [comment]
the problem is still in 2.9.1 

> make setagent
> make: *** No rule to make target `setagent'.  Stop.

thanks for the tips --> "make TARGET=agent build"
