### ISSUE TITLE
Invalid integrity message in the database

### ISSUE THREAD

**Issue by ohadpartuck** [ossec/ossec-hids#810]
my server log is bombed with these messages.
debian 8.3
ossec latest `2016-04`
read that I have to delete ossec's db 
here
http://asrtechnotes.blogspot.co.il/2010/05/ossec-invalid-integrity-message-in-t.html
and here
https://groups.google.com/forum/#!topic/ossec-list/gLi8kfBGe34

but I don't have `syscheck_update`

any help as to how to solve this?

**Comment by aremai** [comment]
Hi,

the binary syscheck_update only exists on the OSSEC managers!
do you have a local or a server (agent/manager) installation?

best,
theresa

**Comment by ohadpartuck** [comment]
i don't understand the question:
I have agents installed  but the log i'm talking about is
in the `ossec server`
```
root@ossec: tail -f /var/ossec/logs/ossec.log
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
2016/04/25 12:00:17 ossec-analysisd: Invalid integrity message in the database.
```

**Comment by aremai** [comment]
which version are you using on the OSSEC manager?
find it out with 

`cat /etc/ossec-init.conf`

**Comment by aremai** [comment]
Hmm, I have a different release than you do....
just to clarify:
you pulled the latest version from github (master branch) and installed that?
and sorry if this sounds stupid:

which binaries do you have in /var/ossec/bin .... I just want to make sure that we are on the same page ;-)

**Comment by ohadpartuck** [comment]
```
ls -ltra /var/ossec/bin
total 10892
-r-xr-x---  1 root ossec  215224 Mar 28 12:26 ossec-lua
-r-xr-x---  1 root ossec  147024 Mar 28 12:26 ossec-luac
dr-xr-x---  2 root ossec    4096 Mar 28 12:42 .
-r-xr-x---  1 root ossec      76 Mar 28 13:40 .process_list
-r-xr-x---  1 root ossec    4360 Mar 29 22:01 util.sh
-r-xr-x---  1 root ossec    7346 Mar 29 22:01 ossec-control
dr-xr-x--- 15 root ossec    4096 Apr  3 11:21 ..
-r-xr-x---  1 root ossec  347184 Apr 19 08:52 ossec-maild
-r-xr-x---  1 root ossec  388768 Apr 19 08:52 ossec-dbd
-r-xr-x---  1 root ossec  332600 Apr 19 08:52 ossec-csyslogd
-r-xr-x---  1 root ossec  331352 Apr 19 08:52 ossec-integratord
-r-xr-x---  1 root ossec  346808 Apr 19 08:52 ossec-agentlessd
-r-xr-x---  1 root ossec  107008 Apr 19 08:52 ossec-execd
-r-xr-x---  1 root ossec 1057704 Apr 19 08:52 ossec-analysisd
-r-xr-x---  1 root ossec 1069472 Apr 19 08:52 ossec-logtest
-r-xr-x---  1 root ossec  985328 Apr 19 08:52 ossec-makelists
-r-xr-x---  1 root ossec  389672 Apr 19 08:52 ossec-logcollector
-r-xr-x---  1 root ossec  545272 Apr 19 08:52 ossec-remoted
-r-xr-x---  1 root ossec  579264 Apr 19 08:52 ossec-agentd
-r-xr-x---  1 root ossec  315104 Apr 19 08:52 manage_agents
-r-xr-x---  1 root ossec  326096 Apr 19 08:52 syscheck_update
-r-xr-x---  1 root ossec  157096 Apr 19 08:52 clear_stats
-r-xr-x---  1 root ossec  229880 Apr 19 08:52 list_agents
-r-xr-x---  1 root ossec  439448 Apr 19 08:52 verify-agent-conf
-r-xr-x---  1 root ossec  340160 Apr 19 08:52 agent_control
-r-xr-x---  1 root ossec  331744 Apr 19 08:52 syscheck_control
-r-xr-x---  1 root ossec  331680 Apr 19 08:52 rootcheck_control
-r-xr-x---  1 root ossec  209072 Apr 19 08:52 ossec-regex
-r-xr-x---  1 root ossec  511968 Apr 19 08:52 ossec-syscheckd
-r-xr-x---  1 root ossec  572072 Apr 19 08:52 ossec-monitord
-r-xr-x---  1 root ossec  218392 Apr 19 08:52 ossec-reportd
-r-xr-x---  1 root ossec  242072 Apr 19 08:52 ossec-authd
```

**Comment by aremai** [comment]
thanks!

but you do have that binary actually... just look:

`-r-xr-x---  1 root ossec  326096 Apr 19 08:52 syscheck_update`

maybe I'm just missing the point? What happens when you run it?

**Comment by atomicturtle** [comment]
VERSION="rel2016-02"

This indicates that the release you are using is not from the OSSEC project.

**Comment by aremai** [comment]
yes, I was surprised as well when I saw that....
isn't the version usually saying "2.8" or "2.9.0" rather than "relYYYY-MM" ?!

**Comment by ohadpartuck** [comment]
@atomicturtle  yes, I updated in order to use the slack notifications which (according to my understanding) are not supported in the latest stable. 
installed from here https://bitbucket.org/dcid/ossec-hids/. is that an issue?

@aremai  I have used the 

```
root@ossec:~# /var/ossec/bin/syscheck_update -u local
** Integrity check database updated.
and 
/var/ossec/bin/syscheck_update -a

** Integrity check database updated.
```

now, how can I verify it's working. in Other words, how can trigger anther scan in the agents?
tried changing the config file in the agent 
`/var/ossec/etc/ossec.conf` to `<frequency>60</frequency>` and restarted using 
`/var/ossec/bin/ossec-control restart` . but All I see in the agent log is this 

```
2016/04/25 13:09:25 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/messages'.
2016/04/25 13:09:25 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/auth.log'.
2016/04/25 13:09:25 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/syslog'.
2016/04/25 13:09:25 ossec-logcollector(1950): INFO: Analyzing file: '/var/log/dpkg.log'.
2016/04/25 13:09:25 ossec-logcollector: INFO: Monitoring output of command(3600): df -h
2016/04/25 13:09:25 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
2016/04/25 13:09:25 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 5
2016/04/25 13:09:25 ossec-logcollector: INFO: Started (pid: 14679).
2016/04/25 13:09:27 ossec-logcollector: WARN: Process locked. Waiting for permission...
2016/04/25 13:09:40 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '104.197.209.206'.
2016/04/25 13:09:42 ossec-agentd: INFO: Trying to connect to server (104.197.209.206:1514).
2016/04/25 13:09:42 ossec-agentd: INFO: Using IPv4 for: 104.197.209.206 .
2016/04/25 13:10:03 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '104.197.209.206'.
```

and nothing in the server log. 
I know the agent is active . verifed using `/var/ossec/bin/list_agents -a`

**Comment by aremai** [comment]
You shouldn't modify the ossec.conf on the agents.
Instead you should be using the shared agent.conf on the manager, located /var/ossec/etc/shared/agent.conf
This is push remotely from the manager onto the agents.......

and then restart the agent(s) in order to receive the agent.conf immediately.

Also it doesn't look like the agent has successfully connected to the manager.... in the ossec.log on the manager you should see something like this:
2016/04/22 18:07:53 ossec-remoted: INFO: Agent linuxAgent connected at 1.2.3.4

**Comment by aremai** [comment]
Also, I wouldn't necessarily be trusting in `list_agents -a`

Instead I would be using this command:
`/var/ossec/bin/agent_control -l`

**Comment by ddpbsd** [comment]
@ohadpartuck It's difficult for us to troubleshoot someone else's (@dcid) fork of OSSEC.

`list_agents -a` provides you all of the agents, `list_agents -c` should show you the connected agents (which that one won't be based on the log messages).

 I also think (but don't know definitively) that `syscheck_update -u local` will only clear the syscheck database for the OSSEC manager, not for the agents. So if the issue is with an agent's syscheck db, this may not have solved it. Adding some debugging to those log messages shouldn't be too difficult.

**Comment by aremai** [comment]
I think it's a general problem in the connection between agent and manager since agentd is reporting the problem that it can't connect to the manager (Process locked, Waiting for server reply, etc...)...
I'd try removing this particular agent from the manager and re-adding it.
I had a very similar problem (same error message) before, and solved it this way...

I assume the agent/manager connection was working correctly before (no firewall issues...)

**Comment by atomicturtle** [comment]
For that matter assuming this is a bug, we cant actually do anything about it

**Comment by ohadpartuck** [comment]
@aremai 
1. I have no `/var/ossec/etc/shared/agent.conf` on the server . but maybe i'll use this feature in the future. 
2. `list_agents -c` output is 
```
backoffice01-xx.xx.xx.xx is active.
algo-server-01-xx.xx.xx.xx6 is active.
chef-production2-mongo01-xx.xx.xx.xx is active.
ping-server01-xx.xx.xx.xx is active.
``` 
but weird enough, the discussed machine is not listed
3. ran the restart on one of the listed agents and i'm getting bombed with:
`2016/04/25 18:44:36 ossec-analysisd: Invalid integrity message in the database.`
on the server. 

4. tried to remove the agent and re-adding it seems to work (tailing the log right now). 
I think the issue was that I initially added the agent via the internal ip and edited the 
`/var/ossec/etc/client.keys` with the external address. 
** BTW - I think that ossec should defently enable placing internal hostnames instead of external ips (that can change) and i'm surprised that this isn't the case **

**Comment by dcid** [comment]
@ohadpartuck That error happens when the syscheck db file is broken somehow. The file format expects the checksum followed by a space and the file name. If there is a line that doesn't match this format, it will generate that warning.

Anyway you can paste the content of the syscheck db files?

**Comment by aremai** [comment]
@ohadpartuck use "any" instead of a dedicated "ip" in case you're behind a NAT or on DHCP

**Comment by aremai** [comment]
and if the `/var/ossec/etc/shared/agent.conf` doesn't exist yet, then you must create it.
you should really use that instead of editing it manually on the agents.

please see this document:
http://ossec-docs.readthedocs.org/en/latest/syntax/head_agent_config.html

**Comment by ohadpartuck** [comment]
@dcid "paste the content of the syscheck db files?" where are those located exactly?
@aremai can you paste an example a complete `/var/ossec/etc/shared/agent.conf` file? 
1. what happens if I have this file and the file on the agent?
2. what configuration are available there?

**Comment by aquerubin** [comment]
On Mon, 25 Apr 2016, Ohad Perry wrote:

> ** BTW - I think that ossec should defently enable placing internal 
> hostnames instead of external ips (that can change) and i'm surprised 
> that this isn't the case **

Yeah that's been on my mind too - need to get away from hard-coded IPs in 
the configs.  The fixes are not so trivial though but now that I'm in the 
semi-retired mode again I may take a stab at this.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by ohadpartuck** [comment]
btw @aremai here is the `` file on the agent for refrence:
`cat  /var/ossec/etc/ossec.conf`
```
<ossec_config>
  <client>
    <server-ip>xx.xx.xx</server-ip>
  </client>

  <syscheck>
    <!-- Frequency that syscheck is executed - default to every 22 hours -->
    <frequency>79200</frequency>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin</directories>
    <directories check_all="yes" realtime="yes">/apps</directories>



    <!-- Files/directories to ignore -->
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/mnttab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>

    <!-- Windows files to ignore -->
    <ignore>C:\WINDOWS/System32/LogFiles</ignore>
    <ignore>C:\WINDOWS/Debug</ignore>
    <ignore>C:\WINDOWS/WindowsUpdate.log</ignore>
    <ignore>C:\WINDOWS/iis6.log</ignore>
    <ignore>C:\WINDOWS/system32/wbem/Logs</ignore>
    <ignore>C:\WINDOWS/system32/wbem/Repository</ignore>
    <ignore>C:\WINDOWS/Prefetch</ignore>
    <ignore>C:\WINDOWS/PCHEALTH/HELPCTR/DataColl</ignore>
    <ignore>C:\WINDOWS/SoftwareDistribution</ignore>
    <ignore>C:\WINDOWS/Temp</ignore>
    <ignore>C:\WINDOWS/system32/config</ignore>
    <ignore>C:\WINDOWS/system32/spool</ignore>
    <ignore>C:\WINDOWS/system32/CatRoot</ignore>
  </syscheck>

  <rootcheck>
    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>
    <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_debian_linux_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_rhel_linux_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_rhel5_linux_rcl.txt</system_audit>
  </rootcheck>
  <!-- Files to monitor (localfiles) -->

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/auth.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/syslog</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/dpkg.log</location>
  </localfile>

  <localfile>
    <log_format>command</log_format>
    <command>df -h</command>
    <frequency>hourly</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort</command>
    <frequency>hourly</frequency>
  </localfile>
</ossec_config>
```

**Comment by aremai** [comment]
@ohadpartuck as for agent.conf please see the 2nd link that I posted...it has all the information you need ;)

I think what @dcid meant was whatever's in /var/ossec/queue/syscheck/ is..... did you? :)

**Comment by ddpbsd** [comment]
@ohadpartuck The syscheck db files are in `/var/ossec/queue/syscheck`. They are plain text files. Choose an agent that is exhibiting the issue, and copy/paste the file here or in a gist.

**Comment by ohadpartuck** [comment]
pasting from the new agent I added with the 'any' 
```
++2923:33279:0:1008:3b81ea9c9e8c6cbd5ba45ccd8b8266ae:5c07c82438968adcf57f7080d8a61db576b58870 !1461613644 /var/ossec/etc/ossec.conf
+++2779:33056:0:1008:598d73f03a708e74b1ad37a20af8f85a:623dd49b0b873093ce8a7c63de1c4627ba17158c !1461613644 /var/ossec/etc/internal_options.conf
+++716:33188:0:0:99a34592e41fb1e0639cf0fc64596346:d50a34b91965e368fc761e65d7e7135de3be40d6 !1461613715 /etc/groff/man.local
+++710:33188:0:0:f8c3e22fae1765942089881d9c5edeae:b7c7b41319b143e134fc97b36658751cc3396362 !1461613715 /etc/groff/mdoc.local
+++611:33188:0:0:fb2946cae573b8ed3d654a180d458733:117d838f3dbe3f94c5007720b41611a4ad0a6a69 !1461613715 /etc/perl/Net/libnet.cfg
+++127:33188:0:0:133aafb01e900b05e75042fd47dec067:59a25f628d8674b72c53c38426cacd46d1186dc9 !1461613715 /etc/apache2/conf-available/javascript-common.conf
+++3515:33188:0:0:e62ae447bdd228160f1f0b6bab8a7fd3:2f3d305fba36d5dd81fe88eb5d482ba54f48ef6f !1461613715 /etc/skel/.bashrc
..
+++3675:33279:0:0:75cd151c8d18bec64ade4747e4b2d03d:2e3ffa2c5b52c9a338e6fea7004d6488244967c4 !1461614075 /apps/after_restart.sh
```
trying to change `/apps/after_restart.sh`  on the agent machine to see if alerts on the change

**Comment by ddpbsd** [comment]
Is this new agent experiencing the issue in the topic? If not, the pasting doesn't mean much.

**Comment by ohadpartuck** [comment]
@ddpbsd yes, it is

**Comment by ohadpartuck** [comment]
thanks everyone the issue is now resolved. 
 removing and re adding the agent worked. 
I tailed the log `/var/ossec/logs/alerts/alerts.log` and saw that alerts are coming normally
