### ISSUE TITLE
How will Ossec work on mongodb data files

### ISSUE THREAD

**Issue by ohadperry** [ossec/ossec-hids#811]
Hi, 
This is not an issue but a question since i'm new to ossec. 
I want to check for data integrity in my database. i use `mongodb`
my data is stored in `/mnt/data/mongo` directory. 
If I set my ossec agent to monitor this directory, I will get alerts all the time, since the data is changing all the time. 
How can the `ossec` tool help me to protect my data there ?
monitor files changes by a different user maybe ?

please help.

**Comment by ddpbsd** [comment]
Is there a transaction log or something you could ingest into OSSEC?

**Comment by ohadpartuck** [comment]
@ddpbsd assuming there is - how will ossec distinct between an intruder transactions and normal transactions?

**Comment by ddpbsd** [comment]
It depends on your rules. Write rules to detect bad events. Write rules to eliminate acceptable events.

**Comment by ohadpartuck** [comment]
@ddpbsd sorry but the rules are simple a text search if i'm not mistaken. what text is valid and what not? do you have an example for a rule (any db is fine, not just mongodb)..

**Comment by ddpbsd** [comment]
Sorry, I don't. Check the rules directory to see if mysql or postgresql rules exist.

**Comment by Rumbles** [comment]
@ohadperry did you ever establish the best way to monitor your mongodb with ossec?
