### ISSUE TITLE
syslog_output should support DNS

### ISSUE THREAD

**Issue by sulaweyo** [ossec/ossec-hids#812]
We use ossec in an AWS environment where we use a bunch of hosts that get re-provisioned often and use a per region syslog collector. I can send syslogs to this collector easily via a single DNS entry that points to the correct collector for the current region. As the AMI is created in one region and deployed to the others i can not predefine the IP of the collector.

Unfortunately ossec requires an IP for syslog_output and does not accept a DNS which it should be able to do easily imho.

**Comment by ddpbsd** [comment]
I have the initial work done here: https://github.com/ddpbsd/ossec-hids/tree/issuee812_csyslog_dns
With us trying to wrapup 2.9 I don't see this making it in right away, but if I don't get to it feel free to remind me after the release.

**Comment by sulaweyo** [comment]
That's just awesome ddpbsd!
It's not actually a blocker as i could work around it but it would be still great to drop out that sed on the config at some point ;)

**Comment by ddpbsd** [comment]
@sulaweyo Which sed do you mean specifically? And what's wrong with it?

**Comment by aquerubin** [comment]
On Thu, 28 Apr 2016, Dan Parriott wrote:

> I have the initial work done here: https://github.com/ddpbsd/ossec-hids/tree/issuee812_csyslog_dns
> With us trying to wrapup 2.9 I don't see this making it in right away, but if I don't get to it feel free to remind me after the release.

I must be missing something.  OS_ConnectUDP() was converted to use strings 
for the server and so doesn't require a specified host to be an IP address 
any more.  And _SyslogConfig.server was converted to a string.  So is 
_SyslogConfig.port (ie. you can use a service name instead of a port 
number).

Bottom line is that other than the agent/key config, almost everything in 
OSSEC that previously required a host specification to be an IP address 
can now use a host name instead - unless I missed something :)

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by sulaweyo** [comment]
@ddpbsd just a sed that i use to patch the dns name to the correct ip in the config (nothing related to ossec code just my evil workaround)

@aquerubin i tried with v2.8.3 but did not get any alerts through until i switched to the IP of my syslog collector.

**Comment by ddpbsd** [comment]
@aquerubin I didn't realize that. Ignore my branch then. :-)

**Comment by aquerubin** [comment]
On Fri, 29 Apr 2016, Sledge Sulaweyo wrote:

> @aquerubin i tried with v2.8.3 but did not get any alerts through until 
> i switched to the IP of my syslog collector.

Right.  The change is already in the master branch but not in 2.8.3.  You 
can try building/installing directly from the master branch.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by sulaweyo** [comment]
Thx a lot!
You guys are doing a great job here!

**Comment by noqcks** [comment]
Is this supported?

I tried using a CNAME: 
```
2018/06/06 17:13:00 ossec-csyslogd(1216): ERROR: Unable to connect to 'syslog-a.logdna.com'.
```

When doing a ping on the host and using the IP
```
2018/06/06 17:16:21 ossec-csyslogd: INFO: Forwarding alerts via syslog to: '13.92.85.36:23907'.
```

My ossec configuration: 
```
  <syslog_output>
    <server>syslog-a.logdna.com</server>
    <port>23907</port>
    <format>cef</format>
  </syslog_output>
```

**Comment by ddpbsd** [comment]
@noqcks Do you have a copy of `/etc/resolv.conf` in `/var/ossec/etc`?
