### ISSUE TITLE
Not considered the transmission stick package problem?

### ISSUE THREAD

**Issue by lazyp** [ossec/ossec-hids#815]
I propose to add a message before transmission message size

**Comment by ddpbsd** [comment]
Can you explain what you mean by "transmission stick package problem?"

**Comment by lazyp** [comment]
@ddpbsd 
Two, stick the package problem analysis and countermeasure

TCP stick package refers to the sender of packet data to the receiver when the stick into a package, from the receive buffer, a packet data header followed by a packet data before the tail.

Causes of sticking phenomenon are in many aspects, it can be caused by the sender, the receiver may also cause. The sender by sticking is caused by the TCP protocol itself, TCP to improve the efficiency of data transmission, the sender is often to collect enough data before sending a packet of data. If the successive transmitted data are rarely, usually TCP based optimization algorithm to these data into a packet once sent out, so that the recipient received stick package data. The receiver caused by stick pack is due to the user process does not receive data, can lead to sticking phenomenon. This is because the receiver first received data in the receiving buffer, User process data from the buffer zone, If a packet arrives before a packet of data has not yet been user process removed, The next packet data into the system when the receiver buffer received a packet data, User process according to the predetermined buffer size buffer to receive data from the system, This is a time to multiple packet data
