### ISSUE TITLE
 ERROR: Unable to open file '/queue/ossec/.agent_info'

### ISSUE THREAD

**Issue by Chandira-2557** [ossec/ossec-hids#817]
When I run verify-agent-conf on the server, I am getting 
 verify-agent-conf(1103): ERROR: Unable to open file '/queue/ossec/.agent_info' . 
I have tried binary installation of server.

**Comment by ddpbsd** [comment]
Does that file exist (remember to account for the chroot to /var/ossec)?

**Comment by Chandira-2557** [comment]
The file does not exists in /var/ossec/queue/ossec directory. 
Do I need to make any other configuration changes to create that file?

**Comment by ddpbsd** [comment]
I cannot reproduce this issue. I don't have an `.agent_info` in `/var/ossec/queue/ossec`, but I also don't get the error.
