### ISSUE TITLE
agent.conf file ignored in Agent

### ISSUE THREAD

**Issue by Chandira-2557** [ossec/ossec-hids#818]
I have installed OSSEC as a server - agent through binary installation . When I change the agent.conf file on the server side, the agent.conf file on the client gets updated but upon restarting the configuration is not read . When I make the same in the /var/ossec/etc/ossec.conf file, the changes are taken . Do know where I went wrong.

**Comment by ddpbsd** [comment]
What version of OSSEC?
What changes are you making?
Are there any messages related to the agent.conf in the agent's ossec.log?

**Comment by Chandira-2557** [comment]
1.  OSSEC version 2.8.3 

 2. 
I have added the following line in the server's agent.conf file which gets updates in the agent : 
<agent_config>
 <syscheck>
  <directories check_all="yes">/var/ossec/etc</directories>
 </syscheck>
 <localfile>
          <log_format>full_command</log_format>
          <command>netstat -ulpn|grep LISTEN |grep -v 127.0.0.1 | sort </command>
          <alias>UDP Port Scan Alert  </alias>
          <frequency>3600</frequency>
 </localfile>
 <localfile>
        <log_format>full_command</log_format>
        <command>netstat -tlpn|grep LISTEN |grep -v 127.0.0.1 | sort </command>
        <alias>TCP Port Scan Alert </alias>
        <frequency>3600</frequency>
 </localfile>

  <localfile>
          <log_format>full_command</log_format>
          <command>w</command>
          <alias>Users Logged in</alias>
          <frequency>3600</frequency>
  </localfile>

 <localfile>
        <log_format>full_command</log_format>
        <command>ps -eo pcpu,pid,user,args| grep ossec</command>
        <alias>Agent Process Details</alias>
        <frequency>3600</frequency>
 </localfile>
</agent_config>

3. I dont get information about agent.conf in ossec.log even when I set  "agent.debug=2".

**Comment by Chandira-2557** [comment]
Any updates ..

**Comment by ddpbsd** [comment]
Check the permissions of the agent.conf?
Restart the agent processes and check for `/var/ossec/etc` being mentioned in a syscheck message.
I don't think commands will work in the agent.conf unless you change a setting in internal_options.conf.

**Comment by Chandira-2557** [comment]
FILE PERMISSION : -rw-r--r-- 1 ossec ossec   -->  agent.conf 
###################
LOG INFO : 
2016/05/04 17:53:33 ossec-agentd: INFO: (unix_domain) Maximum send buffer set to: '124928'.
2016/05/04 17:53:33 ossec-syscheckd: DEBUG: Starting ...
2016/05/04 17:53:33 syscheckd: Reading Configuration [/var/ossec/etc/ossec.conf]
2016/05/04 17:53:33 ossec-rootcheck: DEBUG: Starting ...
2016/05/04 17:53:33 ossec-rootcheck: Starting queue ...
2016/05/04 17:53:33 ossec-syscheckd: INFO: (unix_domain) Maximum send buffer set to: '124928'.
2016/05/04 17:53:34 ossec-syscheckd: INFO: (unix_domain) Maximum send buffer set to: '124928'.
2016/05/04 17:53:34 ossec-syscheckd: INFO: Started (pid: 2056).
2016/05/04 17:53:34 ossec-rootcheck: INFO: Started (pid: 2056).
###################
In internal_options.conf file , 
# Logcollector - If it should accept remote commands from the manager
logcollector.remote_commands=1
 

I dont see a log that reads agent.conf  file...

**Comment by ddpbsd** [comment]
I don't see any syscehck logs in your sampling that contain information on which directories it is watching. Do you have any directories defined in the ossec.conf?
Try running syscheckd in debug mode `pkill ossec-syscheckd && /var/ossec/bin/ossec-syscheckd -d` and check again I guess.

**Comment by Chandira-2557** [comment]
2016/05/04 18:03:53 ossec-syscheckd(1225): INFO: SIGNAL Received. Exit Cleaning...
2016/05/04 18:03:53 ossec-syscheckd(1225): INFO: SIGNAL Received. Exit Cleaning...
2016/05/04 18:03:53 ossec-syscheckd: DEBUG: Starting ...
2016/05/04 18:03:53 ossec-rootcheck: DEBUG: Starting ...
2016/05/04 18:03:53 ossec-rootcheck: Starting queue ...
2016/05/04 18:03:53 ossec-syscheckd: INFO: (unix_domain) Maximum send buffer set to: '124928'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: (unix_domain) Maximum send buffer set to: '124928'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: Started (pid: 6805).
2016/05/04 18:03:57 ossec-rootcheck: INFO: Started (pid: 6805).
2016/05/04 18:03:57 ossec-syscheckd: INFO: Monitoring directory: '/etc'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: Monitoring directory: '/bin'.
2016/05/04 18:03:57 ossec-syscheckd: INFO: Monitoring directory: '/sbin'.
2016/05/04 18:04:09 ossec-syscheckd: Setting SCHED_BATCH returned: 0

**Comment by ddpbsd** [comment]
I just installed 2.8.3 (from source) on a server and an agent. I created a very basic agent.conf
```
<agent_config>
  <syscheck>
    <directories check_all="yes">/var/ossec/etc</directories>
  </syscheck>
</agent_config>
```

And everything seems to be working. Using your agent.conf did not change things.
Perhaps you can strace syscheckd and dig through the output to see if that gives you any clues?

**Comment by Chandira-2557** [comment]
Steps I executed : 
Server : 
1. downloaded https://bintray.com/artifact/download/ossec/ossec-hids/ossec-hids-2.8.3.tar.gz
2. changed /ossec-hids-2.8.3/src/addagent/validate.c : 61 , edited **if( i  >= 9000)** 
3. make setmaxagents (set to 4000)
4. make setdb
5. called install.sh

I tried it twice , I am getting the error #817  when syscheckd starts.

Client  (Did not use the previous ): 
1 . downloaded https://bintray.com/artifact/download/ossec/ossec-hids/ossec-hids-2.8.3.tar.gz 
2. made changes in preloaded_var.conf 
USER_LANGUAGE="en"
USER_NO_STOP="y"
USER_INSTALL_TYPE="agent"
USER_ENABLE_ACTIVE_RESPONSE="y"
USER_ENABLE_SYSCHECK="y"
USER_ENABLE_ROOTCHECK="y"
USER_BINARYINSTALL="y"
 USER_AGENT_SERVER_IP="<Server IP>"
USER_AGENT_CONFIG_PROFILE="generic"
I enabled the above field.
3. Called install.sh

**Comment by ddpbsd** [comment]
I assume the server ip is populated during the install.sh process or manually after?

I did not make those changes, just did a vanilla installation on Ubuntu 14.04.
The BINARYINSTALL option requires that you pre-compile the binaries.
Since your agent.conf doesn't mention a config profile, perhaps try removing whatever that option inserts into the agent's ossec.conf

**Comment by ddpbsd** [comment]
And just tried using the options (except the BINARYINSTALL one) from your preloaded_var.conf in another container and it's still working.

**Comment by Chandira-2557** [comment]
Can you try the same using the Binary Installation. I am still  facing the same issue. Or is there anything I am missing in preloaded_var.conf

**Comment by ddpbsd** [comment]
It'll take me a while to get some systems setup to mess with this.

**Comment by Chandira-2557** [comment]
May be you can try it just once when you are free.. I have tried more than 5-6 times . A small request from your user!!

**Comment by ddpbsd** [comment]
Ok, I just did a binary install on an agent (using 2.8.3), and it worked with the small agent.conf I posted previously.

**Comment by ddpbsd** [comment]
And it works with the agent.conf you posted (accounting for the remote commands, of course).
Can you post the `<client>` section of the agent's ossec.conf?

**Comment by Chandira-2557** [comment]
Client Section of OSSEC.conf : 

 <client>
    <server-ip>192.168.5.10</server-ip>
  </client>
