### ISSUE TITLE
pure-transfer still decodes apache logs

### ISSUE THREAD

**Issue by BP9906** [ossec/ossec-hids#823]
Here's my example from OSSEC 2.8.3 fresh install:

2016/05/02 08:48:17 ossec-testrule: INFO: Reading local decoder file.
2016/05/02 08:48:17 ossec-testrule: INFO: Started (pid: 11076).
ossec-testrule: Type one log per line.

10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" 

**Phase 1: Completed pre-decoding.
       full event: '10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" '
       hostname: 'ossecserver'
       program_name: '(null)'
       log: '10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" '

**Phase 2: Completed decoding.
       decoder: 'pure-transfer'

**Phase 3: Completed filtering (rules).
       Rule id: '11310'
       Level: '0'
       Description: 'Rule grouping for pure ftpd transfers.'

**Comment by ddpbsd** [comment]
I believe this is fixed in master:
```
10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"


**Phase 1: Completed pre-decoding.
       full event: '10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"'
       hostname: 'ix'
       program_name: '(null)'
       log: '10.1.1.1 - - [02/May/2016:08:36:36 -0700] "GET /images/test.png HTTP/1.1" 200 1029 "http://abcxyz.local/css/test.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"'

**Phase 2: Completed decoding.
       decoder: 'web-accesslog'
       srcip: '10.1.1.1'
       url: '/images/test.png'
       id: '200'

**Phase 3: Completed filtering (rules).
       Rule id: '31108'
       Level: '0'
       Description: 'Ignored URLs (simple queries).'
```

**Comment by BP9906** [comment]
Pulled the following from master and overwrote it in decoder.xml and fixed my problem, thanks.

`<decoder name="pure-transfer">
  <prematch>^\S+ - \S+ [\d\d/\S\S\S/\d\d\d\d:\d\d:\d\d:\d\d \S\d\d\d\d] "\w+ \S+" </prematch>
  <regex>^(\S+) - (\S+) [\d\d/\S\S\S/\d\d\d\d:\d\d:\d\d:\d\d -\d\d\d\d] "(\S+) (\.+) (\d+) \d+$</regex>
  <order>extra_data,dstuser,action,url,status</order>
</decoder>
`
