### ISSUE TITLE
2.8.3 Postfix rules not firing?

### ISSUE THREAD

**Issue by LeeUK** [ossec/ossec-hids#835]
For example:

```
root@sentinel:/var/ossec/etc# echo "‌‌May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafinetwork>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>" | /var/ossec/bin/ossec-logtest
2016/05/08 12:52:50 ossec-testrule: INFO: Reading local decoder file.
2016/05/08 12:52:50 ossec-testrule: INFO: Started (pid: 16917).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: '‌‌May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafia.network>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'
       hostname: 'sentinel'
       program_name: '(null)'
       log: '‌‌May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafia.network>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'

**Phase 2: Completed decoding.
       No decoder matched.
```

The chosen log line isn't neccessarily one that would generate an alert, but I get no postfix alerts/active responses, and regardless of the event chosen from /var/log/mail.log, the program_name: is always read as '(null)' which is why I suspect Phase 2 onwards fails. 

The rest of the OSSEC alerts seem to work fine (Dovecot, apache/nginx etc) it's just Postfix it isn't picking up for some reason.

Any ideas/clues?

**Comment by aremai** [comment]
Hi @LeeUK 

hmm, must be your OSSEC environment, because the postfix decoder is matching for me.
Which OSSEC version are you using?

`**Phase 1: Completed pre-decoding.
       full event: 'May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafinetwork>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'
       hostname: 'mail'
       program_name: 'postfix/postscreen'
       log: 'NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafinetwork>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'

**Phase 2: Completed decoding.
       decoder: 'postfix'

**Phase 3: Completed filtering (rules).
       Rule id: '3300'
       Level: '0'
       Description: 'Grouping of the postfix reject rules.'`

The parent Postfix rule is firing...looks like a specific rule needs to be implemented for this event....

**Comment by ddpbsd** [comment]
It works in the 2.9 beta, although the decoder could probably be improved.
May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafia.network>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>


**Phase 1: Completed pre-decoding.
       full event: 'May  8 08:26:55 mail postfix/postscreen[22055]: NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafia.network>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'
       hostname: 'mail'
       program_name: 'postfix/postscreen'
       log: 'NOQUEUE: reject: RCPT from [157.122.148.242]:47407: 550 5.7.1 Service unavailable; client [157.122.148.242] blocked using bl.spamcop.net; from=<kos@mafia.network>, to=<z13699753428@vip.163.com>, proto=ESMTP, helo=<XL-20160217QQJV>'

**Phase 2: Completed decoding.
       decoder: 'postfix'

**Phase 3: Completed filtering (rules).
       Rule id: '3300'
       Level: '0'
       Description: 'Grouping of the postfix reject rules.'

**Comment by LeeUK** [comment]
Thanks @aremai that's interesting to see. I couldn't find any major mentions of it on searching before posting, so I'm not that surprised it may be a localised issue. I'm just stumped as to why, as it's a 99% stock installation (just a few 'level 0' local rules for a couple of persistently annoying false positives. 

I'm running 2.8.3 on Ubuntu 14.04 (server) and 12.04 (agent). Everything else on the same agent works fine (nginx, dovecot, etc) it just fails to pick up 99% of the Postfix log entries. It's an odd one...

**Comment by LeeUK** [comment]
@ddpbsd Dan, good to hear. I'll keep my fingers crossed for 2.9! Thanks for your quick responses.

**Comment by aremai** [comment]
@LeeUK can you maybe show me your postfix_decoders.xml ? There recently has been an update on that.....

**Comment by LeeUK** [comment]
@aremai I'm starting to wonder if there's something up with my install. I don't have a 'postfix_decoders.xml'. I do have a rules/postfix_rules.xml, and an etc/decoders.xml though. github won't let me attach them even after changing the file extensions... 

http://lee.smallbone.com/src/decoder.txt
http://lee.smallbone.com/src/postfix_rules.txt

Hope those help...

**Comment by aremai** [comment]
Ah ok, I understand.
I have a postfix_decoders.xml file, because I'm using the WAZUH ossec-fork. In this fork the decoders are split into separate files, whereas in the standard OSSEC release the decoders are still in one big file.
You might want to look into Dan's latest commit #836 because he fixed your issue.

**Comment by LeeUK** [comment]
Amazing!! I'm just heading off to work, but I'll test that change tomorrow
and let you both know how I get on.

Thanks very much indeed for the awesome response :)

**Comment by LeeUK** [comment]
@aremai @ddpbsd  Still in the same funk here even with #836. I'll just await v1.9... As it's working for everyone else and no one else is reporting "me too!", it must be something unique to my setup here and thus not your issue! I'm glad the issue reported enabled you guys to tweak something though. Thanks again for the really quick responses and help.

**Comment by ddpbsd** [comment]
@LeeUK Feel free to drop a note on the mailing list if you want more help with this.
