### ISSUE TITLE
2.9.0beta06

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#837]
This is kind of a catch-all for issues related to [2.9.0beta06](https://github.com/ossec/ossec-hids/tree/v2.9.0beta06). I would love to see some test results. If there are outstanding issues or pull requests that should be merged in before release, mention them here. For instance, I think PR #809 is important, and should be merged or further analyzed for a better solution.

New issues should be opened for anything that isn't already covered there (and then mentioned here).

So please post. Hopefully we'll be readying a release real soon.

**Comment by ddpbsd** [comment]
Here are source tarballs for beta6: https://github.com/ossec/ossec-hids/releases/tag/v2.9.0beta06

**Comment by calve** [comment]
I think there is a typo in https://github.com/ossec/ossec-hids/releases/tag/v2.9.0beta05

> Add support for the “nodiff” option when using report_changes, sensitive files tagged with in ossec.conf will have their contents included in an alert.

should be

> Add support for the “nodiff” option when using report_changes, sensitive files tagged with in ossec.conf will NOT have their contents included in an alert.

**Comment by ddpbsd** [comment]
@calve Thanks for the heads up!

**Comment by atomicturtle** [comment]
@Calve Updated, thanks for catching that!
