### ISSUE TITLE
Same expression on both sides of '&&'.

### ISSUE THREAD

**Issue by ChristianBeer** [ossec/ossec-hids#84]
cppcheck found this in [ossec-src/src/rootcheck/check_rc_pids.c](https://github.com/ossec/ossec-hids/blob/master/src/rootcheck/check_rc_pids.c#L295) on line 295. I tried to make sense of the mechanism in place but couldn't figure it out. Maybe it's just a copy&paste error as almost the same statement is on line 278 above. Someone with a more profound knowledge on how this works should take a look here.

**Comment by jrossi** [comment]
Looks like this was fixed as part of clean upa while ago.
