### ISSUE TITLE
Questions about the response time of Ossec alarm rules.

### ISSUE THREAD

**Issue by Canon88** [ossec/ossec-hids#841]
I used Ossec V2.8, 
Test rule is the ID 31310 in nginx_rules.xml.
Now my question is,Using echo command manual simulation, triggering ossec alarm.

For example:
**_echo echo '2016/05/10 09:26:27 [error] 44112#0: *173584487 open() "/opt/nginx/html/favicon.ico" failed (2: No such file or directory), client: 211.137.185.72, server: www.xxx.com, request: "GET /favicon.ico HTTP/1.1", host: "www.xxx.com"'>>/var/log/nginx_error.log_**

By observing the "/var/ossec/logs/alerts/alerts.log", I found that ossec does not display the alarm in real time. After the first warning rule is triggered, the next trigger rule is likely to be 30 seconds later.I do not understand why this is so。
I was such a test, because I collected the nginx error log, refresh more frequently.
Who can tell me why, thank you.

**Comment by ddpbsd** [comment]
Are you echoing more than 2 lines into the file? I believe analysisd will compare the log messages and discard duplicates that are generated very close together in time.

**Comment by Canon88** [comment]
Thank you for answering my question has been resolved . As you say, and I tested the log message is indeed the same , I understand what you mean , and modify the log message testing , it is now normal.
