### ISSUE TITLE
How to enable real-time monitoring?

### ISSUE THREAD

**Issue by Canon88** [ossec/ossec-hids#845]
test environment:
**agent ossec.conf**
ossec.conf
[**< directories realtime="yes" report_changes="yes" check_all="yes">/mnt </ directories >**]
**/mnt/test1.file (already existing)
/mnt/test2.file (newly added)**

Read the manual, linux and must install inotify inotify-tools-devel in order to achieve real-time monitoring.

Why sometimes real-time monitoring to work, sometimes real time monitoring does not work?
E.g:
Create '/mnt/test2.file' (new addition), use the vi editor 'test2.file', join 'this is a test!'
Then edit /mnt/test1.file (already existing), real-time monitoring does not work.

It is to wait until after test2.file added to syscheck db, the real-time monitoring work.
I do not know, real-time monitoring is that right?

**Comment by ddpbsd** [comment]
The realtime monitoring does not alert on new file creation, and a file has to have a baseline (created during a full scan) before the changes can be alerted on.

**Comment by Canon88** [comment]
Yes, I know, real-time monitoring and will not remind you create a new file.
I want to know why the real-time monitoring will not work, but after 5-10 minutes and can work.

**Comment by ddpbsd** [comment]
After installing the inotify packages, did you rebuild OSSEC? Does syscheckd report that realtime monitoring has started (`2016/05/17 08:01:24 ossec-syscheckd: INFO: Real time file monitoring started.`)? I just tested it on one of my OSSEC servers, and the file was reported as changed in under 20 seconds.

**Comment by Canon88** [comment]
no rebuild OSSEC.Just restart ossec process.
yes,I can see(2016/05/17 08:01:24 ossec-syscheckd: INFO: Real time file monitoring started.)It is normal.
But I changed the file already exists, and sometimes real-time monitoring of alarms, and sometimes have to wait 5-10 minutes before the alarm. I do not know why, I checked the agent ossec process.
```
2016/05/17 20:31:00 ossec-syscheckd: INFO: Starting syscheck scan.
2016/05/17 20:40:20 ossec-syscheckd: INFO: Ending syscheck scan.
```
Because **Ending syscheck scan**. Real-time monitoring it does not work?

**Comment by Canon88** [comment]
We need to rebuild ossec? Not written in the manual after installing inotify package. Need to rebuild ossec. If  need to rebuild ossec, please tell me how to rebuild, thanks.

**Comment by ddpbsd** [comment]
I would assume that before "ossec-syscheckd: INFO: Real time file monitoring started." realtime support isn't working.

It'd entirely possible you don't have to rebuild it after installing the prerequisites, I haven't really looked into it. When everything is present before I install OSSEC it just seems to work.

How did you initially install OSSEC? I imagine the procedure would be very similar.
```
cd ossec-hids-*/src
sudo make clean
cd ..
sudo ./install.sh
ENTER ENTER ENTER ENTER
```

**Comment by Canon88** [comment]
Yes, installation is the same.But for real-time monitoring, what's the problem?

Now real-time monitoring does not work,
When `**ossec-syscheckd: INFO:. Ending syscheck scan** `file change the alarm will be output
I do not understand

**Comment by ddpbsd** [comment]
Which distro/version of Linux are you using? It's working for me with Ubuntu 14.10. I'm testing between an lxc container and the OSSEC server on the host system.

**Comment by Canon88** [comment]
I'm using Centos 6.5.
Server: Centos 6.5
Client: Centos 6.5

**Comment by Canon88** [comment]
problem solved.
When the end of Ending syscheck scan, real-time monitoring work.
