### ISSUE TITLE
OSSEC widows agent 2.8

### ISSUE THREAD

**Issue by jelladtarek** [ossec/ossec-hids#847]
Hello
When I try to configure fresh install of OSSEC Agent 2.8.1 or 2.9 for Windows, agent can't write our new configuration file and start. It shows 2 errors: "Unable to set permissions on new configuration file" and "Unable to set permissions on auth key file".

In ossec.log apperas that line:

2014/09/17 18:04:10 ossec-win32ui: INFO: Running the following command (C:\Windows\system32\cmd.exe /c echo y|cacls "new-ossec.conf" /T /G Administrators:f)

so pleaaase i'm lookink for agent 2.7.1 (windows)

100000 thanks

**Comment by ddpbsd** [comment]
Do you have the (I'm guessing here) Administrators group on he system? Are you running the ui under an Administrator account?
