### ISSUE TITLE
Port Change Doesn't take effect

### ISSUE THREAD

**Issue by photoeye** [ossec/ossec-hids#863]
v 2.8.3 - I tried using a different port for the server and client.  I changed the ossec.conf file on the server to connect via syslog and use port 1519.  I also edited the clients to use this port as well.  Netstat shows that the manager is indeed listening on the desired port and that the clients are actually connected to the server ip on the desired port but the manager does not receive the activity and the client logs show, "waiting for reply from server."  The server and clients are installed in AWS on their linux ami and there is a SG that allows all between them (for testing only of course), but still no-go.. Any suggestions?

**Comment by ddpbsd** [comment]
Does it work if you change the type to secure instead of syslog?

**Comment by photoeye** [comment]
I have not tried that but I will and get back to you.

**Comment by photoeye** [comment]
Wow, so far so good.  I thought the secure type was reserved for 1514 so i didn't even think to try it.  Big Thanks!

**Comment by ddpbsd** [comment]
IIRC, the `secure` type is used for agents. `syslog` is used for devices that can't run agents (routers, switches, etc). I've opened a documentation ticket to remind myself to do something about the documentation to make this more clear.
