### ISSUE TITLE
Debian package logrotate olddir doesn't exist

### ISSUE THREAD

**Issue by hdep** [ossec/ossec-hids#865]
Hello,

since I upgraded to the last available package I have an issue with logrotate : 

error: /etc/logrotate.d/ossec-hids:13 error verifying olddir path /var/ossec/logs/archives/: Aucun fichier ou dossier de ce type

In fact when you install the package : 
ii  ossec-hids-agent               2.8.3-4jessie               amd64        OSSEC Agent - Host Based Intrusion Detection System

The file /etc/logrotate.d/ossec-hids contain  the following configuration : 

 Log rotation for Ossec HIDS
/var/ossec/logs/*.log {
    create 640 ossec ossec
    rotate 31
    compress
    missingok
    notifempty
    olddir /var/ossec/logs/archives/
    sharedscripts
    postrotate
       /var/ossec/bin/ossec-control restart
    endscript
}

The /var/ossec/logs/archives/ folder doesn't exist.
I think the package should create this folder.

**Comment by santiago-bassett** [comment]
Hi, I believe archives log files are rotated (and compressed) by OSSEC monitord process, so there is no need to add those to logrotate. OSSEC will automatically rotate those once a day.

**Comment by hdep** [comment]
Hello,

I agree if a process deal with it then the logrotate file should be removed from the package.

**Comment by wforumw** [comment]
Hi, as far a I know, on debian the log files are not automatically rotated once a day.
And due to the configuration of /etc/logrotate.d/ossec-hids you got this error.

**Comment by diclophis** [comment]
We are also experiencing this issue and would like to know how best to proceed... from our perspective we can do two things

1. We update our system configuration scripts to ensure `/var/ossec/logs/archives/` exists (this is less than ideal because a package is expected to install itself wholly)
1. We remove the logrotate.d file given that ossec already rotates the log files

**Comment by santiago-bassett** [comment]
I believe option 2 makes sense. Let me double check that and I'll be back with an update.

**Comment by RealRancor** [comment]
Option 2 would also solve the current issue that debsums is complaining about a missing file from the ossec-hids file:

> debsums: missing file /var/ossec/etc/logrotate.d/ossec-hids (from ossec-hids package)

as this file is currently moved from /var/ossec/etc/logrotate.d/ossec-hids to /etc/logrotate.d/

**Comment by cdslashetc** [comment]
This bug is annoying when you're trying to deploy via puppet to most but not all of ~400 servers either I could write some custom fact to check if ossec-hids is installed (and dir should be created), or need to deploy some script to all servers to take care of it.

I suggest adding the following to the logrotate script the "-p" will run silently without error if the dir already exists.

    prerotate
      mkdir -p /var/ossec/logs/archives
    endscript

**Comment by martonsz** [comment]
The same thing happens on ubuntu with version 2.8.3-4xenial.
I have only installed the `ossec-hids-agent` package.

I Found this in the docs about monitord:
[ossec-docs: ossec-monitord](http://ossec-docs.readthedocs.io/en/latest/programs/ossec-monitord.html)
> The ossec-monitord daemon monitors agent connectivity and compress daily log files. ossec-monitord is configured in ossec.conf. (see ossec.conf: Localfile options)  

And in the [ossec-docs FAQ](http://ossec-docs.readthedocs.io/en/latest/faq/ossec.html) it says:
> **How can I get ossec.log to rotate daily?**
> Currently OSSEC does not rotate the ossec.log, use logrotate.d or newsyslog to rotate it for now.

But the logrotate error is coming from my servers running the ossec-agent. So there is no monitord archiving the logs.

**Comment by hdep** [comment]
is there any plan for this issue ?

**Comment by ddpbsd** [comment]
Does this happen with a recent version of ossec?

**Comment by hdep** [comment]
I just installed it on Stretch : 

```
# dpkg --list | grep ossec
ii  ossec-hids-agent                      2.8.3-4stretch                              amd64        OSSEC Agent - Host Based Intrusion Detection System
```

still the same issue. 
To fix this, the package maintener just need to : 
- create /var/ossec/logs/archives/ folder

**Comment by hdep** [comment]
Any update  ?  How can I help  ?

**Comment by atomicturtle** [comment]
Closing this one as out of date, we definitely have an archives folder as of 3.6.0:

```
root@c701f7e5fd74:/var/ossec# ls -la /var/ossec/logs/
total 20
drwxr-x---  5 ossec ossec 4096 Mar 15 19:59 .
dr-xr-x--- 14 root  ossec 4096 Mar 15 19:59 ..
drwxr-x---  2 ossec ossec 4096 Mar 15 19:03 alerts
drwxr-x---  2 ossec ossec 4096 Mar 15 19:03 archives
drwxr-x---  2 ossec ossec 4096 Mar 15 19:03 firewall
-rw-rw-r--  1 ossec ossec    0 Mar 15 19:59 ossec.log
root@c701f7e5fd74:/var/ossec# dpkg-query -l |grep ossec
ii  ossec-hids-server          3.6.0-12034bionic                   amd64        OSSEC Server - Host Based Intrusion Detection System
```
