### ISSUE TITLE
Windows agent getting disconnect after 10 min.

### ISSUE THREAD

**Issue by nikhilve99** [ossec/ossec-hids#867]
agent installed on Windows Server 2012R2. Agent and server can communicate as expected.  In the agent logfile the following error appears every 10 minutes:

More than 600 seconds without server response...sending win32info

I've left it for 8 hours but it never establishes a connection again. However, if I restart the agent on the windows server it connects straight away. I can also restart it from the server using agent-control so the server can get to the agent.

kindly help
Regards
Nikhil

**Comment by ddpbsd** [comment]
This appears to be a duplicate of #415
