### ISSUE TITLE
ssh_integrity_check_bsd fails

### ISSUE THREAD

**Issue by apepojken** [ossec/ossec-hids#868]
The ssh_integrity_chech_bsd script works from terminal when I type out the options but when ossec starts it i get (debug mode):

2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: spawn ssh root@<host>
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Last login: Mon Jun 20 16:18:26 2016 from 172.16.1.104
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: OpenBSD 5.9 (GENERIC) #1761: Fri Feb 26 01:15:04 MST 2016
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer:
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Welcome to OpenBSD: The proactively secure Unix-like operating system.
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer:
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Please use the sendbug(1) utility to report bugs in the system.
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Before reporting a bug, please try to reproduce it with the latest
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: version of the code.  With bug reports, please try to ensure that
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: enough information to reproduce the problem is enclosed, and if a
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: known fix for it exists, include that as well.
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer:
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer:
2016/06/20 16:30:13 ossec-agentlessd: INFO: ssh_integrity_check_bsd: root@<host>: Started.
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: for i in `find  /usr/local /etc /bin /sbin 2>/dev/null`;do tail $i >/dev/null 2>&1 &&  md5=`md5 $i | cut -d "
=" -f 2|cut -d " " -f 2` && sha1=`sha1 $i | cut -d "=" -f 2|cut -d " " -f 2` && echo FWD: `stat -f "%Dz:%Dp:%Du:%Dg" $i`:$md5:$sha1 $i; done; exit
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: exit
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: tset: unknown terminal type network
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Terminal type? tset: unknown terminal type for i in `find  /usr/local /etc /bin /sbin 2>/dev/null`;do tail $i >/dev/null 2>&1 &&  md5=`md5 $i | cut -d "=" -f 2|cut -d " " -f 2` && sha1=`sha1 $i | cut -d "=" -f 2|cut -d " " -f 2` && echo FWD: `stat -f "%Dz:%Dp:%Du:%Dg" $i
`:$md5:$sha1 $i; done; exit
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Terminal type? Terminal type? tset: unknown terminal type exit

After this it waits until the timeout of the script is reached and then fails/timeout. 

If i run 
    agentless/ssh_integrity_check_bsd root@<host> /usr/local /etc /bin /sbin
it works and takes about 4-5 minutes to finish.

What is happening here?

**Comment by ddpbsd** [comment]
It looks like the terminal type isn't set:
```
016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: tset: unknown terminal type network
2016/06/20 16:30:13 ossec-agentlessd: DEBUG: buffer: Terminal type? tset: unknown terminal type for i in
```

**Comment by apepojken** [comment]
You are correct!
Needed to modify the .profile file on my BSD-machines.
Thanks for helping.
