### ISSUE TITLE
Looks like the same issue #865 (can be closed than)

### ISSUE THREAD

**Issue by wforumw** [ossec/ossec-hids#871]
Hi
After installing the new ossec-hids-agent_2.8.3-4jessie_amd64.deb I got this error on every server
```
/etc/cron.daily/logrotate:
error: ossec-hids:13 error verifying olddir path /var/ossec/logs/archives/: No such file or directory
error: found error in file ossec-hids, skipping
```
It seems that the archives directory does not exist or is not automatically created.

**Comment by RealRancor** [comment]
@wforumw You can close issues on your own by hitting the "Close" button below the comment field.
