### ISSUE TITLE
ossec-agentd: INFO: Event count after '20000'

### ISSUE THREAD

**Issue by Canon88** [ossec/ossec-hids#872]
About ossec_agent ossec.log display `Event count after '20000': 7446750->5493672 (73%)`and `WARN: Problem receiving message from 172.172.200.235.`
ossec server ip 172.172.200.235
ossec agent ip 172.172.100.1

 `more /var/ossec/logs/ossec.log`
`
2016/06/24 07:38:28 ossec-agentd: INFO: Event count after '20000': 7446750->5493672 (73%)
2016/06/24 07:41:54 ossec-agentd(1214): WARN: Problem receiving message from 172.172.200.235.
2016/06/24 08:01:54 ossec-agentd(1214): WARN: Problem receiving message from 172.172.200.235.
2016/06/24 08:02:56 ossec-agentd: INFO: Event count after '20000': 7446764->5497000 (73%)
2016/06/24 08:11:54 ossec-agentd(1214): WARN: Problem receiving message from 172.172.200.235.
2016/06/24 08:24:42 ossec-agentd: INFO: Event count after '20000': 7485805->5516704 (73%)
2016/06/24 08:31:54 ossec-agentd(1214): WARN: Problem receiving message from 172.172.200.235.
2016/06/24 08:41:54 ossec-agentd(1214): WARN: Problem receiving message from 172.172.200.235.
2016/06/24 08:45:08 ossec-agentd: INFO: Event count after '20000': 7534213->5552112 (73%)
`

I do not understand `INFO: Event count after '20000': 7446750->5493672 (73%)` and `WARN: Problem receiving message from 172.172.200.235.` What does that mean.

ossec server and ossec agent network connection is no problem.I've seen other agent did not find `WARN: Problem receiving message from 172.172.200.235.`
Who can help me? Thank you.

**Comment by ddpbsd** [comment]
I can't remember what it means exactly, but I don't think I've seen any ill effects related to the message.
