### ISSUE TITLE
Fixed route-null active response for Windows agents

### ISSUE THREAD

**Issue by mfbiux** [ossec/ossec-hids#875]
I fixed two issues:

1) the regular expression for IPs was wrong.

2) added flag -p to the command.

 Without these changes, the active response for newer OS servers is useless.

**Comment by mfbiux** [comment]
![route-null](https://cloud.githubusercontent.com/assets/6702974/16361710/a706cd04-3b99-11e6-94db-902122d560a4.png)

Please rename the exension from .png to .zip. Github wouldn't let me upload otherwise...

**Comment by ddpbsd** [comment]
Can you submit a pull request? This issue doesn't really have any information.
