### ISSUE TITLE
Invalid issue. delete.

### ISSUE THREAD

**Issue by mfbiux** [ossec/ossec-hids#876]

**Comment by aquerubin** [comment]
On Tue, 28 Jun 2016, mfbiux wrote:

> The extra rules are these:
>
> `<decoder name="windows-login">
>  <type>windows</type>
>  <prematch>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Security: \.* Source Network Address: \S+</prematch>
>  <regex>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Security: (\w+)\((\d+)\): (\.+): </regex>
>  <regex>(\.+): \.+: (\S+): </regex>
>  <regex>\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+:\.+Source Network Address: (\d+.\d+.\d+.\d+)</regex>
>  <order>status, id, extra_data, user, system_name, srcip</order>
>  <fts>name, location, user, system_name</fts>
> </decoder>
>
> <decoder name="windows-sql-login">
>  <type>windows</type>
>  <prematch>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Application: AUDIT_FAILURE(\.*): MSSQL\.* [CLIENT: \S+]</prematch>
>  <regex>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Application: (\w+)\((\d+)\): (\.+): </regex>
>  <regex>(\.+): \.+: (\S+): </regex>
>  <regex>\.+[CLIENT: (\d+.\d+.\d+.\d+)]</regex>
>  <order>status, id, extra_data, user, system_name, srcip</order>
> </decoder>`
>
>
> At the moment, they only work if used BEFORE the current **windows** 
> rule. On my server installation, I moved both the windows rule and these 
> two rules to the local_decoder and set the windows rule at the bottom.
>
> They should be added to the main decoder.xml for future releases.

Several of those regex need to be modified to catch IPv6 addresses.

--
Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com
