### ISSUE TITLE
Added two very important decoders for windows os

### ISSUE THREAD

**Issue by mfbiux** [ossec/ossec-hids#877]
Basically, the decoder named **windows** managed to decode events correctly but did not extract the source IP for failed auth attempts. This, in turn, cause the windows active response not to fire.

The extra rules are these:

<decoder name="windows-login">
  <type>windows</type>
  <prematch>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Security: .\* Source Network Address: \S+</prematch>
  <regex>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Security: (\w+)((\d+)): (.+): </regex>
  <regex>(.+): .+: (\S+): </regex>
  <regex>.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+:.+Source Network Address: (\d+.\d+.\d+.\d+)</regex>
  <order>status, id, extra_data, user, system_name, srcip</order>
  <fts>name, location, user, system_name</fts>
</decoder>

<decoder name="windows-sql-login">
  <type>windows</type>
  <prematch>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Application: AUDIT_FAILURE(._): MSSQL._ [CLIENT: \S+]</prematch>
  <regex>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: Application: (\w+)((\d+)): (.+): </regex>
  <regex>(.+): .+: (\S+): </regex>
  <regex>.+[CLIENT: (\d+.\d+.\d+.\d+)]</regex>
  <order>status, id, extra_data, user, system_name, srcip</order>
  <fts>name, location, user, system_name</fts>
</decoder>

At the moment, they only work if used BEFORE the current **windows** rule. On my server installation, I moved both the windows rule and these two rules to the local_decoder and set the windows rule at the bottom.

They should be added to the main decoder.xml for future releases.

**Comment by ddpbsd** [comment]
Can you provide log samples?

**Comment by mfbiux** [comment]
This is a typical Windows event log with source IP. The default decoder will correctly identify it and decode it but it will not extract the **srcip** which makes it useless in terms of active responses. My decoder will both correctly decode and extract the **srcip**

> 2016 Jul 03 09:22:02 WinEvtLog: Security: AUDIT_FAILURE(4625): Microsoft-Windows-Security-Auditing: (no user): no domain: TEST: An account failed to log on. Subject:  Security ID:  S-1-5-18  Account Name:  TEST$  Account Domain:  WORKGROUP  Logon ID:  0x3e7  Logon Type:   10  Account For Which Logon Failed:  Security ID:  S-1-0-0  Account Name:  administrator  Account Domain:  TEST  Failure Information:  Failure Reason:  %%2313  Status:   0xc000006d  Sub Status:  0xc000006a  Process Information:  Caller Process ID: 0x8c4  Caller Process Name: C:\Windows\System32\winlogon.exe  Network Information:  Workstation Name: TEST  Source Network Address: 61.50.133.131  Source Port:  4489  Detailed Authentication Information:  Logon Process:  User32   Authentication Package: Negotiate  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon request fails. It is generated on the computer where access was attempted.

**Comment by mfbiux** [comment]
I would like to add that, by default, Windows Server 2008 and 2012 are not triggering active responses after failed logins because of this issue. We had a drastic drop in the number of attempts after this was fixed.

**Comment by ddpbsd** [comment]
I don't have a whole lot of experience with Windows logs really, but that seems like the "windows" decoder should handle it. And that decoder could be extended to grab a src ip.

**Comment by ddpbsd** [comment]
Ok, so pull request #809 makes this log message decode as a ``windows`` event. Changing the decoders further to something like this might be useful:
```
<decoder name="windows">
  <type>windows</type>
  <program_name>^WinEvtLog</program_name>
</decoder>

<decoder name="windows1">
  <type>windows</type>
  <parent>windows</parent>
  <regex offset="after_parent">^\.+: (\w+)\((\d+)\): (\.+): </regex>
  <regex>(\.+): \.+: (\S+): </regex>
  <order>status, id, extra_data, user, system_name</order>
  <fts>name, location, user, system_name</fts>
</decoder>

<decoder name="windows1">
  <type>windows</type>
  <prematch>Source Network Address: </prematch>
  <regex offset="after_prematch">^(\S+)</regex>
  <regex> Source Network Address: (\S+) Source</regex>
  <order>srcip</order>
</decoder>
```

Of course this doesn't quite work, and I'm not sure I have the time to figure out why right now. I also don't have a lot of windows log messages to test against.

**Comment by ddpbsd** [comment]
Do you have a windows-sql-login log sample? The decoder looks a bit suspect, and if pull request #880 gets accepted I'd like to test vs that.

**Comment by mstarks01** [comment]
Way back when I had the crazy idea of sorting out the Windows decoder and rules situation, I started a Google spreadsheet to make things easier. The idea was to have a place people could contribute log samples, share notes on particular event IDs, etc. No one wanted to participate so I abandoned it. Check it out--maybe it will be helpful: https://docs.google.com/spreadsheets/d/1LN66GU_DSPf30KXW7gTsJFtZDI3KZ826T1TjM7qulck/edit?usp=sharing

**Comment by ddpbsd** [comment]
@mstarks01 Thanks! I'll definitely play around with that.

**Comment by alvaroortizmoya** [comment]
I came to the Ossec issues thread to post something similar to this and I found this fantastic thread!

A few weeks ago I had the same problem while playing with Ossec for my company. I realized that it was not working properly when Windows alerts were being received by the Ossec server. 
For instance, I had the same issue as you when I wanted to get the source IP for that kind of alerts, so I did my windows decoder just like yours. 

After that, I realized that other alerts for auditing, didn't show the user name in the correct field. The Ossec decoder was showing (no user) as the user instead. This alert for example:

`2016 Jul 04 00:00:00 WinEvtLog: Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: mydomain: Special privileges assigned to new logon. Subject: Security ID: S-1-5-21-4211346334-2188977166-335516779-1121 Account Name: myusername Account Domain: mydomain Logon ID: 0x10b72ea0 Privileges: SeBackupPrivilege SeRestorePrivilege`

For this alerts I had to create a new windows decoder and I had to merge both decoders to distinguish those kind of alerts. 
So my final decoder will be something like this one and it works fine:

\<decoder name="windows"\>
  \<type\>windows\</type\>
  \<prematch\>^\d\d\d\d \w\w\w \d\d \d\d:\d\d:\d\d WinEvtLog: |^WinEvtLog: \</prematch\>
\</decoder\>

\<decoder name="windows-nouser"\>
  \<type\>windows\</type\>
  \<parent\>windows\</parent\>
  \<prematch offset="after_parent"\>\(no user\)\</prematch\>
  \<regex offset="after_parent"\>\.+:\s+(\w+)\((\d+)\):\s+(\.+):\s+\</regex\>
  \<order\>status, id, extra_data\</order\>
  \<fts\>name, location, user, system_name\</fts\>
\</decoder\>

\<decoder name="windows-nouser"\>
  \<type\>windows\</type\>
  \<parent\>windows\</parent\>
  \<regex offset="after_regex"\>Account Name:\s+(\.+)\s+Account Domain:\s+(\S+)\</regex\>
  \<order\>dstuser, system_name\</order\>
\</decoder\>

\<decoder name="windows-info"\>
  \<type\>windows\</type\>
  \<parent\>windows\</parent\>
  \<prematch offset="after_parent"\>\w+:\s+\S+\</prematch\>
  \<regex offset="after_parent"\>\.+:\s+(\w+)\((\d+)\):\s+(\.+):\s+\</regex\>
  \<regex\>(\.+):\s+\.+:\s+(\S+):\s+\</regex\>
  \<order\>status, id, extra_data, user, system_name\</order\>
  \<fts\>name, location, user, system_name\</fts\>
\</decoder\>

\<decoder name="windows-info"\>
\<type\>windows\</type\>
\<parent\>windows\</parent\>
\<regex offset="after_regex"\>Source Network Address:\s+(\S+)\</regex\>
  \<order\>srcip\</order\>
\</decoder\>

(Sorry, I couldn't insert the code properly...)

So what do you think? Should I add something to improve the decoder or are there other kind of windows alerts to be included with a new decoder?

Thank you very much in advance people!

**Comment by ddpbsd** [comment]
This is how it decodes with PR #880 
```
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: '2016 Jul 04 00:00:00 WinEvtLog: Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: mydomain: Special privileges assigned to new logon. Subject: Security ID: S-1-5-21-4211346334-2188977166-335516779-1121 Account Name: myusername Account Domain: mydomain Logon ID: 0x10b72ea0 Privileges: SeBackupPrivilege SeRestorePrivilege'
       hostname: 'ix'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: mydomain: Special privileges assigned to new logon. Subject: Security ID: S-1-5-21-4211346334-2188977166-335516779-1121 Account Name: myusername Account Domain: mydomain Logon ID: 0x10b72ea0 Privileges: SeBackupPrivilege SeRestorePrivilege'

**Phase 2: Completed decoding.
       decoder: 'windows'
       status: 'AUDIT_SUCCESS'
       id: '4672'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'mydomain'

**Phase 3: Completed filtering (rules).
       Rule id: '18104'
       Level: '0'
       Description: 'Windows audit success event.'
```

**Comment by alvaroortizmoya** [comment]
@ddpbsd, Yes. The default decoder shows that result. What I wanted to say is that with the decoder I posted the result is:

` **Phase 1: Completed pre-decoding.
       full event: '2016 Jul 04 00:00:00 WinEvtLog: Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: mydomain: Special privileges assigned to new logon. Subject: Security ID: S-1-5-21-4211346334-2188977166-335516779-1121 Account Name: myusername Account Domain: mydomain Logon ID: 0x10b72ea0 Privileges: SeBackupPrivilege SeRestorePrivilege'
       hostname: 'alvaro'
       program_name: '(null)'
       log: '2016 Jul 04 00:00:00 WinEvtLog: Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: mydomain: Special privileges assigned to new logon. Subject: Security ID: S-1-5-21-4211346334-2188977166-335516779-1121 Account Name: myusername Account Domain: mydomain Logon ID: 0x10b72ea0 Privileges: SeBackupPrivilege SeRestorePrivilege'

**Phase 2: Completed decoding.
       decoder: 'windows'
       status: 'AUDIT_SUCCESS'
       id: '4672'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: 'myusername'
       system_name: 'mydomain'

**Phase 3: Completed filtering (rules).
       Rule id: '18104'
       Level: '0'
       Description: 'Windows audit success event.' `

So now, the dstuser is filled with the correct username instead with the "(no user)" string. This is because the windows user name is after the "Account name: ".

**Comment by ddpbsd** [comment]
The default decoder didn't give me anything at all. I've updated the decoders in the PR to grab the account name.
