### ISSUE TITLE
Geoip support in 2.9.0rc2

### ISSUE THREAD

**Issue by dbgdngit** [ossec/ossec-hids#889]
Hi

I'm testing with 2.9.0rc2 as it seems to support agent-authd (it does and we have it working) however having upgraded the connecting master server onto the same version we no longer appear to be able to get geoip support working. There is no 'make' target for setgeoip. I believe geoip was due to be built in but I'm unsure on the status and how it should be configured in version2.9.0rc2

**Comment by ddpbsd** [comment]
I don't use the geoip stuff, but I think it can be compiled in with `env USE_GEOIP=yes ./install.sh`

**Comment by atomicturtle** [comment]
Example from the RPM packages:
make DATABASE=mysql MAXAGENTS=16384 USE_GEOIP=1 TARGET=server V=1

**Comment by dbgdngit** [comment]
Thanks @atomicturtle @ddpbsd 
Trying both of those gives in ossec.log 
"invalid element in ossec.conf for <geoip_db_path>/etc/GeoLiteCity.dat</geoip_db_path> "
This is still supposed to be a relative path to the ossec install right?

**Comment by dbgdngit** [comment]
on AWS Centos AMI

make TARGET=server USE_GEOIP=yes still gives "invalid element in ossec.conf for /etc/GeoLiteCity.dat "

However i then ran yum install GeoIP, restarted OSSEC and bingo!
