### ISSUE TITLE
Contrib tools need to be updated for IPv6.

### ISSUE THREAD

**Issue by aquerubin** [ossec/ossec-hids#892]
There are a number of PERL-based tools in contrib that need to be updated to handle IPv6 addresses.  Most of the problems stem from using regular expression matches that work only for IPv4 addresses.

active-list.pl
ossec2mysqld.pl
ossec2mysql.pl
ossec2snorby.pl
ossectop.pl

**Comment by ddpbsd** [comment]
With the merge of #896 is this resolved?

**Comment by aquerubin** [comment]
On Wed, 13 Jul 2016, Dan Parriott wrote:

> With the merge of #896 is this resolved?

I hope so.  I've closed this issue.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com
