### ISSUE TITLE
Pull Request #862 segfaults with rules_dir

### ISSUE THREAD

**Issue by atomicturtle** [ossec/ossec-hids#900]
From Pull Request #862 comment thread:

"
It looks like this is segfaulting on ossec-logtest if the system is configured to use a rules_dir configuration like this:

<rule_dir pattern=".xml$">etc/rules.d</rule_dir>"

Blocking issue, We will need to resolve or otherwise revert this PR to release 2.9

**Comment by vikman90** [comment]
I'm testing it but I can't reproduce the issue.

I moved `rules/ossec_rules.xml` to `etc/rules.d` and replaced `<include>ossec_rules.xml</include>` for `<rule_dir pattern=".xml$">etc/rules.d</rule_dir>` and `ossec-logtest` seems to work, both with the PR and without it.

Can you describe the steps you followed to get the segfault?

**Comment by ddpbsd** [comment]
Possible fix: https://gist.github.com/ddpbsd/264813ddaeef22f632eb7f6ec0f7ba39
