### ISSUE TITLE
Documentation improvement suggestion for rootcheck audit txt files

### ISSUE THREAD

**Issue by jsilverman-blispay** [ossec/ossec-hids#904]
This took me ages to figure out; it is because the documentation is misleading regarding "registry" as compared to "files" and especially " directories.

The header of the rootcheck system audit files has this stanza:

```
# Additional values:
# For the registry , use "->" to look for a specific entry and another
# "->" to look for the value.
# For files, use "->" to look for a specific value in the file.

```

The misleading part is that **directories also appear to require** a "stepped" search definition (i.e. two "-> " arrows); and that to search "all files in a dir" one needs to use the "^\." regex.

I recommend a change something like this:

```
# For the registry, and for directories , use "->" to look for a specific entry and another
# "->" to look for the value.
# Also, use " -> r:^\. -> ..." to search all files in a directory

```

The precise wording doesn't much matter to me, it is just that this is not documented **anywhere** else.

**Comment by ddpbsd** [comment]
PR #905 addresses this, thanks for the help!
