### ISSUE TITLE
srcip can't match because it ends with quotation mark

### ISSUE THREAD

**Issue by nemapl** [ossec/ossec-hids#906]
I'm trying with ossec hids 2.9rc2
ossec-logtest with following line:
Wed Jul 27 18:32:27 2016 [pid 2] CONNECT: Client "192.168.100.175"

It outputs as:
**Phase 2: Completed decoding.
       decoder: 'vsftpd'
       action: 'CONNECT'
       srcip: '192.168.100.175"'

Quotation mark at the end of srcip line (last line in Phase 2) - with that it is impossible to match.

**Comment by ddpbsd** [comment]
This is an odd one, but please test this decoder:
```
<decoder name="vsftpd_connect">
  <parent>vsftpd</parent>
  <prematch offset="after_parent">^CONNECT:</prematch>
  <regex offset="after_parent">(CONNECT): Client "(\S+\w+)"$</regex>
  <order>action,srcip</order>
</decoder>
```

Brief testing with an ipv4 and an ipv6 addresses

**Comment by nemapl** [comment]
Already better:

**Phase 2: Completed decoding.
       decoder: 'vsftpd'
       action: 'CONNECT'
       srcip: '192.168.100.175'

**Comment by ddpbsd** [comment]
Thanks for the report. I've submitted a PR to fix the issue.

**Comment by nemapl** [comment]
Thanks for extra fast response
