### ISSUE TITLE
ossec-agentd is unable to unmerge files

### ISSUE THREAD

**Issue by HiTechRabbit** [ossec/ossec-hids#908]
Hello there,

I've installed an ossec 2.9 rc2 agent but It keeps logging this strange error : 
`
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/rootkit_trojans.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/rootkit_files.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/cis_rhel6_linux_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/cis_rhel5_linux_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/cis_rhel_linux_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/cis_rhel7_linux_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/win_audit_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/system_audit_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/win_applications_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/cis_debian_linux_rcl.txt'.
2016/07/28 15:15:49 ossec-agentd: ERROR: Unable to unmerge file '/etc/shared/win_malware_rcl.txt'.
`
 What should I do to resolve it ?

**Comment by ddpbsd** [comment]
I think this commit fixed it (probablyadded after rc2): https://github.com/ossec/ossec-hids/commit/19a0b850a0b7b31696f20e2f86326911de50a716
Apply the permission changes and it should work.

**Comment by HiTechRabbit** [comment]
Thx that's exactly what I was looking for c:
