### ISSUE TITLE
ossec syscheck and email notifications issues

### ISSUE THREAD

**Issue by daiyueweng** [ossec/ossec-hids#949]
Hi, I installed a local `ossec`, and tried to monitor some directories for file integrity and file additions (using `<alert_new_files>yes</alert_new_files>`) checking in real time, the `ossec.conf` is as follows,

```
<global>
     <email_notification>yes</email_notification>
     <email_to>my_email@example.com</email_to>
     <smtp_server>ns0.bt.net.</smtp_server>
     <email_from>my_email@example.com</email_from>
</global>
<syscheck>
     <!-- Frequency that syscheck is executed - default to every 22 hours -->
     <frequency>79200</frequency>
     <alert_new_files>yes</alert_new_files>

     <!-- Directories to check  (perform all possible verifications) -->
     <directories report_changes="yes" realtime="yes" check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
     <directories report_changes="yes" realtime="yes" check_all="yes">/bin,/sbin</directories>
     <directories report_changes="yes" realtime="yes" check_all="yes">/home/user_name</directories>
</syscheck>
```

the `local_rules.xml` is as follows,

```
<group name="local,syslog,">

<!-- Note that rule id 5711 is defined at the ssh_rules file
  -  as a ssh failed login. This is just an example
  -  since ip 1.1.1.1 shouldn't be used anywhere.
  -  Level 0 means ignore.
  -->
<rule id="100001" level="0">
  <if_sid>5711</if_sid>
  <srcip>1.1.1.1</srcip>
  <description>Example of rule that will ignore sshd </description>
  <description>failed logins from IP 1.1.1.1.</description>
</rule>

<rule id="554" level="7" overwrite="yes">
  <category>ossec</category>
  <decoded_as>syscheck_new_entry</decoded_as>
  <description>File added to the system.</description>
  <group>syscheck,</group>
</rule>
</group> <!-- SYSLOG,LOCAL -->
```

The problem is whenever I added a file in `home/user_name`, there is no log shown in `alerts.log`, but if I deleted the file, a log would show in `alerts.log` saying file deletion. Although the Email notification is set correctly, there were no emails received either. How to fix these issues?

**Comment by ddpbsd** [comment]
The mailing list is usually the place to look for help. It's a lot easier to deal with than github. In fact someone posted yesterday with the same problems.

> The problem is whenever I added a file in home/user_name, there is no log shown in alerts.log, but if I deleted the file, a log would show in alerts.log saying file deletion.

First, is there a baseline syscheck scan from before you added the file? Next, did a new syscheck scan run after the file was added to the system? Last, if a new scan was run was the file added to the syscheck db (/var/ossec/queue/syscheck/syscheck maybe)?

> Although the Email notification is set correctly, there were no emails received either. How to fix these issues?

Have any alerts shown up in alerts.log? Did any alert that showed up in alerts.log cause an email to be delivered? Is ossec-maild running? If you use tcpdump on the machine (looking on the interface the mail would be sent from) do you see any errors if it tries communicating with your mail server? Perhaps the server requires authentication.
