### ISSUE TITLE
ossec-dbd did not start correctly (CentOS7/v2.8.3)

### ISSUE THREAD

**Issue by telefax** [ossec/ossec-hids#955]
I'm trying to hook up my ossec installation on CentOS 7 (selinux set to permissive atm) to mysql.
I used the official repository to install this.

No matter if I have my database info configured in ossec.conf or not I still get the following error (I have enabled database):

 /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
ossec-dbd did not start correctly.

I tried enabling debug in internal_options.conf on everything just to be doubly sure, yet ossec.log provides no additional details.

How can I proceed?

**Comment by ddpbsd** [comment]
Try running dbd in debug mode: `/var/ossec/bin/ossec-dbd -df`

**Comment by telefax** [comment]
Sorry, I was too eager to get it working so I compiled it from source and it worked perfectly fine that way. Maybe something up with the rpm's or missing deps or so.

**Comment by atomicturtle** [comment]
Did you run /var/ossec/bin/ossec-control enable database?

**Comment by telefax** [comment]
Yes I did.
