### ISSUE TITLE
Invalid "enable integrator" (ossec-control)

### ISSUE THREAD

**Issue by F1LT3R** [ossec/ossec-hids#956]
I noticed that a slack alerts are available: https://ossec.github.io/blog/posts/2016-04-29-OSSEC-2.9.0-beta5-RELEASE.html?highlight=slack

Looking for instructions on how to enable this, I found `enable integrator` details outlined here: https://blog.sucuri.net/2016/01/server-security-integrating-ossec-with-slack-and-pagerduty.html

I have tested this with `Beta 05` and `v2.9.0 RC3` from the releases page: https://github.com/ossec/ossec-hids/releases

When I run the following command ...:

```shell
/var/ossec/bin/ossec-control enable integrator
```

... I get the following output:

```shell
Invalid enable option.

Enable options: database, client-syslog, agentless, debug
Usage: /var/ossec/bin/ossec-control enable [database|client-syslog|agentless|debug]
```

Have the slack integration details changed?
Where can I find documentation for Slack integration?

Thanks for your help.

**Comment by ddpbsd** [comment]
We have not added integrator. There is a slack AR though:
https://github.com/ossec/ossec

**Comment by F1LT3R** [comment]
Thanks, working.
