### ISSUE TITLE
ossec-control exit status is nonzero when maild is disabled by config

### ISSUE THREAD

**Issue by jwives** [ossec/ossec-hids#960]
If `<email_notification>no</email_notification>` is specified in `ossec.conf`, ossec-maild will not be run when starting ossec. Checking service status via `ossec-control status` will report this as not running and then `return 1`.

It seems that the better behavior would be to validate that the service _should_ be running (check `ossec.conf`) and compare current vs desired state when determining return value, rather than simply expecting all services to be running.

**Comment by marcRBD** [comment]
hi 
i confirm that on debian 8.6 ossec-maild is not running after <email_notification>no</email_notification>
