### ISSUE TITLE
Ossec logrotate output

### ISSUE THREAD

**Issue by hdep** [ossec/ossec-hids#963]
Hello,

I'm currently getting spammed by ossec every night, during logrotate, there is a restart of ossec, but the output is not managed hence, logrotate send the output by e-mail :

```
/etc/cron.daily/logrotate:
Killing ossec-logcollector ..
Killing ossec-syscheckd ..
Killing ossec-agentd ..
Killing ossec-execd ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
Started ossec-execd...
2016/10/03 06:53:16 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
Started ossec-agentd...
Started ossec-logcollector...
Started ossec-syscheckd...
Completed.
```

If I take rsysolg has example, the postrotate command send output to /dev/nul : 
`invoke-rc.d rsyslog rotate > /dev/null`

**Comment by ddpbsd** [comment]
How did you install OSSEC? I don't believe using logrotate is part of the default install.

**Comment by hdep** [comment]
Hello,

I'm using the following Debian repository : 

http://ossec.wazuh.com/repos/apt/debian/

If this file is not is not part of the package, i'll have a look on my side then.

**Comment by ddpbsd** [comment]
Ok, I don't know much about the packages.

**Comment by hdep** [comment]
Ok, 
but this is the good place to report this issue ?

**Comment by ddpbsd** [comment]
If you're using Wazuh's OSSEC instead of OSSEC's OSSEC, you might want to try reporting the issue to them. https://github.com/wazuh
