### ISSUE TITLE
ossec-analysisd: ERROR: read error 

### ISSUE THREAD

**Issue by nickbijmoer** [ossec/ossec-hids#965]
Hello guys, I get this error every time, someone knows how to fix it? 

ossec-analysisd: ERROR: read error on /queue/diff/*server*/533/last-entry

Greetings, 

Nick

**Comment by ddpbsd** [comment]
Does the file exist?

**Comment by nickbijmoer** [comment]
It does but its empty

**Comment by ddpbsd** [comment]
What are the permissions, owner, and group of the file and the directory it is in?

**Comment by nickbijmoer** [comment]
-rw-r-----. 1 ossec ossec 604 Oct 11 10:20 last-entry

**Comment by nickbijmoer** [comment]
I just saw a map /queue/diff/server/535 and in that map there is a last-entry file with things written in it

**Comment by ddpbsd** [comment]
The permissions for the file look correct, not sure about the directory though. I have:
`drwxr-x---  2 ossec  ossec  512 Sep  5 21:52 533`

I'd stop the OSSEC processes, delete the last-entry file that's causing you issues, and start the processes again.

**Comment by nickbijmoer** [comment]
Will try that :)

**Comment by nickbijmoer** [comment]
I think That worked thanks :)
