### ISSUE TITLE
Ossec parsing issue with events where day is a single digit (e.g. Jul 7 instead of July 17)

### ISSUE THREAD

**Issue by ellebee123** [ossec/ossec-hids#967]
There seems to be an error in ossec rules parsing ssh events. The same event with a different date results in different alarms being generated.

`echo "Jul 7 12:42:43 appsrv03 sshd[30862]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.55.85" >> /var/log/auth.log`

`echo "Jul 17 12:42:43 appsrv03 sshd[30862]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.55.85" >> /var/log/auth.log`

I think the error is in the way ossec process the log date. The second should be the correct, take a look into the 2 spaces in Jul 7. It seems like OSSEC currently doesn't take into account while resolving the dates that the syslog date may come with a single digit on the day part. 

/* Check for the syslog date format
     * ( ex: Dec 29 10:00:01    <------- This is the only thing they took into account, maybe guessing day 1 would come as 01?
     *   or  2015 Dec 29 10:00:01
     *   or  2007-06-14T15:48:55-04:00 for syslog-ng isodate
     *   or  2009-05-22T09:36:46.214994-07:00 for rsyslog )
     *   or  2015-04-16 21:51:02,805 (proftpd 1.3.5)
     */
    if (
        (
            (loglen > 17) &&
            (pieces[3] == ' ') &&
            (pieces[6] == ' ') &&  <----- From this onwards the parsing shouldn't be as strict
            (pieces[9] == ':') &&
            (pieces[12] == ':') &&
            (pieces[15] == ' ') && (lf->log += 16)
        )

**Comment by ddpbsd** [comment]
Most syslogs use 2 spaces for aingle digit days keeping the number of characters consistent. Which syslog are you using that's decided to buck the trend?

**Comment by ellebee123** [comment]
You're right. I found the problem. It was with the data I was feeding into it. Adjusted the regex and it worked. Thanks for the response!
