### ISSUE TITLE
OSSEC default dashboard : No Results found.

### ISSUE THREAD

**Issue by maniacnl** [ossec/ossec-hids#968]
Hello guys,

A few days ago the default dashboard of OSSEC worked fine, but I had to clean up some space so I deleted some data logs and now when I open the default dashboard it says: No results found. 
So I dont know why but I dont get data anymore and I tought I didnt change anything...
Can some1 help me? If you have questions please ask :)

**Comment by ddpbsd** [comment]
There are no dashboards in OSSEC, so what dashboard do you mean?

**Comment by ddpbsd** [comment]
Oh ok. That might be something to send to the list. I don't think it's an OSSEC issue, so I'll be closing this.
You might want to include which files you deleted.
