### ISSUE TITLE
File Integrity Monitoring for ESXi 4.x, 5.x and 6.x

### ISSUE THREAD

**Issue by jittank** [ossec/ossec-hids#985]
I note that OSSEC agent only supports VMWare ESX 3.0,3.5.

Is it possible to perform file integrity checks on VMware vSphere ESXi 4.x, 5.x and 6.x?

If possible, how is this completed? By agentless monitoring or do new agent binaries need to be compiled for the ESXi 4.x, 5.x and 6.x platforms?

**Comment by ddpbsd** [comment]
My response to your query on the mailing list:
https://marc.info/?l=ossec-list&m=147817714005738&w=2

This isn't really an issue, and the mailing list should suffice.
