### ISSUE TITLE
Ossec agent 2.8.3 `Problem in windows server 2012

### ISSUE THREAD

**Issue by alexpe2828** [ossec/ossec-hids#988]
Hello everybody,

I downloaded osseC-agent 2.8.3 and installed OK in Windows Server 2012 (Spanish), but i have problem with the connection:

https://i.gyazo.com/03b0b205c362d26830b5a02b9af4e91d.png

and the logs is:

https://gyazo.com/05b8c6b79d9aae5dec0154fcd683e475

Please i need information for fix this error and continue with my proyect con OSSIM and Ossec-agents.

Ty

**Comment by ddpbsd** [comment]
Do you have an `Administrators` group?

**Comment by marcRBD** [comment]
You must have an Administrators group with your admin in it.
On the directory of ossec agent i put the right for the user: system that launch the service Ossec
