### ISSUE TITLE
Is there a way to rename the agent that runs on the OSSEC Manager server? 

### ISSUE THREAD

**Issue by greyhammer** [ossec/ossec-hids#993]
Currently I have the following, 

``` 
root@ip-10-0-0-71:~# /var/ossec/bin/agent_control -l

OSSEC HIDS agent_control. List of available agents:
   ID: 000, Name: ip-10-0-0-71 (server), IP: 127.0.0.1, Active/Local
```

As I start to add additional agents I can specify their names, is there a way to rename this local agent so that my dashboards are a little easier to read?

**Comment by aquerubin** [comment]
Look for rename_agent.sh and renumber_agent.sh in the source contrib directory.

Tony

**Comment by ddpbsd** [comment]
By default agent_control gets the server's hostname and uses that. You can modify src/util/agent_control.c to put something else for the name.
