### ISSUE TITLE
Possible false positive in Debian Stretch

### ISSUE THREAD

**Issue by KALRONG** [ossec/ossec-hids#994]
Hi,

I have been receiving the following alert:

Host-based anomaly detection event (rootcheck).	
Trojaned version of file '/bin/grep' detected. Signature used: 'bash|givemer|/dev/' (Generic).

I have tested in the server the following command:
strings /bin/grep | grep -E 'bash|givemer|/dev/'

With the result:
/dev/null

I have been looking around worried that may be a hack but so far chkrootkit and other tests doesn't show this positive.

I was wondering if this may be a false positive from ossec side.

Thanks in advance!

**Comment by KALRONG** [comment]
To give more reasons as why it seems to be a false positive:

root@kserv:/var/ossec/bin# debsums grep
/bin/egrep                                                                    OK
/bin/fgrep                                                                    OK
/bin/grep                                                                     OK
/usr/bin/rgrep                                                                OK
/usr/share/doc/grep/copyright                                                 OK
/usr/share/locale/de/LC_MESSAGES/grep.mo                                      OK
/usr/share/locale/es/LC_MESSAGES/grep.mo                                      OK
/usr/share/locale/fr/LC_MESSAGES/grep.mo                                      OK
/usr/share/locale/ja/LC_MESSAGES/grep.mo                                      OK
/usr/share/locale/zh_CN/LC_MESSAGES/grep.mo                                   OK
/usr/share/locale/zh_TW/LC_MESSAGES/grep.mo                                   OK

**Comment by MagnusMWW** [comment]
Very likely a FP. I've checked a few of my own machines:

Archlinux: strings /bin/grep | grep -E 'bash|givemer|/dev/' returns "/dev/null", as in your example from Debian.
Centos7: strings /bin/grep | grep -E 'bash|givemer|/dev/' returns nothing.

Archlinux has grep 2.27, while Centos 7 has 2.20, so likely this is something that exists in newer versions of GNU-grep. I would expect that Stretch has a newer version than Centos 7 as well.

Given that it is a while ago you submitted this, I guess you've already resolved this some way or the other though.

**Comment by StasGoshtein** [comment]
+1 Debian Stretch, Grep 2.27

**Comment by Averroes** [comment]
Probably false positive
`apt purge grep&&apt clean&&apt install grep`
I uninstalled grep (apt purge ) and reinstalled it.

**Result:**
Same cheksum, same size, same version

`md5sum /bin/grep`
3ff5cbd47b2c25c9be0e505aefc60cd8  /bin/grep

`cat /etc/debian_version`
9.1

`sudo strings /bin/grep | grep -E 'bash|givemer|/dev/'`
/dev/null

**Comment by nbuuck** [comment]
The pattern in use was introduced in the first commit of `rootkit_trojans.txt`, https://github.com/ossec/ossec-hids/commit/83ecf6cf1445bc042af60b84933d7765c5ab08aa. It is not consistent with the pattern used by chkrootkit, `GREP_INFECTED_LABEL="givemer"`. There's evidence of Gentoo and Ubuntu users encountering this false positive on those distros' user forums.

From http://git.savannah.gnu.org/cgit/grep.git/
```
src/grep.c:          if (stat ("/dev/null", &null_stat) == 0
```

As `grep` now legitimately contains a string include the characters `/dev/`, I think a PR to remove that part of the pattern for this rootcheck is warranted.

https://github.com/ossec/ossec-hids/blob/1c4e812e3873d9f058a7dd233cc7a1b121c67129/src/rootcheck/db/rootkit_trojans.txt#L45
