### ISSUE TITLE
RHEL 5.2 - empty pid file for agentd

### ISSUE THREAD

**Issue by BP9906** [ossec/ossec-hids#995]
For some reason on 1 of my RHEL 5.2 servers, I'm seeing agentd not pull down the agent.conf file and its not writing the pid value inside the pid file in /var/ossec/var/run/ossec-agentd-<pid>.pid

If I stop ossec agent, it fails to stop agentd because the agentd pid file is empty. I end up forcefully killing agentd every restart. Its a source compile using 2.8.3. If I echo <pid> >> ossec-agentd-<pid>.pid then ossec-control properly stops the process.  I enabled agentd debug=2 on the agent and I'm not getting any additional feedback.

**Comment by atomicturtle** [comment]
Given that this distro is EOL in march, is it worth pursuing this issue further?
