### ISSUE TITLE
When will Ossec 2.9 stable be out?

### ISSUE THREAD

**Issue by jay-dihenkar** [ossec/ossec-hids#996]
What's the tentative date for ossec 2.9 stable release? any hints please?
It has lots of improvements we want to use but waiting for stable release

**Comment by ddpbsd** [comment]
As always I believe this comes down to time. Real life is eating up our hobby time, which of course causes delays.

**Comment by calve** [comment]
@ddpbsd what can we do to help ?

**Comment by ddpbsd** [comment]
Test, provide feedback, create a 25th hour of the day :-)

**Comment by ddpbsd** [comment]
Actually, if PR #1040 goes in, I think we'll have all of the major outstanding problems (except lack of time) fixed.

**Comment by calve** [comment]
Thanks. Now that #1040 is merged can we cut a RC5 to release and test before a stable ?

**Comment by ddpbsd** [comment]
@calve  @atomicturtle is working on rc5. If that goes well (and he gets his packing stuff sorted out), we should be back on track(ish).

**Comment by calve** [comment]
Nice to read ! Please do not hesitate to ask for testing or any help ;)

**Comment by ddpbsd** [comment]
I'm sure we'll put out a final call on the mailing lists and social media. Thanks!

**Comment by atomicturtle** [comment]
@calve I need assistance testing the RPM upgrade from 2.8.3 agents to 2.9.0 on el7. Ive had reports of the symlinks to ossec-loggcollector not being created correctly
